### ISSUE TITLE
Unknown Interaction/Interaction Failed v2.0.0b4

### ISSUE THREAD

**Issue by Nziie3** [Pycord-Development/pycord#1002]
https://user-images.githubusercontent.com/80853540/153726191-49828b40-626f-4e87-bbeb-766d56203057.MOV

### Summary

I have a persistent view: I clicked the buttons on that view and I got interaction failed error in my console

### Reproduction Steps

Pressing the buttons ~3 times. These buttons are in the view class that is persistent (`client.add_view(MyView())`.

### Minimal Reproducible Code

```python
# main file
client.add_view(MyView())

# class
class MyView(discord.ui.View):
  def __init__(self):
    super().__init__(timeout=None)
  @discord.ui.button(style=discord.ButtonStyle.green, label="Button 1", custom_id="button_one")
  async def mycallback(self, button, interaction):
    # stuff
  @discord.ui.button(style=discord.ButtonStyle.grey, label="Button 2", custom_id="button_two")
  async def mycallback2(self, button, interaction):
    # stuff
  @discord.ui.button(style=discord.ButtonStyle.blurple, label="Button 3", custom_id="button_three")
  async def mycallback3(self, button, interaction):
    #stuff
```

Anything for me using persistent views doesn’t seem to work, always an `Unknown Interaction` error is thrown.

### Expected Results

I expected for the callback to be ran successfully even after 3 clicks of the buttons in the views, since it’s a persistent view.

### Actual Results

I got an `Interaction Failed/Unknown Interaction` error in my console and the callback doesn’t occur.

### Intents

All

### System Information

v2.0.0b4

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Nziie3** [comment]
This doesn’t work with select menus as well.

**Comment by Nziie3** [comment]
Can anyone help?

**Comment by krittick** [comment]
I'm not able to reproduce this error with the example code provided, or with my own bot which uses persistent views heavily. Can you post the full traceback? I suspect there may be something else causing this.

**Comment by Nziie3** [comment]
> I'm not able to reproduce this error with the example code provided, or with my own bot which uses persistent views heavily. Can you post the full traceback? I suspect there may be something else causing this.

This is the main part of the error: ```py
Task exception was never retrieved

future: <Task finished name='discord-ui-vie
w-dispatch-75c1ace21189175e3ccbd1674d4db8dd
" coro=<View. _scheduled_task() done, define
d at /opt/virtualenvs/python3/lib/python3.8
/site-packages/discord/ui/view.py:356> exce
ption=NotFound('404 Not Found (error code:
10062): Unknown interaction' )>

Traceback (most recent call last):

File "/opt/virtualenvs/python3/1lib/python
3.8/site-packages/discord/ui/view.py", line

367, in _scheduled_task
await interaction. response.defer()
File "/opt/virtualenvs/python3/1lib/python
3.8/site-packages/discord/interactions.py",
line 471, in defer
await adapter.create_interaction_respon
Tou (

File "/opt/virtualenvs/python3/1lib/python
3.8/site-packages/discord/webhook/async_.py
"| line 192, in request

raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (err
or code: 10062): Unknown interaction

During handling of the above exception, ano
ther exception occurred:
```

**Comment by Nziie3** [comment]
@krittick

**Comment by Nziie3** [comment]
It also seems to fix itself with v2.0.0b3 or lower but I want to be able to use the modals AND the persistent views work.

**Comment by Dorukyum** [comment]
What about in v2.0.0b5 or master?

**Comment by plun1331** [comment]
Stale
