### ISSUE TITLE
Can't create thread with  discord.Message's create_thread() method 

### ISSUE THREAD

**Issue by JeanLeShiba** [Pycord-Development/pycord#1003]
### Summary

Can't create thread with  discord.Message's create_thread() method 

### Reproduction Steps

This command is used to be in a Cog.
```Python
@commands.Cog.listener("on_message")
@commands.guild_only()
async def threads(self, message):
    """Create threads on message."""
    if message.channel.id == 914227384104919080:
        await message.create_thread(name="Name")
```

### Minimal Reproducible Code

```python
@bot.event
async def on_message(message):
    await message.create_thread(name="Name")
```

### Expected Results

![image](https://user-images.githubusercontent.com/82232821/153734119-e45c3086-db24-4d7a-a470-b334461f9069.png)

### Actual Results

```cmd
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\discord\client.py", line 343, in _run_event     
    await coro(*args, **kwargs)
  File "c:\Users\Jean\Documents\Dev\HHardware Bot\cogs\threads.py", line 21, in threads
    await message.create_thread(name="Name")
AttributeError: 'Message' object has no attribute 'create_thread'
```

### Intents

```python
discord.Intents.all()
```

### System Information

```cmd
PS C:\Users\Jean> python -m discord -v
- Python v3.10.0-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I also updated py-cord to the latest version `py-cord==2.0.0b4`  and discord.py isn't installed so no need to ask if I did.

**Comment by plun1331** [comment]
> I also updated py-cord to the latest version `py-cord==2.0.0b4` and discord.py isn't installed so no need to ask if I did.

Look at your system info:
> - discord.py v1.7.3-final

**Comment by JeanLeShiba** [comment]
I had to reinstall Python entirely but it's fixed x) Thank anyway.
