### ISSUE TITLE
@discord.commands.permissions.is_owner() not working in DMs

### ISSUE THREAD

**Issue by f4b14n-d** [Pycord-Development/pycord#1005]
### Summary

If you use the @discord.commands.permissions.is_owner decorator on a slash command, it will work for the bot owner in servers, but not if you try to use the command in DMs with the bot (the command is greyed out)

### Reproduction Steps

- Make a Slash Command and use the @discord.commands.permissions.is_owner() check

### Minimal Reproducible Code

```python
import discord
from discord.commands import permissions

bot = discord.Bot(intents=discord.Intents.all(), owner_id=123)

@bot.slash_command()
@permissions.is_owner()
async def test(ctx):
    await ctx.send("No.", ephemeral=True)

bot.run("ABC")
```

### Expected Results

I (as the bot owner) can use the command in both servers and dms

### Actual Results

I could only use the command in servers; in dms with the bot it was greyed out

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
       - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Linux 5.16.8-arch1-1 # 1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Most likely an issue with Discord, pycord just sends the "OWNER" restriction.

**Comment by Revnoplex** [comment]
so it is suppost to work in dms

**Comment by BobDotCom** [comment]
Use the ext.commands is_owner check. discord.commands.permissions.is_owner will be deprecated soon
