### ISSUE TITLE
@permissions.is_admin()

### ISSUE THREAD

**Issue by rpop0** [Pycord-Development/pycord#1006]
### Summary

Create a @permissions.is_admin() decorator for slash commands that allows the specific slash command to be used by all roles which have the "Administrator" permission.

### What is the feature request for?

The core library

### The Problem

The issue with slash command permissions currently is that you have to hard code the roles you want to grant permissions to. This is an issue if you want to grant a command to all roles who have the "Administrator" permission set.

### The Ideal Solution

Create a decorator @permissions.is_admin() that makes a slash command available to all roles that are administrators.

**Comment by rpop0** [comment]
Would that be due to the fact that the command would need to be re-registered each time a new role using that permission is added?

**Comment by plun1331** [comment]
> Would that be due to the fact that the command would need to be re-registered each time a new role using that permission is added?

The command wouldn't need to be re-registered, the permissions would need to be updated though.

**Comment by BobDotCom** [comment]
Will be possible with permissions v2
