### ISSUE TITLE
Update documentation for new API

### ISSUE THREAD

**Issue by KitsuneSan89** [Pycord-Development/pycord#101]
### Summary

Add basic information about migrating to new APIs and changes post-fork

### What is the feature request for?

The documentation

### The Problem

The current documentation doesn't appear to have changed much from the discord.py docs. While the reference information includes functions that haven been added, there's no high-level information about slash_command and other changes coming to the API

### The Ideal Solution

The documentation should include a "Migrating to 2.0" guide and basic information about using slash_commands and other new features.

### The Current Solution

There are some example programs using the new features. These could be referred to or used as the basis for a guide.

### Additional Context

For people new to Discord development, the current state is fairly confusing, because much of the information is now out-of-date with slated changes on Discord's end. It would be helpful to mark outdated documentation as such and add information on the new way of doing things more prominently.

**Comment by nerdguyahmad** [comment]
Master docs are here: https://pycord.readthedocs.io/en/master

For migration guide, It will be written and reased once changes are finialized. Many things are subject to change as of now. You can track the breaking changes and other minor changes in projects kanban.

**Comment by Lulalaby** [comment]
still working on it.
we already documented a big part of the new things with the beta release.
Closing.
