### ISSUE TITLE
AttributeError: discord.client.Client().application_flags

### ISSUE THREAD

**Issue by cclauss** [Pycord-Development/pycord#102]
### Summary

AttributeError: 'ConnectionState' object has no attribute 'application_flags'

### Reproduction Steps

import discord ; discord.client.Client().application_flags

### Minimal Reproducible Code

```python
import discord ; discord.client.Client().application_flags
```

### Expected Results

flags

### Actual Results

AttributeError: 'ConnectionState' object has no attribute 'application_flags'

### Intents

None

### System Information

master branch of this repo.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by cclauss** [comment]
`ConnectionState.application_flags` is not created in [`ConnectionState.__init__()`](https://github.com/Pycord-Development/pycord/blob/master/discord/state.py#L148-L236) but is [created only conditionally](https://github.com/Pycord-Development/pycord/blob/master/discord/state.py#L557-L565) in `ConnectionState.parse_ready()`.

**Comment by Lulalaby** [comment]
Stale
