### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by D4rkS0ulMC** [Pycord-Development/pycord#1033]
### Summary

My code works perfectly fine (but slow) on my test server, but on the bigger server with more than 100 people I (almost) always get the error message above. If this happens, it only sends the "Adding users...", but it doesn't edit it and after around 1min I get the error above.

### Reproduction Steps

```py
import discord
from discord.ext import commands

from Config import ping_role_id, mod_role_id


class ThreadSystem(commands.Cog):

    def __init__(self, bot):
        self.client = bot
        self.flag = False

    @commands.Cog.listener()
    async def on_thread_join(self, thread):
        if self.flag:
            self.flag = False
            return
        if not self.flag:
            self.flag = True
        await thread.join()
        if thread.guild.premium_tier == 3:
            await thread.edit(auto_archive_duration=10080)
        elif thread.guild.premium_tier == 2:
            await thread.edit(auto_archive_duration=4320)
        elif thread.guild.premium_tier == 1:
            await thread.edit(auto_archive_duration=1440)
        ping_role = thread.guild.get_role(ping_role_id)
        members = [m for m in thread.guild.members if ping_role in m.roles]
        if len(members) == 0:
            return
        member_mentions = [member.mention for member in members]
        returned_string = ""
        ping_msg = await thread.send("Adding users...")

        for member_mention in member_mentions:
            if len(returned_string + member_mention) > 2000:
                await ping_msg.edit(returned_string)
                returned_string = member_mention + " "
            else:
                returned_string += member_mention + " "
        if len(returned_string) != 0:
            await ping_msg.edit(returned_string)
        await ping_msg.delete()

    @commands.command()
    async def addMembers(self, ctx, arg1: discord.Thread):
        mod_role = ctx.guild.get_role(mod_role_id)
        if mod_role in ctx.author.roles or ctx.author.id == 672768917885681678:
            thread = arg1
            await thread.join()
            if thread.guild.premium_tier == 3:
                await thread.edit(auto_archive_duration=10080)
            elif thread.guild.premium_tier == 2:
                await thread.edit(auto_archive_duration=4320)
            elif thread.guild.premium_tier == 1:
                await thread.edit(auto_archive_duration=1440)
            ping_role = thread.guild.get_role(ping_role_id)
            members = [m for m in thread.guild.members if ping_role in m.roles]
            if len(members) == 0:
                return
            member_mentions = [member.mention for member in members]
            returned_string = ""
            ping_msg = await thread.send("Adding users...")

            for member_mention in member_mentions:
                if len(returned_string + member_mention) > 2000:
                    await ping_msg.edit(returned_string)
                    returned_string = member_mention + " "
                else:
                    returned_string += member_mention + " "
            if len(returned_string) != 0:
                await ping_msg.edit(returned_string)
            await ping_msg.delete()


def setup(bot):
    bot.add_cog(ThreadSystem(bot))
   ```
   I get the error almost every time the event or the command gets triggered. (Only on a bigger server with 100+ members and more than 100 members who have the ping role. 

### Minimal Reproducible Code

```python
for member_mention in member_mentions:
                if len(returned_string + member_mention) > 2000:
                    await ping_msg.edit(returned_string)
                    returned_string = member_mention + " "
                else:
                    returned_string += member_mention + " "
            if len(returned_string) != 0:
                await ping_msg.edit(returned_string)
            await ping_msg.delete()
```

### Expected Results

This event gets triggert after a thread was created. Since it gets triggered twice per thread (when created and when bot joines) it only reacts to every other event. After that it iterates trough all members on the server and adds those to a list, which have the ping_role. Then it sends a message ("Adding users...") in the thread that was just created, edits it and mentions (without pinging, since it's edited) as many members as the character limit allows and repeats this till everybody in the list was mentioned.

### Actual Results

Ignoring exception in command addMembers:
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\RIP_Bot\venv\lib\site-packages\discord\ext\commands\core.py", line 183, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\RIP_Bot\cogs\ThreadSystem.py", line 67, in addMembers
    await ping_msg.edit(returned_string)
  File "C:\Users\User\PycharmProjects\RIP_Bot\venv\lib\site-packages\discord\message.py", line 1429, in edit
    data = await self._state.http.edit_message(
  File "C:\Users\User\PycharmProjects\RIP_Bot\venv\lib\site-packages\discord\http.py", line 381, in request
    raise DiscordServerError(response, data)
discord.errors.DiscordServerError: 500 Internal Server Error (error code: 0): 500: Internal Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\RIP_Bot\venv\lib\site-packages\discord\ext\commands\bot.py", line 366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\User\PycharmProjects\RIP_Bot\venv\lib\site-packages\discord\ext\commands\core.py", line 955, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\User\PycharmProjects\RIP_Bot\venv\lib\site-packages\discord\ext\commands\core.py", line 192, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DiscordServerError: 500 Internal Server Error (error code: 0): 500: Internal Server Error

### Intents

all intents

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
This is on Discord's end, not the library's.
You can (I think) report it at https://github.com/discord/discord-api-docs/.

Additionally, adding that many members to a thread like that is spam and may be considered API abuse.

**Comment by D4rkS0ulMC** [comment]
Ok, I'll ask there. And it doesn't actually ping anybody since it's a edited message. We just a role first, but since adding members by mentioning the role only works for roles with less 100 members we had to change it.
