### ISSUE TITLE
commands.when_mentioned_or allows list inside paramters

### ISSUE THREAD

**Issue by Jerry-py** [Pycord-Development/pycord#104]
### Summary

Adding list into commands.when_mentioned_or

### What is the feature request for?

discord.ext.commands

### The Problem

I'm trying to solve that normally command_prefix can use list why not commands.when_mention_or

### The Ideal Solution

The solution to me would be letting list be in the parameters

### The Current Solution

Same thing but just like this: `commands.when_mention_or(['!', '?'])`

### Additional Context

I don't

**Comment by mccoderpy** [comment]
I don't know what for... you can just give them without a list 
```py
commands.when_mentioned_or('!', '?')
```
or
```py
commands.when_mentioned_or(('!', '?'))
```

**Comment by Jerry-py** [comment]
What if i wanted a list?

**Comment by mccoderpy** [comment]
> What if i wanted a list?

Then implement it yourself. Or just do it like this
```py
commands.when_mentioned_or(*['!', '?'])
```` xD

**Comment by Dorukyum** [comment]
You could pass a list by splitting it into arguments.
```py
prefixes: list[str] = [...]
prefix = when_mentioned_or(*prefixes)
```
