### ISSUE TITLE
Add option to delete desynced commands when the bot starts up 

### ISSUE THREAD

**Issue by HigherOrderLogic** [Pycord-Development/pycord#1043]
### Summary

Add option to delete desynced commands when the bot starts up 

### What is the feature request for?

The core library

### The Problem

When I run the bot, some desynced slash commands from the previous run still appear and when users use them, the bot simply doesn't respond, which isn't nice

### The Ideal Solution

Add a parameter to `discord.Bot`

### The Current Solution

N/A

**Comment by Lulalaby** [comment]
@guitaristtom this is out of context.
Topic is slash, not text / message commands.

**Comment by BobDotCom** [comment]
This should already be fixed in b5 (master branch). If you need to update guild commands, there's a kwarg for that.
