### ISSUE TITLE
Buttons exclude themselves

### ISSUE THREAD

**Issue by skayus** [Pycord-Development/pycord#1046]
### Summary

Buttons exclude themselves

### Reproduction Steps

I tried to make buttons and when I added the url variable, an error popped up that the button did not have such a variable and when I removed it, it showed that it is needed

### Minimal Reproducible Code

![unknown](https://user-images.githubusercontent.com/72523014/154678690-dab69c3b-b3b3-4b08-9a8c-31a16c00f3ff.png)
![unknown](https://user-images.githubusercontent.com/72523014/154678747-8fc45832-d985-4a22-a432-ca933ef6a8ca.png)
![unknown](https://user-images.githubusercontent.com/72523014/154678754-8cfde819-c70c-4d3d-ba41-9d086471feef.png)
![unknown](https://user-images.githubusercontent.com/72523014/154678761-2d0ab4a3-634a-4cfd-ad0b-cca03202f4d2.png)

### Expected Results

Normal button operation

### Actual Results

Buttons exclude themselves

### Intents

all

### System Information

- Python v3.9.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Windows 10 10.0.22543

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
URL buttons cant have callbacks so the second error is expected.

**Comment by krittick** [comment]
For the first error, you can't use ButtonStyle.link for non-URL buttons, per here: https://discord.com/developers/docs/interactions/message-components#button-object-button-styles
