### ISSUE TITLE
Discord raised "Already connected to a voice channel." after being disconected using right click in discord app

### ISSUE THREAD

**Issue by Grolicek** [Pycord-Development/pycord#1049]
### Summary

Discord raised "Already connected to a voice channel." after being disconected using right click in discord app

### Reproduction Steps

Connect to voice channel, after that disconnect bot using right click.
![image](https://user-images.githubusercontent.com/58747066/154793033-d2cf1326-a487-4260-ab17-5758dcfe5c8b.png)

After try again connecting bot to voice channel and error will be raised.

### Minimal Reproducible Code

```python
async def connect(ctx: ApplicationContext):
    await ctx.author.voice.channel.connect()
```

### Expected Results

Bot connected to voice channel.

### Actual Results

Ignoring exception in command connect:
Traceback (most recent call last):
  File "C:\Users\Oliver\.virtualenvs\MusicianByGroli\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
  File "C:\Users\Oliver\.virtualenvs\MusicianByGroli\lib\site-packages\discord\commands\core.py", line 770, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "c:\Users\Oliver\Documents\python\MusicianByGroli\cogs\music_controller.py", line 33, in connect
    player = await self._connect(interaction, channel)
  File "c:\Users\Oliver\Documents\python\MusicianByGroli\cogs\music_controller.py", line 22, in _connect
    return await channel.connect(cls=wavelink.Player)
  File "C:\Users\Oliver\.virtualenvs\MusicianByGroli\lib\site-packages\discord\abc.py", line 1739, in connect
    raise ClientException('Already connected to a voice channel.')
discord.errors.ClientException: Already connected to a voice channel.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Oliver\.virtualenvs\MusicianByGroli\lib\site-packages\discord\bot.py", line 768, in process_application_commands
    await ctx.command.invoke(ctx)
  File "C:\Users\Oliver\.virtualenvs\MusicianByGroli\lib\site-packages\discord\commands\core.py", line 306, in invoke
    await injected(ctx)
  File "C:\Users\Oliver\.virtualenvs\MusicianByGroli\lib\site-packages\discord\commands\core.py", line 116, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: ClientException: Already connected to a voice channel.

### Intents

all

### System Information

- Python v3.9.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by TheShubhendra** [comment]
It is working fine on my end
Python-3.10.0
py-cord==2.0.0b4884+g68e9cf3d
OS: rasbian
ARM v6

**Comment by Dorukyum** [comment]
Can reproduce on master.

**Comment by Paradoxis** [comment]
I'm experiencing this issue as well, it happens when a bot connects and plays audio, and is subsequently disconnected manually by a server admin. The issue occurs at the `discord.abc.Connectable.connect` method, where the `_get_voice_client` method does not properly validate if the active voice client is connected before returning the object.

```
>>> key_id, _ = voice_channel._get_voice_client_key()
>>> state = voice_channel._state
>>> voice_client = state._get_voice_client(key_id)
>>> voice_client.is_connected()
False
```

Rewriting the code to check if the client is still active would fix the issue. In this case a new voice client would be created and the old one would be overwritten after the `if` condition fails.

```python
key_id, _ = self._get_voice_client_key()
state = self._state

client = state._get_voice_client(key_id)
if client and client.is_connected():
    raise ClientException("Already connected to a voice channel.")
```

For others looking for a workaround, I used the following solution:

Before connecting to the channel, remove the voice client if it is not connected and let the `connect` method do the rest of the work. This ensures the voice client dictionary is clean before it can be used.

```python3
key_id, _ = voice_channel._get_voice_client_key()
state = voice_channel._state
voice_client = state._get_voice_client(key_id)
if voice_client and not voice_client.is_connected():
    state._remove_voice_client(key_id)

await voice_channel.connect()
```
