### ISSUE TITLE
Hotloading Changes

### ISSUE THREAD

**Issue by NathanX-S** [Pycord-Development/pycord#105]
### Summary

Hot loading

### What is the feature request for?

The core library

### The Problem

The inability to hotload changes.

### The Ideal Solution

Provide a simple and easy to use solution to hotload changes during runtime.

**Comment by jgayfer** [comment]
Extensions can already be reloaded.

See: https://pycord.readthedocs.io/en/latest/ext/commands/api.html?highlight=reload#discord.ext.commands.Bot.reload_extension
