### ISSUE TITLE
message.content is blank after updating to latest development version (not a selfbot)

### ISSUE THREAD

**Issue by GoatInAHat** [Pycord-Development/pycord#1056]
### Summary

After installing the development version of pycord from github instead of the pip version (so I could use ui views) message.content is not available.

### Reproduction Steps

1. install the latest version of pycord from github
2. print the message in the on_message event
3. it will return something like `<Message id=944844858516975616 channel=<TextChannel id=942613188699095091 name='meme-feed-bot' position=3 nsfw=False news=False category_id=944810173757792287> type=<MessageType.default: 0> author=<User id=942613190381015041 name='Meme Feed Bot' discriminator='0000' bot=True> flags=<MessageFlags value=0>>` which has no content available.

### Minimal Reproducible Code

```python
import discord

class botClass(discord.Client):
    async def on_ready(self):
        print(f'Logged in as {bot.user.name}')

    async def on_message(self, message):
        print(message.content)
 
bot = botClass()
bot.run('token')
```

### Expected Results

The code should print the content of the message.

### Actual Results

A blank newline is printed to the console.

### Intents

discord.Intents(messages=True, guilds=True)

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.6.3
- system info: Windows 10 10.0.22543

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Attempting to fetch the message by its id returns an Unknown Message error:

`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\benne\OneDrive\Desktop\meme-poster\main.py", line 49, in on_message
    newmsg = await BASED_VIDEOS_CHANNEL.fetch_message(message.id)
  File "C:\Python39\lib\site-packages\discord\abc.py", line 1517, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "C:\Python39\lib\site-packages\discord\http.py", line 353, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message`
 
and getting the most recent message in the channel returns the same useless message object with no content member:

`<Message id=944840024032170004 channel=<TextChannel id=942613188699095091 name='meme-feed-bot' position=3 nsfw=False news=False category_id=944810173757792287> type=<MessageType.default: 0> author=<User id=942613190381015041 name='Meme Feed Bot' discriminator='0000' bot=True> flags=<MessageFlags value=0>>`

**Comment by EmreTech** [comment]
Enable Message Content Intent

**Comment by EmreTech** [comment]
Oh I think you did

**Comment by plun1331** [comment]
> Oh I think you did

They didn't

**Comment by GoatInAHat** [comment]
Found the issue, I had enabled `intents.messages` but not `intents.message_content`.
