### ISSUE TITLE
Fix Interaction Race Conditions rooted to using is_done() method

### ISSUE THREAD

**Issue by BadWolf1023** [Pycord-Development/pycord#1057]
### Summary

Several race conditions regarding interactions responded boolean exist and need to be fixed

### Reproduction Steps

There are many open PRs that have to do with these race conditions (eg 963 and possibly 1041). This issue is just to document my findings so they don't get lost.

### Minimal Reproducible Code

See open issues (eg 963 and possibly 1041)

### Expected Results

- [`discord.commands.context.ApplicationContext.respond()`](https://github.com/Pycord-Development/pycord/blob/master/discord/commands/context.py#L218-L225) should correctly issue either a response or a follow-up response depending on if the interaction has been responded to yet or not.

- [`discord.commands.context.ApplicationContext.send_response()`](https://github.com/Pycord-Development/pycord/blob/master/discord/commands/context.py#L227-L234) should _not_ send a message if the interaction has been responded to. (It should consistently raise a `RunTimeError` if the interaction has not been responded to.)

- [`discord.commands.context.ApplicationContext.delete()`](https://github.com/Pycord-Development/pycord/blob/master/discord/commands/context.py#L253-L259) should _not_ `defer()` if the interaction has been responded to. (It should consistently skip deferring if the interaction has been responded to.)

- [`discord.ext.pages.pagination.Paginator.respond()`](https://github.com/Pycord-Development/pycord/blob/master/discord/ext/pages/pagination.py#L697-L715) should correctly issue either a response or a follow-up response depending on if the interaction has been responded to yet or not.

### Actual Results

They vary because, well, these are race conditions! Likely, various 404 Not Found HTTPExceptions are thrown.

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Solution:
- Use `asyncio` locks in the `InteractionResponse` class for all the methods that call `await adapter.create_interaction_response()`
   - If the caller of these methods returns a Callable, callers should use wrappers
   - Callers should properly catch `InteractionResponded` exceptions in the appropriate situations.

For an example, see #1039. **However, please note that #1039 does not fully solve all of the race conditions I have outlined in this issue.**

**Comment by Mihitoko** [comment]
I'll fix all race conditions mentioned above in my PR when locks are approved to be the right solution.
