### ISSUE TITLE
`slash_command` shortcut decorator fails to register a "private" command if not in a cog

### ISSUE THREAD

**Issue by Icebluewolf** [Pycord-Development/pycord#1059]
### Summary

When not in a cog and using the `slash_command` shortcut decorator with the `guild_ids` argument it will not register the command. It still works with public commands, and public and private commands within a cog.

#### **Not In A Cog**
Make a command with the `slash_command` decorator **different** from `bot.slash_command`.

Add the `guild_id` argument and enter in a test guild ID

Observe the command not registering on in the guild (also note that I have tried this for over an hour so it is also not accidentally registering as a global command)

Change `@slash_command(...` to @bot.slash_command(...` and observe how the command registers proving there is nothing wrong with the command

### Minimal Reproducible Code

```python
from discord.commands import slash_command

bot = ...

@slash_command(guild_ids=[xxx])
async def hello(ctx):
    await ctx.respond("Hello")

bot.run(xxx)
```

### Expected Results

The command registered is registered in the specified guilds

### Actual Results

The Command is not registered and no errors are thrown

### Intents

Members

### System Information

- Python v3.9.6-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
The `bot.slash_command` decorator is designed for this functionality. If you *need* to use the `slash_command` decorator for some reason, you should be able to then use `bot.add_application_command` (prior to startup) to add the command to the internal list.
