### ISSUE TITLE
`interaction.response.defer` Does Not Work in the `discord.Modal` Class

### ISSUE THREAD

**Issue by Pysics** [Pycord-Development/pycord#1063]
### Summary

`interaction.response.defer` does not work in the callback function for the `discord.Modal` class even after [this commit](https://github.com/Pycord-Development/pycord/commit/761c302ad0f8c7f21e435a9af81e1bc222eaa7ca).

### Reproduction Steps

1. Clone the latest version of Pycord from GitHub.
2. Use the code below.

### Minimal Reproducible Code

```python
import discord
 
from discord.ext import commands
from discord.ui import InputText, Modal, View, Button
 
bot = commands.Bot(command_prefix='!')
 
class MyModal(Modal):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.add_item(InputText(label="Short Input", placeholder="Placeholder Test"))
 
        self.add_item(
            InputText(
                label="Longer Input",
                value="Longer Value\nSuper Long Value",
                style=discord.InputTextStyle.long,
            )
        )
 
    async def callback(self, interaction: discord.Interaction):
        await interaction.response.defer()
 
@bot.slash_command(name='modaltest', guild_ids=[...])
async def modaltest(ctx):
    button = Button(label="Open Modal")
    async def callback(interaction):
        modal = MyModal(title="Modal")
        await interaction.response.send_modal(modal)
    button.callback = callback
    await ctx.respond("Hello", view=View(button))
 
bot.run('token')
```

### Expected Results

There should be no error and nothing should happen.

### Actual Results

[This](https://media.discordapp.net/attachments/881309521610412082/944601730220445706/unknown.png) is the error that comes in the modal window.

### Intents

None

### System Information

Windows 11
Python 3.10
Pycord Master Branch (on GitHub)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Please provide the system info from `python -m discord -v`

**Comment by Pysics** [comment]
Please delete this issue. I was using an older version.

**Comment by plun1331** [comment]
> Please close this issue. I was using an older version.

Just close it

**Comment by Pysics** [comment]
I don't have the option to close it.

**Comment by plun1331** [comment]
> I don't have the option to close it.

You should, you made the issue
