### ISSUE TITLE
Can't iterate through threads via `TextChannel.threads`

### ISSUE THREAD

**Issue by Space-Turtle0** [Pycord-Development/pycord#1068]
### Summary

AttributeError: 'Object' object has no attribute '_threads'

### Reproduction Steps

Use a task loop to go through all the threads in a channel and if they are archived, they should be unarchived. 

### Minimal Reproducible Code

```python
@tasks.loop(hours=1.0)
    async def AUTO_UNARHCIVE(self):
        """
        A task loop to make sure threads don't automatically archive due to inactivity.
        """
        channel = await self.bot.fetch_channel(int(TECH_ID.ch_botreq))
        print(channel.name, type(channel)) # This part yields the correct results
        for thread in channel.threads:
            if thread.archived:
                await thread.unarchive()
```

### Expected Results

I expected the code above to be able to iterate through each thread in a channel.  

### Actual Results

```py
Unhandled exception in internal background task 'AUTO_UNARHCIVE'.
Traceback (most recent call last):
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/TimmyVenv/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 178, in _loop
    await self.coro(*args, **kwargs)
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/utils/bots/CoreBot/cogs/techProject.py", line 162, in AUTO_UNARHCIVE
    for thread in channel.threads:
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/TimmyVenv/lib/python3.8/site-packages/discord/channel.py", line 235, in threads
    return [thread for thread in self.guild._threads.values() if thread.parent_id == self.id]
AttributeError: 'Object' object has no attribute '_threads'
```

### Intents

discord.Intents.all()

### System Information

- Python v3.8.9-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Also; executing `print(channel.name, type(channel))` yielded:

`✅┃bot-requests <class 'discord.channel.TextChannel'>`

**Comment by EmreTech** [comment]
The reproduction steps are a little too specific for your use case. You might want to make them more generic.

**Comment by EmreTech** [comment]
Also, your system information states that you are using v2.0.0 beta 4. I know this issue was made before beta 5 (I think) but can you try beta 5 now?

**Comment by Middledot** [comment]
The guild was not found because it's not in the cache or the bot's not in the guild, so it was replaced with `discord.Object` https://github.com/Pycord-Development/pycord/blob/688b59c76a0034d2c72e21a9c585ff644b9228fe/discord/client.py#L1611
What you can do instead is fetching the guild, using `guild.get_channel` for the channel, and then iterate the threads (or you could just use `on_thread_update` to detect when a thread is archived).
