### ISSUE TITLE
Webhook adapter doesn't work/import

### ISSUE THREAD

**Issue by RGBCube** [Pycord-Development/pycord#1070]
### Summary

Webhook adapter doesn't work

### Reproduction Steps

i imported `RequestsWebhookAdapter`

### Minimal Reproducible Code

```python
from discord import Webhook, RequestsWebhookAdapter
```

### Expected Results

It imports normally

### Actual Results

Error:
```
/usr/bin/python3 /home/asus/PyProjects/ClutterRewrite2/modules/error_handler.py
Traceback (most recent call last):
  File "/home/asus/PyProjects/ClutterRewrite2/modules/error_handler.py", line 5, in <module>
    from discord import Webhook, RequestsWebhookAdapter
ImportError: cannot import name 'RequestsWebhookAdapter' from 'discord' (/home/asus/.local/lib/python3.10/site-packages/discord/__init__.py)
```

### Intents

discord.Intents.all()

### System Information

Python 3.10.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
`RequestsWebhookAdapter` was removed in d.py 2.0. Use `SyncWebhook` instead.
