### ISSUE TITLE
Unable To Edit Ephemeral Messages in the `discord.ui.Modal` Class

### ISSUE THREAD

**Issue by Pysics** [Pycord-Development/pycord#1077]
### Summary

I am unable to edit ephemeral messages in the `callback` function in the `discord.ui.Modal` class.

### Reproduction Steps

1. Clone the latest version of Pycord from GitHub
2. Use the code below.

### Minimal Reproducible Code

```python
import discord

from discord.ext import commands

bot = commands.Bot(command_prefix='!')

@bot.command()
async def test(ctx):
    class Modal(discord.ui.Modal):
        def __init__(self, *args, **kwargs) -> None:
            super().__init__(*args, **kwargs)
            self.add_item(discord.ui.InputText(label="Emoji Name", value='test', placeholder="Enter input here."))
        async def callback(self, interaction):
            embed = discord.Embed(title='test', description='test')
            await interaction.edit_original_message(embed=embed) #await interaction.message.edit(embed) leads to a similar error
            await interaction.response.send_message('hello')
    async def callback(interaction):
        modal = Modal(title='Modal Form')
        await interaction.response.send_modal(modal)
    async def callback_2(interaction):
        b = discord.ui.Button(label='test')
        b.callback = callback
        await interaction.response.send_message('test', view=discord.ui.View(b), ephemeral=True)
    b = discord.ui.Button(label='test')
    b.callback = callback_2
    await ctx.send('test', view=discord.ui.View(b))

bot.run('token')
```

### Expected Results

 1. Upon clicking the button **test**, there should be an ephemeral response with a button.
 2. Upon clicking the button  **test** (on the ephemeral message), a modal should be sent.
 3. After submission of the modal, the message should be edited, and an embed (with title **test** and description **test**) should be added.

### Actual Results

The message is not edited. Instead I get the following error:
```
Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ui/modal.py", line 195, in dispatch
     await value.callback(interaction)
   File "<string>", line 16, in callback
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/interactions.py", line 372, in edit_original_message
     data = await adapter.edit_original_interaction_response(
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/webhook/async_.py", line 211, in request
     raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
```

### Intents

None

### System Information

Windows 11
Pycord Master Branch (on GitHub)
Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
Is this the same issue you logged in #1058?

**Comment by Pysics** [comment]
There a slight difference. Over there, I was responding while editing the message. Over here, I am responding **after** editing the message. Note that this works for normal messages. This error is raised only for ephemeral messages.

**Comment by krittick** [comment]
Got it, thanks for clarifying!

**Comment by Pysics** [comment]
For some reason, this happens if the button on the ephemeral message is clicked:
- **hello** is sent
- the message is not edited with an embed
- there is no error

**Comment by Pysics** [comment]
> For this issue, replacing `await interaction.edit_original_message(embed=embed)` with `await interaction.response.edit_message(embed=embed)` seems to resolve it for me. Can you please try that and confirm on your end as well?

Notice that what you mentioned is similar to my previous issue (#1058).
