### ISSUE TITLE
`slash_autocomplete.py` example does not work

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1084]
### Summary

The [`slash_autocomplete.py`] file does not work and errors out upon running the file.

### Reproduction Steps

Just run [`slash_autocomplete.py`] and it errors out.

### Expected Results

It should work.

### Actual Results

It errors out with this error:
```py
Traceback (most recent call last):
  File "slash_autocomplete.py", line 127, in <module>
    async def autocomplete_example(
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\bot.py", line 834, in decorator
    result = command(**kwargs)(func)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\core.py", line 1464, in decorator
    return cls(func, **attrs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\core.py", line 575, in __init__
    validate_chat_input_description(description)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\core.py", line 1507, in validate_chat_input_description
    raise ValidationError(
discord.errors.ValidationError: Command description must be 1-100 characters long. Received This demonstrates using the ctx.options parameter to create slash command options that are dependent on the values entered for other options.
```

### Intents

Intents are not relevant here

### System Information

Python Version: 3.8.11
OS: Windows 10
Pycord Version: 2.0.0b4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

[`slash_autocomplete.py`]: https://github.com/Pycord-Development/pycord/blob/master/examples/app_commands/slash_autocomplete.py

**Comment by Icebluewolf** [comment]
Replacing 
https://github.com/Pycord-Development/pycord/blob/e6355fdde2e0bb28d96abac8d40f4bcd98ce00e5/examples/app_commands/slash_autocomplete.py#L132

With 
```
"""Demonstrates using ctx.options to create options that are dependent on the values of other options.
    For the `color` option, a callback is passed, where additional logic can be added to determine which values are returned.
    For the `animal` option, the callback uses the input from the color option to return an iterable of animals"""
```
Would fix this issue and add some more clarification to the command. As the command description is only taken from the first line of the docstring.
