### ISSUE TITLE
`slash_options.py` example does not work

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1085]
### Summary

The [`slash_options.py`] file does not work and errors out upon running the file.

### Reproduction Steps

Just run [`slash_options.py`] and it errors out.

### Expected Results

It should work.

### Actual Results

```py
Traceback (most recent call last):
  File "slash_options.py", line 25, in <module>
    channel: Option([discord.TextChannel, discord.VoiceChannel], "Select a channel")
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\options.py", line 75, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\enums.py", line 657, in from_datatype
    if datatype.__name__ in ["Member", "User"]:
AttributeError: 'list' object has no attribute '__name__'
```

### Intents

Intents are not relevant here

### System Information

Python Version: 3.8.11
OS: Windows 10
Pycord Version: 2.0.0b4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This was initially discovered in #991 in [this comment](https://github.com/Pycord-Development/pycord/issues/991#issuecomment-1036958629).  I am making an issue about it.

[`slash_options.py`]: https://github.com/Pycord-Development/pycord/blob/master/examples/app_commands/slash_options.py

**Comment by NarmyOnDiscord** [comment]
See #1054, there's an error in the examples. You have to use () instead of [] since the source is checking for a tuple, not a list.
