### ISSUE TITLE
Add the option for a submit button in a paginator

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1087]
### Summary

I would like to have the option for a submit button in a paginator.

### What is the feature request for?

discord.ext.pages

### The Problem

If I am taking information from a user using a paginator I would like there to be a submit button once they are done submitting the information.  See the following example:

![Custom View for Each Page of Paginator](https://user-images.githubusercontent.com/34612646/155868402-25cb0e22-900f-490e-b297-d4df8ab267f7.gif)

### The Ideal Solution

I don't think this would fit well in current Paginator as that is already jam-packed with functionality (honestly some of the functionality should be removed from the current Paginator class and placed into subclasses of the Paginator [like for example the `PageGroups`] but that is a discussion for another time).  I think it would be best if there was a subclass of the Paginator called `SubmitPaginator` that implemented this functionality.  Perhaps there would a special method that would be called upon the submitting of a paginator, like for example the `callback` method in all the buttons.

### The Current Solution

None, other than subclassing and writing custom code or using a custom view as mentioned by @krittick [here](https://github.com/Pycord-Development/pycord/issues/1087#issuecomment-1053165855).

**Comment by krittick** [comment]
Couldn't this be handled with using a custom view with the Paginator?

**Comment by Ahsoka** [comment]
> Couldn't this be handled with using a custom view with the Paginator?

Perhaps but I think it would be nice if it was a part of the library itself.  I guess a custom view can be a temporary workaround until this is implemented.  Maybe I wrong here, but I feel like this would be a common enough use case to make it worth implement as a subclass of the Paginator.
