### ISSUE TITLE
Optional Modal InputText fields with existing values do not accept empty strings

### ISSUE THREAD

**Issue by DefiDebauchery** [Pycord-Development/pycord#1092]
### Summary

Submitted Empty InputText fields revert to stored value

### Reproduction Steps

1. Create a Modal with an `InputText` that is both `required=False` and has a `value`
2. Delete the text in the Modal and submit
3. Inspect the Modal's children in the callback.

### Expected Results

Expected: The incoming field (e.g. `self.children[0].value`) should be empty

### Actual Results

Actual: The field retains its previous/existing `value` instead of being overwritten by the empty string.

### Intents

members

### System Information

Python 3.9
Pycord 2.0.0b4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I did verify through logging that the Modal does indeed submit the empty value, but I was unable to find where in the code this was handled.

**Comment by krittick** [comment]
Confirmed bug, working on a fix.
