### ISSUE TITLE
App Commands error handler not registering

### ISSUE THREAD

**Issue by goose1218** [Pycord-Development/pycord#1102]
### Summary

The `on_application_command_error` handler is not working or even registering

### Reproduction Steps

Write code in a cog and make sure other code/commands work in that cog,
use a slash command you don't have permission to, like with the _@commands.has_permissions decorator_
watch as it doesn't register the handler and shows 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/77335090/156476732-8ec830bb-1824-4099-ab48-1ab2b70c0dc2.png">
in discord
In terminal it will say, 
    **raise MissingPermissions(missing)
discord.ext.commands.errors.MissingPermissions: You are missing Administrator permission(s) to run this command.**

### Minimal Reproducible Code

```python
@commands.Cog.listener()
    async def on_application_command_error(self, ctx, error):
        if isinstance(error, commands.MissingPermissions):
      await ctx.respond(“Missing Perms”)
      return
```

### Expected Results

For it to say missing perms to the user when they try and use a command with the decorator _@commands.has_permissions decorator_ and dont have the specified permission

### Actual Results

It doesn't register, shows <img width="385" alt="image" src="https://user-images.githubusercontent.com/77335090/156476742-81a21b61-444e-453a-a32e-1d78974a4cc8.png"> 
and says     **raise MissingPermissions(missing)
discord.ext.commands.errors.MissingPermissions: You are missing Administrator permission(s) to run this command.** in the terminal

### Intents

all

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### Additional Context

**Other users have experienced this as well**

**Comment by Ahsoka** [comment]
Can you send more code?  I have not had a problem with the on_application_command_error listener.

**Comment by goose1218** [comment]
> Can you send more code? I have not had a problem with the on_application_command_error listener.

```py
import discord
from discord.ext import commands
import traceback
import logging
import sys
from traceback import format_exception 
from datetime import datetime
from discord.commands import *


class Error(commands.Cog):

    def __init__(self, client):
        self.client = client


    @commands.Cog.listener()
    async def on_application_commmand_error(self, ctx, error):
        embed = discord.Embed(title = "Error!" , description = f"{error}", color = discord.Color.blue())
        await ctx.respond(embed=embed, ephemeral = True)
        return
```
Its in a cog, but I know its loaded and it works because I have a on_command_error handler and that one works just fine

**Comment by goose1218** [comment]
@Ahsoka is your code different or did I type something wrong?

**Comment by Ahsoka** [comment]
Are you trying to use the `on_application_command_error` handler in this specific cog to listen for errors in all cogs?

**Comment by goose1218** [comment]
yes, but it works for on_command_error
Is it different for `on_application_command_error`?
@Ahsoka

**Comment by Ahsoka** [comment]
You cannot use `on_application_command_error` to listen for errors in other cogs.  It will only trigger if the error happens in the same cog.

**Comment by goose1218** [comment]
ok thanks. I didn't realize as on_command_error works for every cog and they are documented the same
Thanks for helping!

**Comment by Ahsoka** [comment]
If you want a global listener you can use:
```py
import discord

bot = discord.Bot(...)

@bot.event
async def on_application_command_error(ctx, error):
    ...
```

**Comment by plun1331** [comment]
> You cannot use `on_application_command_error` to listen for errors in other cogs.  It will only trigger if the error happens in the same cog.

All listeners are global, not cog specific.

**Comment by Ahsoka** [comment]
> > You cannot use `on_application_command_error` to listen for errors in other cogs.  It will only trigger if the error happens in the same cog.
> 
> All listeners are global, not cog specific.

My bad I stand corrected, this is in fact correct.  I did a test of this with the following code to verify this:
```py
from discord.ext import commands

import discord

class Error(commands.Cog):
    @commands.slash_command(
        description="This command will error out in the Error Cog"
    )
    async def error_cog(self, ctx: discord.ApplicationContext):
        await ctx.respond("Erroring out in Error Cog")
        raise RuntimeError('uh oh error in error cog :(')

    @commands.Cog.listener()
    async def on_application_command_error(self, ctx, error):
        embed = discord.Embed(title = "Error!" , description = f"{error}", color = discord.Color.blue())
        await ctx.respond(embed=embed, ephemeral = True)


class Commands(commands.Cog):
    @commands.slash_command(
        description="This command will error out in the Commands Cog."
    )
    async def command_cog(self, ctx: discord.ApplicationContext):
        await ctx.respond("Erroring out in Commands Cog")
        raise RuntimeError('uh oh error in commands cog :(')

test = discord.Bot(debug_guilds=[...])
test.add_cog(Error())
test.add_cog(Commands())

@test.event
async def on_ready():
    print('Bot is ready!')

test.run(...)
```

**Comment by Ahsoka** [comment]
> > Can you send more code? I have not had a problem with the on_application_command_error listener.
> 
> ```python
> import discord
> from discord.ext import commands
> import traceback
> import logging
> import sys
> from traceback import format_exception 
> from datetime import datetime
> from discord.commands import *
> 
> 
> class Error(commands.Cog):
> 
>     def __init__(self, client):
>         self.client = client
> 
> 
>     @commands.Cog.listener()
>     async def on_application_commmand_error(self, ctx, error):
>         embed = discord.Embed(title = "Error!" , description = f"{error}", color = discord.Color.blue())
>         await ctx.respond(embed=embed, ephemeral = True)
>         return
> ```
> 
> Its in a cog, but I know its loaded and it works because I have a on_command_error handler and that one works just fine

The reason this code is not working is because you have spelled "commands" wrong.  You wrote `on_application_commmand_error` with three m's instead of `on_application_command_error`.

**Comment by Ahsoka** [comment]
> > You cannot use `on_application_command_error` to listen for errors in other cogs.  It will only trigger if the error happens in the same cog.
> 
> All listeners are global, not cog specific.

But this begs the question is there a way to handle slash command errors for a specific cog?  If not this might something that might be worth adding into the library.

**Comment by krittick** [comment]
> > > You cannot use `on_application_command_error` to listen for errors in other cogs.  It will only trigger if the error happens in the same cog.
> > 
> > 
> > All listeners are global, not cog specific.
> 
> But this begs the question is there a way to handle slash command errors for a specific cog? If not this might something that might be worth adding into the library.

You could just check the value of `ApplicationContext.cog` in the error handler.

**Comment by Ahsoka** [comment]
Does anyone know if `on_command_error` for message commands was also universal of cog specific?

**Comment by Ahsoka** [comment]
It seems like it was `on_command_error` was specific to a cog errors only.  Reference: https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#event-reference

**Comment by plun1331** [comment]
> It seems like it was `on_command_error` was specific to command errors in that specific cog.  Reference: https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#event-reference 

It is not and never was. As I said **all** listeners are global.

**Comment by Ahsoka** [comment]
Yep after further testing, I stand corrected again.  It does seem odd to me that `on_command_error` and `on_application_command_error` are not specific to cogs.  Perhaps I have unusual use cases but it seems to me at least like it would be more of use to have them be specific to cogs.  Can anyone think of use case where you might want to listen for errors from another cog?

**Comment by plun1331** [comment]
> Can anyone think of use case where you might want to listen for errors from another cog?
Not making one error handler for every single cog

If you really want a cog-specific error handler, I believe you can define a `cog_command_error` method within the cog.
