### ISSUE TITLE
Member.kick() does not provide reason

### ISSUE THREAD

**Issue by AlexFlipnote** [Pycord-Development/pycord#1109]
### Summary

No reason given with a kick

### Reproduction Steps

Basically, have a kick command like this example and try to kick user with a nice reason
![](https://i.alexflipnote.dev/2SLXVDj.png)

### Minimal Reproducible Code

```python
Look above
```

### Expected Results

User would be kicked successfully **and** the reason would be provided to audit logs.

### Actual Results

![](https://i.alexflipnote.dev/6zbfX3U.png)
![](https://i.alexflipnote.dev/2SLXVDj.png)
![](https://i.alexflipnote.dev/3q3cQ9r.png)

### Intents

guilds, members, messages, bans, emojis, voice_states, reactions, message_content

## Local Windows machine
```
- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000
```

## Server which the bot runs on 
```
- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
Potentially related to some issues I uncovered while implementing #1067. Will dig into this and see.
