### ISSUE TITLE
register_command() not updating options

### ISSUE THREAD

**Issue by Miolus** [Pycord-Development/pycord#1110]
### Summary

When changing the options of a command, the command won't work anymore.

### Reproduction Steps

Create a command with multiple options.
Run bot.
Change code and remove some options.
Run bot.
Command will error now and not update the options in discord.

### Minimal Reproducible Code

```python
@command_group.command(name="start", description="start the command")
async def giveaway_start(self, ctx : ApplicationContext, channel1 : Option(SlashCommandOptionType.channel),  channel2 : Option(SlashCommandOptionType.channel)):
    await ctx.respond("working")

Switch to this command in second run:

@command_group.command(name="start", description="start the command")
async def giveaway_start(self, ctx : ApplicationContext, channel1 : Option(SlashCommandOptionType.channel)):
    await ctx.respond("working")
```

### Expected Results

Load command with one option in second run

### Actual Results

Not updating the command options and erroring on command execution.

Workaround: Fully delete the command, then readd it.

### Intents

members

### System Information

2.0.0b4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
Fixed in the master branch
