### ISSUE TITLE
Gateway v10 not sending message content when messages are fetched using `.fetch_message` or `.history` even with correct intents

### ISSUE THREAD

**Issue by AceExpert** [Pycord-Development/pycord#1111]
### Summary

Upon calling the `discord.TextChannel.fetch_message` and `discord.TextChannel.history`, the returned Message/AsyncIterator[Message], all of their `content` is empty that is `''` even with message_content intent.

### Reproduction Steps

1. Create a bot.
2. Add a command that makes use of `discord.TextChannel.fetch_message` or `discord.TextChannel.history`.
3. Print the `.content` attribute of the returned `discord.Message` / `AsyncIterator[discord.Message]`.
4. Expected output is nothing/empty which is the issue.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = commands.Bot(intents = discord.Intents.all(), prefix = '!')

@bot.command(name = 'give-content')
async def fetch_message_content(ctx, message_id: int):
  m = await ctx.channel.fetch_message(message_id)
  print(m.content) #empty

@bot.command(name = 'give-history')
async def message_history(ctx, how_many: int):
  async for message in ctx.channel.history(limit = how_many):
    print(message.content) #empty

bot.run(token)
```

### Expected Results

the message content of my message 
hehehelululz
amogus

### Actual Results

_empty_

### Intents

`discord.Intents.all()` (in short, message_content is True)

### System Information

- Python v3.8.6-final
- py-cord v2.0.0-beta (Master Branch)
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.6.3
- system info: Windows 8.1 6.3.9600

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

- This also affects the other methods that make use of `.fetch_message` or `.history` on `discord.TextChannel`s. Example: `.purge` method not being able to use `check`s based on conditions on the `message.content`.
- `.content` gives correct content when sent through `on_message` event.
- Other attributes that require `message_content` intent like `.embeds`, `.attachments` and `.components` are available when using the two methods with the issue.
- `discord.http.API_VERSION = 9` solves the issue implying this could possibly an issue on discord's end.
- I'm not aware if Discord is already aware of this and informed the developers.

**Comment by BobDotCom** [comment]
Looks like your problem is that you used "prefix" instead of "command_prefix" in the kwargs of your bot constructor. The commands never end up getting executed with the provided code. Swapping out that kwarg effectively fixed the issue in my reproduction.

**Comment by sputh-the-pigeon** [comment]
> Looks like your problem is that you used "prefix" instead of "command_prefix" in the kwargs of your bot constructor. The commands never end up getting executed with the provided code. Swapping out that kwarg effectively fixed the issue in my reproduction.

Im really sorry but, that's a totally different thing. I wrote that kwarg wrongly but in my actual code its correct and I haven't even tried it this code, this reproduction is just to make it easy 😂 please check out how im actually doing it in the screenshots in the suggestion thread and the screenshot in #discussions. Im running the code in a raw manner to show u. Secondly, I found out about this issue when i created my purge command, where i can use a regexp to check the message content for a filtered purge but turns out all `message.content`s are `''` so nothing actually gets purged. 

(Im the alt of the main issue creator)
