### ISSUE TITLE
View Timeouts incorrectly working

### ISSUE THREAD

**Issue by Wizinator** [Pycord-Development/pycord#1113]
### Summary

View Timeouts do not update, when changing from one view to another

### Reproduction Steps

Use the code pasted below to reproduce this. You will need to link it to some sort of command.

### Minimal Reproducible Code

```python
button1 = Button(style=discord.ButtonStyle.green, label="Test Button", custom_id="test")
button2 = Button(style=discord.ButtonStyle.blurple, label="Placeholder Button", custom_id="placeholder")

view_1 = View(button1, timeout=15)
view_2 = View(button2, timeout=30)

async def test_function(interaction):
    await interaction.response.edit_message(view=view_2)

async def timeout1():
    print("View_1 Timedout")

async def timeout2():
    print("View_2 Timedout")

button1.callback = test_function
view_1.on_timeout = timeout1
view_2.on_timeout = timeout2
```

### Expected Results

Expected the timeout of View_2 to be applied, when removing view_1 and adding view_2 to the message.

### Actual Results

Timeout of View_1 was applied, even though view_1 was removed from the message.

### Intents

discord.Intents.all()

### System Information

- Python v3.8.3-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Hopefull this can be fixed soon.

**Comment by Dorukyum** [comment]
Removing the View doesnt stop listening. Try using `View.stop()`.

**Comment by Dorukyum** [comment]
Closing as stale.
