### ISSUE TITLE
AttributeError: 'Message' object has no attribute 'create_thread' 

### ISSUE THREAD

**Issue by SpaceNerden** [Pycord-Development/pycord#1117]
### Summary

I tried to make a thread from a message but I got this AttributeError.

### Reproduction Steps

1: Delete `venv`
2: `python -m venv venv`
3: `source venv/bin/activate`
4: `pip cache purge`
5: `pip install -r requirements.txt`
6: Run bot
7: Get error

### Minimal Reproducible Code

```python
embed = discord.Embed(title=f"{announcement.title} ({subject.name})",
												  description=md(announcement.message))
message = await channel.send(f"New announcement! ({announcement.id})", embed=embed) #Message does send
await message.create_thread(name=f"{announcement.title} ({subject.name})")
```

### Expected Results

![image](https://user-images.githubusercontent.com/72929861/156866781-14fa68bf-4e96-4fcd-95c8-93b5043d0cb4.png)

### Actual Results

```
Unhandled exception in internal background task 'announcementsLoop'.
Traceback (most recent call last):
  File "/home/spacenerden/Code/Projects/ProjectIsla/venv/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/spacenerden/Code/Projects/ProjectIsla/cogs/Announcements.py", line 66, in announcementsLoop
    await message.create_thread(name=f"{announcement.title} ({subject.name})")
AttributeError: 'Message' object has no attribute 'create_thread'
```

### Intents

`intents = discord.Intents.all()`

### System Information

```
(venv) [spacenerden@DESKTOP-GP7FLPG ProjectIsla]$ python -m discord -v
- Python v3.10.2-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.16.11-arch1-2 #1 SMP PREEMPT Mon, 28 Feb 2022 10:17:30 +0000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The ` python -m discord -v` is from after I re-initialized the venv.

requirements.txt:
```
py-cord
python-dotenv
requests~=2.25.1
termcolor~=1.1.0
canvasapi~=2.2.0
colorama~=0.4.4
pyfiglet~=0.8.post1
python-dateutil~=2.8.1
markdownify
```
#1003's OP said that he had to re-install python to get it fixed. However, after running `pip list` on both in the venv and normally, discord.py was not in any of them. I want to avoid reinstalling python as it takes a ridiculous amount of time on my laptop.

**Comment by krittick** [comment]
You're using the 1.7.3 version of pycord (which is the same thing as discord.py 1.7.3), but `create_thread` was added in 2.0. You'll want to do the following to make sure you're actually using the latest version of pycord:

`pip uninstall py-cord`
`pip uninstall discord.py`
`pip install py-cord==2.0.0b4` (or `pip install git+https://github.com/Pycord-Development/pycord` for the latest `master` branch)

**Comment by SpaceNerden** [comment]
Thanks!

Just a quick question, why did pip install 1.7.3 instead of 2.0? Because its still in beta?

**Comment by plun1331** [comment]
> Thanks!
> 
> Just a quick question, why did pip install 1.7.3 instead of 2.0? Because its still in beta?

It's marked as a pre-release on PyPi, therefore pip considers it unstable and installs the latest stable version

You can include pre releases by adding the `--pre` flag to `pip install`
