### ISSUE TITLE
Extend timeout

### ISSUE THREAD

**Issue by UP929312** [Pycord-Development/pycord#1125]
### Summary

Add the ability to do member.extend_timeout()

### What is the feature request for?

The core library

### The Problem

Currently, to do this (while it may seem trivial for everyone to implement individually), there's a few cases which make this more awkward, e.g. the communication_disabled_until can be a negative timedelta/datetime.

This helper function would aid in extending the timeout, which appears to be a semi-common use case with timeouts.

### The Ideal Solution

Currently you have to:
Create a timedelta object,
Check if communications_disabled_until is not None
Check if communication_disabled_until > datetime.now(timezone.utc)
If both of these are true, increase the timedelta object to the difference between now and when it should expire
await member.timeout_for(duration/extended_duration, reason=...)

It would be much easier and cleaner if you could do

`duration = timedelta(hours=5)`
`await member.extend_timeout(for=duration)`

### The Current Solution

Implement the above, probably in a utils function/file

**Comment by Iinksafe** [comment]
This keyword-only argument would raise a SyntaxError, because it is an statement for `for` loops.
![image](https://user-images.githubusercontent.com/78565096/156939572-ba2f571f-57e8-41cb-a2bb-059b067a31bf.png)

**Comment by UP929312** [comment]
Ah, good point, maybe even just duration= then
So allow duration=, or until=

**Comment by plun1331** [comment]
This really isn't difficult to do yourself:
```py
if member.timed_out:
    # if they're timed out, communication_disabled_until can't be None
    await member.timeout(member.communication_disabled_until + duration)
else:
    await member.timeout_for(duration)
```

**Comment by UP929312** [comment]
> This really isn't difficult to do yourself:
> 
> ```python
> if member.timed_out:
>     # if they're timed out, communication_disabled_until can't be None
>     await member.timeout(member.communication_disabled_until + duration)
> else:
>     await member.timeout_for(duration)
> ```

As I said in the original message,
