### ISSUE TITLE
Full Guild Stickers Support

### ISSUE THREAD

**Issue by SunkenSplash** [Pycord-Development/pycord#113]
### Summary

Add full support for sending guild stickers, modifying stickers of a guild, etc.

### What is the feature request for?

The core library

### The Problem

Stickers have been part of Discord for quite a while and discord.py (now pycord) has not seen their full implementation as of yet. Bots are allowed by Discord to send guild stickers (not default Discord stickers) and other libraries have implemented this already (discord.js) in addition to allowing bots to manage guild stickers. Discord.py is only able to get some information on stickers, while not being able to send them or edit the guild's stickers.

### The Ideal Solution

Full implementation of stickers should be added to pycord. This includes the ability for bots to both send and edit the guild's stickers, along with any other functionality the Discord API provides in regards to stickers.

### The Current Solution

Other than making manual API requests directly to the Discord API to send stickers or edit a guild's stickers, there is no implementation of stickers aside from the ability for bots to view information on them.

**Comment by nerdguyahmad** [comment]
Stickers are implemented in master branch iirc. You can send them, delete or create guild stickers, fetch them etc. Although I think the ability of editing guild stickers isn't yet implemented.
