### ISSUE TITLE
Discord.py is back

### ISSUE THREAD

**Issue by Ender2K89** [Pycord-Development/pycord#1142]
### Summary

remove this library

### What is the feature request for?

The core library

### The Problem

Discord.py is back and now Pycord or whatever it's called is useless, this is a very bad fork of discord.py and it should be deleted.

### The Ideal Solution

https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository

### The Current Solution

https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository

**Comment by ksIsCute** [comment]
kek

**Comment by EmreTech** [comment]
No, it is not useless. So far discord.py's implementation of slash commands isn't the best for most people, and it's very new and probably prone to bugs. Plus, so far Pycord has implemented more features compared to discord.py. So no, Pycord is not useless anymore, in fact, it's still a good discord.py alternative.

**Comment by Ender2K89** [comment]
Yes, it is useless, discord.py's implementation of slash commands isn't meant for morons like you.

**Comment by EmreTech** [comment]
Don't. Their implementation is so verbose and isn't really well suited for beginners.

**Comment by TigerNinja22** [comment]
This dude just hates Py-cord, doesn't he?
Py-cord is a well-maintained fork of discord.py and is quite well in what it does. Discord.py's slash implementation isn't exactly the best and it hasn't completely caught up to the new updates either.

Also, would you mind not being so rude to other people here?

**Comment by Ender2K89** [comment]
what is this + L + ratio + wrong + get a job + unfunny + you fell off + never liked you anyway + cope + ur allergic to gluten + don't care + cringe ur a kid + literally shut the fuck up + galileo did it better + your avi was made in MS Excel + ur bf is kinda ugly + i have more subscribers + owned + ur a toddler + reverse double take back + u sleep in a different bedroom from your wife + get rekt + i said it better + u smell + copy + who asked + dead game + seethe + ur a coward + stay mad + you main yuumi + aired + you drive a fiat 500 + the hood watches xqc now + yo mama + ok + currently listening to rizzle kicks without u. plus ur mind numbingly stupid plus ur voice is ronald mcdonald.

**Comment by ksIsCute** [comment]
![im jut watching](https://i.imgur.com/J1tTYZs.png)

**Comment by Ender2K89** [comment]
Discord.py >>>> Nextcord >>>> Pycord
This isn't my personal opinion, it's the right opinion, cry about it, you Pycord stans.

**Comment by ksIsCute** [comment]
![sad](https://i.imgur.com/GNxPxLU.png)

**Comment by Dorukyum** [comment]
What does doing this grant you? Feeling of power? Intelligence? Superiority?
All this does is show us how bad the community has become. What's wrong with people? It's okay to share your opinion, just not like this.
