### ISSUE TITLE
get information of PSPs

### ISSUE THREAD

**Issue by ksIsCute** [Pycord-Development/pycord#1143]
### Summary

custom profiles, about mes, and avatars per server

### What is the feature request for?

discord.ext.commands

### The Problem

With the recent (ish) push of per server profiles, there should be an attribute to `member`, `author` and / or `bot` depending on the user.

### The Ideal Solution

Just adding a new attribute to author, member, and / or bot like `server.avatar.url` and `server.about_user` if possible and if it doesnt conflict with other attributes. this could work the same with anything else the idea could work with, as there is already a display_name feature for nicknames, this seems like a good idea. But, prove me wrong and close this if it isnt.

**Comment by Middledot** [comment]
Per-guild avatars are available through `Member.guild_avatar`
and banners are available through `User.banner` (but only usable after fetching the user)

About-mes aren’t given at the moment
