### ISSUE TITLE
Slash Commands Permissions don't work sometimes

### ISSUE THREAD

**Issue by AwesomeSam9523** [Pycord-Development/pycord#1155]
### Summary

The permissions aren't registered correctly.

### Reproduction Steps

So I have 2 bots. 1 main bot and other beta bot.
I tested out `@permissions.has_role` on a slash commnad.

Here is the code: (Same on both bots)
```py
@slash_command(default_permission=False)
@permissions.has_role(868890524755582995)
async def bgpanel(
    self,
    ctx: ApplicationContext,
    type_: discord.Option(str, description='Type of panel- pbg or cbg.', name='type', choices=['Personal BG', 'Clan BG']),
    name: discord.Option(str, description='Name of the background.')
):
    '''
    This is a developer/staff command. Top secret!!!
    '''
    ...
```

The permission works on beta bot but not on main bot.
This is to note that I also have `debug_guilds=[...]` for my beta bot.

This is also to mention that its been 2-3 hours since the main bot was started. No restarts in between.

### Expected Results

The command permissions should work on both equally.

### Actual Results

![image](https://user-images.githubusercontent.com/76945339/157685411-9938a4b2-9a7e-4610-8438-6168bd3390d9.png)
Works only on beta bot.

### Intents

intents = discord.Intents(guild_reactions=True, guild_messages=True, guilds=True, dm_messages=True, members=True)

### System Information

```sh
- Python v3.8.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Linux 5.11.0-1029-gcp #33~20.04.3-Ubuntu SMP Tue Jan 18 12:03:29 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AwesomeSam9523** [comment]
Update: 6 hours and still not accessible.

**Comment by tkuye** [comment]
I'm experiencing a similar issue as well as once I made the commands global, the permissions were loading incorrectly.

**Comment by DaTurr3t** [comment]
Same. Something that seemed odd to me is that there is a section in Bot.sync_commands, which seems to handle global commands but is not triggered unless there are some guild-specific ones. I was unable to replicate this tho, Im gonna try to modify the routine anyways

**Comment by TurnrDev** [comment]
I have a similar issue, I have used `@permissions.is_owner()` but the command is available to all

```py
    @_cog_control.command(name="list", default_permission=False)
    @permissions.is_owner()
    async def list_cogs(self, ctx: ApplicationContext) -> None:
        """List all cogs."""
        ...
```

**Comment by DaTurr3t** [comment]
Update: looks like the current permission model only supports guild-specific permissions. Code to register global permissions is not run when not registering to a specific guild. We'll se what [permissions v2](https://github.com/Pycord-Development/pycord/pull/1183)  will give us.

**Comment by BobDotCom** [comment]
All effort on the permissions front will be put towards v2, as v1 will be deprecated soon. No plans to fix this as it's soon to be obsolete.
