### ISSUE TITLE
mention in embed

### ISSUE THREAD

**Issue by ArtyomKor** [Pycord-Development/pycord#1162]
### Summary

bug in embed

### Reproduction Steps

I mentioned the user in the embed

### Minimal Reproducible Code

```python
embed.add_field(name=f"Player: {ctx.author.mention}", value="⬛|⬛|⬛\n------------\n⬛|⬛|⬛\n------------\n⬛|⬛|⬛")
```

### Expected Results

I expected: @PlayerName

### Actual Results

<@!playerid>

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by tcprescott** [comment]
Are you allowed to even have mentions in the name of an embed field?

**Comment by Lulalaby** [comment]
This is an client side caching problem.
