### ISSUE TITLE
`ApplicationContext.respond` not working with preset None

### ISSUE THREAD

**Issue by Snawe** [Pycord-Development/pycord#1169]
### Summary

`ApplicationContext.respond` is using `None` as default value  on response and `Missing` as default value on respond

### Reproduction Steps

I am using a wrapper function like:
```py
    async def channel_send(self, ctx, embed = None, content = None, view = None, ephemeral = None, file = None):
            if isinstance(ctx, discord.ext.commands.context.Context):
                message = await ctx.channel.send(content=content,
                    embed=embed,
                    view=view,
                    file=file)
            elif isinstance(ctx, discord.commands.ApplicationContext):
                await ctx.respond(content=content,
                    embed=embed,
                    view=view,
                    ephemeral=ephemeral,
                    file=file)
```
to support both slash and prefix commands.
And that does not work if I do a followup (example with `ctx.defer()`

That works:
```py
        await ctx.defer()
        embed=discord.Embed(title="test")
        await ctx.respond(embed=embed)
```
This does not
```py 
        await ctx.defer()
        embed=discord.Embed(title="test")
        await channel_send(ctx, embed=embed)
```
Whoever, this does:
```py
        embed=discord.Embed(title="test")
        await channel_send(ctx, embed=embed)
```

I guess the issue is that on followup `handle_message_parameters` expects that those parameters are `MISSING`
```py
def handle_message_parameters(
    content: Optional[str] = MISSING,
    *,
    username: str = MISSING,
    avatar_url: Any = MISSING,
    tts: bool = False,
    ephemeral: bool = False,
    file: File = MISSING,
    files: List[File] = MISSING,
    attachments: List[Attachment] = MISSING,
    embed: Optional[Embed] = MISSING,
    embeds: List[Embed] = MISSING,
    view: Optional[View] = None,
    allowed_mentions: Optional[AllowedMentions] = MISSING,
    previous_allowed_mentions: Optional[AllowedMentions] = None,
) -> ExecuteWebhookParameters:
```
where on response they are expected as `None`
```py
    async def send_message(
        self,
        content: Optional[Any] = None,
        *,
        embed: Embed = None,
        embeds: List[Embed] = None,
        view: View = None,
        tts: bool = False,
        ephemeral: bool = False,
        allowed_mentions: AllowedMentions = None,
        file: File = None,
        files: List[File] = None,
        delete_after: float = None,
    ) -> Interaction:
```

### Expected Results

Successfull print of "Test" :)

### Actual Results

'NoneType' object has no attribute 'fp'

### Intents

all

### System Information

- Python v3.9.4-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.7.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
I'll look into this error some more, but you might want to consider using ext.bridge (see #1131) for command compatibility instead. It'll be fully released soon.

**Comment by EmreTech** [comment]
ext.bridge is out now, please try that and see if it works
