### ISSUE TITLE
Strange Behavior Of Interaction.user.roles

### ISSUE THREAD

**Issue by Icebluewolf** [Pycord-Development/pycord#1172]
### Summary

`Interaction.user.roles` returns `[None]` No matter how many roles the user has

### Reproduction Steps

Retrieve the interaction data from a button press (persistent button in my case) and access `user.roles`.

### Minimal Reproducible Code

```python
import discord

class RoleButton(discord.ui.Button):
    def __init__(self):
        super().__init__(label="Button", style=discord.enums.ButtonStyle.primary)

    async def callback(self, interaction: discord.Interaction):
        print(interaction.user.roles)

class ButtonRoleCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command(guild_ids=[...])
    async def post(self, ctx: commands.Context):
        view = discord.ui.View(timeout=None)
        view.add_item(RoleButton())

        await ctx.respond("Click The Button", view=view)

def setup(bot):
    bot.add_cog(ButtonRoleCog(bot))
```

### Expected Results

If user had no roles: a list with one item being the guilds default (@ everyone) role object.

If the user had roles: the above with added role objects based on the roles

### Actual Results

No matter how many roles the user had a list of one `None` item 
`[None]`

### Intents

Members

### System Information

- Python v3.9.6-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I think the issue is in the Interactions class 
https://github.com/Pycord-Development/pycord/blob/master/discord/interactions.py#L176-L190
```py
       # TODO: there's a potential data loss here
        if self.guild_id:
            guild = self.guild or Object(id=self.guild_id)
            try:
                member = data["member"]  # type: ignore
            except KeyError:
                pass
            else:
                self.user = Member(state=self._state, guild=guild, data=member)  # type: ignore
                self._permissions = int(member.get("permissions", 0))
        else:
            try:
                self.user = User(state=self._state, data=data["user"])
            except KeyError:
                pass
```

**Comment by Middledot** [comment]
Do you have the `guilds` intent on?

**Comment by Icebluewolf** [comment]
No :/
