### ISSUE TITLE
cannot style link buttons

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#1176]
### Summary

I am unable to style link buttons. Im not sure if this is a bug or an api feature that does not exist

### Reproduction Steps

create a view with a button and specify a style. example blurple. it does not apply it and just uses the secondary style

### Minimal Reproducible Code

```python
view = discord.ui.View(discord.ui.Button(style=discord.ButtonStyle.blurple, label="Click Me", 
                                                 url=f'https://myurl.com'))
```

### Expected Results

to style the button

### Actual Results

used the default secondary style instead

### Intents

all

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Snawe** [comment]
Thats a Discord limitation and not a lib bug
