### ISSUE TITLE
Unable to edit PartialMessage's embed on 2.0.0b5

### ISSUE THREAD

**Issue by argo0n** [Pycord-Development/pycord#1182]
### Summary

I am unable to edit a PartialMessage's embed on Pycord's 2.0.0b5 version, although editing the content works.

### Reproduction Steps

1) Send a message
2) Get the partial message through get_partial_message(message id)
3) edit the partial message with `.edit(embed=embed)`

### Minimal Reproducible Code

```python
import asyncio
embed = discord.Embed(title="Alpha")
msg = await ctx.send("Alpha", embed=embed)
await asyncio.sleep(1.0)
partialmsg = ctx.channel.get_partial_message(msg.id)
embed.title = "Bravo"
await partialmsg.edit(content = "Bravo", embed=embed)
```

### Expected Results

When editing the message, both the content and the embed gets edited.

### Actual Results

Only the content got edited. If you only pass `embed` and not `content`, the same thing happens.

### Intents

discord.Intents(guilds = True, members = True, presences = True, messages = True, reactions = True, emojis = True, invites = True, voice_states = True, message_content = True)

### System Information

- Python v3.8.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Editing the partial message still works on 2.0.0b4 and lower.

Here's a video: https://cdn.discordapp.com/attachments/871737314831908974/954658593217585172/2022-03-19_16-30-36.mp4

**Comment by Tiffinini** [comment]
Ran into this same issue today which is what led me here. No attempts to push embed changes via the .edit method of a partial message appear to work in b5.

**Comment by argo0n** [comment]
Just found out setting `discord.http.API_VERSION = 9` is a workaround for this problem, so I'm assuming it's a problem with the HTTP state/API?

**Comment by argo0n** [comment]
Thank you so much for fixing it!
