### ISSUE TITLE
bot.wait_for not working in pre version 2.0.0b5

### ISSUE THREAD

**Issue by evanpurl** [Pycord-Development/pycord#1184]
### Summary

updated from the previous preview version to 2.0.0b5, now bot.wait_for is no longer allowing you to get content.

### Reproduction Steps

![image](https://user-images.githubusercontent.com/19613096/159141742-0b4cc7ce-0b4f-400e-9206-66a42813fb12.png)

Typing this code for me does the same thing every time, does not pull the content from the wait_for function.

I tried printing just the message object that was waited for, there is no longer a content tag that shows the message content.

### Minimal Reproducible Code

```python
name = await bot.wait_for('message', check=None, timeout=300)
print(name)
```

### Expected Results

The content of the waited for message to be available using this code
![image](https://user-images.githubusercontent.com/19613096/159141844-f00de01f-6272-49f1-a9a8-a31bffa9c8fc.png)

### Actual Results

The content of the message is not available.
![image](https://user-images.githubusercontent.com/19613096/159141853-a41fe8d8-bb3a-4af7-ad7e-022d796d8bc0.png)

### Intents

Server Members, Message content, Presence

### System Information

![image](https://user-images.githubusercontent.com/19613096/159141821-62632342-3b65-47b7-a809-f784958874af.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

It seems to only be an issue with wait_for functions. But I can't fully tell.

**Comment by plun1331** [comment]
Are you sure you have the message content intent enabled?

**Comment by evanpurl** [comment]
> Are you sure you have the message content intent enabled?

I am sure, I double checked before submitting. I didn't change anything in the development portal from the last time this worked.

**Comment by evanpurl** [comment]
What it shows when I print the message object:
`<Message id=* channel=<TextChannel id=*name='wbtest' position=21 nsfw=False news=False category_id=*> type=<MessageType.default: 0> author=<Member id=* name='*' discriminator='*' bot=False nick=None guild=<Guild id=*name='*' shard_id=0 chunked=False member_count=7>> flags=<MessageFlags value=0>>`

**Comment by evanpurl** [comment]
And finally, I did just uninstall the latest version, reinstalled 2.0.0b4 and tried my code and it worked.

**Comment by Dorukyum** [comment]
Cannot reproduce with the master branch.

**Comment by BobDotCom** [comment]
> > Are you sure you have the message content intent enabled?
> 
> I am sure, I double checked before submitting. I didn't change anything in the development portal from the last time this worked.

This appears to be intended functionality.

Beta 5 implemented support for the v10 gateway which requires the message content intent, so you do need to change intents both in the developer portal and in your code. Make sure you have the message content intent enabled in discord, and please send the code you used to initialize your intents.

**Comment by evanpurl** [comment]
> 

This was probably the issue, can't believe I forgot to put the intents into my code. I'll test it when I have time to, thank you.

**Comment by evanpurl** [comment]
![image](https://user-images.githubusercontent.com/19613096/159840069-16cfe7e5-f1a8-4bb9-a488-06cceba7c944.png)
![image](https://user-images.githubusercontent.com/19613096/159840132-54f57d8f-625b-4726-98dc-119abca2d159.png)

Let me know if I'm doing anything wrong, I would love to know how to do it correctly.

**Comment by evanpurl** [comment]
https://docs.pycord.dev/en/master/intents.html

I looked here for how I put the intents into my code

**Comment by plun1331** [comment]
> ![image](https://user-images.githubusercontent.com/19613096/159840069-16cfe7e5-f1a8-4bb9-a488-06cceba7c944.png)
> ![image](https://user-images.githubusercontent.com/19613096/159840132-54f57d8f-625b-4726-98dc-119abca2d159.png)
> 
> Let me know if I'm doing anything wrong, I would love to know how to do it correctly.

You need to specify the `message_content` intent

**Comment by evanpurl** [comment]
How do I put that, is it message_content=True in the discord.Intents line?

**Comment by plun1331** [comment]
> How do I put that, is it message_content=True in the discord.Intents line?

Try it and see

**Comment by evanpurl** [comment]
![image](https://user-images.githubusercontent.com/19613096/159841990-3a9f16d4-dd9e-4468-9ce2-ba70062e6042.png)
![image](https://user-images.githubusercontent.com/19613096/159842006-64db1835-a3e0-409e-ac35-e24cd94d39ab.png)

That didn't work

**Comment by evanpurl** [comment]
![image](https://user-images.githubusercontent.com/19613096/159843780-734b711a-e7fb-42ab-9d67-3597ae80765d.png)
I ended up putting discord.Intents.all(), but I now receive this error. Not sure what is causing it.

**Comment by evanpurl** [comment]
![image](https://user-images.githubusercontent.com/19613096/159845483-b21b0d8b-b450-454f-af4b-f3e09a2be3f0.png)

changing intents = to discord.Intents.all() fixed it.
