### ISSUE TITLE
slash-commands initialization on b5 doest workt all the time

### ISSUE THREAD

**Issue by TominoLP** [Pycord-Development/pycord#1187]
### Summary

rollback the command register to b4 -_-

### Reproduction Steps

initialization a slash comm in a cogs extension 

### Expected Results

[Discord Error 403 error code: 50001 Missing Access](https://stackoverflow.com/questions/71543862/discord-error-403-error-code-50001-missing-access)

### Actual Results

command will not register

### Intents

intents=discord.Intents.all()

### System Information

- Python v3.10.3-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4 (switcht from b5)
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Fabio3323-cmd** [comment]
I have the same problem. I get errors all the time with Unknown interaction, the bot is extremely slow and works very slowly.

**Comment by shplack** [comment]
I've had problems with `Discord Error 403 error code: 50001 Missing Access` as well. The solution I found was to tick the box for `applications.commands` when choosing permissions for the bot url generator in the developer portal.

![image](https://user-images.githubusercontent.com/62137686/161404299-f11573ad-c6c9-47ff-8b73-7a309c76f5ea.png)

**Comment by EmreTech** [comment]
@TominoLP it seems that you forgot to toggle the `application.commands` box when making the OAuth2 link. That is required in order to make Application Commands and manage them.

**Comment by TominoLP** [comment]
> @TominoLP it seems that you forgot to toggle the `application.commands` box when making the OAuth2 link. That is required in order to make Application Commands and manage them.

No, that was also my first thought 
But im 100% that it was enabled 

On the pycord discors in help-2 i send a screenshot i think

**Comment by shplack** [comment]
> No, that was also my first thought 
> But im 100% that it was enabled 
> 
> On the pycord discors in help-2 i send a screenshot i think
> 
Have you double checked the permissions of the bot on the discord channel? 

It would be nice if pycord had some better error outputs if possible to be able to tell which permission was tried and denied

**Comment by BobDotCom** [comment]
Please provide a minimal reproducible code sample so we can try to investigate this some more.

**Comment by cannonballchris** [comment]
I am sure the slash commands don't register at all in b5. The commands cannot be initialized aka if we just have lets say a SlashCommand group, the commands are never registered to the discord.
