### ISSUE TITLE
Add a changelog for each version

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1191]
### Summary

It would be very nice to see a changelog for each version of this library.

### What is the feature request for?

The documentation

### The Problem

Currently, I have no idea what has been added or changed in each version other than just analyzing every commit between the last and current version.  This makes it difficult to determine if I can update the library to the latest beta version and not have my bot crash.  Additionally, it also makes it difficult to determine if some breaking changes were made, what those changes even were in the first place.

### The Ideal Solution

Please add a changelog with each new version. I understand this library is still in beta but I don't think that's a good reason to not have a changelog.

### The Current Solution

None, other than analyzing all the commits.

**Comment by Ahsoka** [comment]
Also if possible, it would be much appreciated if this changes also happened retroactively to previously released versions.

**Comment by BobDotCom** [comment]
We do have changelogs. We plan to have a complete changelog for 2.0 stable when it releases. https://docs.pycord.dev/en/master/whats_new.html

**Comment by Ahsoka** [comment]
> We do have changelogs. We plan to have a complete changelog for 2.0 stable when it releases. https://docs.pycord.dev/en/master/whats_new.html

Hello,
I was referring to adding change logs to all the beta version, such  as `v2.0.0b4` or `v2.0.0b5`. Currently I have no idea what the difference between `v2.0.0b4` and `v2.0.0b5` without looking at every commit between each version.

**Comment by Dorukyum** [comment]
A brief summary of changes is posted in the Discord server when a new beta version is released.

**Comment by Ahsoka** [comment]
> A brief summary of changes is posted in the Discord server when a new beta version is released.

Oh excellent, if this could be copy and pasted to the versions on PyPi and the [GitHub Release page](https://github.com/Pycord-Development/pycord/releases) that would be much appreciated.

Thank you!

**Comment by Dorukyum** [comment]
Comparison between beta versions can be done on the [tags page](https://github.com/Pycord-Development/pycord/tags) and a changelog will be published for stable releases.

**Comment by krittick** [comment]
We're also planning to implement weekly changelogs for `master` once 2.0 stable is out, in the event that it takes longer than a week between stable releases.

**Comment by BobDotCom** [comment]
https://github.com/Pycord-Development/pycord/releases
