### ISSUE TITLE
commands.cooldown not working with slash commands

### ISSUE THREAD

**Issue by Fallcrim** [Pycord-Development/pycord#1197]
### Summary

The commands.cooldown decorator doesn't work on slashcommands

### Reproduction Steps

Create a slashcommand and use the @commands.cooldown(args) decorator on it

### Minimal Reproducible Code

```python
@slash_command()
@commands.cooldown(1, 20, commands.BucketType.user)
async def the_command(args):
...
```

### Expected Results

Raise cooldown error if command is executed within the cooldown

### Actual Results

Nothing. The command could be used as usual and no error was logged

### Intents

all

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by argo0n** [comment]
I'm able to reproduce too, but it's intermittent; some of my slash commands have cooldowns while others don't and it's always the same commands that have cooldown issues. 

For some reason, some of my prefixed commands has no cooldown either, not sure if it's related to this.

**Comment by Fallcrim** [comment]
> I'm not able to reproduce, cooldowns work in my slash commands, I use a cog just letting you know and I use py-cord `2.0.0b1`.

I tried to reinstall b1 and retried but I got the same result

**Comment by Fallcrim** [comment]
So, does anyone from the main dev team know where the issue comes from? I'm always updating to the latest github version but it still doesn't work

**Comment by argo0n** [comment]
If anyone's still following this thread, this method works on 2.0.0! https://github.com/Pycord-Development/pycord/issues/1511#issuecomment-1189628333

**Comment by Fallcrim** [comment]
Addition: Cool-down now working when upgrading to the newest versions, no matter what function
