### ISSUE TITLE
Unable to use Slash Command on mobile

### ISSUE THREAD

**Issue by Ricardolcm888** [Pycord-Development/pycord#1210]
### Summary

Slash Commands come back with "This application didn't respond" on mobile while it works on PC

### Reproduction Steps

Write a code of a simple slash command like the following:

```py
@client.slash_command(name="ping", description="Show the bot latency")
async def ping(ctx):
    await ctx.respond(f"Pong! {round(bot.latency * 1000)}ms
```

Use a mobile phone to run the command.

### Minimal Reproducible Code

```python
@client.slash_command(name="ping", description="Show the bot latency")
async def ping(ctx):
    await ctx.respond(f"Pong! {round(bot.latency * 1000)}ms
```

### Expected Results

Reply "Pong! 9ms"

### Actual Results

Throw out an error showing "This interaction failed."

### Intents

discord.Intents.all()

### System Information

- Python v3.10.3-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The bot console doesn't show any errors occurred, and the codes are correct, no internet issues.

**Comment by Fallcrim** [comment]
Are you sure this isn't a bug on the Discord clientside?

**Comment by Ricardolcm888** [comment]
> Are you sure this isn't a bug on the Discord clientside?

I am not sure but I make my bots with pycord library and it doesn't allow me to use slash commands on mobile.

**Comment by Ricardolcm888** [comment]
> Are you sure this isn't a bug on the Discord clientside?

I am not sure but I make my bots with pycord library and it doesn't allow me to use slash commands on mobile.

**Comment by BobDotCom** [comment]
Client versions are unrelated to Pycord. This is a discord issue. Try updating your device.
