### ISSUE TITLE
CommandPermission Only Working In Specific Guild

### ISSUE THREAD

**Issue by AmirAvram** [Pycord-Development/pycord#1213]
### Summary

When having multiple SlashCommandGroups with CommandPermission (one of them with guild limitation) the commands that are not guild limited will be greyed out

### Reproduction Steps

Add the bot to at-least two guilds, one with the used in the SlashCommandGroup with the guild limitation and another for the SlashCommandGroup without the guild limitation to see the bug.

### Minimal Reproducible Code

```python
from datetime import datetime

import discord
from discord import AutoShardedBot, Option
from discord.commands import SlashCommandGroup, CommandPermission
from discord.ext import commands

allowed_user_ids_for_command = []  # your user id goes here
admin_commands_guild_id_list = []  # the admin guild goes here
bot_token = "TOKEN HERE"


class Beta(commands.Cog):
    def __init__(self, bot: AutoShardedBot):
        self.bot = bot

    name = 'beta'
    permissions = [CommandPermission(id=member_id, type=2, permission=True) for member_id in
                   allowed_user_ids_for_command]
    beta = SlashCommandGroup(name, "Various beta tester commands", permissions=permissions)

    @beta.command()
    async def print(self, ctx: discord.ApplicationContext, msg: Option(str, "The message to print")):
        await ctx.channel.send(msg)


class Admin(commands.Cog):
    def __init__(self, bot: AutoShardedBot):
        self.bot = bot

    name = 'admin'
    permissions = [CommandPermission(id=member_id, type=2, permission=True) for member_id in
                   allowed_user_ids_for_command]
    admin = SlashCommandGroup(name, "Various Admin commands", permissions=permissions,
                              guild_ids=admin_commands_guild_id_list)

    @admin.command()
    async def print_admin(self, ctx: discord.ApplicationContext, msg: Option(str, "The message to print")):
        await ctx.channel.send(msg)


class MyClient(discord.AutoShardedBot):
    def __init__(self):
        intents = discord.Intents.default()
        intents.members = True
        super().__init__(intents=intents)  # shard_count=2 if needed for tests
        self.on_ready_start_time = datetime.now()

    async def on_ready(self) -> None:
        time_delta = datetime.now() - self.on_ready_start_time
        print(f'on_ready took {round(time_delta.total_seconds(), 3)} seconds')
        print(f"Logged on as {self.user}")


if __name__ == '__main__':
    client = MyClient()
    for cog in [Admin, Beta]:
        client.add_cog(cog(client))
    client.run(bot_token)
```

### Expected Results

I expected the admin commands to be available only in the admin guild and only to users with user_id inside allowed_user_ids_for_command, and beta commands to be available everywhere (but only usable to users in admin_commands_guild_id_list)

### Actual Results

Admin and beta commands work as expected in the admin guild, admin commands are indeed not available in the none admin guild, but the beta commands should be useable in the none admin guild and are currently greyed out

Admin Guild Results:
![image](https://user-images.githubusercontent.com/7930622/160906718-b32399f7-6c07-468f-8bd1-b25a416cb51c.png)
![image](https://user-images.githubusercontent.com/7930622/160906693-1ced43b7-dfaa-4f6a-8771-0a4a5ed3527e.png)

None Admin Guild Results:
![image](https://user-images.githubusercontent.com/7930622/160907172-2d3beb99-3889-4668-a516-864129bd9f2f.png)

### Intents

members

### System Information

- Python v3.9.4-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
Command permissions v1 will be deprecated soon, replaced by command permissions v2. Won't fix.

**Comment by AmirAvram** [comment]
> Command permissions v1 will be deprecated soon, replaced by command permissions v2. Won't fix.

From what I understood looking at `permissions-v2` branch theres no way to use custom permissions anymore (allowing specific user_ids), only checking discord role permissions and guild restrictions, is that correct?

Thats not very much useful as some commands should be accessed only by bot maintainers and support teams for many purposes including helping users and debugging.

Is that a new discord-api restriction or pycord one?
