### ISSUE TITLE
`on_error` for `discord.ui.Modal` does not work

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1216]
### Summary

`on_error` method is not called when there is an error in the `callback` method of the `discord.ui.Modal`

### Reproduction Steps

See the minimal reproducible code.

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot(debug_guilds=[...])

class Modal(discord.ui.Modal):
    def __init__(self):
        super().__init__('testing')
        self.add_item(discord.ui.InputText(style=discord.InputTextStyle.long, label='stuff'))

    async def callback(self, interaction: discord.Interaction):
        raise RuntimeError()

    async def on_error(self, error: Exception, interaction: discord.Interaction):
        print(f'error was: {error!r}')

@bot.slash_command()
async def test_modal(ctx: discord.ApplicationContext):
    await ctx.send_modal(Modal())

@bot.event
async def on_ready():
    print(f"{bot.user} is ready!")


bot.run(...)
```

### Expected Results

Whenever there is an unhandled error in the `callback` method it should activate the `on_error` method.

### Actual Results

The `on_error` method is not called and the following error appears on the console:
```py
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<ModalStore.dispatch() done, defined at C:\ProgramData\Anaconda3\lib\site-packages\discord\ui\modal.py:181> exception=RuntimeError()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\ui\modal.py", line 197, in dispatch
    await value.callback(interaction)
  File "C:\Users\AA12 Louqe\Google Drive\Coding\Github Repositories\Clovis\test-modals.py", line 11, in callback
    raise RuntimeError()
RuntimeError
```

### Intents

Intents are not relevant here

### System Information

Python Version: 3.9.7
OS: Windows 10
Pycord Version: 2.0.0b5

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is briefly mentioned in #1001

**Comment by Dorukyum** [comment]
This method has been added after beta 5 was released, beta 6 should be coming soon.

**Comment by Ahsoka** [comment]
> This method has been added after beta 5 was released, beta 6 should be coming soon.

Could you paste the link to the commit? Thanks.

**Comment by Dorukyum** [comment]
Here: https://github.com/Pycord-Development/pycord/commit/ceb23a5311bfcecb8ccdd1e2bb6b7de1072f7e98
