### ISSUE TITLE
Link Buttons are changing there position, after making interaction and stopping them or timeout...

### ISSUE THREAD

**Issue by Zaeem20** [Pycord-Development/pycord#1223]
### Summary

Buttons with URL are changing there position after doing an interaction and stopping them

### Reproduction Steps

```py
class HelpMenu(discord.ui.View):
    def __init__(self, ctx: commands.Context, embeds: namedtuple, timeout: int):
        super().__init__(timeout=timeout)
        self.ctx = ctx
        self.embed = embeds
        self.message: discord.Message = None
        support = Button(label='Support', url='https://discord.gg/zbRrTm97Sm')
        addme = Button(emoji='🤖',url="https://discord.com/oauth2/authorize?client_id=783788636969238560&permissions=4265607167&scope=bot%20applications.commands")
        self.add_item(support)
        self.add_item(addme)

    @discord.ui.select(
        placeholder='Choose Help Menu',
        options=[
            SelectOption(
                label='Home',
                value='index',
                description='Return To Index',
                emoji='🏠'
            ),
            SelectOption(
                label='Moderation',
                value='mod',
                description='List of Moderation commands',
                emoji='🚨'
            ),
            SelectOption(
                label='Utility',
                description='Utility commands list',
                emoji='🛠'
            ),
            SelectOption(
                label='Ethical Hacking',
                value='hacking',
                description='All Hacking Stuffs commands.',
                emoji='💻'
            ),
            SelectOption(
                label='Music',
                description='List of Music commands.',
                emoji='🎧'
            ),
            SelectOption(
                label='Admin',
                description="Guild owner only can use this",
                emoji='🛡'
            )
        ], row=2, custom_id='selectmenu')
    async def menu_callback(self, select, interaction: discord.Interaction):
        selected = select.values[0]
        if selected == 'index':
            await interaction.response.edit_message(embed=self.embed.index)
        elif selected == 'mod':
            await interaction.response.edit_message(embed=self.embed.mod)
        elif selected == 'Utility':
            await interaction.response.edit_message(embed=self.embed.utility)
        elif selected == 'hacking':
            await interaction.response.edit_message(embed=self.embed.hack)
        elif selected == 'Music':
            await interaction.response.edit_message(embed=self.embed.music)
        elif selected == 'Admin':
            await interaction.response.edit_message(embed=self.embed.admin)

    @discord.ui.button(emoji='🏠', style=discord.ButtonStyle.green)
    async def home_callback(self, button, interaction: discord.Interaction):
        await interaction.response.edit_message(embed=self.embed.index)
    
    @discord.ui.button(emoji='🛑', style=discord.ButtonStyle.danger)
    async def stop_callback(self, button, interaction: discord.Interaction):
        for items in self.children:
            items.disabled = True
        await interaction.response.edit_message(view=self)
        self.stop()
    
    @discord.ui.button(emoji='❔', style=discord.ButtonStyle.primary)
    async def about_callback(self, button, interaction: discord.Interaction):
        embed = discord.Embed(title="About Me", description="**\n🤖My Developer:-**\n`                           `\n**I am Coded by Zaeem Technical**\n**He is a Programmer, ETHICAL HACKER & SocialMedia Influencer**\n\n **Follow Him:-**\n __**Here is a link of his Website**__👇\n https://zaeemtechnical.ml", color=0xf1c40f)
        await interaction.response.edit_message(embed=embed)

    async def on_timeout(self):
        if not self.stop():
            select = [x for x in self.children if x.custom_id == 'selectmenu'][0]
            select.placeholder = 'Disabled Due to Timeout'
            for item in self.children:
                item.disabled = True
            await self.message.edit(view=self)


    async def interaction_check(self, interaction: discord.Interaction) -> bool:
        if interaction.user and interaction.user.id in (self.ctx.bot.owner_id, self.ctx.author.id):
            return True
        await interaction.response.send_message('This pagination menu cannot be controlled by you, sorry!', ephemeral=True)
        return False
```
        
this is my code execute it and see result

### Expected Results

![image](https://user-images.githubusercontent.com/60778335/161390703-161398cf-11fa-4abb-b648-efe0e0ad1910.png)

Like this we want

### Actual Results

**Result without making any interaction**

![image](https://user-images.githubusercontent.com/60778335/161390723-b69a9967-7fa9-4c08-98c1-12ef3ea531b4.png)

**Result after making an interaction, and stopping them or timed out...**

![image](https://user-images.githubusercontent.com/60778335/161390763-b5bfb030-f2c8-40c2-9f22-ac424c5dc58a.png)

### Intents

discord.Intents.all

### System Information

- Python v3.9.9-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I testes this code in discord.py 2.0.0 (alpha)
and it works fine on it

**Comment by EmreTech** [comment]
This isn't entirely related to the issue, but you forgot to end the code block after showing your code example.

**Comment by Zaeem20** [comment]
oops sorry i edited it now see it @EmreTech  @krittick

**Comment by Zaeem20** [comment]
please check it and see outcome, it was working fine in discord 2.0.0 alpha

**Comment by Zaeem20** [comment]
@krittick pls have a look now i tried it in discord.py and it is working fine on it
it becomes development-barrier

**Comment by Zaeem20** [comment]
No Response Received from dev team??? @BobDotCom

**Comment by Lulalaby** [comment]
Even there you are not allowed to ping us core devs.
Please behave.

**Comment by Zaeem20** [comment]
ok sorry bro, but i just reminded them coz its a serious bug may be i think...

**Comment by Lulalaby** [comment]
A position move bug of buttons is in no way an serious bug

**Comment by Zaeem20** [comment]
Then will u leave it as it is???

**Comment by Lulalaby** [comment]
For now, yes.
First: because the way you stress
Second: because it's low prio

Make yourself familiar with our code of conduct please.

**Comment by baronkobama** [comment]
I'm unable to reproduce this behavior with the given code, is this issue still valid?

**Comment by Zaeem20** [comment]
> I'm unable to reproduce this behavior with the given code, is this issue still valid?

i don't know that it was fixed or not, but when i not got satisfactory answer from developers i switched to discord.py,  but i tested it in one of my pycord bot instance and yep this issue is not fixed yet....

**Comment by baronkobama** [comment]
> i tested it in one of my pycord bot instance and yep this issue is not fixed yet....

Still utilizing the same code given above? If not please send the updated reproduction code as we can't fix this issue without being able to reproduce it.

**Comment by Zaeem20** [comment]
are u using same code given above with no changes

**Comment by baronkobama** [comment]
I had to make some slight changes in order for it to work with my bot but they shouldn't have affected the behavior. Please try using 2.0.0rc1, the newest release, and let us know if it appears as fixed.

**Comment by Zaeem20** [comment]
ok thanks for you reply

**Comment by argo0n** [comment]
I've managed to reproduce it on rc1 using the code above (but manually added embeds since that was left out). Just like OP said, it only switches positions after pressing any button other than the stop button. 

https://user-images.githubusercontent.com/67531837/169642271-3c1790d1-54ab-4f5b-a233-5cff5a55b4f2.mp4

**Comment by Zaeem20** [comment]
> I've managed to reproduce it on rc1 using the code above (but manually added embeds since that was left out). Just like OP said, it only switches positions after pressing any button other than the stop button.
> 
>  repro.mp4


@argo0n Thanks alot bro, see @baronkobama,

**Comment by argo0n** [comment]
I'm not sure how you work with others on GitHub, but I'm sure an unspoken rule is to not mention (ping) people unless it's urgent 🙃

**Comment by Zaeem20** [comment]
Sorry 😜😜

**Comment by UP929312** [comment]
@Zaeem20 I'd recommend leaving this issue for now, you seem to be working against your case rather than for it, mentioning people unnecessarily, being impatient, etc.

With reproducible code, I'm sure a developer will take a look at this when they have time, but in the meantime I suggest you don't make things worse.

**Comment by Zaeem20** [comment]
bro i am just helping devs to debug that bug, and i am not being impatient, just replying to them, already i apologize for it...

please don't tell it again and again...
