### ISSUE TITLE
Application commands break after several restarts

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#1225]
### Summary

this has happened multiple times when i restart my bot

### Reproduction Steps

after restarting my bot several times, my slash commands stop responding. then after a few minutes i get an error. sometimes restarting my bot will fix this or switching off my bot for several minutes. other times it will completely break the registered slash commands causing the bot to reach the 200 application command limit.

### Minimal Reproducible Code

```python
a bot with application commands. just restart until the commands stop responding. then wait for an error
```

### Expected Results

to restart and for application commands to respond

### Actual Results

application commands stop responding after several restarts and then the bot threw the following error:
File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)

  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 1041, in on_interaction
    await self.process_application_commands(interaction)

  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 742, in process_application_commands
    await self.sync_commands(unregister_guilds=[guild_id])

  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 685, in sync_commands
    await self.http.bulk_upsert_command_permissions(self.user.id, guild_id, guild_cmd_perms)

  File "/bot-dir/venv/lib/python3.10/site-packages/discord/http.py", line 357, in request
    raise HTTPException(response, data)

HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 0: Invalid application command id provided

### Intents

all

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Linux 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

this is simular to #1048 but with traceback occuring afterwards

**Comment by Revnoplex** [comment]
update: this is more likely to occur after updating code in a command

**Comment by Revnoplex** [comment]
This error still occurs and has not been fixed

**Comment by Revnoplex** [comment]
some extra info: if you restart the bot and application commands don't respond. if you don't shut it down or restart it gives that error and then gives the following error on the next restart: HTTPException: 400 Bad Request (error code: 30034): Max number of daily application command creates has been reached (200).

**Comment by IotaSpencer** [comment]
seems to still occur in current master

**Comment by cannonballchris** [comment]
I am facing the same issue. However I am also facing a new issue that the bot is not registering commands globally properly for some reasons

**Comment by Lulalaby** [comment]
Kinda duplicate.
Will keep an eye on that internally.
