### ISSUE TITLE
TypeError: 'tuple' object is not callable when a channel is provided as a slash command option. (2.0.0b7)

### ISSUE THREAD

**Issue by Tiffinini** [Pycord-Development/pycord#1241]
### Summary

Error in core.py when specifying a type of channel as a slash command option.

### Reproduction Steps

1. Create a slash command with an option parameter of type discord.TextChannel or discord.VoiceChannel.
2. Attempt to run the slash command and the error will occur.

### Minimal Reproducible Code

```python
@slash_command(guild_ids=globals.COMMAND_GUILD_ID_REGISTER_LIST)
async def testing(self, ctx, chan: Option(discord.TextChannel, "Specify channel:")):
    pass
```

### Expected Results

The code would run and I would have access to the channel object as the "chan" parameter, as per the example.

### Actual Results

Crash with traceback:

Traceback (most recent call last):
  File "c:\Users\Tiffany\dev\pycord-bot-testing\venv\lib\site-packages\discord\commands\core.py", line 122, in wrapped
    ret = await coro(arg)
  File "c:\Users\Tiffany\dev\pycord-bot-testing\venv\lib\site-packages\discord\commands\core.py", line 810, in _invoke
    arg = obj_type(state=ctx.interaction._state, data=_data, **kw)
TypeError: 'tuple' object is not callable

### Intents

All

### System Information

- Python v3.9.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 8.1 6.3.9600

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Commands were previously working fine in any version under py-cord 2.0.0b6.

**Comment by R4zzerYT** [comment]
I have the same issue. 

`async def gwstart_cmd(self, ctx: discord.ApplicationContext, channel: Option(discord.TextChannel, 'channel type is broken'),`

**Comment by Xyaren** [comment]
Same Issue here with 2.0.0b6 and 2.0.0b7
