### ISSUE TITLE
[ext.bridge] Errors while using discord.commands.options.Option with bridge commands.

### ISSUE THREAD

**Issue by TheGiga** [Pycord-Development/pycord#1244]
### Summary

Using Option() with bridge commands gives errors. While using Application Command - it works, but with message commands - it don't.

### Reproduction Steps

I replaced:
- `discord.Bot` with `bridge.Bot`
- `@slash_command` with `@bridge_command`

Then i just used message command, aka `@ping command <argument1 (not Option) <argument2 (Option)>`
Application command works.
_I gave Option() default argument, and code is working if `Argument2` is not specified._ 

### Minimal Reproducible Code

```python
@bot.bridge_command(name='command')
async def command(
        ctx,
        argument1: str,
        argument2: Option(
            SlashCommandOptionType.string,
            choices=["1", "2", "3"]
        )
):
    await ctx.respond('Hey!')
```

### Expected Results

Command works as intended and responds `Hey!`

### Actual Results

Error:
```Ignoring exception in command player:
Traceback (most recent call last):
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\converter.py", line 1078, in _actual_conversion
    return converter(argument)
TypeError: 'Option' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\bot.py", line 360, in invoke
    await ctx.command.invoke(ctx)
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\core.py", line 919, in invoke
    await self.prepare(ctx)
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\core.py", line 849, in prepare
    await self._parse_arguments(ctx)
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\core.py", line 755, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\core.py", line 605, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\converter.py", line 1175, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
  File "R:\.osu-stats-new\venv\lib\site-packages\discord\ext\commands\converter.py", line 1087, in _actual_conversion
    raise BadArgument(f'Converting to "{name}" failed for parameter "{param.name}".') from exc
discord.ext.commands.errors.BadArgument: Converting to "Option" failed for parameter "mode".
```

### Intents

discord.Intents.default()

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

- **I ping bot for commands, so `message_content` is not needed**

**Comment by EmreTech** [comment]
For the minimal reproducible code, you need to add another argument since your error focuses on the second argument.

**Comment by EmreTech** [comment]
Just reproduced this problem, and I do get the same error

**Comment by BobDotCom** [comment]
> #1250 should be able to fix this problem

I don't think it changes anything for the detection of converters, have you tested to see if it resolves the issue?

**Comment by Lulalaby** [comment]
Is this still a problem?

**Comment by TheGiga** [comment]
> Is this still a problem?

no, its seems fixed now.
![image](https://user-images.githubusercontent.com/49173264/177224462-ed980fa0-a1c7-4a1e-9685-2440962e3180.png)
