### ISSUE TITLE
When editing roles position, the code doesnt continue 

### ISSUE THREAD

**Issue by Veyd3mo** [Pycord-Development/pycord#1277]
### Summary

Title says it all, when i try to edit a role position, it *does* succesfully edit the position, however it seems to just return and not carry on the code from then on. Just tested this as well, when trying to edit the name, the role **does not** get edited, the name is **not changed** and the code below that line **does not** get ran.

### Reproduction Steps

The code below will essentially explain the steps, this was ran via command

### Minimal Reproducible Code

```python
role = get(ctx.guild.roles, id=927033965246812201) # Role you want to edit 
separator = get(ctx.guild.roles, id=747313670509559866) # A seperator 

await role.edit(position=separator.position - 1) # Edits the position to appear beneath the separator (this is successful and does exactly this)

await ctx.send('Success!') # Success message and anything after this never appears and gives no errors
```

### Expected Results

I expected that every single line of code after the role being edited in some way will be ran

### Actual Results

Everything works including the role being edited, however every piece of code after the role being edited is complete **does not** get ran

### Intents

message_content=True, messages=True, guilds=True, reactions=True, guild_reactions=True, members=True, presences=True, voice_states=True

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Apologies in advance if it's just me being dumb and missing out information on to why this is happening 😅

**Comment by rtk-rnjn** [comment]
> it *does* succesfully edit the position, however it seems to just return and not carry on the code from then on

![image_2022-04-19_110547555](https://user-images.githubusercontent.com/37435729/163927021-e534ca92-444a-457a-86a7-01801fb2aff5.png)

Can't reproduce, works fine for me

**Comment by Veyd3mo** [comment]
> > it _does_ succesfully edit the position, however it seems to just return and not carry on the code from then on
> 
> ![image_2022-04-19_110547555](https://user-images.githubusercontent.com/37435729/163927021-e534ca92-444a-457a-86a7-01801fb2aff5.png)
> 
> Can't reproduce, works fine for me

![image](https://user-images.githubusercontent.com/51832077/164047648-4da071cf-fbd6-450c-bfcc-eff46aeca2c7.png)

doesnt work for me for some reason, all i have going on is a command within a cog that gets loaded up once the bot starts.

**Comment by rtk-rnjn** [comment]
Can you send the proper codes, seems you are messing with something else!

**Comment by Veyd3mo** [comment]
> Can you send the proper codes, seems you are messing with something else!

a file in a folder called developer 
```python
import discord
from db import *
from var import *
from discord.utils import get
from discord.ext import commands

class Developer(commands.Cog, name="Developer"):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name='test')
    @commands.is_owner()
    async def test(self, ctx):

        role = get(ctx.guild.roles, id=927033965246812201)
        separator = get(ctx.guild.roles, id=747313670509559866)

        await role.edit(position=separator.position-1)

        await ctx.send('success')


def setup(bot):
    bot.add_cog(Developer(bot))
```
and then this is where everything gets loaded up
```python
@bot.event
async def on_ready():
    status = discord.Game("some random status")
    await bot.change_presence(status=discord.Status.online, activity=status)
    print(bot.user, 'is so ready!')

for dir in os.listdir(f'./commands/'):
    if dir != '__pycache__':
        print(f'Loading {dir} Commands')
        for command in os.listdir(f'./commands/{dir}'):
            if command.endswith('.py'):
                bot.load_extension(f'commands.{dir}.{command[:-3]}')
                print(f'Loaded Command {command[:-3]}')

bot.run('token')
```

**Comment by BobDotCom** [comment]
Do you have an error handler in your bot?

**Comment by Veyd3mo** [comment]
> Do you have an error handler in your bot?

I do, hasnt shown anything, made sure that it would print errors if there were any. 

After a few days of just leaving the code, I came back to it today and tried testing it again, and it's worked for some reason. I'm awfully confused on what happened because I haven't touched anything. So I'm just going to assume you guys did something 😅
