### ISSUE TITLE
Deferred Paginators in a Slash Command Group and Cog will cause Error on Timeout

### ISSUE THREAD

**Issue by JustaSqu1d** [Pycord-Development/pycord#1280]
### Summary

discord.ext.Pages.Paginator Timeout Error

### Reproduction Steps

Download 2.0.0b7
Make a slash command and defer it. Respond with a Paginator

### Minimal Reproducible Code

```python
import discord
from discord.ext.pages import Pages, Paginator

bot = discord.Bot()

@bot.slash_command(name="test", description="test slashy")
async def test(ctx):
    pages = []
    await ctx.defer()
    for i in range(0,10):
        embed = discord.Embed(title=f"Page {i}")
        pages.append(pages.append(Page(embeds=[embed])))
    paginator = Paginator(pages=pages)
    await paginator.respond(ctx.interaction)
```

### Expected Results

Correctly disable upon timeout

### Actual Results

Errors upon timeout:
```
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-85157e3bd1eda0c8740120f2da78e568' coro=<Paginator.on_timeout() done, defined at /opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/pages/pagination.py:465> exception=AttributeError("'NoneType' object has no attribute 'edit'")>
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/pages/pagination.py", line 470, in on_timeout
    await self.message.edit(view=self)
AttributeError: 'NoneType' object has no attribute 'edit'
```

### Intents

message_content

### System Information

- Python v3.8.12-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.7.4.post0
- system info: Linux 5.13.0-1023-gcp #28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
I can't reproduce the issue on the latest `master` branch with the provided code. Can you confirm if you're using the b7 release or `master`? If b7, please try updating to `master`.

**Comment by JustaSqu1d** [comment]
Actually, it turns out that the issue only occurs within a "cog"ed slash command group.

**Comment by krittick** [comment]
> Actually, it turns out that the issue only occurs within a "cog"ed slash command group.

I still can't reproduce the issue with the latest `master`, including in a slash command group in a cog.

**Comment by JustaSqu1d** [comment]
Forgot ot address why I closed it, but it turns out that I was missing permissions.
