### ISSUE TITLE
discord.SelectOption default doesn't register into values of the discord.ui.Select

### ISSUE THREAD

**Issue by Lezyes** [Pycord-Development/pycord#1281]
### Summary

discord.SelectOption default doesn't register into values of the discord.ui.Select

### Reproduction Steps

Create a dropdown feature with discord.ui.Select, when adding a discord.SelectOption(default=True) into the view, the "values" property doesn't reflect that the option is actually already selected 

### Minimal Reproducible Code

```python
class Dropdown(discord.ui.Select):
    def __init__(self, options, title="Pick your pick"):
        self.options_data = options
        select_options = [
            discord.SelectOption(label=option, default=True) for option in options
        ]
        super().__init__(
            placeholder=title,
            min_values=1,
            max_values=len(options),
            options=select_options,
        )
```

### Expected Results

Dropdown.values == options

### Actual Results

Dropdown.values = []

### Intents

all

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
The `values` parameter represents the options that were selected when the interaction was sent, not what is currently selected in the UI.

**Comment by krittick** [comment]
> The `values` parameter represents the options that were selected when the interaction was sent, not what is currently selected in the UI.

@plun1331 is correct. This is also reflected in the documentation: https://docs.pycord.dev/en/master/api.html#discord.ui.Select.values
> A list of values **that have been selected by the user.**

(emphasis added)

**Comment by Lezyes** [comment]
How do you differentiate in the following situation then:
1) The view has a few pre-selected options
2) the user chooses new options, deselcts only a part of the originally (defaulted) options
3) now .values has some of the options but not all of them, and you can't assume anything on the defaulted options because some of them were deselected
Other than keeping another state property, that lists *all* selected values, and maintaining it in the callbacks, which seems pretty "dirty"

**Comment by krittick** [comment]
> How do you differentiate in the following situation then:
> 
> 1. The view has a few pre-selected options
> 2. the user chooses new options, deselcts only a part of the originally (defaulted) options
> 3. now .values has some of the options but not all of them, and you can't assume anything on the defaulted options because some of them were deselected
> 
> Other than keeping another state property, that lists _all_ selected values, and maintaining it in the callbacks, which seems pretty "dirty"

`values` already shows what is selected when the menu callback fires, including any pre-selected (i.e. default) options that the user chose to leave selected. Which options are missing in this situation?

**Comment by Lezyes** [comment]
Sorry, that was a bug on my end. retesting showed that case above behaves properly. 
A different case is that the user is prompted several options, some are pre-selected, and the user deselects all of them. in this case, .values is still empty. 
This means that the beginning state with some pre-selected options, and the end state with no selected options are actually the same state. right?

**Comment by krittick** [comment]
> Sorry, that was a bug on my end. retesting showed that case above behaves properly. 
> A different case is that the user is prompted several options, some are pre-selected, and the user deselects all of them. in this case, .values is still empty. 
> This means that the beginning state with some pre-selected options, and the end state with no selected options are actually the same state. Is this the desired behavior of this feature?

The beginning state is before any interaction data has been sent and it's not expected to have data until the interaction is submitted, so it's not accurate to compare the `values` fields in this situation when one is always expected to be empty. Default pre-selected options are only meant to guide a user - the values actually submitted by the user are what your code should be checking for regardless. In your example, the user is de-selecting all pre-selected values before submitting, which would be expected to return an empty list since the field reflects the values submitted by the user's interaction.

**Comment by Lezyes** [comment]
and if the user doesn't change anything and submits it, `values ` is going to be empty when the user submits even though some values seem to be selected (pre-selected)
