### ISSUE TITLE
Invalid permissions

### ISSUE THREAD

**Issue by Krutoy-4el** [Pycord-Development/pycord#1283]
### Summary

Pycord gives invalid permissions

### Reproduction Steps

1. Make a slash command which takes a channel as argument.
2. Invoke it with a channel where the bot doesn't have permissions to send messages.
3. Permissions are not correct

### Minimal Reproducible Code

```python
@bot.slash_command()
async def test(ctx, channel: discord.Option(discord.TextChannel)):
    print(
        "Test result: ",
        channel.permissions_for(ctx.me)
        == ctx.guild.get_channel(channel.id).permissions_for(ctx.me),
    )
```

### Expected Results

Test result: True

### Actual Results

Test result: False
(permissions got from `channel` argument are not valid)

### Intents

none

### System Information

- Python v3.9.9-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.17763

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This was discussed in #help-1
https://discord.com/channels/881207955029110855/881309496385884180/966397457187606558

**Comment by plun1331** [comment]
Without intents, the permissions in the cached channel would not be up-to-date, causing such an issue

**Comment by krittick** [comment]
> Without intents, the permissions in the cached channel would not be up-to-date, causing such an issue

I can reproduce the issue myself with Intents.all().

**Comment by plun1331** [comment]
The way app command arguments are parsed may be relevant, including the data sent by discord
