### ISSUE TITLE
Wrong website image at latest

### ISSUE THREAD

**Issue by Puncher1** [Pycord-Development/pycord#129]
### Summary

For the website image the discord.py logo has been used instead of the pycord image. 

### Reproduction Steps

I used the latest pycord docs (https://pycord.readthedocs.io/en/latest/ext/commands/api.html).
As you can see in the screenshot below, the wrong logo has been used.

![image](https://user-images.githubusercontent.com/65789180/132392723-bdd268c0-5d66-43d3-a7a5-8c5e775f1e3b.png)
(See left top corner)

### Expected Results

I expect to see the pycord logo.

### Actual Results

I see the discord.py logo

### Intents

-

### System Information

-

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
this is expected and will resolve once 2.0 stable releases
