### ISSUE TITLE
Deregistering Slash commands on Testbots

### ISSUE THREAD

**Issue by MuffinAmor** [Pycord-Development/pycord#1293]
### Summary

Discord delete all Slash commands from specific Bots after running one

### Reproduction Steps

i dont know how do you can reproduction this. 
its happened on two of my Testbots. 
Now its pretty annoying

### Expected Results

stuff that the bot should doin

### Actual Results

unregistered slash commands without a restart.

### Intents

discord.Intents.all()

### System Information

(venv) niko@vmd48616:~/Timmy$ python -m discord -v
- Python v3.9.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Linux 5.10.0-13-amd64 # 1 SMP Debian 5.10.106-1 (2022-03-17)

### Checklist

- [X] I have shown the entire traceback, if possible.
- [X] I have searched the open issues for duplicates.
- [X] I have removed my token from display, if visible.

### Additional Context

![grafik](https://user-images.githubusercontent.com/55553342/164992906-f64019fb-7dcd-4642-b132-502981ad3664.png)

**Comment by Dorukyum** [comment]
I dont get what you mean, do all the commands of a bot get unregistered when you run one of the same bot?

**Comment by MuffinAmor** [comment]
yes

**Comment by MuffinAmor** [comment]
got it.
there was a dead bot ghost session behind the application without slash commands.
rebooting the whole server killed the issue.

**Comment by Lulalaby** [comment]
GG
