### ISSUE TITLE
AttributeError: module 'discord.ext' has no attribute 'bridge'

### ISSUE THREAD

**Issue by Craftzman7** [Pycord-Development/pycord#1294]
### Summary

This error occurs when attempting to load one of my cogs.

### Reproduction Steps

I have no idea what causes this. I do not use whatever 'bridge' is. Seems to be something slash command related.

### Expected Results

The cog to load.

### Actual Results

This stack trace
```py
Traceback (most recent call last):
  File "/home/crafter/.pyenv/versions/3.9.7/lib/python3.9/site-packages/discord/cog.py", line 715, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
AttributeError: module 'discord.ext' has no attribute 'bridge'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/crafter/.pyenv/versions/3.9.7/lib/python3.9/site-packages/jishaku/features/management.py", line 56, in jsk_load
    await discord.utils.maybe_coroutine(method, extension)
discord.errors.ExtensionFailed: Extension 'cogs.moderation' raised an error: AttributeError: module 'discord.ext' has no attribute 'bridge'
```

It's not an issue with Jishaku by the way. It happens on startup.

### Intents

discord.Intents.all()

### System Information
```
- Python v3.9.7-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.0
- system info: Linux 5.10.0-9-cloud-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This works on my local machine with the same code and version of Pycord, no idea why.

**Comment by Craftzman7** [comment]
I seem to have narrowed it down to [this commit](https://github.com/Pycord-Development/pycord/commit/a30f76dcf180196f5b17919460748679c8b6107f).

**Comment by krittick** [comment]
Please provide the code from your cog that is causing the issue.

**Comment by Craftzman7** [comment]
I have idea what code could be causing it. The stack trace doesn't tell me.

**Comment by Indominus-Rexian** [comment]
This seems to be a error on my side as well.

**Comment by krittick** [comment]
> I have idea what code could be causing it. The stack trace doesn't tell me.

You mentioned it happens when loading one of your cogs. Post that cog's code.

**Comment by krittick** [comment]
> `from discord.ext.pages import Paginator`

I cannot reproduce the issue when using this line, or at all. Can you please ensure that you're on the latest `master` version of the library?

**Comment by Craftzman7** [comment]
> I'm getting this error too and for me it's caused by this line:
> 
> `from discord.ext.pages import Paginator`
> 
> 
> 
> Here's the exception i get running a blank python script with just this line:
> 
> ```py
> 
> Traceback (most recent call last):
> 
>   File "/home/kiko/Projects/example.py", line 1, in <module>
> 
>     from discord.ext.pages import Paginator
> 
>   File "/home/kiko/.local/lib/python3.10/site-packages/discord/ext/pages/__init__.py", line 10, in <module>
> 
>     from .pagination import *
> 
>   File "/home/kiko/.local/lib/python3.10/site-packages/discord/ext/pages/pagination.py", line 270, in <module>
> 
>     class Paginator(discord.ui.View):
> 
>   File "/home/kiko/.local/lib/python3.10/site-packages/discord/ext/pages/pagination.py", line 909, in Paginator
> 
>     interaction: Union[discord.Interaction, discord.ext.bridge.BridgeContext],
> 
> AttributeError: module 'discord.ext' has no attribute 'bridge'```

My cog contains that code. Seems to be the issue.

**Comment by krittick** [comment]
I think I found the culprit, working on a fix now. Workaround in the meantime is to add `from discord.ext import bridge` before the offending line.

**Comment by krittick** [comment]
This should be fixed in the latest `master` update now.

**Comment by Craftzman7** [comment]
This issue still persists with the latest update.

**Comment by BobDotCom** [comment]
> This issue still persists with the latest update. (The work around works however)

It shouldn't really be able to occur now, since the code that caused it no longer exists.

**Comment by Craftzman7** [comment]
> > This issue still persists with the latest update. (The work around works however)
> 
> 
> 
> It shouldn't really be able to occur now, since the code that caused it no longer exists.

Seems I forgot to add the -u flag when updating, disregard.
