### ISSUE TITLE
User.create_dm() fails with RuntimeError

### ISSUE THREAD

**Issue by Fallcrim** [Pycord-Development/pycord#1297]
### Summary

Trying to create a dm with a user fails and throws a RuntimeException

### Reproduction Steps

For me it was just
```py
user = self.bot.get_user(id)
user.send("some stuff")
```

### Expected Results

Sending a message to the fetched user

### Actual Results

Raised 
```
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\\Desktop\Python Code Projekte\Radio\cogs\economy.py", line 295, in on_pet_death
    ch = await self.bot.get_user(u_id).create_dm()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\user.py", line 498, in create_dm
    data: DMChannelPayload = await state.http.start_private_message(self.id)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 276, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 466, in _request
    with timer:
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```

### Intents

discord.Intents.all()

### System Information

```- Python v3.10.2-final
- py-cord v2.0.0-beta 
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If this is my mistake please tell me.
PS: I'm using this in a 'custom' event I created

**Comment by krittick** [comment]
> PS: I'm using this in a 'custom' event I created

I can't reproduce the issue with the basic info you provided, so I suspect this is indeed the cause. Can you share your full code that's actually triggering the error?

**Comment by Dorukyum** [comment]
Try running the code you shared in an asyncio task (like a command or an event handler)

**Comment by Fallcrim** [comment]
Well, running it in a Task works not completely. So it doesn't return an error but it simply does nothing

**Comment by Dorukyum** [comment]
You have to use the `await` keyword: `await user.send(...)`

**Comment by Fallcrim** [comment]
I know, sadly I forgot it in the code I commented in the reproduction steps

**Comment by Dorukyum** [comment]
So the message is sent and the error is gone?

**Comment by Fallcrim** [comment]
No message

**Comment by Fallcrim** [comment]
I don't get a message but there is no error as well.

**Comment by erincerys** [comment]
Is the cog that this custom event listener resides in being passed the Bot client correctly?

**Comment by Fallcrim** [comment]
> Is the cog that this custom event listener resides in being passed the Bot client correctly?

Yes, it is
