### ISSUE TITLE
RAM usage exploding after reconnect

### ISSUE THREAD

**Issue by Miolus** [Pycord-Development/pycord#1304]
### Summary

My bot is exponentially using ram after reconnecting

### Reproduction Steps

Run a bot on a few thousand guilds

### Expected Results

Reconnect and move on normally

### Actual Results

After startup: 2gb am
After reconnect 1: 7gb  ram
After reconnect 2: 10gb  ram
This goes on forever until memory is full

### Intents

members

### System Information

2.0.0b6

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Some extra information would be helpful, such as the features your bot is using (views, modals, etc.) and the bot class being used.
If you want, tracking ram usage with the same techniques used in #420 could help a lot.

Additionally, are you sure this hasn't been caused by your own code?

**Comment by Miolus** [comment]
Using views and modals. (No permanent views)
Will check on the other tips later, thanks for reply.
