### ISSUE TITLE
Error when passing arguments in debug_guilds

### ISSUE THREAD

**Issue by holy-tanuki** [Pycord-Development/pycord#1321]
### Summary

When I pass a list of guild ids in debug_guilds, I get a 405 Method Not Allowed Error

### Reproduction Steps

1. Pass a list of guild ids in the discord.Bot.debug_guilds parameters
2. Run the bot

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

...

class Bot(commands.Bot):
   def __init__(self):
      ...

      super().__init__(
         command_prefix="!",
         help_command=None,
         ...
         debug_guilds=[757735469875524877]
      )
```

### Expected Results

No errors and the slash commands work

### Actual Results

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event

    await coro(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/discord/bot.py", line 1147, in on_connect

    await self.sync_commands()

  File "/usr/local/lib/python3.10/site-packages/discord/bot.py", line 770, in sync_commands

    await self._bot.http.bulk_upsert_command_permissions(self._bot.user.id, guild_id, guild_cmd_perms)

  File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 359, in request

    raise HTTPException(response, data)

discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed
```

### Intents

discord.Intents().all()

### System Information

- Python v3.10.3-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
This is already fixed in the master branch.
