### ISSUE TITLE
Content attribute missing for MessageType.thread_starter_message

### ISSUE THREAD

**Issue by elviskahoro** [Pycord-Development/pycord#1327]
### Summary

Content attribute missing for MessageType.thread_starter_message

### Reproduction Steps

* Create a message in a channel
* Create a thread from that message
* Call the history() function on the Thread object
* Flatten the history iterator into a list
* Extract the earliest message (MessageType.thread_starter_message)
* Inspect the object
* Notice that the content field of the object is empty when it should have the actual content of the message that the thread was created from

### Minimal Reproducible Code

```python
message_channel: Thread
thread_history: List[Message] = await message_channel.history(oldest_first=True).flatten()
message_to_inspect = thread_history[0]
print(message_to_inspect)
print(message_to_inspect.content)
```

### Expected Results

The content of the message should be the original message's content and not empty.

### Actual Results

The message has an empty string for content field

### Intents

defaults, members, message.content

### System Information

n/a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
The thread a message was started from is considered a system message by Discord, and does not technically have any content.
If you want the content of these messages, you can use `message.system_content` or get the content of the message in `message.reference`.

**Comment by elviskahoro** [comment]
@plun1331 Thanks so much. You work wonders!
