### ISSUE TITLE
Unable to definition slash_command

### ISSUE THREAD

**Issue by Twylixy** [Pycord-Development/pycord#1331]
### Summary

Trows exception "Invalid class"

### Reproduction Steps

```py
class InfractorCog(commands.Cog):
    """Represents an `infractor` cog-module"""

    def __init__(self, bot: commands.Bot) -> None:
        """
        Initialize a new 'infractor' instance

        Params:
            bot: discord.ext.commands.Bot
        """
        self.bot= bot

    @commands.slash_command()
    async def infractor(self, ctx: commands.Context) -> None:
        """
        Setup command for infractor

        Params:
            ctx: commands.Context
        """
        ...
```

### Minimal Reproducible Code

```python
@commands.slash_command()
async def infractor(self, ctx: commands.Context) -> None:
    """
    Setup command for infractor

    Params:
        ctx: commands.Context
    """
    ...
```

### Expected Results

Define slash_command

### Actual Results

TypeError: Invalid class <class 'discord.ext.commands.context.Context'> used as 
an input type for an Option

### Intents

messages and message_content

### System Information

- Python v3.9.8-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Can you reproduce this with installing from the master branch?

**Comment by krittick** [comment]
Also, please post the full traceback.

**Comment by plun1331** [comment]
Discussing this in the [`#discussions`](https://discord.com/channels/881207955029110855/881735314987708456) Discord channel, seems to be valid

**Comment by Lulalaby** [comment]
> Discussing this in the [`#discussions`](https://discord.com/channels/881207955029110855/881735314987708456) Discord channel, seems to be valid, but for a different reason (params being parsed when they shouldn't)


Yes, is valid 🤪

**Comment by Twylixy** [comment]
I've found the problem. Exception caused by annotation `ctx: commands.Context`. If remove annotation the code will work.

**Test Code**
```
import discord
from discord.ext import commands

intents = discord.Intents(messages=True, message_content=True)
bot = commands.Bot()

class MyCog(commands.Cog):
    @commands.slash_command()
    async def myslah(self, ctx: commands.Context):
        ...
        
bot.add_cog(MyCog())

bot.run('token')
```

**Traceback**
```
Traceback (most recent call last):
  File "D:\Projects\py_cord_test\__main__.py", line 7, in <module>
    class MyCog(commands.Cog):
  File "D:\Projects\py_cord_test\__main__.py", line 9, in MyCog
    async def myslah(self, ctx: commands.Context):
  File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\core.py", line 1571, in decorator
    return cls(func, **attrs)
  File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\core.py", line 646, in __init__
    self.options: List[Option] = self._parse_options(params)
  File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\core.py", line 691, in _parse_options
    option = Option(option, "No description provided")
  File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\options.py", line 138, in __init__
    raise exc
  File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\options.py", line 133, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "D:\Projects\py_cord_test\lib\site-packages\discord\enums.py", line 705, in from_datatype
    raise TypeError(
TypeError: Invalid class <class 'discord.ext.commands.context.Context'> used as an input type for an Option
```

**Comment by plun1331** [comment]
> I've found the problem. Exception caused by annotation `ctx: commands.Context`. If remove annotation the code will work.
> 
> **Test Code**
> 
> ```
> import discord
> from discord.ext import commands
> 
> intents = discord.Intents(messages=True, message_content=True)
> bot = commands.Bot()
> 
> class MyCog(commands.Cog):
>     @commands.slash_command()
>     async def myslah(self, ctx: commands.Context):
>         ...
>         
> bot.add_cog(MyCog())
> 
> bot.run('token')
> ```
> 
> **Traceback**
> 
> ```
> Traceback (most recent call last):
>   File "D:\Projects\py_cord_test\__main__.py", line 7, in <module>
>     class MyCog(commands.Cog):
>   File "D:\Projects\py_cord_test\__main__.py", line 9, in MyCog
>     async def myslah(self, ctx: commands.Context):
>   File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\core.py", line 1571, in decorator
>     return cls(func, **attrs)
>   File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\core.py", line 646, in __init__
>     self.options: List[Option] = self._parse_options(params)
>   File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\core.py", line 691, in _parse_options
>     option = Option(option, "No description provided")
>   File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\options.py", line 138, in __init__
>     raise exc
>   File "D:\Projects\py_cord_test\lib\site-packages\discord\commands\options.py", line 133, in __init__
>     _type = SlashCommandOptionType.from_datatype(input_type)
>   File "D:\Projects\py_cord_test\lib\site-packages\discord\enums.py", line 705, in from_datatype
>     raise TypeError(
> TypeError: Invalid class <class 'discord.ext.commands.context.Context'> used as an input type for an Option
> ```

There's still an underlying bug regarding parameters being parsed improperly at runtime though
Shouldn't affect you as long as you change/remove the typehint

**Comment by Twylixy** [comment]
Solved. Use `discord.commands.context.ApplicationContext` instead `discord.ext.commands.Context`
