### ISSUE TITLE
[ext.bridge] 'BridgeExtContext' object has no attribute 'delete'

### ISSUE THREAD

**Issue by tiltowait** [Pycord-Development/pycord#1343]
### Summary

Calling `await ctx.delete()` on a message-based bridge command raises an exception.

### Reproduction Steps

• Create a bridge command
• Call `await ctx.reply(...)` followed by `await ctx.delete()`
• Run the command from a message

### Minimal Reproducible Code

```python
import discord
from discord.ext import bridge

intents = discord.Intents.default()
intents.message_content = True

bot = bridge.Bot(command_prefix=".", intents=intents)

@bot.bridge_command()
async def test_delete(ctx: bridge.BridgeContext):
    """Test ctx.delete()"""
    await ctx.reply("Message")
    await ctx.delete()

bot.run(...)
```

### Expected Results

The bot should post a message, which should then be deleted.

### Actual Results

The command works properly when invoked as a slash command; however, when invoked as a **_message command_**, the following exception is raised:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 70, in on_command_error
    await bridge_error(ctx, error)
  File "main.py", line 89, in bridge_error
    raise error from error
  File "/opt/homebrew/lib/python3.10/site-packages/discord/ext/commands/core.py", line 181, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 48, in test_delete
    await ctx.delete()
AttributeError: 'BridgeExtContext' object has no attribute 'delete'
```

### Intents

default + message contents

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This bug is present both in b7 and in master.

**Comment by EmreTech** [comment]
Hm from the looks of the Pycord docs, this should probably be marked as a feature request. `ext.commands.Context` doesn't seem to have a delete function.

**Comment by tiltowait** [comment]
@EmreTech It felt like a bug to me, since it works when used as a slash command.

**Comment by EmreTech** [comment]
The thing is, it's not available with `BridgeExtContext` because it's not available in `ext.commands.Context`. If it were, then it should work fine.

**Comment by krittick** [comment]
Agreed, this is more of a feature request. It should also be fairly simple to implement for anyone interested in making a PR.

**Comment by tiltowait** [comment]
If it's a feature request, then it's a feature request. It felt like a bug to me, as a user, because it worked in one context and not the other 🤷‍♂️
