### ISSUE TITLE
wait_for messages do not contain attachments

### ISSUE THREAD

**Issue by acdo** [Pycord-Development/pycord#1347]
### Summary

When inspecting a message sent with an image or video via a check function for bot.wait_for, no attachments are listed. 

### Reproduction Steps

1. Await a message using bot.wait_for('message, check=check)
2. Send a message with an attached image.
3. Inspect message.attachments list.

### Minimal Reproducible Code

```python
import discord
bot = discord.Bot()

@bot.slash_command(guild_ids=GUILD_IDS, description=DESC_ADD_BA)
async def add_ba_counter(ctx: discord.ApplicationContext):
  attach_prompt = await ctx.respond('Please attach the image of the counter comp in your next message.')
  def check(message: discord.InteractionMessage):
       return message.author == user and len(message.attachments) > 0 and 
       message.attachments[0].content_type.startswith('image')

   image_msg = await bot.wait_for('message', check=check)

bot.run(DISCORD_TOKEN)
```

### Expected Results

Expected wait_for to return the message with the attached image.

### Actual Results

The message received by wait_for has no attachments in the list, so the wait_for call never returns.

### Intents

N/A

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The listed code was functional before updating to fix the 405 error.

**Comment by plun1331** [comment]
You most likely need the message content intent

**Comment by acdo** [comment]
@plun1331 Enabling the message content intent option in the discord developer portal did not resolve the issue

**Comment by plun1331** [comment]
> @plun1331 Enabling the message content intent option in the discord developer portal did not resolve the issue

It must be enabled in your code to receive content in events

**Comment by acdo** [comment]
> > @plun1331 Enabling the message content intent option in the discord developer portal did not resolve the issue
> 
> It must be enabled in your code to receive content in events

intents = discord.Intents.default()
bot = discord.Bot(intents=intents)

Is this sufficient to enable in the code with the message content intent enabled in portal? Doesn't seem to resolve the issue either.

**Comment by acdo** [comment]
Mistakenly read that intents.message_content was readonly, set it to True and now wait_for is functional. Thank you for help, marking as closed.
