### ISSUE TITLE
405 when registering slash commands

### ISSUE THREAD

**Issue by jaimevisser** [Pycord-Development/pycord#1349]
### Summary

405 when registering slash commands

### Reproduction Steps

Run previously working code. No changes.

### Minimal Reproducible Code

```python
https://github.com/jaimevisser/scrimbot
```

### Expected Results

Slash commands work.

### Actual Results

`Ignoring exception in on_connect
Traceback (most recent call last):
  File "/Users/jaime/GitHub/scrimbot/venv/lib/python3.9/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/Users/jaime/GitHub/scrimbot/venv/lib/python3.9/site-packages/discord/bot.py", line 1147, in on_connect
    await self.sync_commands()
  File "/Users/jaime/GitHub/scrimbot/venv/lib/python3.9/site-packages/discord/bot.py", line 770, in sync_commands
    await self._bot.http.bulk_upsert_command_permissions(self._bot.user.id, guild_id, guild_cmd_perms)
  File "/Users/jaime/GitHub/scrimbot/venv/lib/python3.9/site-packages/discord/http.py", line 359, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed`

### Intents

intents.members = True

### System Information

py-cord @ git+https://github.com/Pycord-Development/pycord@ab95493a3a56aa03ce92de13de401b6cf6e58715

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by jaimevisser** [comment]
Still reproducible with 8df222d86319dd16a5e55958524634319836e7cf (current master)

**Comment by jaimevisser** [comment]
Minimally reproducible code. Seems to be the 'guild_ids' parameter to slash_command that breaks it.

```
bot = discord.Bot()


@bot.slash_command(guild_ids=[id_here])
async def ping(
        ctx
):
    await ctx.respond("pong")

bot.run(config.token)
```

**Comment by plun1331** [comment]
> Minimally reproducible code. Seems to be the 'guild_ids' parameter to slash_command that breaks it.
> 
> ```
> bot = discord.Bot()
> 
> 
> @bot.slash_command(guild_ids=[id_here])
> async def ping(
>         ctx
> ):
>     await ctx.respond("pong")
> 
> bot.run(config.token)
> ```

Please send your traceback

**Comment by jaimevisser** [comment]
Dirty venv. Cleaned and now it does work. PEBKAC
