### ISSUE TITLE
Slash command group error

### ISSUE THREAD

**Issue by goose1218** [Pycord-Development/pycord#1354]
### Summary

When I try to run my bot after making a slash command group, I get the below error

### Reproduction Steps

Create a slash command group and then add commands to it
Run the command and I got the following error:
```py
Traceback (most recent call last):
  File "c:\Users\user\Desktop\New folder\shadowtest\main.py", line 144, in <module>
    client.load_extension(f'cogs.{filename[:-3]}')
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 783, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 714, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.adminslash' raised an error: AttributeError: 'SlashCommandGroup' object has no attribute '_callback'
```

### Minimal Reproducible Code

```python
role = SlashCommandGroup(name="role", description="Command group for setting all of the roles the bot needs to know!")

Then after this I add a bunch of commands using the role.command decorator. I get the above error when I try and run the bot.
Also, **ALL** of these commands that I add to the slash command group work perfectly fine when stand alone slash commands
```

### Expected Results

For the commands to be added to the slash command group

### Actual Results

The following error occured:
```py
Traceback (most recent call last):
  File "c:\Users\user\Desktop\New folder\shadowtest\main.py", line 144, in <module>
    client.load_extension(f'cogs.{filename[:-3]}')
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 783, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 714, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.adminslash' raised an error: AttributeError: 'SlashCommandGroup' object has no attribute '_callback'
```

### Intents

intents.members = True intents.guilds = True intents.message_content = True

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

As said above, **ALL** of these commands that I add to the slash command group work perfectly fine when stand alone slash commands

**Comment by plun1331** [comment]
Please show the full traceback

**Comment by goose1218** [comment]
I figured out why I was having the error.
I had 
```py
class Adminslash(commands.Cog, command_attrs=dict(description="Admin commands for admins"))
```
as my cog class and when I removed the command_attrs it worked
