### ISSUE TITLE
`scheduled_events` method of Guild Object isn't working as it should

### ISSUE THREAD

**Issue by EitoZX** [Pycord-Development/pycord#1364]
### Summary

It gives TypeError where it should return the list of scheduled events

### Reproduction Steps

I used jishaku and did the following: 
```py
!jsk py _ctx.guild.scheduled_events
```

### Minimal Reproducible Code

```python
@bot jsk py _ctx.guild.scheduled_events
```

### Expected Results

I expect it to return ScheduledEvent Object just like how it is suppose to work.
When I tried the same thing (`ctx.guild.scheduled_events`) with discord.py, i was able to retrieve ScheduledEvent object as per my expectations.

### Actual Results

i tried `_ctx.guild.scheduled_events` with jishaku and I got this 

```py
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/jishaku/features/python.py", line 145, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/app/.heroku/python/lib/python3.9/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/app/.heroku/python/lib/python3.9/site-packages/jishaku/repl/compilation.py", line 140, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/app/.heroku/python/lib/python3.9/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 1, in _repl_coroutine
    _ctx.guild.scheduled_events.__repr__()
  File "/app/.heroku/python/lib/python3.9/site-packages/discord/scheduled_events.py", line 230, in __repr__
    f"<ScheduledEvent id={self.id} "
TypeError: __str__ returned non-string (type Object)
```
It's always TypeError when there is some scheduled event in guild (this is not fine), but when there's no scheduled, it returns an empty list (this is fine)

### Intents

default intents

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Can you check if the commit I added to my fork, https://github.com/plun1331/pycord/commit/37b62c7f272979d2da2f14772de3cb3808776fdd, fixes this?

Also, are you using the latest version from GitHub? If not, I would see if that fixes the issue.

**Comment by EitoZX** [comment]
> Also, are you using the latest version from GitHub? If not, I would see if that fixes the issue.

Yes, I'm using latest version from Github, master branch,,

**Comment by EitoZX** [comment]
Well i noticed some weird stuff.. 
When I tried `jsk py _ctx.guild.scheduled_events` in one of my server.. it worked fine (img attached below):

![image](https://user-images.githubusercontent.com/72309146/168961399-c447496c-bd33-49bf-9ef9-07acfa32ebef.png)

But when I tried the same thing in **another server**.. it gave me error (image attached):

![image](https://user-images.githubusercontent.com/72309146/168961493-200514bb-854f-4d05-bcf2-574ec33043e6.png)

And the error that I received is:
```py
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/jishaku/features/python.py", line 151, in jsk_python
    send(await self.jsk_python_result_handling(ctx, result))
  File "/app/.heroku/python/lib/python3.9/site-packages/jishaku/features/python.py", line 101, in jsk_python_result_handling
    result = repr(result)
  File "/app/.heroku/python/lib/python3.9/site-packages/discord/scheduled_events.py", line 230, in __repr__
    f"<ScheduledEvent id={self.id} "
TypeError: __str__ returned non-string (type Object)
```

*P.S: This all happened **without** using @plun1331 's commit. Informing cuz.. i just felt like telling 'bout this :>*

**Comment by EitoZX** [comment]
> Can you check if the commit I added to my fork, [plun1331@37b62c7](https://github.com/plun1331/pycord/commit/37b62c7f272979d2da2f14772de3cb3808776fdd), fixes this?

yes @plun1331 , your commit is working, i tried it in the guild where i was getting the error & with your commit it worked totally fine. Waiting for commit to get merged in master branch ASAP 😐
