### ISSUE TITLE
Slash Options not working as intended

### ISSUE THREAD

**Issue by martinbndr** [Pycord-Development/pycord#1371]
### Summary

Slash_options Example not working or options buggy

### Reproduction Steps

Create a slash command (The channel command) using the example:
https://github.com/Pycord-Development/pycord/blob/master/examples/app_commands/slash_options.py

### Minimal Reproducible Code

```python
@bot.slash_command()
@option(
    "channel",
    [discord.TextChannel, discord.VoiceChannel],
    # you can specify allowed channel types by passing a list of them like this
    description="Select a channel",
)
async def testcommand(
    ctx: discord.ApplicationContext,
    channel: Union[discord.TextChannel, discord.VoiceChannel],
):
    await ctx.respond(f"Hi! You selected {channel.mention} channel.")
```

### Expected Results

The Bot starts and the command can be used.

### Actual Results

```py
Exception has occurred: TypeError
issubclass() arg 1 must be a class
```
(Running the bot in debug mode in vsc)
Running the bot file normally prints this traceback:
```
Traceback (most recent call last):
  File "c:\Users\MA\Documents\PythonBots\Rubicon\rubicon.py", line 175, in <module>
    async def testcommand(
  File "C:\Users\MA\Documents\PythonBots\Rubicon\env\lib\site-packages\discord\commands\options.py", line 270, in decorator
    func.__annotations__[name] = Option(type, **kwargs)
  File "C:\Users\MA\Documents\PythonBots\Rubicon\env\lib\site-packages\discord\commands\options.py", line 134, in __init__ 
    elif issubclass(input_type, (Enum, DiscordEnum)):
TypeError: issubclass() arg 1 must be a class
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

### Intents

discord.Intents.default

### System Information

- Python v3.9.0-final
- py-cord v2.0.0-candidate
    - py-cord pkg_resources: v2.0.0rc1
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I guess either the example coe is incorrect or something wrong with the new option system

**Comment by Dorukyum** [comment]
This was fixed in https://github.com/Pycord-Development/pycord/commit/a9da6412824c039e3a346e607cdc60914de8085d , the traceback looks outdated.

**Comment by Dorukyum** [comment]
Should be fixed in https://github.com/Pycord-Development/pycord/commit/06ac55bde20ee48184b1026b29280fa0e3906009.
