### ISSUE TITLE
TypeError: 'SlashCommand' object is not subscriptable

### ISSUE THREAD

**Issue by LeeWen0802** [Pycord-Development/pycord#1373]
### Summary

Run Pycord bot.run and shows errors

### Reproduction Steps

- Run Docker
- Run Python 3.10
- Run a python environment
- bot = discord.Bot(intents=discord.Intents.all(), help_command=None)
- bot.run("token")

### Expected Results

Run the bot

### Actual Results

Error: `TypeError: 'SlashCommand' object is not subscriptable`

### Intents

all

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-candidate
    - py-cord pkg_resources: v2.0.0rc1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22610

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Please show the full traceback

**Comment by LeeWen0802** [comment]
Kinda of weird, but only
`'SlashCommand' object is not subscriptable
  File "D:\bot\main.py", line 562, in <module>
    bot.run(config["botToken"])`

**Comment by LeeWen0802** [comment]
If I run that two code in a new Python environment, it seems to work fine
