### ISSUE TITLE
intents.members

### ISSUE THREAD

**Issue by krigjo25** [Pycord-Development/pycord#1375]
### Summary

Tried to create a command by using intents.members = True

### Reproduction Steps

Tried to create a command which allows you to view online members, by using intents.none(), default() or intents() class.
while intents.all() works

### Minimal Reproducible Code

```python
class DiscordSetup():

    def __init__(self):

        self.intents= Intents()
        self.bot = DiscordBot(intents=self.intents)

        return

    def SystemSetup(self):

        #   System Configuration
        self.intents.bans = True                    #   Allows the bot to ban / unban members
        self.intents.guilds = True                  #   Allows the bot to interect with guilds
        self.intents.members = True                 #   Allows the bot to interact with members
        self.intents.messages = True                #   Allows the bot to send messages Guild & DM
        self.intents.presences = True               #   Allows the bot to track member activty
        self.intents.message_content =True          #   Allows the bot to send embeded message
        self.intents.guild_reactions = True         #   Allows the bot to add reactions with-in the guild
        #self.intents. = True            
        self.intents.emojis = True     #   emoji, sticker related events


        self.bot.add_cog(ErrorHandler(self.bot))
        self.bot.add_cog(FrequentlyAskedQuestions(self.bot))

        return

    def ModerationSetup(self):

        #   Moderation - Module
        self.bot.add_cog(Administrator(self.bot))
        self.bot.add_cog(RoleModeration(self.bot))
        self.bot.add_cog(RolePermissions(self.bot))

        self.bot.add_cog(MemberModeration(self.bot))
        self.bot.add_cog(ChannelModeration(self.bot))
        self.bot.add_cog(GeneralModeration(self.bot))


        return

    def MiscModuleSetup(self):

        #   Community module
        self.bot.add_cog(CommunityModule(self.bot))

        return

def RunBot ():

        # necsessary values from .env
        disc = DiscordSetup()
        botKey = getenv('PyMod')

        disc.SystemSetup()
        disc.MiscModuleSetup()
        disc.ModerationSetup()

        disc.bot.run(botKey)

if __name__ == '__main__':
    RunBot()
```

### Expected Results

expected to view the online list of members

### Actual Results

No members were added to the list

### Intents

Intents() / intents.none() / intents.default()

### System Information

- Python v3.10.4-final                                                                                                  
- py-cord v2.0.0-candidate                                                                                                  
     - py-cord pkg_resources: v2.0.0rc1                                                                                 
-  - aiohttp v3.7.4.post0                                                                                                 
-  - system info: Windows 10 10.0.19044  

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Did you enabled the privileged intent in the developer portal?

**Comment by krigjo25** [comment]
Yes everything is enabled, as i stated the intents.members works while using intents.all, but not while you're using intents.member

**Comment by Dorukyum** [comment]
The intents object probably isn't being updated after being passed to the bot.

**Comment by Dorukyum** [comment]
> So I assume it's a bug

I assume it's a bug with the code they wrote, because they pass the intents object to the bot before it is updated.
To fix this, why not subclass the Bot class or update bot.intents instead?
