### ISSUE TITLE
Implement a Slash Command Group decorator outside of the Bot class

### ISSUE THREAD

**Issue by NeloBlivion** [Pycord-Development/pycord#1376]
### Summary

Add a slash_group decorator to discord.commands or ext.commands that isn't tied to the Bot class.

### What is the feature request for?

The core library

### The Problem

At the moment, we have decorators for various application command implementations and other 2.0 features across the library; decorators for slash commands, message commands, user commands and slash groups were added. 

We have `Bot.slash_command`, `discord.slash_command`, `commands.slash_command` and `ext.commands.slash_command` shortcuts for all the above mentioned... apart from one. Slash groups lack decorators outside of the bot class: that is to say, their only decorators are under `bot.slash_group` / `bot.group`, which is rather odd considering the other three types have them across the board. 

This also means that **it's not possible to define slash groups with a decorator inside cogs**, as you can't use `self` in a decorator so you would normally rely on importing the decorator... which doesn't exist.

### The Ideal Solution

Implement the `@slash_group` decorator in the library outside of the Bot class (i.e. `discord.slash_group`, `commands.slash_group` etc.)

**Comment by Dorukyum** [comment]
Slash command groups do not have callbacks, hence they can't be created with decorators.

**Comment by NeloBlivion** [comment]
> Slash command groups do not have callbacks

While this is true, groups are still internally considered by Discord as commands and are "useable" if no subcommands are present; I don't think it'd be entirely unreasonable for them to have support for decorator creation with a callback (though fair enough, at that point this should be an entirely different feature request.)
