### ISSUE TITLE
Slash Commands, 10 per cog

### ISSUE THREAD

**Issue by Nzii3** [Pycord-Development/pycord#1431]
### Summary

So, apparently, I can't add more than 10 slash commands per cog. I have 10 slash commands in my cog (not sending them - don't ask as it's really long code and it's nothing with the code), when I add another one, it doesn't register. When I remove a slash command from the cog, then add the new one, the new one registers. When I add the new slash command to another cog, it does register. So I'm really confused.

### Reproduction Steps

I have 10 slash commands in a cog, I needed to add 1 more and it doesn't register the new slash command added. There is no error or traceback.

### Minimal Reproducible Code

```python
  @slash_command(guild_ids=[..])
  async def slash_command_1(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_2(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_3(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_4(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_5(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_6(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_7(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_8(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_9(self, ctx):
   return
  @slash_command(guild_ids=[..])
  async def slash_command_10(self, ctx):
    return
  @slash_command(guild_ids=[..])
  async def slash_command_11(self, ctx):
    return
```

### Expected Results

I expect to be able to add more than 10 slash commands in a cog.

### Actual Results

I wasn't able to add more than 10 slash commands, the new ones don't register.

### Intents

all

### System Information

Version: 2.0.0rc1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I did make sure that the slash command doesn't have the same name as another one, or the same function name to there are no duplicates.

**Comment by EmreTech** [comment]
This is more likely because you reached the 200 Application Command registration limit per day

**Comment by Nzii3** [comment]
@EmreTech How do I see if this has happened? And it is highly unlikely.

**Comment by EmreTech** [comment]
You can enable the debug logger via `logging.basicConfig(level=logging.DEBUG)` (remember to import logging), I think it will have a debug message if it reaches this limit
Not 100% sure tho

**Comment by EmreTech** [comment]
This could also be because of the Global Application Command limits (100 Slash Commands, 5 User/Message Commands)

**Comment by Nzii3** [comment]
@EmreTech Im not even close to that limit, or any limit.

**Comment by Nzii3** [comment]
And when I have logging.DEBUG, it prints a WHOLE BUNCH of stuff in my console, dictionaries of member objects and channels.

**Comment by EmreTech** [comment]
> @EmreTech Im not even close to that limit, or any limit.

Then I think it's because of the other limit. Try now, it's been a day since you opened the issue.

**Comment by Nzii3** [comment]
@EmreTech Just tried it, it still doesn't work.

**Comment by Nzii3** [comment]
Oh my gosh, I had the indention incorrect so it was like this and didn't raise an error 🤦‍♂️
```py
  @slash_command(..)
  async def mycommand(self, ctx):
    # stuff
    @slash_command(...)
    async def mycommand2(self, ctx):
      #stuff
```

**Comment by Nzii3** [comment]
Dang, I apologize for not seeing that. Closing this issue now.
