### ISSUE TITLE
Replying to activation command for prefix bridge commands

### ISSUE THREAD

**Issue by OliMations** [Pycord-Development/pycord#1437]
### Summary

Add the ability to disable activation command replying with prefix bridge commands, or automatically resend a response without the reply if response with reply previously failed

### What is the feature request for?

discord.ext.bridge

### The Problem

At the moment if the prefixed version of a command is run it will automatically reply to the activation command, which is great. However, for various reasons, sometimes the activation command becomes unavailable. And currently, if that occurs a HTTPException is raised, which is fine but as far as I can tell I can't do anything about this as the reference is added outside my own code without any obvious method of controlling it. Adding this feature would of course prevent unnecessary errors.

### The Ideal Solution

I would like the ability to disable this behaviour outright to prevent this issue, and for the bot to automatically resend messages without the reference, with that feature being defaulted to on with the ability to also disable it.

### The Current Solution

I don't think there currently is one, at least not a pleasant one, I have tried a few different options I could think of and none worked. Apologies if there is one.

### Post Discussion Edit
A reasonable solution would be to override `fail_if_not_exists` to `False` as I presume it is currently not being overridden. Although the ability to disable message referencing would still be appreciated

**Comment by baronkobama** [comment]
Correct me if I'm wrong, but are you just looking to disable replying when the bridge command is used as a prefixed command? If so, since `BridgeExtContext` inherits from the standard `ext.commands.Context` you can use the standard `ctx.send(**kwargs)` to send a message without replying.

**Comment by OliMations** [comment]
But wouldn't that then fail when used as an application command? Using send for one and respond for another isn't super graceful...

**Comment by KrishnanS2006** [comment]
I'm not sure what you mean - the current implementation (using `reply`) just sends a message, which happens to reference the activation command. Using `send` instead (when an `HTTPException` is thrown) does almost the exact same actions as `reply`, with the only major difference being the removal of the actual reply.

Regarding ephemeral messages, I don't believe those are supported at all in prefix commands and are only possible in slash commands. How would that impact anything?

**Comment by OliMations** [comment]
Ignore the comment about ephemeral messages, I wasn't quite thinking straight.

I see what you're saying but that's quite impractical for me and many other people to do when they have bots with hundreds of message responses. It may work as a temporary solution, but I feel there needs to be a better one.

**Comment by KrishnanS2006** [comment]
Using a normal send does exactly what bots did pre-application-commands, which is just sending a message as a response. I don't get why this is impractical? And how is a reply more practical, when it is also just a sent message?

**Comment by OliMations** [comment]
As this is the bridge library I can't just use normal send as that wouldn't work when said command is used in slash form. The command would forever just be waiting for a response. You need to use respond (as covered [here](https://docs.pycord.dev/en/master/ext/bridge/index.html#discord.ext.bridge.BridgeContext.respond)) if you want to play nicely with both. I could, as you sort of suggested, wrap every respond in a try-except looking for HTTPExceptions, at which point I could use send. However, that's the impractical bit.

**Comment by baronkobama** [comment]
Or you could just use `isinstance(ctx, Bridge...Context)` and then handle how you need to respond as needed? I think the way of handling prefix vs slash in bridge commands is fine currently and not really impractical at all.

**Comment by KrishnanS2006** [comment]
What I was referring to was `BridgeExtContext._respond()`, which currently uses `self._get_super("reply")(*args, **kwargs)` to send a reply. A possible fix would be `except`ing an HTTPException here, and using `self._get_super("_get_channel")().send(*args, **kwargs)` to just send a plain message when a reply isn't possible. I feel like it's better to include this in `BridgeExtContext` directly, as it is something the class would benefit from (as opposed to implementing it yourself in the bridge command).

**Comment by EmreTech** [comment]
> What I was referring to was `BridgeExtContext._respond()`, which currently uses `self._get_super("reply")(*args, **kwargs)` to send a reply. A possible fix would be `except`ing an HTTPException here, and using `self._get_super("_get_channel")().send(*args, **kwargs)` to just send a plain message when a reply isn't possible. I feel like it's better to include this in `BridgeExtContext` directly, as it is something the class would benefit from (as opposed to implementing it yourself in the bridge command).

When would a reply not be possible?

**Comment by KrishnanS2006** [comment]
As @OliMations mentioned, this would be when the message containing the activation command becomes "unavailable". I'm still unsure of what exactly this means, however.

**Comment by OliMations** [comment]
> As @OliMations mentioned, this would be when the message containing the activation command becomes "unavailable". I'm still unsure of what exactly this means, however.

I am also unsure of how this happens, but since 01/06 I have seen it occur 37 times, but, regardless of whether or not you'd expect it to happen. Having redundancy in place is always important, especially with something running on a platform not controlled by yourself, that is honestly not the most stable or bug-free.

**Comment by KrishnanS2006** [comment]
> > When would a reply not be possible?
> 
> When the invocation message is deleted

Won't that just make it reply to a "This message was deleted"? I doubt an `HTTPException` would be thrown in that case...

**Comment by OliMations** [comment]
`File "/usr/local/lib/python3.9/dist-packages/discord/ext/bridge/context.py", line 81, in respond
return await self._respond(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/discord/ext/bridge/context.py", line 147, in _respond
message = await self._get_super("reply")(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/context.py", line 399, in reply
return await self.message.reply(content, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/discord/message.py", line 1637, in reply
return await self.channel.send(content, reference=self, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/discord/abc.py", line 1521, in send
data = await state.http.send_message(
File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 359, in request
raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 344, in invoke
await ctx.command.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/core.py", line 927, in invoke
await injected(*ctx.args, **ctx.kwargs)
File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/core.py", line 190, in wrapped
raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message`

That is most of the error raised for me, a very simple change would be to modify `to_reference` so that `fail_if_not_exists` is False as I presume its not currently being overridden

**Comment by plun1331** [comment]
> > > When would a reply not be possible?
> > 
> > 
> > When the invocation message is deleted
> 
> Won't that just make it reply to a "This message was deleted"? I doubt an `HTTPException` would be thrown in that case...

An HTTPException can and will be thrown unless the bot specifies that it shouldn't fail, as detailed in the above comment.
