### ISSUE TITLE
Timeout on Modal wait_for

### ISSUE THREAD

**Issue by KrishnanS2006** [Pycord-Development/pycord#1442]
### Summary

Add a timeout to Modals, in case of a cancellation

### What is the feature request for?

The core library

### The Problem

When a Modal is sent as a response to a command, there is an option to both submit and cancel the dialog. On modal submission, processing can be done through `callback`. However, when the modal is canceled, there is no way whatsoever for the code to detect this. Therefore, if a `modal.wait()` is used to wait for a Modal submission, if a submission never occurs and the cancel button is pressed, the script will thang indefinitely.

### The Ideal Solution

The simplest solution is to add a simple `timeout=` keyword argument to the `wait()` coroutine, or to implement a possible `on_timeout` method similar to `ui.View`. This allows for the script to actually continue in case a Modal is canceled, although the user must wait for the Modal to time out before the script continues.

### The Current Solution

There is no current solution.

### Additional Context

I am not aware of the Discord API and whether they report canceled modals - I believe they do not report them, but if by some way Pycord can access the state of a modal aside from whether it has been submitted or not, the most ideal solution would be to create an `on_cancel` callback when the Modal is canceled. However, I don't believe this is possible.

**Comment by NeloBlivion** [comment]
This isn't possible as Discord doesn't provide any event for cancelling a modal.
