### ISSUE TITLE
Support for optional BridgeOption's

### ISSUE THREAD

**Issue by KrishnanS2006** [Pycord-Development/pycord#1458]
### Summary

Make the `required=` parameter in a `BridgeOption` affect the prefix command.

### What is the feature request for?

discord.ext.bridge

### The Problem

Currently, when specifying a Bridge Option like below, the option becomes required for the prefix command. However, it is still optional for the slash command version.
```py
@bridge_command(name="profile", description="Check out your profile (or someone else's)")
async def _profile(
    self,
    context: ApplicationContext,
    user: BridgeOption(
        discord.User,
        "The user whose profile you want to view - defaults to your own if unspecified",
        required=False,
    ),
):
```
When trying to use the prefix command without a user, the below error is thrown:
```py
Ignoring exception in command profile:
Traceback (most recent call last):
  File "/home/krishnan/Coding/Hobby/ChessCord/ChessCordv2.0/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 344, in invoke
    await ctx.command.invoke(ctx)
  File "/home/krishnan/Coding/Hobby/ChessCord/ChessCordv2.0/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 919, in invoke
    await self.prepare(ctx)
  File "/home/krishnan/Coding/Hobby/ChessCord/ChessCordv2.0/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 849, in prepare
    await self._parse_arguments(ctx)
  File "/home/krishnan/Coding/Hobby/ChessCord/ChessCordv2.0/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 755, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/home/krishnan/Coding/Hobby/ChessCord/ChessCordv2.0/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 588, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: user is a required argument that is missing.
```

### The Ideal Solution

Somehow allow the `required=` kwarg to get passed into the converted prefix command, so it actually makes the option optional.

### The Current Solution

None

### Additional Context

N/A

**Comment by KrishnanS2006** [comment]
Update: I've gotten it to work! It turns out, adding ` = None` to give it a default worked for the prefixed command version.
```py
@bridge_command(name="profile", description="Check out your profile (or someone else's)")
async def _profile(
    self,
    context: ApplicationContext,
    user: BridgeOption(
        discord.User,
        "The user whose profile you want to view - defaults to your own if unspecified",
        required=False,
    ) = None,
):
```
From my debugging, it seems that the `required=` parameter is being passed correctly, and the only issue is that it has no effect in prefixed commands without the default value being provided. Although this is definitely different from the behavior of slash commands, it seems fine and doesn't affect the application command at all.

**Comment by dragonyc1002** [comment]
Where can I find the BridgeOption

**Comment by Revnoplex** [comment]
where even is BridgeOption in the pycord library?

**Comment by EmreTech** [comment]
https://github.com/Pycord-Development/pycord/blob/master/discord/ext/bridge/core.py#L247-L276

**Comment by Revnoplex** [comment]
why isnt it in the __init__.py

**Comment by Revnoplex** [comment]
Edit: i forgot about  __all__. why isnt it in __all__?

**Comment by EmreTech** [comment]
It monkeypatches `discord.commands.Option` to `BridgeOption`, so putting it in `__all__` is unnecessary

**Comment by Revnoplex** [comment]
so plain Option should just work in bridge commands

**Comment by Revnoplex** [comment]
because it doesn't work

**Comment by KrishnanS2006** [comment]
It should theoretically work, but personally, it doesn't work for me - I do feel like this is a horrible implementation (overwriting the default `Option` with `BridgeOption`, that is), and I mentioned this in the Discord server. My workaround for this as of now is to just `from discord.ext.bridge.core import BridgeOption` and use it directly, which is why the code snippet includes it.

**Comment by Revnoplex** [comment]
the thing that sucks is that my IDE screams at me when i do it
