### ISSUE TITLE
embed colors

### ISSUE THREAD

**Issue by BOTDEV123** [Pycord-Development/pycord#146]
### Summary

setting embed colors is not working nor raising any errors

### Reproduction Steps

i wanted to set a color to embed, it dint work or raise an error

### Minimal Reproducible Code

```python
color = discord.Color.green()
```

### Expected Results

to set my embed color as green

### Actual Results

![image](https://user-images.githubusercontent.com/82380093/132720332-8a6eff34-0286-463d-8baa-237b34b103cd.png)

### Intents

the same

### System Information

![image](https://user-images.githubusercontent.com/82380093/132720503-c2c8d004-1f99-42f7-80ce-0b94ea5bdade.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
The first place to ask something related to code problems is the Discord server. You also have to provide more info about the command.
