### ISSUE TITLE
Strange behaviour with a TextChannel in a tuple with something else

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#1461]
### Summary

for some reason printing a tuple containing a `TextChannel` and something else object throws an error

### Reproduction Steps

either print or write to a file a tuple containing a `TextChannel` object and 1 other thing anywhere (in an event function, command, slash command, etc)

### Minimal Reproducible Code

```python
@commands.command(name="test", description="for testing")
async def test_cmd(self, ctx):
    print((ctx.channel, None))
```

### Expected Results

to show a tuple normally

### Actual Results

threw:  `AttributeError: 'TextChannel' object has no attribute 'news'.`
traceback:
```python
File "/bot-dir/venv/lib/python3.10/site-packages/discord/commands/core.py", line 126, in wrapped
    ret = await coro(arg)

File "/bot-dir/venv/lib/python3.10/site-packages/discord/commands/core.py", line 852, in _invoke
    await self.callback(self.cog, ctx, **kwargs)

File "/bot-dir/cogs/testing.py", line 41, in test_cmd
    print((ctx.channel, None))

File "/bot-dir/venv/lib/python3.10/site-packages/discord/channel.py", line 190, in __repr__
    attrs = [(val, getattr(self, val)) for val in self._repr_attrs]

File "/bot-dir/venv/lib/python3.10/site-packages/discord/channel.py", line 190, in <listcomp>
    attrs = [(val, getattr(self, val)) for val in self._repr_attrs]
```

### Intents

all

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-candidate
    - py-cord pkg_resources: v2.0.0rc1
- aiohttp v3.8.1
- system info: Linux 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
This was fixed on `master`.

**Comment by Revnoplex** [comment]
I guess i'll update then
