### ISSUE TITLE
Ephemeral views stop responding after 15-30 minutes

### ISSUE THREAD

**Issue by Icebluewolf** [Pycord-Development/pycord#1481]
### Summary

When sending a View in an ephemeral message it will stop working after some time. The lib is still receiving the interaction but not processing and responding to it. 

### Reproduction Steps

Run the code below and wait 15-30 minutes pressing the button after this time. It will not respond.

### Minimal Reproducible Code

```python
import discord

class EphemeralPersistentView(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=None)

    @discord.ui.button(
        label="Ephemeral persistent button",
        style=discord.ButtonStyle.success,
        custom_id="EphemeralPersistentView:click",
    )
    async def click(self, button: discord.ui.Button, interaction: discord.Interaction):
        await interaction.response.send_message("received", ephemeral=True)

class Utility(discord.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command()
    async def test(self, ctx):
        await ctx.respond("respond", view=EphemeralPersistentView(), ephemeral=True)
```

### Expected Results

The "received" message to be sent

### Actual Results

The interaction timed out

### Intents

default

### System Information

2.0.0rc1 (I am fairly sure that it has not been fixed in the release)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I did test that the bot was receiving the interaction and it was not being cut off by discord.

**Comment by EmreTech** [comment]
`await ctx.prespond.general`
`ApplicationContext.prespond` doesn't seem to be defined, and even if you meant `ApplicationContext.response`, `InteractionResponse.general` also isn't defined. Could you maybe correct this in your example?

**Comment by Icebluewolf** [comment]
Sorry, I created some custom context and forgot to switch it back, should be good now

**Comment by Lulalaby** [comment]
Ephemeral messages aren't made to be responded after 15 mins
