### ISSUE TITLE
Guild locale

### ISSUE THREAD

**Issue by McJojo22** [Pycord-Development/pycord#1498]
### Summary

Make the guild_locale not just trough interactions accessable

### What is the feature request for?

The core library

### The Problem

guild_locale is just through interactions accessable

### The Ideal Solution

Add guild_locale to a normal guild object

### The Current Solution

Nothing

**Comment by baronkobama** [comment]
Already exists [here](https://docs.pycord.dev/en/master/api.html#discord.Guild.preferred_locale).

**Comment by McJojo22** [comment]
Oh, nice thank u ;)
