### ISSUE TITLE
Bot.load_extension doesn't raise exception if it cause exception inside imported module

### ISSUE THREAD

**Issue by yehorparkhomenko** [Pycord-Development/pycord#1502]
### Summary

Bot.load_extension doesn't raise exception if it cause exception inside imported module

### Reproduction Steps

1. Create module with error and setup function
2. Load module with bot.load_extension
3. Try to catch exception after bot.load_extension

### Minimal Reproducible Code

```python
# module.__init__.py

def setup(bot):
    raise Exception('test exception')

# run.py
bot = Bot(...)
try:
    bot.load_extension('module')
except Exception as e:
    print(e)
```

### Expected Results

We want to catch exception outside bot.load_extension.

### Actual Results

We got nothing.

### Intents

All intents

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-candidate
    - py-cord pkg_resources: v2.0.0rc1
- aiohttp v3.7.4.post0
- system info: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

https://github.com/Pycord-Development/pycord/pull/1423#issuecomment-1184555787

**Comment by baronkobama** [comment]
This is intentional behavior. If you want the exception to be raised, set the `store` parameter to `False`.

**Comment by vproyaev** [comment]
> This is intentional behavior. If you want the exception to be raised, set the `store` parameter to `False`.

can you tell me why such implicitness and in general why is this behavior intentional here?

**Comment by baronkobama** [comment]
> can you tell me why such implicitness and in general why is this behavior intentional here?

The reworked load_extension is designed to allow multiple extensions to be loaded at once (either via `recursive=True`, passing a folder, or using `load_extensions`) and to have the option to either raise the exception on encounter (therefore halting all loading), or to store it in a dictionary that the programmer can manually review on their own. This is also explained [here](https://docs.pycord.dev/en/master/api.html#discord.Bot.load_extension).

**Comment by yehorparkhomenko** [comment]
Thanks for the explanation!
