### ISSUE TITLE
SlashCommandGroup() raises "description must be of type str" but description is optional

### ISSUE THREAD

**Issue by Rag404** [Pycord-Development/pycord#1503]
### Summary

When creating a SlashCommandGroup object, the argument "description" is optional, but when it is not provided it raises "description must be of type str. Recieved "None"" error

### Reproduction Steps

Create a slash command group without providing the description:
```
my_group = discord.SlashCommandGroup("my_group_name")
```
You get the error

### Minimal Reproducible Code

```python
import discord
my_group = discord.SlashCommandGroup("my_group_name")
```

### Expected Results

Not getting any error since the "description" parameter is optional and its default value is None.

### Actual Results

Getting an error
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    my_group = discord.SlashCommandGroup("my_group_name")
  File "bot-env\lib\site-packages\discord\commands\core.py", line 1014, in __init__
    validate_chat_input_description(description)
  File "bot-env\lib\site-packages\discord\commands\core.py", line 1722, in validate_chat_input_description
    raise error
TypeError: Command and option description must be of type str. Received "None"
```

### Intents

discord.Intents.all()

### System Information

```
- Python v3.9.6-final
- py-cord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I am using a bot-env

**Comment by Middledot** [comment]
Will be fixed in #1496
