### ISSUE TITLE
Bridge commands - Cooldown does not work in cogs

### ISSUE THREAD

**Issue by nicholasyoannou** [Pycord-Development/pycord#1511]
### Summary

Cooldown works on commands in the main.py file, but not in cogs.

### Reproduction Steps

Try using commands.cooldown in a cog, isn't activated.
Try using commands.cooldown in the main.py file, it works fine.

### Minimal Reproducible Code

```python
Code for cog:

@commands.cooldown(1, 5, BucketType.user)
    @bridge.bridge_command(name='anime',
                           aliases=['amine', 'a'],
                           description='Lookup an anime')
    async def AnimeSearch(self, ctx, *, args):
       . . .
```

### Expected Results

Cooldown to activate and to say a warning (as I've configured it).

### Actual Results

Cooldown isn't activated, cooldown is ignored entirely.

### Intents

intents=discord.Intents(messages=True, reactions=True, members=True, guilds=True, message_content=True)

### System Information

- Python v3.9.6-final
- py-cord v2.0.0-final
- aiohttp v3.7.2
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by nicholasyoannou** [comment]
Seems like it's a simple mistake, thanks to the Pycord Discord community again,
your meant to put the cooldown after command decorator. Normally prefix this doesn't make a difference, but for bridge it seems it does.

**Comment by argo0n** [comment]
> Seems like it's a simple mistake, thanks to the Pycord Discord community again, your meant to put the cooldown after command decorator. Normally prefix this doesn't make a difference, but for bridge it seems it does.

Just found this solution after I thought an issue with my slash commands' cooldowns was occuring past 2.0.0. Thanks for pointing this out here!
