### ISSUE TITLE
VoiceClient automatically stops playing audio after X seconds

### ISSUE THREAD

**Issue by MaelstromDota** [Pycord-Development/pycord#1514]
### Summary

bot does not play audio fully

### Reproduction Steps

create FFmpegPCMAudio with url
pass FFmpegPCMAudio into VoiceClient.play

### Minimal Reproducible Code

```python
ytdl_format_options = {
    "format": "bestaudio/best",
    "restrictfilenames": True,
    "extractaudio": True,
    "audioformat": "mp3",
    "noplaylist": True,
    "nocheckcertificate": True,
    "ignoreerrors": False,
    "logtostderr": False,
    "quiet": True,
    "no_warnings": True,
    "default_search": "auto",
	"source_address": "0.0.0.0"
}
ffmpeg_options = {
	"before_options": "-nostdin",
	"options": "-vn",
}
ytdl = yt_dlp.YoutubeDL(params=ytdl_format_options)

class Song(discord.PCMVolumeTransformer):
	def __init__(self, source: discord.AudioSource, *, data: dict, volume: float=0.5):
		super().__init__(source, volume)
		self._data = data

	@classmethod
	async def from_url(cls, url: str):
		loop = asyncio.get_event_loop()
		data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=False))
		if "entries" in data:
			data = data["entries"][0]
		info = {
			"url": data["url"],
		}
		del data
		return cls(discord.FFmpegPCMAudio(info["url"], **ffmpeg_options), data=info)

guild.voice_client.play(source=await Song.from_url(url="song name here"))
```

### Expected Results

bot plays audio till end

### Actual Results

bot stops playing audio after 30s

### Intents

discord.Intents().all()

### System Information

- Python v3.10.5-final
- py-cord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by mojansch** [comment]
I don't think that's an issue with pycord, but with ffmpeg and the way youtube streams the audio. Try changing your ffmpeg options to
```python
{
    "before_options": "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -nostdin",
    "options": "-vn",
}
```
That fixed it for me.

**Comment by MaelstromDota** [comment]
> I don't think that's an issue with pycord, but with ffmpeg and the way youtube streams the audio. Try changing your ffmpeg options to
> 
> ```python
> {
>     "before_options": "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -nostdin",
>     "options": "-vn",
> }
> ```
> 
> That fixed it for me.

thank you, it works
