### ISSUE TITLE
Update/ Correct PyCord guide for receiving voice samples section

### ISSUE THREAD

**Issue by kilgoreandy** [Pycord-Development/pycord#1516]
### Summary

An update is needed to the PyCord guide for receiving voice samples section 

### Reproduction Steps

Currently, following the guide at https://guide.pycord.dev/voice/receiving/ does not produce the expected functionality. The user is left with three error messages. 

With the help of some PyCord members, I altered the code to a working version pasted below. 

Please update the docs to fix the incorrect references:
1) Once_done function references two separate variables (user_recorded and recorded_user)
2) In Once_done function, replace discord.Sink with discord.sinks
3) Replace discord.WaveSink with discord.sinks.WaveSink

I have added.a snippet of code with all of the modifications for reference. 

![image](https://user-images.githubusercontent.com/92450298/179863537-d3f3dfa9-22c7-4c21-864b-de5f5b4b79c1.png)

### Expected Results

User is able to directly copy and paste from the documentation and have a working example. 

### Actual Results

User is presented with at least three errors that hinder code execution. 

### Intents

N/A

### System Information

Python 3.9 
Pycord[voice] 2.0.0
Mac OS Ventura B1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment]
If this is an issue with the guide (and is not a library issue) then please open an issue on the guide's repo.

**Comment by kilgoreandy** [comment]
Moved to correct repo
