### ISSUE TITLE
register / load the cogs

### ISSUE THREAD

**Issue by callednao** [Pycord-Development/pycord#1528]
### Summary

Often the bot dont load cogs that got loaded with the load_extension function. you dont get an error in the console or anything else it just stops working

### Reproduction Steps

To make the bug appear i just use this loading cog code. even i you load every cog manually it doesnt work. 

```
for filename in os.listdir('commands'):
    if filename.endswith('.py'):
        if filename != "__init__.py":
            bot.load_extension(f'commands.{filename[:-3]}')
            print(f'[+] {filename[:-3]}')
```

My Cog Class looks like the example on the website and worked some versions ago perfect. 
After i opened a help thread on the discord it was confirmed to me that it is a bug.

### Minimal Reproducible Code

```python
bot.load_extension(f'commands.Moderation')
```

### Expected Results

when i used the `load_extension` function usually the specified cog file was always loaded and you could use the listeners and commands in the cog.

### Actual Results

The commands and listeners are not loaded. If you debug the `def setup` method to load the cog, it is not displayed in the console either. 

### Intents

discord.Intents.all()

### System Information

- Python v3.10.4-final
- py-cord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Load the cog with `store=False` to raise the errors. This wont be needed in the next version.
