### ISSUE TITLE
Update to work with two factor

### ISSUE THREAD

**Issue by Dlopo100** [Pycord-Development/pycord#1538]
### Summary

If the bot is in a guild with discovery activated, when doing an action it gives you an error, and returns that the two factor is required in this operation

### Reproduction Steps

So far I have detected it when creating a text channel

### Expected Results

I expected you to create the text channel

### Actual Results

  File "c:\Users\dotra\Downloads\Programacion\FiveM\bot_discord\python_files\tickets.py", line 504, in actions_button_create_ticket
    channel_created = await guild.create_text_channel(label_ticket + ' - ' + str(ticket_str), category=category , overwrites=overwrites)
  File "C:\Users\dotra\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\guild.py", line 1206, in create_text_channel
    data = await self._create_channel(
  File "C:\Users\dotra\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 353, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 60003): Two factor is required for this operation

### Intents

discord.Intents.all()

### System Information

- Python v3.9.2-final
- py-cord v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
This is done by server administrators in server settings. To do moderation actions, you need to enable 2FA on your account.
