### ISSUE TITLE
Says 'discord.py' instead of 'Pycord' AND logo for the website is dpy logo not Pycord.

### ISSUE THREAD

**Issue by iTzNao** [Pycord-Development/pycord#154]
### Summary

Says 'discord.py' instead of 'Pycord' AND logo for the website is dpy logo not Pycord.

### Reproduction Steps

Visit the documentation.

### Expected Results

Say pycord and have pycord logo

### Actual Results

Say discord.py and discord.py logo

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by iTzNao** [comment]
you have to go to https://pycord.readthedocs.io/en/latest/ not https://pycord.readthedocs.io/en/master/#

**Comment by nerdguyahmad** [comment]
Docs site will be updated when 2.0 releases.
