### ISSUE TITLE
Thread for message creating thread is None

### ISSUE THREAD

**Issue by rohanbansal12** [Pycord-Development/pycord#1548]
### Summary

I'm trying to get the thread id from  a message which creates the thread, but I'm getting None

### Reproduction Steps

I set up a simple bot to read messages, and am testing it with creating a thread

### Minimal Reproducible Code

```python
class MyClient(discord.Client):
    def __init__(self):
        intents = discord.Intents.default()
        intents.messages = True
        intents.message_content = True
        intents.members = True
        intents.guilds = True
        super().__init__(intents=intents)
        self.s3_client = boto3.client("s3")
        self.BUCKET = os.environ.get("S3_BUCKET")

    async def on_message(self, message):
        message_dict = {
            "guild_id": message.guild.id,
            "id": message.id,
            "channel_id": message.channel.id,
            "user_id": message.author.id,
            "content": message.content,
            "mentions": [x.id for x in message.mentions],
            "created_at": message.created_at.timestamp(),
            "embeds": [x.url for x in message.embeds],
            "jump_url": message.jump_url,
            "thread": message.thread,
        }
        print(message_dict)
        self.s3_client.put_object(
            Body=json.dumps(message_dict, default=str), Bucket=self.BUCKET, Key=f"{message.guild.id}/{message.id}.json"
        )

    async def on_thread_create(self, thread):
        thread_dict = {
            "guild_id": thread.guild.id,
            "id": thread.id,
            "created_at": thread.created_at.timestamp(),
            "parent_id": thread.parent_id,
            "owner_id": thread.owner_id,
            "name": thread.name,
            "last_message": thread.last_message_id,
        }
        print("Thread: ", thread_dict)
```

### Expected Results

I expected the thread attribute in on_message to be a valid thread id.

### Actual Results

The thread seems to come back as None each time.

### Intents

messages, members, guilds, message_content

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
`message.thread` refers to a thread that was created from a message, not the thread the message was in.

For the thread the message is in, you can use the channel `attribute`.

**Comment by rohanbansal12** [comment]
I understand that, the message is creating a thread but the thread value is still None

**Comment by baronkobama** [comment]
> I understand that, the message is creating a thread but the thread value is still None

If you're attempting to get that thread via on_message, you won't get it. When on_message fires, that thread won't exist yet.

**Comment by rohanbansal12** [comment]
Ah interesting, so is there some way I could go about getting that? Even on the on_thread_create method, the last_message parameter returns None, but I need some way to determine the message initiating the thread and the thread itself

**Comment by baronkobama** [comment]
> Ah interesting, so is there some way I could go about getting that? Even on the on_thread_create method, the last_message parameter returns None, but I need some way to determine the message initiating the thread and the thread itself

The ID of the thread and the message which created the thread will always be the same, if there is a thread to be found. If you can get the ID of the thread or the message, you can always get the other object that you don't have.
