### ISSUE TITLE
Add support for interaction.to_dict()

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#155]
### Summary

Add support for interaction.to_dict()

### What is the feature request for?

The core library

### The Problem

When an interaction is called in DMs, the event goes to Shard 0. This is fine for most use cases, but multi-process bots need to provide this event to the right process. This often works through some connection which exchanges JSON strings.

### The Ideal Solution

A `Interaction.to_dict` function.

### The Current Solution

none

**Comment by UP929312** [comment]
@Dorukyum You want to close this? https://github.com/Pycord-Development/pycord/commit/711576aa395cede2911963e47fc24a3f80170c2d added this (as you are aware)
