### ISSUE TITLE
discord.cog.Cog not loading correctly

### ISSUE THREAD

**Issue by Fallcrim** [Pycord-Development/pycord#1554]
### Summary

One of my cogs is not correctly being registered

### Reproduction Steps

It is a cog, with default implementation. Means a class with a few functions and a setup() function.

### Minimal Reproducible Code

```python
import ...
class Cog(discord.cog.Cog):
    def __init__(self, bot):
        self.bot = bot
    @discord.slash_command()
    async def command(self, ctx):
        ...

def setup(bot):
    bot.add_cog(Cog(bot))
```

### Expected Results

The command should get loaded without any issue and be included in bot.extensions

### Actual Results

The cog was loaded with raising an exception. After checking bot.extensions it wasn't there

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-candidate
    - py-cord pkg_resources: v2.0.0rc1
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If you need any specific code please just tell me
Otherwise kind regards :D

**Comment by JustaSqu1d** [comment]
Refer to #1528

**Comment by Fallcrim** [comment]
Thanks for the reference @JustaSqu1d. After adding the 'store' argument to the loading method, I got a traceback:
`TypeError: Command.__init__() missing 1 required positional argument: 'func'`

**Comment by Fallcrim** [comment]
Actually I found out that the commands.Group causes the issue

**Comment by Fallcrim** [comment]
NOTE: Removed commands.Group and replaced it with `discord.SlashCommandGroup`.
Now working
