### ISSUE TITLE
ApplicationCommand mention

### ISSUE THREAD

**Issue by LuisWollenschneider** [Pycord-Development/pycord#1564]
### Summary

Add mention parameter to ApplicationCommand

### What is the feature request for?

The core library

### The Problem

There is no easy way to properly highlight an ApplicationCommand in a message.

The markdown has the format
`</COMMAND_NAME:APPLICATION_ID>`

### The Ideal Solution

The solution would be to have a `mention` attribute for ApplicationCommands.

```py
@bot.application_command()
async def command(ctx: ApplicationContext):
    await ctx.respond(ctx.command.mention)
```

### The Current Solution

The best way currently is to craft the markdown by hand every time.
```py
@bot.application_command()
async def command(ctx: ApplicationContext):
    await ctx.respond(f"</{ctx.command.name}:{ctx.bot.application_id}>")
```

### Additional Context

As far as I see, the `application_id` is not accessible within the `ApplicationCommand` class, which is necessary for the markdown.

**Comment by stickfab** [comment]
This was addressed in PR #1523 and has been added to the source code ever since
