### ISSUE TITLE
Installation using pip install -r requirements_file is not functional

### ISSUE THREAD

**Issue by Smrt666** [Pycord-Development/pycord#1570]
### Summary

When installing discord.py and py-cord at the same time using pip install -r, installed module does not work.

### Reproduction Steps

requirements.txt has only two lines:
```
discord.py
py-cord
```
I installed it using `pip install -r requirements.txt`.

### Minimal Reproducible Code

```python
import discord
```

### Expected Results

Nothing

### Actual Results

When running program with `import discord` line, it gives the following error:
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import discord
  File "/home/jost/Documents/disc-bot/env2/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/jost/Documents/disc-bot/env2/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/home/jost/Documents/disc-bot/env2/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/home/jost/Documents/disc-bot/env2/lib/python3.8/site-packages/discord/webhook/async_.py", line 52, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/home/jost/Documents/disc-bot/env2/lib/python3.8/site-packages/discord/channel.py)

```

### Intents

Execute slash commands.

### System Information

The given command gives the error above. When installing discord.py and py-cord separately it produces:

- Python v3.8.13-final
- py-cord v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Installing the two libraries separately using `pip install discord.py` and `pip install py-cord` does not cause an error.

**Comment by plun1331** [comment]
discord.py cannot be installed alongside py-cord as they use the same namespace.
