### ISSUE TITLE
Fetch_guild getting with_counts

### ISSUE THREAD

**Issue by JDJGInc** [Pycord-Development/pycord#159]
### Summary

This basically adds the ability to correctly get prescence_count

### What is the feature request for?

The core library

### The Problem

The problem is that you can't do this on the guild object itself(and to add stuff that doesn't exist in guild stuff)

### The Ideal Solution

I would like this fork to be able to get prescence_count, the new member_count at the time, and of course other guild information

having a fetch_guild with the prescence_count and member_count as a part of the guild object, otherwise normal get would have prescence_count None, and member_count would be the most updated(it also doesn't require intents to get all the users online, you can't always get intents either. Discord would probaly like it even more if you added this)
and being able to get with_counts on many guilds with fetch_guilds.

### The Current Solution

The current one is to fetch the invite(which as we know we don't always have permissions to make, and not all guilds have vanity urls), but even so you should only have to be able to use fetch_guild or fetch_guilds.

for example now you need to have an invite object to get the prescence count, and an accurate member_count.

**Comment by Grace-codes** [comment]
Could you elaborate on this?

**Comment by JDJGInc** [comment]
Discord.py was missing the option to grab prescence data(a.k.a those who are not offline), except by invites, the with_counts has it fetch via fetch__guild which is much better than getting it on invite.

**Comment by JDJGInc** [comment]
https://github.com/Rapptz/discord.py/pull/4029/files
Look at this old pull request.

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/141887649-35a13b95-763f-4337-bcde-c5f8e435cc3d.png)
It's also probably better than having to make a manually invite in order to get these.
Source: https://discord.com/developers/docs/resources/guild
Can you also add other missing values rom https://discord.com/developers/docs/resources/guild?
if so thanks :D.
I'll uh find out what values aren't covered yet.
(I am not talking about threads or stuff that's already covered as the update suggests)

**Comment by JDJGInc** [comment]
This a copy and paste( a bit from my old thing)

**Comment by JDJGInc** [comment]
So yes, it will work better with this, and discord will likely appreciate this, rather than getting intents to just get the data.

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/141926782-46a17299-c9fb-4ec4-805a-84de190ac423.png)
you could be supporting something other libraries have
https://gist.github.com/advaith1/e69bcc1cdd6d0087322734451f15aa2f

**Comment by JDJGInc** [comment]
https://github.com/Pycord-Development/pycord/pull/465
this should fix it I believe
