### ISSUE TITLE
Modal builder missing significant functionality

### ISSUE THREAD

**Issue by huths0lo** [Pycord-Development/pycord#1604]
### Summary

Unable to add placeholder, and select menus to Modal Dialogue

### What is the feature request for?

The core library

### The Problem

Feature request is for "discord.ui.Modal", which isnt an option in the selection above.

With the Modal builder, there is only a couple of options: Children, Title, Custom ID, and Timeout.  This essentially only allows you to pop up a box to fill in with a title, and nothing more.  This misses a couple of key needs.

### The Ideal Solution

Need to add the placeholder, min_length, max_length, and required (true/false) options, just to complete the text box.

Need to have an optional passthrough variable(s), between the callup (slash command/button) and the modal builder class.  This way variables can be used to populate the components of the text input.  This is especially important for the placeholder, as it can be tailored to the user who initiated it.

I believe I had read that a modal could include both text input, and select menu.  Although I'm not able to find that info to cite here.  If thats correct, the text input class builder should allow the use of select menu builder commands.

### The Current Solution

Use incoming_payload = ctx.to_dict(), and modal_payload = modal.to_dict() to collect the info from the incoming request, and the nonce data created by the modal.  Recreate the json payload, and then send directly to url = f'{API_ENDPOINT}/webhooks/{application_id}/{interaction_token}'.

**Comment by JustaSqu1d** [comment]
> I believe I had read that a modal could include both text input, and select menu. 

This was true. Discord recently removed Select Menus from modals because it was incompatible with mobile applications, meaning that Select Menus are not currently supported in modals.

To quote Discord's Documentation:
> Support for components in modals is currently limited to type 4 (Text Input).

[source](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal)

**Comment by Lulalaby** [comment]
"Significant"

You're requesting features work doesn't exist for modals. 
I have an own library which implements upcoming stuff very fast but I haven't even touched that nor any other lib. 

You're requesting the impossible. 

If you want to see it in the lib, ask download to work faster on it 🤷‍♀️

**Comment by huths0lo** [comment]
// this is a modal
{
  "title": "My Cool Modal",
  "custom_id": "cool_modal",
  "components": [{
    "type": 1,
    "components": [{
      "type": 4,
      "custom_id": "name",
      "label": "Name",
      "style": 1,
      "min_length": 1,  <---------- THAT RIGHT THERE
      "max_length": 4000,  <---------- THAT RIGHT THERE
      "placeholder": "John",  <---------- THAT RIGHT THERE
      "required": true
    }]
  }]
}

The info in the literal Discord API documentation is here:  https://discord.com/developers/docs/interactions/message-components#text-inputs

**Comment by Dorukyum** [comment]
And right here, in the pycord documentation: https://docs.pycord.dev/en/master/api.html#discord.ui.InputText

**Comment by Lulalaby** [comment]
This isn't implemented? Are you sure. 

I was only talking about modals btw

**Comment by huths0lo** [comment]
Not implemented in pycord as far as I can tell.

Help on class Modal in module discord.ui.modal:

class Modal(builtins.object)
 |  Modal(*children: 'InputText', title: 'str', custom_id: 'Optional[str]' = None, timeout: 'Optional[float]' = None) -> 'None'
 |
 |  Represents a UI Modal dialog.
 |
 |  This object must be inherited to create a UI within Discord.
 |
 |  .. versionadded:: 2.0
 |
 |  Parameters
 |  ----------
 |  children: :class:`InputText`
 |      The initial InputText fields that are displayed in the modal dialog.
 |  title: :class:`str`
 |      The title of the modal dialog.
 |      Must be 45 characters or fewer.
 |  custom_id: Optional[:class:`str`]
 |      The ID of the modal dialog that gets received during an interaction.
 |      Must be 100 characters or fewer.
 |  timeout: Optional[:class:`float`]
 |      Timeout in seconds from last interaction with the UI before no longer accepting input.
 |      If ``None`` then there is no timeout.

**Comment by Dorukyum** [comment]
The fields belong to the input field, I shared the link above.

**Comment by huths0lo** [comment]
I see it now.  I could have sworn I tried this several times.  But clearly I hadnt.

self.add_item(discord.ui.InputText(label="Label Name", placeholder="10"))

**Comment by plun1331** [comment]
> So it looks like it only accepts label, and nothing else.

the only **required** field is `label`, the rest are optional
