### ISSUE TITLE
Include silence in voice recording / combine audio from all users

### ISSUE THREAD

**Issue by TheBluekr** [Pycord-Development/pycord#1611]
### Summary

Add the option to include silence packets Discord sends in a sink for the duration of a recording. In addition, add the option to combine audio from all users at once into a single file.

### What is the feature request for?

The core library

### The Problem

Currently pycord drops any silent packets sent by Discord and thus won't be included in the recording. With this it could also be easier to combine audio from multiple users into a single audio file with more proper timings. 

### The Ideal Solution

Include silent packets in the recording allowing the recording of users to be full length.

**Comment by Icebluewolf** [comment]
A good solution for this would be an opt-in argument like `include_silence=boolean`

**Comment by Om1609** [comment]
Discord doesn't actually send all silence packets. It only sends 5 frames of silence of to indicate the start of silence. 

A workaround is in works in #1984. Although it relies on timestamp of receipt of packets to figure out silence, which is dependent on the network. This isn't ideal, but network also affects any normal user connected to a Voice Channel, so it is fair enough.
