### ISSUE TITLE
Bridge command missing description

### ISSUE THREAD

**Issue by Krutyi-4el** [Pycord-Development/pycord#1619]
### Summary

Description of prefix bridge command is missing

### Reproduction Steps

Create any bridge command with `description`.

### Minimal Reproducible Code

```python
@bot.bridge_command(description="really useful description")
async def test(ctx):
    await ctx.respond(f"Description: {ctx.command.description}")
```

### Expected Results

![shoud_be](https://user-images.githubusercontent.com/60041069/188631244-05b18b93-8840-4d76-abe8-0d93612cb87e.jpg)

### Actual Results

![actually_is](https://user-images.githubusercontent.com/60041069/188631314-6a9ced7d-7632-46ae-aea6-c7416be5822d.jpg)

### Intents

default + message_content

### System Information

- Python v3.9.9-final
- py-cord v2.1.1-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.17763

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The cause:
https://github.com/Pycord-Development/pycord/blob/master/discord/ext/bridge/core.py#L72

**Comment by Lulalaby** [comment]
Status Update please 
@Pycord-Development/maintainers
