### ISSUE TITLE
`interaction.response.edit_message` produces error without upgrade to latest from Py-cord 2.0.1.

### ISSUE THREAD

**Issue by iodeslykos** [Pycord-Development/pycord#1634]
### Summary

`interaction.response.edit_message` produces error without upgrade to latest from Py-cord 2.0.1.

### Reproduction Steps

When creating a new virtual environment or working with global packages: the first installation Py-cord and attempt to run a bot results produces the stack trace in "Actual Results" below.

The issue is mitigated by:
- pip3 install py-cord==2.0.1
- pip3 install --upgrade py-cord (installs 2.1.3 currently)

After the installation and then subsequent upgrade, the bot runs without issue.

### Minimal Reproducible Code

```python
class GeneralResponseButtons(discord.ui.View):
    def __init__(self, *, timeout=180):
        super().__init__(timeout=timeout)

    @discord.ui.button(label="Tell me more.", style=discord.ButtonStyle.blurple)
    async def blurple_button(self, button: discord.ui.Button, interaction: discord.Interaction):
        button.style = discord.ButtonStyle.red

        await interaction.response.edit_message(content=f"This is merely a test of button functionality!", view=self)

    @discord.ui.button(label="OK", style=discord.ButtonStyle.grey)
    async def ok_button(self, button: discord.ui.Button, interaction: discord.Interaction):
        button.style = discord.ButtonStyle.green
        await interaction.response.edit_message(content=f"You clicked OK!", view=self)

    @discord.ui.button(label="CANCEL", style=discord.ButtonStyle.red)
    async def cancel_button(self, button: discord.ui.Button, interaction: discord.Interaction):
        button.style = discord.ButtonStyle.grey
        for child in self.children:
            child.disabled = True
        await interaction.response.edit_message(content="Cancelled!", view=self)
```

### Expected Results

Execution to occur without the requirement of installing a package multiple times.

### Actual Results

```
Traceback (most recent call last):
  File <redacted>/main.py", line 9, in <module>
    from discord.ext import bridge
  File "<redacted>/.venv/lib/python3.10/site-packages/discord/ext/bridge/__init__.py", line 26, in <module>
    from .bot import *
  File "<redacted>/.venv/lib/python3.10/site-packages/discord/ext/bridge/bot.py", line 32, in <module>
    from .context import BridgeApplicationContext, BridgeExtContext
  File "<redacted>/.venv/lib/python3.10/site-packages/discord/ext/bridge/context.py", line 28, in <module>
    from discord.commands import ApplicationContext
  File "<redacted>/.venv/lib/python3.10/site-packages/discord/commands/__init__.py", line 26, in <module>
    from .context import *
  File "<redacted>/.venv/lib/python3.10/site-packages/discord/commands/context.py", line 68, in <module>
    class ApplicationContext(discord.abc.Messageable):
  File "<redacted>/.venv/lib/python3.10/site-packages/discord/commands/context.py", line 336, in ApplicationContext
    @discord.utils.copy_doc(Interaction.edit_original_message)
AttributeError: type object 'Interaction' has no attribute 'edit_original_message'. Did you mean: 'edit_original_response'?
```

### Intents

discord.Intents.default()

### System Information

- Python v3.10.6-final
- py-cord v2.1.3-final
- aiohttp v3.8.1
- system info: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

- Discord.py v2.0.1

**Comment by iodeslykos** [comment]
Currently under the impression that this issue may be related to this PR: https://github.com/Pycord-Development/pycord/pull/1609

**Comment by JustaSqu1d** [comment]
But that PR isn't merged. Perhaps you have another package that shares the namespace `discord`?

**Comment by iodeslykos** [comment]
> But that PR isn't merged. Perhaps you have another package that shares the namespace `discord`?

You're correct. I hadn't removed `discord.py==2.0.1` from my requirements.txt which was causing the namespace collision/overwriting Py-cord's files.

Apologies for the oversight.
