### ISSUE TITLE
Missing parameters and properties for ForumChannel Type

### ISSUE THREAD

**Issue by lorddusk** [Pycord-Development/pycord#1635]
### Summary

Support for forum tags was added in the API

### What is the feature request for?

The core library

### The Problem

Discord finally released the tag properties for guilds. 
Which allows us to interact with forum tags through our bots.

The tag object:
https://discord.com/developers/docs/resources/channel#forum-tag-object

Missing properties found here:
https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel-jsonform-params

Especially since the forum feature itself was released to the public literally 15 minutes after I posted this feature request.

### The Ideal Solution

Implemented into the library for people to use.

**Comment by Lulalaby** [comment]
This should be already added. Are you sure it's missing

**Comment by lorddusk** [comment]
Yeah pretty sure, as there is no get/fetch method for the forum tags, nor a parameter/method to add them to forum threads.

**Comment by lorddusk** [comment]
Yeah, just checked the following 2 files + methods, and they both have no tag support as of current master branch.

https://github.com/Pycord-Development/pycord/blob/master/discord/http.py#L1096

and 

https://github.com/Pycord-Development/pycord/blob/master/discord/channel.py#L802
