### ISSUE TITLE
on_thread_create fires too early for forum threads - or on_thread_first_message is missing.

### ISSUE THREAD

**Issue by Slluxx** [Pycord-Development/pycord#1637]
### Summary

I want to post a message in a forum thread upon creation, however this is only possible if the post author has has send an initial message. That initial message can be delayed due to an image upload for example (drag and drop an image into the "new forum post" window), creating a period of time where i am forced to stop my script for that to happen.

### Reproduction Steps

Create a forum and a bot that autoreplies a message to a thread upon creation.

### Minimal Reproducible Code

```python
@commands.Cog.listener()
    async def on_thread_create(self, thread):
        if thread.parent.type == discord.ChannelType.forum:
            await thread.send(response)
```

### Expected Results

I expect to wait for a thread to be "fully initalized" before on_thread_create is triggered.

### Actual Results

discord.errors.Forbidden: 403 Forbidden (error code: 40058): Cannot message this thread until after the post author has sent an initial message.

### Intents

all

### System Information

- Python v3.10.6-final
- py-cord v2.1.1-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I do understand that `on_thread_create` is not just used for forum threads but all, which work just fine with the above code.

Possible solutions (imho):
- just wait till the thread is fully usable before emitting the event (you are supplying the thread as argument, so i expect the methods in it to work)
- split `on_thread_create` into `on_thread_create` and `on_forumThread_create`, in which you wait for the first message to be send
- create a new event like: `on_thread_first_message`

**Comment by BobDotCom** [comment]
This is an event sent directly by discord, so delaying the event simply wouldn't make sense. If you want to add handling in your own code to wait until the first message has been sent, that would be a feasible solution.
