### ISSUE TITLE
SlashCommand inside the cog not registering

### ISSUE THREAD

**Issue by ThiagoLira** [Pycord-Development/pycord#1648]
### Summary

I create a simple cog with a command and I can't call the command via the main bot

### Reproduction Steps

run my main application, the bot connects to discord, but the command doesn't work

### Minimal Reproducible Code

```python
// on main bot
class DreamBot(commands.Bot):
    def __init__(self):
        intents = discord.Intents.default()
        intents.members = True
        super().__init__(command_prefix=commands.when_mentioned_or('?'), intents=intents, auto_sync_commands=True)
        self.logger = get_logger(__name__)

    async def on_ready(self):
        self.logger.info(f'Logged in as {self.user.name} ({self.user.id})')
        self.load_extension('stablecog')


    async def close(self):
        await self._bot.close()


// on cog file
class StableCog(commands.Cog, name='Stable Diffusion', description='Create images from natural language.'):
    def __init__(self, bot):
        self.text2image_model = pipe
        self.bot = bot

    @discord.slash_command(name='dream')
    @option(// a bunch of options...)
    async def dream(self, ctx: discord.ApplicationContext):
          # command code
def setup(bot):
    bot.add_cog(StableCog(bot))


// on main application 
dreambot = DreamBot()
dreambot.run(TOKEN)
```

### Expected Results

A expected to call "/dream" or ?dream or something like that on discord and have the bot run this command

### Actual Results

Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "dream" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "/dream" is not found

### Intents

intents = discord.Intents.default()

### System Information

- Python v3.8.5-final
- py-cord v2.1.3-final
- aiohttp v3.8.3
- system info: Linux 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Extensions must be loaded before the bot connects to Discord for commands to be registered
