### ISSUE TITLE
All slash commands disappear after using one

### ISSUE THREAD

**Issue by M1N0RM1N3R** [Pycord-Development/pycord#1650]
### Summary

When I run a slash command in my bot, all my commands deregister

### Reproduction Steps

1. Create a bot with slash commands
2. Run it, and use one of its slash commands.
3. The command runs as intended.
4. Now, the bot's profile picture is gone from the slash command menu. While its commands may linger for a bit, they show an "Invalid interaction application command" error when you try to run them. Nothing is printed to the terminal.

### Minimal Reproducible Code

```python
bot = discord.Bot(debug_guilds=[secrets['discord']['guild_id']])

@bot.slash_command()
async def ping(ctx):
    await ctx.send_response(f"Pong! Latency: {bot.latency} secs. Active since <t:{login_time}>. Version: {VERSION}", ephemeral=True)

bot.run(secrets['discord']['bot_token'])
```

### Expected Results

Commands are persistent, I don't have to restart the bot every time I use a command

### Actual Results

All my bot's commands disappear after I run one of them.

### Intents

N/A

### System Information

```
- Python v3.10.6-final
- py-cord v2.1.3-final
- aiohttp v3.8.3
- system info: Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by waliens** [comment]
This might also be caused by two concurrent instances of your bot running at the same time.
