### ISSUE TITLE
Slash Command Shows Interaction Failed Message Even After Responding

### ISSUE THREAD

**Issue by wa1ker38552** [Pycord-Development/pycord#1651]
### Summary

The application shows a 'did not respond' message even after it has already responded.

### Reproduction Steps

Create and send a command

### Minimal Reproducible Code

```python
import discord

# functions
def create_embed(em):
  embed = discord.Embed()
  embed.title = em['title']
  embed.color = em['color']
  embed.description = em['description']

  return embed


client = discord.Bot()

@client.event
async def on_ready():
  print(client.user)

@client.command(description='Show debug information')
async def debug(ctx):
  embed = create_embed({
    'title': 'Debug',
    'color': 0x338CFF,
    'description': f'**Latency: **`{round(client.latency, 3)}` ms'
  })
  await ctx.send(embed=embed)


client.run('TOKEN')
```

### Expected Results

The application returns a response

### Actual Results

The application returned a response but also showed an error message.
As you can see, the application responded twice.
![image](https://user-images.githubusercontent.com/100868154/192184796-b3509441-5f05-4652-a79c-51a28bc6d208.png)

### Intents

discord.Intents.default()

### System Information

- Python v3.10.6-final
- py-cord v2.1.3-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22000

I don't know why it says 10, i'm using 11. Running on pycharm.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JustaSqu1d** [comment]
To respond to an interaction, you should use `ctx.respond`.
