### ISSUE TITLE
Using Python V3.10 breaks the arguments in Group slash commands

### ISSUE THREAD

**Issue by ShahrukhAbrar** [Pycord-Development/pycord#1679]
### Summary

Using python V3.10 breaks the argument input in Group slash commands. Using V3.8 fixes this

### Reproduction Steps

1: Make a Group Slash Command with arguments
2: Run the Bot
3: Try using slash command 

### Minimal Reproducible Code

```python
wiki= bot.create_group(name="wikipedia", description="Your Personal Wikipedia")
@wiki.command(name="summary", description="Provides Short summary from Wikipedia")
async def summary(ctx, *, word :str, line=4):
  try:
    wikiResult=wikipedia.summary(word, sentences=line)
    picURL=picwiki.get_wiki_image(word)
    embed=discord.Embed(title=word, description=wikiResult)
    embed.set_image(url=picURL)
    await ctx.response.defer()#This line defers the function
     #Do your process here
    await ctx.followup(embed=embed, delete_after=120)

  except Exception as e:
    await ctx.respond("Not Found", delete_after=10)
```

### Expected Results

I should be able to add a word to find the summary from wikipedia.

### Actual Results

It would show no option to add a argument.

### Intents

intents = discord.Intents().all()

### System Information

- Python v3.10.0-final
- py-cord v2.2.2-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Using Python Version 3.8.0 fixes this issue.

**Comment by NeloBlivion** [comment]
Can't replicate on 3.10.0 and v2.2.2
> Using python V3.10 breaks the argument input in Group slash commands. Using V3.8 fixes this

This sounds like you have different versions of pycord installed on 3.8 and 3.10, can you double check this?
