### ISSUE TITLE
When fetching VoiceChannel from guild, members are empty

### ISSUE THREAD

**Issue by dankmolot** [Pycord-Development/pycord#1692]
### Summary

When fetching channel using `bot.fetch_channel`, members list aren't empty. But `Guild.fetch_channel` returns VoiceChannel with empty members 

### Reproduction Steps

Using `Guild.fetch_channel` fetch a voice channel with member. `VoiceChannel.members` must return valid list of members, but instead returns empty list.

### Minimal Reproducible Code

```python
This code runs in `on_ready` event

guild_id = 945000000000000000
channel_id = 945000000000000001

guild = await bot.fetch_guild( guild_id )
channel_from_bot = await bot.fetch_channel( channel_id  )
channel_from_guild = await guild.fetch_channel( channel_id  )

print("Are channels equal", channel_from_bot.id == channel_from_guild.id)
print("Are channel members equal", len(channel_from_bot.members) == len(channel_from_guild.members))
```

### Expected Results

Channel members must be equal.

### Actual Results

When fetching channel from guild, channel members are empty.

Code output:
```
Are channels equal True
Are channel members equal False
```

### Intents

default + members

### System Information

- Python v3.10.4-final
- py-cord v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
`fetch_guild` does not come with cached members, so using `fetch_channel` and trying to access `members` from a fetched `Guild` object will yield no results as there are no members in the guild's cache
