### ISSUE TITLE
Accessing Command Context From discord.ui

### ISSUE THREAD

**Issue by wa1ker38552** [Pycord-Development/pycord#1700]
### Summary

Is there a way to access ctx from discord.ui

### What is the feature request for?

The documentation

### The Problem

I can't seem to be able to access ctx from a discord.ui.view class. Is there a way to do this?

### The Ideal Solution

```py
class Select(discord.ui.View):
    @discord.ui.select(
        placeholder = "Select a role",
        min_values = 1,
        max_values = 1,
        options = [discord.SelectOption(label=i.name) for i in ctx.guild.roles] # doesn't work since ctx can't be accessed
    )
    async def select_callback(self, select, interaction):
        await interaction.response.send_message(f"Awesome! I like {select.values[0]} too!")
```

**Comment by plun1331** [comment]
Just use attributes from `Interaction`
If you mean the original command's context, just modify the view class yourself to pass it in

**Comment by Pixel2075** [comment]
Use this, does the thing you need :)
```
async def test(self,ctx):
        select = Select(
            placeholder='Select a role',
            max_values=1,
            min_values=1,
            options=[discord.SelectOption(label=i.name) for i in ctx.guild.roles]
        )
        async def select_callback(interaction):
            await interaction.response.send_message(f"Awesome! I like {select.values[0]} too!")
        select.callback = select_callback
        await ctx.respond(view=View(select))
```

**Comment by plun1331** [comment]
> Use this, does the thing you need :)
> ```
> async def test(self,ctx):
>         select = Select(
>             placeholder='Select a role',
>             max_values=1,
>             min_values=1,
>             options=[discord.SelectOption(label=i.name) for i in ctx.guild.roles]
>         )
>         async def select_callback(interaction):
>             await interaction.response.send_message(f"Awesome! I like {select.values[0]} too!")
>         select.callback = select_callback
>         await ctx.respond(view=View(select))
> ```

Please don't spoonfeed.
