### ISSUE TITLE
PEP 604 used while minimum Python version is 3.8

### ISSUE THREAD

**Issue by davidhozic** [Pycord-Development/pycord#1704]
### Summary

The library has used ``|`` to write Union types, even though this is only supported from Python 3.10

### Reproduction Steps

Open http.py, look thru annotations, for example line 188

### Expected Results

Union types should not be written with ``|`` since it is supported only from 3.10 forward.

### Actual Results

Union types should are written with ``|``

### Intents

Unrevelant

### System Information

- Python v3.10.8-final
- py-cord v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NeloBlivion** [comment]
This is a non-issue due to using __future__ annotations, the library functions fine on 3.8.
