### ISSUE TITLE
Bridge Command Cooldown bug.

### ISSUE THREAD

**Issue by GidorStudios** [Pycord-Development/pycord#1721]
### Summary

Bridge Commands gets different cooldown with text command and slash command

### Reproduction Steps

1. Use the code snippet linked.
2. Type in p.hello
3. Type in /hello
4. It should give a cooldown with wrong seconds.
![image](https://user-images.githubusercontent.com/60816479/197353834-fb3496b0-a786-4954-8447-cd68fa479896.png)

### Minimal Reproducible Code

```python
@bridge.bridge_command()
@commands.cooldown(1, 7, commands.BucketType.user)
async def hello(self, ctx):
```

### Expected Results

The command would give a 7 second cooldown.

### Actual Results

The commands gives a bigger cooldown than 7 seconds. Usually 50 seconds.

### Intents

Guild, Members, Message content

### System Information

- Python v3.10.7-final
- py-cord v2.2.0-final (also tested with v2.2.2)
- aiohttp v3.8.3
- system info: Windows 11 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Cannot reproduce. Maybe something's wrong with your application command error handler? You can always visit the help channel in our Discord server too.

**Comment by Revnoplex** [comment]
I'm having the same bug occur except its 80 seconds
