### ISSUE TITLE
Cogs don't raise an exception.

### ISSUE THREAD

**Issue by pernydev** [Pycord-Development/pycord#1728]
### Summary

If you have any error inside a cog, no exception is raised.

### Reproduction Steps

You can just follow the [official guide](https://guide.pycord.dev/popular-topics/cogs) on setting up cogs. Then do something like import a module that doesn't exist and the commands inside the cog won't work but no error traceback will be shown to the developer.

### Minimal Reproducible Code

```python
cogs/test.py:
this obviously should raise an error.

----------------------------------------------------

bot.py:
import discord

bot = discord.Bot()

bot.load_extension(f"cogs.test")

bot.run(TOKEN)
```

### Expected Results

The program would raise an exception like:
```
  File "C:\Users\Admin\Documents\Pycord\cogerror\cogs\test.py", line 1
    this obviously should raise an error.
         ^^^^^^^^
```

### Actual Results

The bot runs as normal.

### Intents

None

### System Information

```
- Python v3.10.5-final
- py-cord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.22621
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NeloBlivion** [comment]
Upgrade to 2.2.2

**Comment by pernydev** [comment]
I am aware that ////
