### ISSUE TITLE
Add Support for Student Hubs 

### ISSUE THREAD

**Issue by Grace-codes** [Pycord-Development/pycord#174]
### Summary

Support Student Hub Channels

### What is the feature request for?

The core library

### The Problem

Bot's can't join Student Hubs (for now) but they can fetch the invites which throw errors, see https://github.com/discord/discord-api-docs/pull/3757

### The Ideal Solution

Add an implementation for this

**Comment by Lulalaby** [comment]
Closing as bots can't use it.
Channel type is added. Should not throw any problems.
