### ISSUE TITLE
Adding "applications.commands.update" Support

### ISSUE THREAD

**Issue by Waffleer** [Pycord-Development/pycord#1762]
### Summary

Adding "applications.commands.update" Support to allow bot to edit server integrations, allowing for roles to have access to certain /commands and not see other /commands

### What is the feature request for?

The core library

### The Problem

I want to edit the discord integrations for my bot with my bot so that I can change what roles have access to what commands when my bot first joins the server. If everyone can uses the commands then shit will go down.

I was informed by JustaSqu1d that 
" The only way to edit application command permissions is with the scope: applications.commands.update. "

Adding this functionality would allow the bots commands to only be visible to certain roles and make the overall professionalism of the bot a lot better.

I'd rather not have someone have to go into the discord settings and manually add the channels that can run commands. 
Its wrong to assume that the end user will do thing correctly.
I would also prefer not to add a check to every single one of my functions to see if it is run in the right channel in the right category.

### The Ideal Solution

Adding "applications.commands.update" Support would make the overall experience a lot cleaner for both the end user and the developer

**Comment by Lulalaby** [comment]
You would need to implement a whole web frontend for that because that scope required oauth and a users oauth token. 
It's nothing which can be simply done. 

It's not really worth implementing it. 
It might be easier to code a website apart from the bot which goes through the whole oauth flow and handles the permission update itself.
