### ISSUE TITLE
Add more parameters in ctx.respond

### ISSUE THREAD

**Issue by Cheeseboy8020** [Pycord-Development/pycord#177]
### Summary

I want the parameters in `ctx.respond()` for slash commands to be the same as `ctx.send()` in the regular commands.

### What is the feature request for?

The core library

### The Problem

I want more parameters in `ctx.respond()` in slash commands like delete_after. I'm trying to change from discord.py's command framework to slash commands.

For example,

```python
@bot.slash_command()
async def test(ctx):
    await ctx.respond('whatever', delete_after=60.0)
 ```   
that would not work.

### The Ideal Solution

Make the same parameters as the `ctx.respond` in commands.

**Comment by Grace-codes** [comment]
`ctx.send` was an alias for `ctx.respond` in the alpha, however this has been changed. So I request you to change the title to `ctx.respond` as that is what should be used.
