### ISSUE TITLE
Bot not able to run when import discord.ext.commands

### ISSUE THREAD

**Issue by CobaltGames** [Pycord-Development/pycord#1771]
### Summary

importing discord.ext.commands breaks script

### Reproduction Steps

1: make a new script
2: add 'import discord.ext.commands'
3: run.

### Minimal Reproducible Code

```python
import discord.ext.commands
```

### Expected Results

Runs fine.

### Actual Results

Script Crashes.

### Intents

None (in code), Presence, Server Members, Message Content (in developer application)

### System Information

- Python v3.11.0-final
- py-cord v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22622

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by frosetrain** [comment]
What do you mean by "script crashes"? Does it cause an exception?

**Comment by plun1331** [comment]
Please install from the latest GitHub commit, the version on PyPi does not support 3.11
