### ISSUE TITLE
Role.id (and guild.id) is returning different values

### ISSUE THREAD

**Issue by DWAA1660** [Pycord-Development/pycord#1774]
### Summary

In some scenerios it returns different ids than other scenerios

### Reproduction Steps

when i input role id to database from command argument `async def setup_ticket(self, ctx: discord.ApplicationContext, channel: discord.TextChannel, view_ticket_role: discord.Role)` it inserts view_ticket_role.id to database so in db it stores 1033221340523679700 but when i copy it in app or when i loop through roles its a different id 1033221340523679805 same with guild id when i store ctx.guild.id it puts 1024102454943559700 but actual id is 1024102454943559730

### Minimal Reproducible Code

```python
async def setup_ticket(self, ctx: discord.ApplicationContext, view_ticket_role: discord.Role)
    self.db.moderators.insert_one({'mod_role': view_ticket_role.id, 'guild': ctx.guild.id})
    for role in ctx.guild.roles:  
                res2 = await self.db.moderators.find_one({'guild': ctx.guild.id, 'role': role.id})
                if role.name =="Moderator":
                    print(role.id, res2)#this prints actual role id None
```

### Expected Results

It should be the same in all instances

### Actual Results

its different in arguments than actual id

### Intents

All

### System Information

Command didnt work on my machine i am on python 3.11 but my production machine is on 3.9 and its same result

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DWAA1660** [comment]
here is full code is theres somthing else im messing up
`import discord
from discord import option
from discord.ext import tasks, commands
import motor.motor_asyncio
from discord.utils import get


class TicketView(discord.ui.View):
    def __init__(self, moderators, db):
        super().__init__(timeout=None)
        self.modertators = db.moderators
        self.db = db
        # self.title = title
        # self.description = description
        # self.color = color


    @discord.ui.button(
    label="Open a ticket",
    style=discord.ButtonStyle.green,
    custom_id="persistent_view:green",
    )
    async def open(self, button: discord.ui.Button, interaction: discord.Interaction):
        res = get(interaction.guild.channels, name=f"ticket-{interaction.user.id}")
        await interaction.response.defer()
        if res is None:
            await interaction.followup.send("Creating ticket (this may take a minute)", ephemeral=True)
            ticketcata = get(interaction.guild.categories, name="Tickets")
            ticket = await ticketcata.create_text_channel(f"ticket-{interaction.user.id}")
            await ticket.send(f"Here is your ticket {interaction.user.mention}")
            for role in interaction.guild.roles:  
                res2 = await self.db.moderators.find_one({'guild': interaction.guild.id, 'role': role.id})
                if role.name =="Moderator":
                    print(role.id, res2)
                if res2 is not None:
                    perms = ticket.overwrites_for(role)
                    perms.view_channel = True
                    perms.send_messages = True
                    perms.read_message_history = True
                    perms.read_messages = True
                    await ticket.set_permissions(role, overwrite=perms)
                    print("mod finished")
                    return
                perms = ticket.overwrites_for(role)
                perms.view_channel = False
                await ticket.set_permissions(role, overwrite=perms)
            user_perms = ticket.overwrites_for(interaction.user)
            user_perms.view_channel = True
            user_perms.send_messages = True
            user_perms.read_message_history = True
            user_perms.read_messages = True
            await ticket.set_permissions(interaction.user, overwrite=user_perms)
            print("finished")
            return
        await interaction.followup.send(f"You already have a ticket <#{res.id}>", ephemeral=True)

class Tickets(commands.Cog):
    def __init__(self, bot, db) -> None:
        self.bot = bot
        self.db: motor.motor_asyncio.AsyncIOMotorDatabase = db
        self.moderators: motor.motor_asyncio = db.moderators
        
        
    @commands.Cog.listener()
    async def on_ready(self):
        self.bot.add_view(TicketView(self.moderators, db=self.db))
        
    @commands.slash_command(description="Sets up tockets channel")
    @discord.default_permissions(
        administrator=True,
    )
    async def setup_ticket(self, ctx: discord.ApplicationContext, channel: discord.TextChannel, view_ticket_role: discord.Role, embed_title: str, embed_description: str, embed_color: str, button_color: discord.ButtonStyle):
        await ctx.respond("Setting up!")
        res = await self.db.moderators.find_one({'guild': ctx.guild.id})
        if res is None:
            await self.db.moderators.insert_one({'mod_role': view_ticket_role.id, 'guild': ctx.guild.id})
        else:
            await self.db.moderators.replace_one({'guild': ctx.guild.id},{'mod_role': view_ticket_role.id, 'guild': ctx.guild.id})
        await ctx.guild.create_category(name="Tickets")
        embed= discord.Embed(title=embed_title, description=embed_description, color=int(embed_color, 16))
        await channel.send(embed=embed, view=TicketView(self.db.moderators, db=self.db))`

**Comment by Lulalaby** [comment]
https://discord.com/channels/881207955029110855/881224361015672863/1040029158639673484

**Comment by BobDotCom** [comment]
This appears to be a max safe integer limit issue with your database. Given one of the IDs you listed, javascript has the exact same issue when evaluating the integer. This isn't an issue with pycord, but regardless you may want to consider storing IDs as string values
<img width="155" alt="Screen Shot 2022-11-09 at 4 25 20 PM" src="https://user-images.githubusercontent.com/71356958/200955245-41c308ba-bc78-426e-ae95-641df7c17dab.png">
