### ISSUE TITLE
A .md file explaining why pycord exists, including the whole dpy situation

### ISSUE THREAD

**Issue by ImNimboss** [Pycord-Development/pycord#18]
### Summary

A .md file explaining why pycord exists, including the whole dpy situation. This is so that newbies know what happened, just to clear confusion

### What is the feature request for?

The documentation

### The Problem

When newbies find this, they should know about how the lib came into existence, and the whole situation about dpy.

### The Ideal Solution

Add a file called about.md including the info above

**Comment by Mapegz** [comment]
Is this a possible substitute, a maintained branch of discord.py ??

**Comment by oliiiiiiiiiiiii** [comment]
Yes currently it is quite well maintained branch and possibly the best substitute to dpy atm. Also as an additional info buttons and slash commands are gonna be released soon.

**Comment by Mapegz** [comment]
> Yes currently it is quite well maintained branch and possibly the best substitute to dpy atm. Also as an additional info slash commands are gonna be released soon.

as for slash commands, i am currently using [discord-interactions by goverfl0w](https://github.com/goverfl0w/discord-interactions)
But I still need to use discord.py, hope this fork is well maintained.
For some time, i'll stick to discord.py until a library update becomes necessary.

**Comment by Dorukyum** [comment]
Done in #22.
