### ISSUE TITLE
'AutoShardedBot' object has no attribute '_bridge_commands'.

### ISSUE THREAD

**Issue by GidorStudios** [Pycord-Development/pycord#1800]
### Summary

@bot.bridge_group fails to create a bridge command group.

### Reproduction Steps

1. Make a bridge group, not in a cog, but in the main bot file.
2. put in your token
3. start the bot
4. it should fail

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
from discord.ext import bridge

intents = discord.Intents.all()

bot = bridge.AutoShardedBot(command_prefix=commands.when_mentioned_or("!"), intents=intents, auto_sync_commands=True)

@bot.event
async def on_ready():
    print(f"{bot.user} is ready and online!")

@bot.bridge_group(invoke_without_command=True, help="Showing categories for commands.")
@bridge.map_to("help", "Shows the basic help menu.")
async def help(ctx):
    e = discord.Embed(
        description="test",
    )
    await ctx.respond(embed=e)

bot.run("token")
```

### Expected Results

The commands and the bridge group would work like it did in 2.2.2

### Actual Results

It fails with an error., and the bot wont even start.

![image](https://user-images.githubusercontent.com/60816479/204002281-a07438a6-e0ae-4153-baa7-5946141ceec6.png)

### Intents

all

### System Information

- Python v3.11.0-final
- py-cord v2.3.None-final (tried on the release version too)
- aiohttp v3.8.3
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Worked good in pycord 2.2.2 and on py 3.10.7
Updated to 3.11 and 2.3.0 uninstalled the any other python version other than 3.11 and still not works.
I also checked that python is added to the path, and it is.
Honestly i dont know what is happening here.

**Comment by BobDotCom** [comment]
@Middledot mind checking this out and letting me know what you find?
