### ISSUE TITLE
applied_tags returning empty list

### ISSUE THREAD

**Issue by neilstottler** [Pycord-Development/pycord#1807]
### Summary

applied_tags returns an empty list

### Reproduction Steps

try and get any tag from a post within a forum.

### Minimal Reproducible Code

```python
`
    @discord.slash_command(description="text here", guild_ids=[global_config.guild_id])
    async def close(self, ctx):
        message = await ctx.respond(f"reply text")

        #get thread ID
        channel_id = ctx.channel.id
        print(ctx.channel.id)

        #add tag to channel
        thread = await ctx.guild.fetch_channel(channel_id)
        print(thread.applied_tags)
        await thread.edit(
            name=thread,
            archived=True,
            locked=False,
            invitable=True,
            auto_archive_duration=60,
            slowmode_delay=0,
            reason=f"close reason {ctx.author}.",
            pinned=False,
            applied_tags=[thread.parent.get_tag(tag id here),]
            )
`
```

### Expected Results

console would print tags on post

### Actual Results

empty list

### Intents

intents = discord.Intents.default() intents.members = True intents.guilds = True

### System Information

- Python v3.8.10-final
- py-cord v2.3.1-final
- aiohttp v3.8.1
- system info: Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

posted in the discord and was told to make an issue

**Comment by Dorukyum** [comment]
Can't reproduce, reopen if persists.
