### ISSUE TITLE
Slash commands not showing up on Discord

### ISSUE THREAD

**Issue by kryllyxofficial01** [Pycord-Development/pycord#1813]
### Summary

I have my code written out just like in the docs. However, the slash command I created isn't showing up, even though I used the parameter "guild_ids".

### Reproduction Steps

The bot itself:
```python
intents = discord.Intents.all()
client = discord.Bot(command_prefix="//", intents=intents, help_command=None)
```
#

The slash command:
```python
@client.slash_command(name="ping", description="Gets the bot's current message latency.", guild_ids=[976256461887897650])
async def ping(ctx: ApplicationContext):
	await ctx.respond(f"Current Ping: {round(client.latency)} ms")
```

### Expected Results

The slash command to show up in Discord.

### Actual Results

Nothing is happening. I run the command, but I get no output.

### Intents

All

### System Information

/home/vscode/.local/lib/python3.10/site-packages/discord/__main__.py:47: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
/home/vscode/.local/lib/python3.10/site-packages/discord/__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.10.8-final
- py-cord v2.3.1-final
- aiohttp v3.8.3
- system info: Linux 5.4.0-1094-azure #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by penut85420** [comment]
Have the same issue, i have two application, one is verified bot. Only the verified one will output these errors, both of them can't sync slash command.

```
Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\penut\.virtualenvs\DiscordFries-mz6g3d4C\lib\site-packages\discord\client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\penut\.virtualenvs\DiscordFries-mz6g3d4C\lib\site-packages\discord\bot.py", line 1041, in on_connect
    await self.sync_commands()
  File "C:\Users\penut\.virtualenvs\DiscordFries-mz6g3d4C\lib\site-packages\discord\bot.py", line 643, in sync_commands
    registered_guild_commands[guild_id] = await self.register_commands(
  File "C:\Users\penut\.virtualenvs\DiscordFries-mz6g3d4C\lib\site-packages\discord\bot.py", line 472, in register_commands
    prefetched_commands = await self.http.get_guild_commands(self.user.id, guild_id)
  File "C:\Users\penut\.virtualenvs\DiscordFries-mz6g3d4C\lib\site-packages\discord\http.py", line 354, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by kryllyxofficial01** [comment]
@penut85420 When creating your bot, did you give it the `application.commands` permission?

**Comment by Lulalaby** [comment]
> @penut85420 When creating your bot, did you give it the `application.commands` permission?

This doesn't apply anymore.
The scope is included in bot.

Only exception would be if it was added ages ago.
Another reason I can think of would be if they have too many commands on the server, but that would give  another error

**Comment by kryllyxofficial01** [comment]
@Lulalaby what about my issue? any solutions?

**Comment by Lulalaby** [comment]
I believe we don't use `guild_ids` but `debug_guilds`

**Comment by Lulalaby** [comment]
nvm that

**Comment by Lulalaby** [comment]
I don't have a clue tbh

@plun1331 care to look into it?

**Comment by penut85420** [comment]
@kryllyxofficial01 Yes, the bot has been functioning well for a couple of months on many servers. I was working on some new features yesterday, and everything seemed to be working fine on my development bot. But when I tried to use the verified bot, all of the application commands were missing. I switched back to the development bot to see if the issue was there as well, and to my surprise, the application commands on that bot were also missing. I'm not sure what's happening at this point and I'm feeling quite confused :(

**Comment by JustaSqu1d** [comment]
@kryllyxofficial01 Is this still an issue? If so, please check if

• Does your bot have the `application.commands` scope in your guild?
• Are you loading cogs before `on_ready` and `on_connect`?
• Is `on_connect` not overridden?
• Did you update to the newest version of `pycord`?
• Is "User Settings" > "Accessibility" > "Chat Input" > "Use legacy chat input" turned off?

If these issues still persist, please use the [help channel](https://canary.discord.com/channels/881207955029110855/969574202413838426) in the [support server](https://discord.gg/pycord), not as an issue.
