### ISSUE TITLE
Attribute error for `class.BridgeCommandGroup` in `HelpComand()`

### ISSUE THREAD

**Issue by DevInfinix** [Pycord-Development/pycord#1816]
### Summary

Error raised while using `help` command:  'BridgeCommandGroup' object has no attribute 'parent' 

### Reproduction Steps

Was using a custom `discord.ext.commands.HelpCommand` earlier, however the error is raised even while using `discord.ext.commands.DefaultHelpCommand`

### Minimal Reproducible Code

```python
class AbletonBot(bridge.Bot):
    def __init__(self):
        intents = discord.Intents.all()
        intents.presences = False
        prefixlist = ["o!","O!"]
        super().__init__(
            intents=intents,
            command_prefix=commands.when_mentioned_or(*prefixlist),
            case_insensitive=True,
            enable_debug_events=True,
            strip_after_prefix=True,
            description="something...",
            help_command=commands.DefaultHelpCommand()
        )
```

### Expected Results

The bot to return the help menu. It was working fine before the bridge commands were added.

### Actual Results

![image](https://user-images.githubusercontent.com/72700816/205429989-07bcd67c-b9ee-462a-af25-529e956d8aef.png)

Error:
```py
  File "G:/Development/infinix/ableton/env/lib/python3.9/site-packages/discord/ext/commands/cog.py", line 84, in get_commands
    return [c for c in self.__cog_commands__ if c.parent is None]
  File "G:/Development/infinix/ableton/env/lib/python3.9/site-packages/discord/ext/commands/cog.py", line 84, in <listcomp>
    return [c for c in self.__cog_commands__ if c.parent is None]
AttributeError: 'BridgeCommandGroup' object has no attribute 'parent'
```

### Intents

all (except `intents.presences`)

### System Information

DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.11.0-final
- py-cord v2.3.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JustaSqu1d** [comment]
[Further context](https://canary.discord.com/channels/881207955029110855/1048166266453639288)

**Comment by DevInfinix** [comment]
**Update:** Rolling back to `v2.3.0` fixes the error.

**Comment by lol219** [comment]
Prob a bug
