### ISSUE TITLE
Custom Emoji Rate Limit Handling

### ISSUE THREAD

**Issue by RedVersaMC** [Pycord-Development/pycord#1832]
### Summary

Code stops without throwing an error

### Reproduction Steps

I have a back up bot that backs up all the data from one guild, and restores it to another guild. This includes channels, categories, roles, emojis, pinned messages, and member data.

However, when trying to import emojis, I had the bot use `ctx.guild.create_custom_emoji` to make the emojis. It started making the emojis just fine for the first 50 emojis. However, every emoji after that stops the code from working, without throwing an error. I am aware that there should be at max 50 emojis, but in my situation, there were 37 regular emojis, and 13 animated emojis, both did not reach the limit, and can make more manually

### Minimal Reproducible Code

```python
for i in range(100):
  r = requests.get("imgur.com") #This can be a regular picture (png/jpg) or a animated picture (gif)
  await ctx.guild.create_custom_emoji(
    name = f"emoji-{i}",
    image = r.content)
```

### Expected Results

Create 100 emojis, 50 regular and 50 animated (Depending on the image from URL)

### Actual Results

Code just stops after 50 emojis have been created. Did not throw an error, and won't execute the code after.

### Intents

discord.Intents.all()

### System Information

py-cord == 2.2.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Om1609** [comment]
The bot should be ratelimited. The library will wait and retry automatically. [Turn on logging](https://docs.pycord.dev/en/stable/logging.html) to get more data about this.
