### ISSUE TITLE
Can't run examples/audio_recoding.py

### ISSUE THREAD

**Issue by twmht** [Pycord-Development/pycord#1837]
### Summary

Can't run examples/audio_recoding.py

### Reproduction Steps

install latest version and run examples/audio_recoding.py

it threw the exception,

![image](https://user-images.githubusercontent.com/1567200/208913844-50d9252d-c133-4055-9818-320c08e7233c.png)

### Expected Results

run successfuly.

### Actual Results

exceptions

### Intents

default

### System Information

![image](https://user-images.githubusercontent.com/1567200/208914046-39779840-9e9b-4072-99ed-a9381f2e2bb2.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Add your code

**Comment by twmht** [comment]
it's my fault. it works well after updating https://github.com/Pycord-Development/pycord/blob/master/examples/audio_recording.py#L5.

but how can i invoke the command? I have tried `start mp3` but nothing happen.

**Comment by Lulalaby** [comment]
Please join https://discord.gg/pycord and use our help channel
