### ISSUE TITLE
Code does not run when there is a __pycache__ folder

### ISSUE THREAD

**Issue by pratheek78** [Pycord-Development/pycord#186]
### Summary

The code wont run when the pycache folder is in the cogs folder. 

### Reproduction Steps

Run the existing code with pycord 2.0.0. The code wont run unless the pycache folder is deleted. This needs to be done everytime the code is run.

### Minimal Reproducible Code

```python
for cog in listdir(path.join(path.dirname(path.abspath(__file__)), "cogs")):
    if cog.endswith(".py"):
        client.load_extension(f"cogs.{cog[:-3]}")

    else:
        print(f'unable to load {cog[:-3]}') #loads in all the cogs in the specified folder
```

### Expected Results

The expected result is for it to load in all the cogs, and display the message "unable to load __pycach"(last 3 characters cut off because of the code).

### Actual Results

The actual result is this error message:
Traceback (most recent call last):
  File "c:\Users\prath\Desktop\Python\Projects\discord bot\DiscordBot.py", line 32, in <module>
    client.load_extension(f"cogs.{cog[:-3]}")
  File "C:\Python Installation\Python39\lib\site-packages\discord\ext\commands\bot.py", line 732, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Python Installation\Python39\lib\site-packages\discord\ext\commands\bot.py", line 663, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
AttributeError: module 'discord.ext.commands.errors' has no attribute 'ExtensionFailed'

### Intents

intents = discord.Intents.all()

### System Information

- Python v3.9.6-final
- pycord v2.0.0-alpha
    - pycord pkg_resources: v0.0.1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Not a bug, there is something wrong with your code logic.

**Comment by pratheek78** [comment]
it works sometimes, sometimes it doesnt. i'll check my code once

**Comment by Grace-codes** [comment]
> Not a bug, there is something wrong with your code logic.

It is a bug. Someone removed ExtensionFailed from commands.errors.

**Comment by pratheek78** [comment]
Oh ok

**Comment by pratheek78** [comment]
But still though, why does it work sometimes, and doesnt work at others?

**Comment by Dorukyum** [comment]
> > Not a bug, there is something wrong with your code logic.
> 
> It is a bug. Someone removed ExtensionFailed from commands.errors. And didn't fix it with commands.Bot.

_That_ is a known bug. I was talking about the ExtensionFailed error, not the AttributeError.

**Comment by nerdguyahmad** [comment]
#109 pull request fixes it.
