### ISSUE TITLE
ContextMenuCommand sync error

### ISSUE THREAD

**Issue by pvyParts** [Pycord-Development/pycord#1865]
### Summary

ContextMenuCommand to_dict output is not passing discord sanity checks during sync

### Reproduction Steps

https://github.com/Pycord-Development/pycord/blob/master/examples/modal_dialogs.py

using this eample and using the context menu callbacks

### Minimal Reproducible Code

```python
https://github.com/Pycord-Development/pycord/blob/master/examples/modal_dialogs.py

this example shows the errors
```

### Expected Results

Commands synced to server

### Actual Results

```
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/.../discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/.../discord/bot.py", line 1164, in on_connect
    await self.sync_commands()
  File "/.../discord/bot.py", line 738, in sync_commands
    app_cmds = await self.register_commands(
  File "/.../discord/bot.py", line 599, in register_commands
    registered = await register("bulk", data, _log=False)
  File "/.../discord/http.py", line 366, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 1.description: Must be between 1 and 100 in length.
In 2.description: Must be between 1 and 100 in length.
```

### Intents

messages

### System Information

- Python v3.8.10-final
- py-cord v2.3.2-final

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

i think it is related to this
https://github.com/Pycord-Development/pycord/blob/master/discord/commands/core.py#L1436

and this
https://github.com/Pycord-Development/pycord/blob/master/discord/commands/core.py#L1492

i believe the `description` filed should be added to the output dict for commands that require it only.

[line 1436](https://github.com/Pycord-Development/pycord/blob/master/discord/commands/core.py#L1436)
remove entirely

```python
        # Discord API doesn't support setting descriptions for context menu commands, so it must be empty
        # self.description = None
```

[line 1489](https://github.com/Pycord-Development/pycord/blob/master/discord/commands/core.py#L1489)
remove description

```python
    def to_dict(self) -> dict[str, str | int]:
        as_dict = {
            "name": self.name,
            "type": self.type,
        }
```

could be related to this discord update as that's roughly when it started for myself.
https://discord.com/channels/613425648685547541/697138785317814292/1062203446087921774

**Comment by EmreTech** [comment]
This looks to be a bug with the Discord API: https://github.com/discord/discord-api-docs/issues/5836

**Comment by pvyParts** [comment]
Ah slick. I didn't find that one while I was searching

**Comment by pvyParts** [comment]
This is fixed

**Comment by Lulalaby** [comment]
Oh neat
