### ISSUE TITLE
Make Slash Command Support

### ISSUE THREAD

**Issue by ProtechGG** [Pycord-Development/pycord#187]
### Summary

Make slash command support so that i can use slash commands in my bot.

### What is the feature request for?

discord.ext.commands

### The Problem

Now discord is making every bot (except verified bot) to use slash commands and i want to implement it in my bot, so that i have no problems later. So please add slash commands support.

### The Ideal Solution

The only ideal solution is that you add slash commands using python.

### Additional Context

:)

**Comment by easonuwu** [comment]
Slash commands is already supported in the Beta branch, if you wanna try out slash commands you can use the slash branch ig

**Comment by CodeWithSwastik** [comment]
Slash commands are already supported in the alpha [master branch]
