### ISSUE TITLE
applied_tags does not update when tags are changed on forum posts

### ISSUE THREAD

**Issue by JonSatriani** [Pycord-Development/pycord#1870]
### Summary

applied_tags does not update when tags are changed on forum posts

### Reproduction Steps

Start bot
fetch before.applied_tags
change tags on forum post
fetch after.applied_tags
before.applied_tags == after.applied_tags

### Minimal Reproducible Code

```python
@Cog.listener()
    async def on_thread_update(self, before, after):
        print(before.applied_tags == after.applied_tags)
```

### Expected Results

applied_tags to return the updated list of tags

### Actual Results

applied_tags returns the initial list of tags (collected at bot first run?)

### Intents

discord.Intents.default(), intents.members = True

### System Information

- Python v3.10.2-final
- py-cord v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Pixel2075** [comment]
**It is a bug probably.** In the meantime you could use the `on_raw_thread_update `event. You can use a database or just a simple json simple to store the initial values of the tags in a list then compare it with the value from the payload.

```
@Cog.listener()
async def on_raw_thread_update(payload):
    print(payload.data['applied_tags'])
```
