### ISSUE TITLE
add selects in modal

### ISSUE THREAD

**Issue by PolyTree18** [Pycord-Development/pycord#1876]
### Summary

add select menus in modal dialogs

### What is the feature request for?

The core library

### The Problem

This is already implemented in discord.net and in js discord-modals, and its still not implemented in pycord

### The Ideal Solution

The ideal solution of this problem is to use the existing discord.ui.select class in modal dialogs as SelectOption class

**Comment by Lulalaby** [comment]
The select menu component was removed from discord and not announced to come back

**Comment by PolyTree18** [comment]
its sad
