### ISSUE TITLE
Paginator View doesn't respond if paginator buttons were added via editing the message

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#1877]
### Summary

This seems to be happening with Paginator.edit() in all cases ive been able to test

### Reproduction Steps

Send a message using e.g. ctx.respond or ctx.send
create a paginator object 
and use await `paginator.edit(message)` to add the paginator view to the message
The buttons appear, but they dont work, this also occurs when using a previous view in the initial message which items from that become unresponsive too.

### Minimal Reproducible Code

```python
async def test_cmd(self, ctx: bridge.BridgeContext):
    embed = utils.minimal_embed("Hello World")
    message = await ctx.respond(embed=embed)
    if isinstance(message, discord.Interaction):
        message = await message.original_response()
    if isinstance(message, (discord.WebhookMessage, discord.PartialMessage)):
        message = self.client.get_message(message.id)
    paginator = pages.Paginator(pages=["message 1", "message 2", "message 3", "message 4"])
    await paginator.edit(message)
```

### Expected Results

The buttons should respond like other views when they are edited, they work fine

### Actual Results

Instead I get a "This Interaction Failed" when clicking any of the buttons

### Intents

all

### System Information

discord/__main__.py:47: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
discord/__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.10.9-final
- py-cord v2.3.2-final
- aiohttp v3.8.3
- system info: Linux 6.1.6-arch1-1 #&#8203;1 SMP PREEMPT_DYNAMIC Sat, 14 Jan 2023 13:09:35 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Om1609** [comment]
This should be fixed by #1997. Can you test if this error persists on the master branch?

**Comment by Revnoplex** [comment]
Nope, still same behaviour with the same code on 2.4.1.dev88+ga09e728f

**Comment by Revnoplex** [comment]
For now the `pages.Paginator(author_check=False)` is a working workaround

**Comment by Om1609** [comment]
> For now the `pages.Paginator(author_check=False)` is a working workaround

How about manually setting `paginator.user` to `ctx.author` after using `paginator.edit`? That might work too
