### ISSUE TITLE
discord.ForumChannel Bug

### ISSUE THREAD

**Issue by Locopengu1337** [Pycord-Development/pycord#1882]
### Summary

discord.ForumChannel not showing Forum Channels

### Reproduction Steps

https://docs.pycord.dev/en/master/api/models.html#discord.ForumChannel

### Minimal Reproducible Code

```python
@slash_command()
    async def forum(self, ctx, forum: discord.Option(discord.ForumChannel, "..")):
        print(forum)
        print(forum.category)
```

### Expected Results

Showing Forum Channels

### Actual Results

Not Showing Forum Channels

### Intents

All

### System Information

- Python v3.11.1-final
- py-cord v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Credits to : zReaxrYT#1799 for finding the Bug.

**Comment by Lulalaby** [comment]
We need more context. What is shown?

A wild guess of me: You want to let users select posts of forum channels?
If so, the correct type is thread. But afaik there is a limitation client side with which threads are shown.

If not, provide more details

**Comment by zReaxrYT** [comment]
![image](https://user-images.githubusercontent.com/94801710/213013238-3609b31c-0fb1-4a96-ad5f-03559fb08cb6.png)
Thank you for the credtis ⭐

**Comment by Lulalaby** [comment]
And I think the code is wrong
@Pycord-Development/contributors?

**Comment by zReaxrYT** [comment]
> And I think the code is wrong @Pycord-Development/contributors?

No i think thats right because when i write in die option a normal channel then he gives me the error ChannelNotFound.
But when i write the name from the forum channel then he gives me the informations to the channel

**Comment by Locopengu1337** [comment]
> And I think the code is wrong @Pycord-Development/contributors?

![image](https://user-images.githubusercontent.com/121500487/213014075-01aa65fb-c5f9-4316-91d7-421e9eebaf96.png)
This is what discord.py is showing when you use discord.ForumChannel. 

It's also not working with `async def forum(self, ctx, forum: discord.Option(discord.ForumChannel)):`
nor `async def forum(self, ctx, forum: discord.ForumChannel)` is working either.

**Comment by Lulalaby** [comment]
Squid, could you look into this


>  I mean, go ahead and test it yourself.

Sorry I don't use python :p

**Comment by NeloBlivion** [comment]
You're meant to use the `channel_types` argument in `discord.Option`. 
```py
    @slash_command()
    async def forum(self, ctx, forum: discord.Option(discord.TextChannel, channel_types=[discord.ChannelType.forum])):
        ...
```
Though I fully understand the confusion:
1. This *still* isn't documented... I'll do it now since I'm free
2. Considering all the other types we have, the code in the OP seem like it should work.
3. To add to the above, the example code I used above isn't exactly ideal since it's two clashing types. If I'm not mistaken, using `channel_types` overrides the option type channel.

**Comment by Lulalaby** [comment]
Oh thanks nelo, so i was right

**Comment by Locopengu1337** [comment]
![image](https://user-images.githubusercontent.com/121500487/213015852-b7d35a7f-b65f-4cdf-9b70-ab689705883e.png)

using
```
    @slash_command()
    async def forum(self, ctx, forum: discord.Option(discord.TextChannel, channel_types=[discord.ChannelType.forum])):
        ...
```
This is still not working. It's just showing TextChannels?

**Comment by Lulalaby** [comment]
try `discord.SlashCommandOptionType.channel, channel_types=[discord.ChannelType.forum]`

**Comment by zReaxrYT** [comment]
> discord.SlashCommandOptionType.channel, channel_types=[discord.ChannelType.forum]

WORKED! Thanks ⭐

**Comment by Locopengu1337** [comment]
Why isn't it like TextChannel and VoiceChannels and CategoryChannels? 

So, your Code is working. But why isn't it just like the others? Why so complicated?

**Comment by Lulalaby** [comment]
Because this is not d.py anymore lmfao

and forum is not a text channel technically

**Comment by NeloBlivion** [comment]
Also bear in mind ForumChannels came way after this was implemented, adding support for it shouldn't be too hard so I'll look into that within the next hour or so.

**Comment by Locopengu1337** [comment]
imo i would just change it to discord.ForumChannel until v3 or sum idk ... It's working fine with the other options.
But we found a solution, Thank you very much @Lulalaby
