### ISSUE TITLE
message.add_reaction fails in subsequent calls to the same command

### ISSUE THREAD

**Issue by thomasnappi** [Pycord-Development/pycord#1893]
### Summary

When attempting to add a reaction within a command, it only works on the first run of the command; subsequently, it fails, without errors or blocking execution.

### Reproduction Steps

I was attempting to port over some bot code from discord.py; the minimum reproducible code has been tested to demonstrate the issue. It works fine on discord.py, but fails silently on pycord.

### Minimal Reproducible Code

```python
#!/usr/bin/env python
# vim:fileencoding=utf8
import os
import asyncio
import discord
from discord.ext import commands

CLIENT = commands.Bot(command_prefix="!",intents=discord.Intents.all())
TOKEN = os.environ.get("TOKEN", None)
if not TOKEN:
    with open("token.txt", encoding="utf8") as file:
        TOKEN = file.readlines()[0]
else:
    TOKEN = str(TOKEN)

@CLIENT.command()
async def test(ctx):
    print("a")
    await ctx.message.add_reaction("🗿")
    print("b")

if __name__ == "__main__":
    asyncio.run(CLIENT.start(TOKEN))
```

### Expected Results

I expect if I execute the command 3 times, the emoji will be a reaction to the message on all 3.
Console output:
```
a
b
a
b
a
b
```

### Actual Results

If I actually execute the command 3 times, the emoji is only a reaction on the first message.
Console output:
```
a
b
a
a
```

### Intents

discord.Intents.all()

### System Information

/opt/.pyenv/versions/3.10.6/lib/python3.10/site-packages/discord/__main__.py:47: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
/opt/.pyenv/versions/3.10.6/lib/python3.10/site-packages/discord/__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.10.6-final
- py-cord v2.3.2-final
- aiohttp v3.8.3
- system info: Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is run inside a rockylinux8 based docker container, where python is installed with pyenv.
I have checked that the source file is in fact utf-8, as I had a concern putting the emoji directly in the code might be the issue; however, this code executes as expected on discord.py==2.1.0, and it still does work on the first execution of the command.

**Comment by Dorukyum** [comment]
Can't reproduce.

![image](https://github.com/Pycord-Development/pycord/assets/53639936/2411d9a8-fd39-4112-b585-15a38f7b51ea)

There must be something wrong in your own code.
