### ISSUE TITLE
Move ``@Bot.listen``, ``Bot.add_listener`` and ``Bot.remove_listener`` into ``Client`` (multiple event handlers)

### ISSUE THREAD

**Issue by davidhozic** [Pycord-Development/pycord#1906]
### Summary
PR: #1907 
The issue proposes to move multiple event handlers functionality out of the ``discord.Bot`` and put it into ``discord.Client`` in order to allow additional event handlers to be registered in the client itself instead of just the inherited ``discord.Bot``
This would add the mentioned functionality to all classes inherited from ``Client``

### What is the feature request for?

The core library

### The Problem
``discord.Client`` only allows to register a single event handler which can be an obstruction if the developer is creating an application on top of PyCord, that does not utilize the bot framework, but developer still wants to have multiple events handlers (eg. in multiple modules of their application).

### The Ideal Solution
Introduced changes would allow to register additional event handlers through the ``@client.listen()`` decorator and  ``client.add_listener()``, ``client.remove_listener()`` functions. 

The ``@client.event`` decorator would still be used to override the default methods.

```py
import discord
import secret


class MyClient(discord.Client):
    async def on_ready(self):
        print("Default handler")


intents = discord.Intents.default()
intents.message_content = True
client = MyClient(intents=intents)


@client.event # Override the default handler
async def on_ready():
    print(f"Handler 1: {client.user.name} has logged in!")

@client.listen # Additional handler
async def on_ready():
    print(f"Handler 2: {client.user.name} has logged in!")

@client.listen("on_ready") # Additional handler
async def ready_handler():
    print(f"Handler 3: {client.user.name} has logged in!")

@client.listen("on_ready") # Additional handler
async def ready_handler():
    print(f"Handler 4: {client.user.name} has logged in!")

@client.listen()
async def on_message(message: discord.Message):
    print(f"Received message {message.content}")


client.run(secret.TOKEN)
```

### The Current Solution

```py
class MyBotClient(discord.Client):
    async def on_ready(self):
        print(f"{self.user.name} has logged in!")

client = discord.Client()

# Overrides the default handler inside the class definition, no way to add additional handlers
@client.event
async def on_ready(): 
    print(f"{client.user.name} has logged in!")
```

**Comment by Om1609** [comment]
I don't see the point of this. You already have `@bot.listen()` that does exactly this.

**Comment by davidhozic** [comment]
> I don't see the point of this. You already have `@bot.listen()` that does exactly this.

Not available in the client, this can only be used if using the ``discord.Bot`` instead of ``discord.Client``

**Comment by davidhozic** [comment]
Updated the issue to completely move the functionality. This does not affect ``Bot`` since it inherits ``Client``
