### ISSUE TITLE
after=callback in vc.play runs at the beginning of media not end

### ISSUE THREAD

**Issue by ionburger** [Pycord-Development/pycord#1908]
### Summary

after should be called after media source is exhausted or upon error but instead is called immediately. 

### Reproduction Steps

running provided code with a valid test.wav file in the same dir

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

intents = discord.Intents.all()
bot = commands.Bot(intents=intents,command_prefix=".")

def testcallback(error=None):
    if error:
        print("error")
    print("done")

@bot.event
async def on_ready():
    print("ready")

@bot.command()
async def test(ctx):
    channel = ctx.author.voice.channel
    vc = await channel.connect()
    vc.play(discord.FFmpegPCMAudio("test.wav"),after=testcallback())

bot.run("token")
```

### Expected Results

testcallback to be called after the media source is exhausted. 

### Actual Results

testcallback is called immediately. 

### Intents

intents = discord.Intents.all()

### System Information

/home/deez/.local/lib/python3.8/site-packages/discord/__main__.py:47: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
/home/deez/.local/lib/python3.8/site-packages/discord/__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.8.10-final
- py-cord v2.3.2-final
- aiohttp v3.8.3
- system info: Linux 6.0.9-060009-generic #202211161102 SMP PREEMPT_DYNAMIC Wed Nov 16 12:14:18 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Om1609** [comment]
You are yourself calling the function when passing `testcallback()`. 
The after parameter accepts a callable. Eg- `after=testcallback` without the parentheses
