### ISSUE TITLE
cannot import name 'PartialMessageable' from 'discord.channel'

### ISSUE THREAD

**Issue by WhoTheOOF** [Pycord-Development/pycord#191]
### Summary

Basically, in 2.0.0a (not sure if its just me) I am testing, and I came across this issue.

### Reproduction Steps

Whilst installing all my other packages, I installed pycord 2.0.0a from the github link in the discord, and then 
`ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (C:\Users\jadg5\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\channel.py)` pops out of nowhere.

### Minimal Reproducible Code

```python
There is no code, this is just whilst installing things.
```

### Expected Results

To start my bot.

### Actual Results

An error with PartialMessagable occured.

### Intents

Members.

### System Information

Pycord 2,0.0a
Python 3.9.5

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BruceCodesGithub** [comment]
Try to uninstall discord.py and re install py-cord

**Comment by WhoTheOOF** [comment]
I’ll try that when I get home. Going to close this and if another issue occurs I’ll reopen it.
