### ISSUE TITLE
Files and Attachment are not working, "giving attribute errors"

### ISSUE THREAD

**Issue by BOTDEV123** [Pycord-Development/pycord#193]
### Summary

discord.Files and discord.Attachment are giving attribute error when awaited or saved

### Reproduction Steps

`	bytesio = io.BytesIO()
	background.save(bytesio, "PNG")
	bytesio.seek(0)
	file = Attachment(bytesio, filename="yourfile.png")
	await ctx.send(file=file)`

### Expected Results

	bytesio = io.BytesIO()
	background.save(bytesio, "PNG")
	bytesio.seek(0)
	file = Attachment(bytesio, filename="yourfile.png")
	await ctx.send(file=file)
	
tthought this will send me the image (file)

### Actual Results

gave me an attribute error 
![image](https://user-images.githubusercontent.com/82380093/133275303-c7fa02c4-d8e1-4424-a650-1d2c7a94760c.png)

### Intents

default

### System Information

![image](https://user-images.githubusercontent.com/82380093/133275372-387642d6-66d6-4e96-b116-6031c246d178.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
The error clearly states that the `background` variable which is an `Editor` object doesnt have a "save" attribute. Are you sure this problem is related to this library?

**Comment by BOTDEV123** [comment]
> The error clearly states that the `background` variable which is an `Editor` object doesnt have a "save" attribute. Are you sure this problem is related to this library?

yes because i even tried without saving

**Comment by OEUG99** [comment]
The following example seemed to work for me in my testing with discord.File, I used a random image for reference
`
        # Reading bytes from a random image into a bystream.
        with open("random_image.png", "rb") as image:
            f = image.read()
            b = bytearray(f)

        # Creating BytesIO object from bytestream
        myio = io.BytesIO(b)

        # Sending file named "random_image_2.png" composed from the bytestream
        file = discord.File(myio, filename="random_image_2.png")
        await ctx.send(file=file)
`

**Comment by BOTDEV123** [comment]
I'm using easy_pil

**Comment by CodeWithSwastik** [comment]
This is not a bug with this library, your `background` doesn't have a save method.
