### ISSUE TITLE
Support for stage channel chat

### ISSUE THREAD

**Issue by honzajavorek** [Pycord-Development/pycord#1934]
### Summary

The stage channels now have a chat. I'd like to be able to read it or send messages to it the same way I can do it with the voice channel chat.

### What is the feature request for?

The core library

### The Problem

Currently it seems there is no way to send messages to a stage channel's chat.

### The Ideal Solution

Analogous to voice channel's chat.

### Additional Context

[Introducing Video, Screen Share, and Text Chat Support for Stage Channels](https://discord.com/blog/introducing-video-screen-share-text-chat-support-for-stage-channels)

**Comment by NeloBlivion** [comment]
Will be implemented in 2.5. I noticed in your original repo that you've commented out your send code, but you can get around this issue by using `bot.get_partial_messageable(id).send) to send to any channel.

**Comment by honzajavorek** [comment]
@NeloBlivion Wow, that's interesting, I didn't know about this option. I see that `PartialMessageable` also has a `history`, so that allows me to check what's already in there to prevent double posting. That's exactly what I need, nice!

**Comment by honzajavorek** [comment]
> Generally if you only need to send to a channel, using get_partial_messageable would be better than fetching every time.
That is also a nice tip, I suppose now I can rewrite half of my code and make it more efficient 😂
