### ISSUE TITLE
Unintuituve behaviour of ctx.send in slash commands causes interactions to show as failed

### ISSUE THREAD

**Issue by laundmo** [Pycord-Development/pycord#194]
### Summary

I was mistaken with the below statement, the actual issue is that ctx.send sends a message normally instead of replying to the slash command.

~~Currently the `on_application_command_completion` event is not implemented, causing user-facing "This interaction failed" errors.~~

### Reproduction Steps

Run the example code for slash commands found here: https://github.com/Pycord-Development/pycord#quick-example

Run the /hello command

observe it return "This interaction failed"

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot()

@bot.slash_command()
async def hello(ctx, name: str = None):
    name = name or ctx.author.name
    await ctx.send(f"Hello {name}!")

bot.run("token")
```

### Expected Results

![](https://img.laundmo.com/u/RzkR6q.png)

### Actual Results

![](https://img.laundmo.com/u/xn43Oz.png)

### Intents

None, literally just using the example

### System Information

- Python v3.9.0-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

Using Poetry + local venv

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by laundmo** [comment]
Offtopic: For issues like this, which are basically just showing a TODO, having to go through that issue form thing is really annyoing. I recommend a much shorter form or just a blank issue template for anything that does not fit in either a feature request or a bug report.

**Comment by BobDotCom** [comment]
A couple questions
1. Which branch are you on? 
2. I'm a bit confused as to what this report actually is. `send()` sends to the channel, so it doesn't respond to the slash command in the example, and that's expected. Are you saying that there's a way to cancel the response to the slash command and just send a message to the channel?

**Comment by laundmo** [comment]
1. im on the feature/slash branch

2. looking at the code again, i think i have misunderstood `on_application_command_completion` I thought it was a part of finishing the interaction when its only something internal to the framework.

I think what happened is that i assumed the example here: https://github.com/Pycord-Development/pycord#quick-example should work as is, when it doesn't, since it never responds to the interaction. I think ctx.send should, in the context of a slash command, respond to the slash command directly instead of sending a normal message. Alternatively, a error or warning should be raised when a slash command finishes without a reply, so that this does not cause further confusion.

**Comment by laundmo** [comment]
After some more research: it appears that the ctx.send works just fine on master, it seems thats something that changed in feature/slash

**Comment by krittick** [comment]
> After some more research: it appears that the ctx.send works just fine on master, it seems thats something that changed in feature/slash

Have you tried using ctx.respond()? The examples in `feature/slash` were updated to use this in #182

**Comment by laundmo** [comment]
Yep, ive used that now, though its odd since i managed to somehow, through reinstalling, make ctx.send work again. Honestly, you can probably close this issue as i cant reproduce the issue any more.

**Comment by CodeWithSwastik** [comment]
`ctx.send` was an alias to `ctx.respond` in the alpha, however this was changed in the slash branch and will remain like this. `ctx.send` now just sends a message to the channel, you need to respond at least once to not get the `This interaction failed!`

**Comment by laundmo** [comment]
in that case would it be possible to raise a warning if someone never responds or defers?

**Comment by Lulalaby** [comment]
> in that case would it be possible to raise a warning if someone never responds or defers?

@laundmo please write a feature request for this
