### ISSUE TITLE
Can't create Forum threads with a file

### ISSUE THREAD

**Issue by NeloBlivion** [Pycord-Development/pycord#1949]
### Summary

Trying to pass `file` or `files` into `ForumChannel.create_thread` raises a `HTTPException` due to using the wrong method.

### Reproduction Steps

1) Attempt to create a forum thread with either the `file` or `files` parameter

### Minimal Reproducible Code

```python
forum_channel_id = ...  # Whatever your ID is
path = "..."  # some image path
forum_channel = bot.get_channel(forum_channel_id)
await forum_channel.create_thread(name="A Thread", file=discord.File(path))
```

### Expected Results

The thread is created with the file included.

### Actual Results

```py
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/channel.py", line 1278, in create_thread
    data = await state.http.send_files(
  File "/home/container/.local/lib/python3.10/site-packages/discord/http.py", line 366, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50008): Cannot send messages in a non-text channel
```

### Intents

all

### System Information

- Python v3.10.0-final
- py-cord v2.4.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This happens because when `file` or `files` is passed in, [we use the separate `http.send_files` method](https://github.com/Pycord-Development/pycord/blob/master/discord/channel.py#L1277) which directs *to the forum channel ID*, not the thread ID.
```py
        if file is not None:
            ...
            try:
                data = await state.http.send_files(self.id, files=[file], ... )  # ForumChannel ID
            finally:
                file.close()

        elif files is not None:
            ...
            try:
                data = await state.http.send_files(self.id,  files=files, ... )  # ForumChannel ID
            finally:
                for f in files:
                    f.close()
        else:
            data = await state.http.start_forum_thread(...)  # No files arg
```
This method is only used in the default `Messageable.send` and isn't really made for this purpose as it's a `send` method, not for creating threads. [The thread creation endpoint supports files directly](https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel) as part of its message payload, so if I had to guess this was just an oversight that hadn't been considered. I've created this issue for posterity and may look into fixing it myself, but if anyone else wants to go for it then be my guest.

**Comment by stickfab** [comment]
May I add, same thing happens when a webhook tries creating a forum thread with files attached. It seems that the `thread_name` entry tries to get included in the `payload` dict, but when this happens, `payload` equals to None and throws this error.
```
File "C:\Users\Stickfab\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook\async_.py", line 1745, in send
    data = await adapter.execute_webhook(
  File "C:\Users\Stickfab\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\webhook\async_.py", line 344, in execute_webhook
    payload["thread_name"] = thread_name
TypeError: 'NoneType' object does not support item assignment
```

Upon further investigation, it seems that the code turns `payload` to None when files are included in the message, which contradicts the fact that it needs a payload to create a thread.
```py
# /discord/webhook/async_.py ; lines 610-631
def handle_message_parameters(...) -> ExecuteWebhookParameters:
    ...
    payload = {}
```
```py
# /discord/webhook/async_.py ; lines 668-670
if files:
        multipart.append({"name": "payload_json", "value": utils._to_json(payload)})
        payload = None
```
```py
# /discord/webhook/async_.py ; lines 1726-1757
params = handle_message_parameters(...)     # in this case, since it has files, params.payload is None
...
data = await adapter.execute_webhook(
            ...
            payload=params.payload,
            ...
        )
```

```py
# /discord/webhook/async_.py ; lines 324-344
def execute_webhook(...) -> Response[MessagePayload | None]:
        params = {"wait": int(wait)}
        if thread_id:
            params["thread_id"] = thread_id

        if thread_name:
            payload["thread_name"] = thread_name     # payload is still None, and throws the "TypeError: 'NoneType' object does not support item assignment" exception
```

**Comment by elliotcubit** [comment]
Mirroring @honzajavorek's  workaround from their previous [discussion](https://github.com/Pycord-Development/pycord/discussions/1948) post here for convenience:

Editing forum threads to add a file upload, like so, is working as expected

```python
thread = await channel.create_thread(...)
message = await thread.fetch_message(thread.id)
await message.edit(file=File(path))
```
