### ISSUE TITLE
Support files for interaction.send_message

### ISSUE THREAD

**Issue by BobDotCom** [Pycord-Development/pycord#196]
### Summary

Title explains it all

### What is the feature request for?

The core library

### The Problem

files cannot currently be sent in send_message

### The Ideal Solution

add a files and file kwarg to interaction.send_message

**Comment by Grace-codes** [comment]
I think this might be a discord limitation, though I might be wrong.

**Comment by MhmCats** [comment]
The [discord API docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-data-structure) don't list this as a field that they support, also it says that "Not all message fields are currently supported.".

**Comment by BOTDEV123** [comment]
yes this is feature that needs to be added not discord limitation...
i have the same problem

**Comment by BobDotCom** [comment]
> I think this might be a discord limitation, though I might be wrong. 

I asked in the discord API server and was told that they can be sent

**Comment by Grace-codes** [comment]
That's great then, someone can remove the `discord limitation` label I guess.

**Comment by Grace-codes** [comment]
> I think this might be a discord limitation, though I might be wrong.

Seems like I was wrong, it is possible. Refer: https://github.com/discord/discord-api-docs/discussions/3799
