### ISSUE TITLE
on_auto_moderation_rule_X events TypeError

### ISSUE THREAD

**Issue by Quintenvw** [Pycord-Development/pycord#1976]
### Summary

on_auto_moderation_rule_X events throw TypeErrors

### Reproduction Steps

Try to use the events.

### Minimal Reproducible Code

```python
@commands.Cog.listener()
async def on_auto_moderation_rule_create(self, rule):
    print(rule.guild.id)
```

### Expected Results

A usable guild object.

### Actual Results

TypeError: No '__dict__' attribute on 'AutoModRule' instance to cache 'guild' property

### Intents

auto_moderation_configuration, guilds, etc.

### System Information

Python v3.10.6-final
py-cord v2.4.None-final
aiohttp v3.8.3
Linux 5.15.0-67-generic #74-Ubuntu

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Quintenvw** [comment]
![image](https://user-images.githubusercontent.com/12460903/225941643-e3bd2100-3620-45b5-90ef-87dfc129008d.png)

**Comment by UP929312** [comment]
This may be of help?
https://github.com/Pycord-Development/pycord/blob/f8b4294ff06e0f700bcfe8c0ec13d0ec0085c7dd/discord/automod.py#L402
