### ISSUE TITLE
Inform user of voice support status

### ISSUE THREAD

**Issue by srwhaley** [Pycord-Development/pycord#1991]
### Summary

Would like to let the user know that voice commands cannot be used if voice library is not installed.

### What is the feature request for?

The core library

### The Problem

I upgraded my installation of py-cord recently, and had a long bout of trying to figure out why my bots suddenly could not connect to voice. Would just hang on the voice_channel.connect() calls. 

### The Ideal Solution

Would be nice to not hang and spit out an error informing the user that voice library is not installed.

**Comment by plun1331** [comment]
This is already output as a logging message when the client is created: 
https://github.com/Pycord-Development/pycord/blob/2e9ab6177c5a464dedcd76cf6a17596607587e86/discord/client.py#L252-L254

And is in fact output as a traceback when `connect()` is called:
```py
Traceback (most recent call last):
  [eval internals omitted]
  File "<repl>", line 1, in _repl_coroutine
    await _bot.get_channel(999348484857675826).connect()
  File "/usr/local/lib/python3.11/site-packages/discord/abc.py", line 1937, in connect
    voice = cls(client, self)
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/discord/voice_client.py", line 233, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
```
https://github.com/Pycord-Development/pycord/blob/2e9ab6177c5a464dedcd76cf6a17596607587e86/discord/voice_client.py#L231-L233

**Comment by srwhaley** [comment]
Odd, I guess since I had PyNaCl installed from an older version of py-cord it didn't output those messages.
