### ISSUE TITLE
Send files in slash commands

### ISSUE THREAD

**Issue by Munzu** [Pycord-Development/pycord#200]
### Summary

`file=discord.File(<path>)` in `ctx.send()` with slash commands

### What is the feature request for?

discord.ext.commands

### The Problem

With a prefix command, I can send both a text message, as well as a file, e.g. an image, in the same message like this:

```python
@bot.command(name='test', guild_ids=[<guild_id>])
async def test(ctx):
    await ctx.send("Test text", file=discord.File(<filepath>))
```

Unfortunately, I can't do the same with a slash command:

```python
@bot.slash_command(name='test', guild_ids=[<guild_id>])
async def test(ctx):
    await ctx.send("Test text", file=discord.File(<filepath>))
```

I get the following error:
```
TypeError: send_message() got an unexpected keyword argument 'file'
```

### The Ideal Solution

I'd like for slash commands to be able to send files as well so the usage of `ctx.send()` is consistent with prefix commands.

### The Current Solution

I'd like to use slash commands exclusively so I don't want to use a prefix command for this. 

My current solution is to just post a link to the image but it's not visually appealing since the link is visible in the message.

**Comment by Dorukyum** [comment]
Duplicate of #196.

**Comment by Munzu** [comment]
Oh my bad, should I close this issue then?
