### ISSUE TITLE
AttributeError module 'discord' has no attribute named 'Bot'

### ISSUE THREAD

**Issue by ytorian** [Pycord-Development/pycord#2021]
### Summary

Even though i installed both discord.py and pycord even with the pip install i still get the error

### Reproduction Steps

dk tbf. was trying to host the bot and then got the error. on home pc works fine

### Expected Results

not crash

### Actual Results

Requirement already satisfied: discord.py in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pycord in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.1.1)
Requirement already satisfied: py-cord in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.4.1)
Requirement already satisfied: aiohttp<4,>=3.7.4 in ./.local/lib/python3.10/site-packages (from discord.py->-r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: ffmpeg-python>=0.2.0 in ./.local/lib/python3.10/site-packages (from pycord->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: imageio-ffmpeg>=0.4.2 in ./.local/lib/python3.10/site-packages (from pycord->-r requirements.txt (line 2)) (0.4.8)
Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from pycord->-r requirements.txt (line 2)) (1.24.2)
Requirement already satisfied: typing-extensions<5,>=4 in ./.local/lib/python3.10/site-packages (from py-cord->-r requirements.txt (line 3)) (4.5.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in ./.local/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: future in ./.local/lib/python3.10/site-packages (from ffmpeg-python>=0.2.0->pycord->-r requirements.txt (line 2)) (0.18.3)
Requirement already satisfied: idna>=2.0 in ./.local/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (3.4)
[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/container/main.py", line 6, in <module>
    bot = discord.Bot(intents=discord.Intents.all())
AttributeError: module 'discord' has no attribute 'Bot'

### Intents

discord.Intents.all

### System Information

..

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ytorian** [comment]
i know that this has been issued before but i have already done the pip install of pycord yet it still doesn't work. also did a reinstall

**Comment by Lulalaby** [comment]
Learn to read guides/docs

https://guide.pycord.dev/installation#migrating-from-other-libraries
