### ISSUE TITLE
on_raw_reaction_remove missing data

### ISSUE THREAD

**Issue by Quintenvw** [Pycord-Development/pycord#2045]
### Summary

message_author_id and emoji.animated missing from on_raw_reaction_remove

### Reproduction Steps

Listen for an animated reaction removal with on_raw_reaction_remove.

### Minimal Reproducible Code

```python
@commands.Cog.listener()
async def on_raw_reaction_remove(self, payload: discord.RawReactionActionEvent):
    print(payload)
```

### Expected Results

Reaction removed (animated): {
  "user_id": "856780995629154305",
  "type": 0,
  "message_id": "1103740517881217084",
  "message_author_id": "123468845749895170",
  "emoji": {
    "name": "AnimatedEmoji",
    "id": "1035832566625873920",
    "animated": true
  },
  "channel_id": "395998061639368726",
  "burst": false,
  "guild_id": "394854570926407682"
}

### Actual Results

Reaction removed (animated): {
  "user_id": "856780995629154305",
  "type": 0,
  "message_id": "1103740517881217084",
  "emoji": {
    "name": "AnimatedEmoji",
    "id": "1035832566625873920"
  },
  "channel_id": "395998061639368726",
  "burst": false,
  "guild_id": "394854570926407682"
}

### Intents

guild_messages, guild_reactions, etc.

### System Information

- Python v3.10.6-final
- py-cord v2.4.None-final
- aiohttp v3.8.3
- system info: any

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Upstream bug by discord

**Comment by Lulalaby** [comment]
Discord fixed the missing `emoji.animated` for the gateway event(s).
This might need a code check @Pycord-Development/contributors.

`message_author_id` is p new, they didn't communicate whether or not it'll be added

**Comment by Dorukyum** [comment]
The data received seems to be complete at the moment.
