### ISSUE TITLE
channel.edit(name=?) only works 2 times, after that = not working

### ISSUE THREAD

**Issue by Nykoos** [Pycord-Development/pycord#2050]
### Summary

When you edit a Channel Name with `await ctx.channel.edit(name=?)` you can do this 2 times in the same channel but when you do it a third time you dont get an error and the channel name is not changing

### Reproduction Steps

Make a command which changes the name e.g. to "test". When you use the command and the channel name has changed rename the channel name manually to something else. The first two times the Bot will change the Channel Name but when you do it a third time nothing happens, you wont get an error and the code stops. After the 3 time I waited 2min but nothing happened.

### Minimal Reproducible Code

```python
# My test cog (I only had this cog while testing and my main file nothing else):

from discord.commands import slash_command
from discord.ext import commands


class test(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command(description="test")
    @commands.guild_only()
    async def test(self, ctx):
        await ctx.channel.edit(name="test")
        await ctx.respond("Channel editiert!")


def setup(bot):
    bot.add_cog(test(bot))
```

### Expected Results

I expect that the bot can change the name of the same channel 3 times in a row or give an error.

### Actual Results

Nothing ¯\_(.-.)_/¯

### Intents

discord.Intents.all()

### System Information

- Python v3.10.7-final
- py-cord v2.4.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
You are being rate limited by Discord, the rate limit for channel name/topic changes is 2 per 10 minutes.

**Comment by Revnoplex** [comment]
Isn't it suppose to return a 429 instead of the request hanging?

**Comment by plun1331** [comment]
> Isn't it suppose to return a 429 instead of the request hanging?

Builtin ratelimit handling waits for the ratelimit to expire before retrying

**Comment by Revnoplex** [comment]
should't there be some sort better Indication for use cases where channel edits might get queued up and the latest version needs to be prioritised first?

**Comment by plun1331** [comment]
Discord makes the ratelimits, we just handle them.
If you'd like to suggest a new feature, feel free to make an issue
