### ISSUE TITLE
'Embed.author.name' positional argument

### ISSUE THREAD

**Issue by mahtoid** [Pycord-Development/pycord#2052]
### Summary

Trying to retrieve the `embed.author.name` returns missing positional argument.

### Reproduction Steps

1. Create an embed
2. Send and capture the embed
3. Try to access the `embed.author.name`
4. See `Missing 1 required positional argument: 'name'` error

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())


@bot.command()
async def embed(ctx: commands.Context):
    embed = discord.Embed(
        title="Hello",
        description="abc",
    )

    message: discord.Message = await ctx.send(embed=embed)
    print(message.embeds[0].author.name)

@bot.event
async def on_ready():
    print("Alive")


if __name__ == "__main__":
    bot.run("TOKEN")
```

### Expected Results

Return of `Author` or `EmbedEmpty`

### Actual Results

```
File "C:\Users\matth\PycharmProjects\repo\discordChatExporterPy\DiscordChatExporterPy\chat_exporter\construct\assets\embed.py", line 110, in build_author
    author_name = self.embed.author.name
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\embeds.py", line 704, in author
    return EmbedAuthor(**getattr(self, "_author", {}))  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EmbedAuthor.__init__() missing 1 required positional argument: 'name'
```

### Intents

all

### System Information

```
- Python v3.11.1-final
- py-cord v2.4.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.22621
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Well if author isn't defined when you send the embed, it's obvious that it fails.
You need to check if author is missing I guess.
That doesn't seems to be a library bug.

But I might be wrong.

@Om1609 what do you think

**Comment by Om1609** [comment]
> Well if author isn't defined when you send the embed, it's obvious that it fails.
> You need to check if author is missing I guess.
> That doesn't seems to be a library bug.
> 
> But I might be wrong.
> 
> @Om1609 what do you think 

If author was no defined then it should return EmbedEmpty or None, not raise an error.

Shouldn't name be optional here? https://github.com/Pycord-Development/pycord/blob/master/discord/embeds.py#L125

Same for text here https://github.com/Pycord-Development/pycord/blob/master/discord/embeds.py#L154

**Comment by plun1331** [comment]
> > Well if author isn't defined when you send the embed, it's obvious that it fails.
> > You need to check if author is missing I guess.
> > That doesn't seems to be a library bug.
> > But I might be wrong.
> > @Om1609 what do you think
> 
> If author was no defined then it should return EmbedEmpty or None, not raise an error.
> 
> Shouldn't name be optional here? https://github.com/Pycord-Development/pycord/blob/master/discord/embeds.py#L125
> 
> Same for text here https://github.com/Pycord-Development/pycord/blob/master/discord/embeds.py#L154

I don't believe they should be optional, we should figure out why name is missing

**Comment by plun1331** [comment]
What was the behavior previously like?
