### ISSUE TITLE
Possible bug in cooldowns

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#2057]
It might be that cooldowns and before_invoke would never run if you don't have max concurrency set for slash commands

https://github.com/Pycord-Development/pycord/blob/a09e728f7ff2b0911571341cefc5545043d7851a/discord/commands/core.py#L297-L308

Reported by @Om1609

**Comment by NeloBlivion** [comment]
All commands have the `_max_concurrency` attribute
https://github.com/Pycord-Development/pycord/blob/43642603e15b545c9f6d07574db6042dc66825a1/discord/commands/core.py#L198
Odd logic, but not a bug (and in my personal experience, cooldowns work fine without `max_concurrency`).

**Comment by Om1609** [comment]
> All commands have the `_max_concurrency` attribute
> https://github.com/Pycord-Development/pycord/blob/43642603e15b545c9f6d07574db6042dc66825a1/discord/commands/core.py#L198
> Odd logic, but not a bug (and in my personal experience, cooldowns work fine without `max_concurrency`).
> 
> 

No. `SlashCommandGroup` overrides the `__init__` and doesn't call the super method

It doesn't have max_concurrency and cooldown attributes. If we add those to `SlashCommandGroup`s then the logic can be simplified

**Comment by NeloBlivion** [comment]
> No. SlashCommandGroup overrides the __init__ and doesn't call the super method.

This is true, but it's irrelevant: you can't use a group on its own, so it doesn't have the attributes - [neither have you ever been able to add cooldowns to groups in their init](https://docs.pycord.dev/en/master/api/application_commands.html#discord.SlashCommandGroup), and you can't create them with a decorator either. All of its subcommands still have `_max_concurrency`, thus everything works as intended.

**Comment by Om1609** [comment]
> [neither have you ever been able to add cooldowns to groups in their init](https://docs.pycord.dev/en/master/api/application_commands.html#discord.SlashCommandGroup), and you can't create them with a decorator either

Yes I'm aware. But you could accept them through the kwrags for SlashCommandGroup init. 

I added this to the init-
```py
class SlashCommandGroup(ApplicationCommand):

    ...

    def __init__(...):

        ...

        from ..ext.commands.cooldowns import BucketType, CooldownMapping, MaxConcurrency

        cooldown = getattr(self, "__commands_cooldown__", kwargs.get("cooldown"))

        if cooldown is None:
            buckets = CooldownMapping(cooldown, BucketType.default)
        elif isinstance(cooldown, CooldownMapping):
            buckets = cooldown
        else:
            raise TypeError(
                "Cooldown must be a an instance of CooldownMapping or None."
            )

        self._buckets: CooldownMapping = buckets

        max_concurrency = getattr(
            self, "__commands_max_concurrency__", kwargs.get("max_concurrency")
        )

        self._max_concurrency: MaxConcurrency | None = max_concurrency
```

and changed the logic to 
```py
        if self._max_concurrency:
            # For this application, context can be duck-typed as a Message
            await self._max_concurrency.acquire(ctx)  # type: ignore # ctx instead of non-existent message

        try:
            self._prepare_cooldowns(ctx)
            await self.call_before_hooks(ctx)
        except:
            if self._max_concurrency:
                await self._max_concurrency.release(ctx)  # type: ignore # ctx instead of non-existent message
            raise
```
Didn't face issues in my limited scope of testing.

If you want to read those changes in a better way, check out [my commit](https://github.com/Om1609/pycord/commit/e7a98471919d31e1979cf615e883a2a335523289) from when I was trying stuff out. Ignore the untested fix for #2058

**Comment by NeloBlivion** [comment]
That's fair, my point was that this isn't a bug; it's a feature request. Just throw in a `feat` pr and go for it.

**Comment by Om1609** [comment]
Oh lol alright.
