### ISSUE TITLE
Re-calling import in slash commands

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#2058]
The following code runs on every call to this function.
We should move that up to the general imports.

https://github.com/Pycord-Development/pycord/blob/a09e728f7ff2b0911571341cefc5545043d7851a/discord/commands/core.py#L119

**Comment by Lulalaby** [comment]
oh

**Comment by Om1609** [comment]
> Pretty sure it has to be this way to prevent a circular import.

Yes thats right. This should be fixed by #1606 as it cleans up the structure. 

Another way I thought of would be checking `exc.__class__.__name__ == "CommandError"` in the `except Exception as exc:` block. Although I'm not sure if this works

**Comment by Dorukyum** [comment]
I'm closing as this will be fixed with the refactoring of slash commands and probably won't be fixed independently.
