### ISSUE TITLE
Interaction Defered Response not ephemeral

### ISSUE THREAD

**Issue by martinbndr** [Pycord-Development/pycord#2065]
### Summary

Interaction Defered Response not ephemeral

### Reproduction Steps

- Create slash command group command
- send a modal  response
- in the modal callback, defer a response
- send followup response

### Minimal Reproducible Code

```python
# Note!! This is created in a cog, and a little diffrent, this is just an example how it is made by concept

class Modal(discord.ui.Modal):
    def __init__(self):

        betreff = discord.ui.InputText(
            style=discord.InputTextStyle.short,
            label='Betreff',
            placeholder='Worum geht es?',
            min_length=1,
            max_length=30,
            required=True
            )
        nachricht = discord.ui.InputText(
            style=discord.InputTextStyle.long,
            label='Nachricht',
            placeholder='Beschreibe dein Anliegen',
            min_length=1,
            max_length=1900,
            required=True
            )
        super().__init__(
            betreff, 
            nachricht, 
            title='Ticket erstellen'
            )

    async def callback(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)
        betreff = self.children[0].value
        nachricht = self.children[1].value
        embed = discord.Embed(
            title=f'{betreff}',
            description=f'{nachricht}'
        )
        await interaction.followup.send(embed=embed)

ticket = SlashCommandGroup('ticket', 'Ticket System', guild_only=True)
@ticket.command(name='create', description='Erstelle ein Ticket')
async def ticket_create(ctx: discord.ApplicationContext):
    modal = TicketCreateModal()
    await ctx.response.send_modal(modal)
```

### Expected Results

await interaction.response.defer(ephemeral=True) - Should send first followup response to ephemeral

await interaction.followup.send(embed=embed) - as before it should be send ephemeral because it was set in the defer response

### Actual Results

Message is sent without ephemeral

### Intents

all default intents and members, message_content intent enabled

### System Information

- Python v3.10.9-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Om1609** [comment]
I believe you need to pass `ephemeral=True` to the followup too. This is a discord feature, not a bug

**Comment by martinbndr** [comment]
Or do you mean discord changed that without py-cord making any change on that?

**Comment by Lulalaby** [comment]
It was never changed. It never worked that way. Followups where always separate.

And you should edit your response instead of defer + followup.

This is a mistake from your side.

**Comment by martinbndr** [comment]
> It was never changed.
It was, I used this method in older versions and worked fine.

https://github.com/Pycord-Development/pycord/blob/23da5e3da840d9d236ecc34298d7b0cf3b25d7cf/discord/interactions.py#L665
And why should ephemeral or invisible even be passed into the function if its not used in the code?

**Comment by Lulalaby** [comment]
because defer is for response edit later, not followup

**Comment by plun1331** [comment]
Set `invisible` to `False` in `defer`, otherwise it sends a deferred update instead of a deferred message
