### ISSUE TITLE
`add_field_` when used on 1 embed automatically gets added to all other embeds of the bot for all commands even if used for 1 command

### ISSUE THREAD

**Issue by 27Saumya** [Pycord-Development/pycord#2070]
### Summary

Recently i was working on a client's bot using pycord dev version and i noticed the bot added embed fields to all the embeds of the bot to all the commands even though it was just used in one command and as i switched to the stable ver everything worked fine

### Reproduction Steps

used `.add_field` func in the embed

### Minimal Reproducible Code

```python
runs = s[1]
balls = s[2]
runs_conceded = s[3]
balls_bowled = s[4]
wickets = s[5]
matches = s[6]

await ctx.send(embed = discord.Embed(
                title="Player stats for FPL",
                description=user.name,
                colour=user.color
            ).set_thumbnail(url=user.avatar.url).set_footer(text=f"{user.name}'s FPL S4 stats!", icon_url=user.avatar.url).add_field(name="Matches Played", value=matches, inline=True).add_field(name="Runs", value=runs, inline=True).add_field(name="Balls Played", value=balls, inline=True).add_field(name="Wickets",value=wickets, inline=True).add_field(name="Runs Conceded", value=runs_conceded, inline=True).add_field(name="Balls Bowled", value=balls_bowled, inline=True))
```

### Expected Results

expected a normal embed with 6-7 fields

### Actual Results

got an embed with 6-7+ fields on every use, like basically it repeats the fields until it reaches the limit

### Intents

discord.Intents.all()

### System Information

py version 3.10,0
pycord version git+https://github.com/Pycord-Development/pycord (couldn't give the exact details because delated the dev version and installed the stable version to check if the code ran and it did)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
This should be fixed in the latest commit

**Comment by 27Saumya** [comment]
okay great, thanks
