### ISSUE TITLE
No module named 'discord_ui'

### ISSUE THREAD

**Issue by ntosis** [Pycord-Development/pycord#2080]
### Summary

UI Module cannot be inluded

### Reproduction Steps

I try to run a ticket system bot.

### Minimal Reproducible Code

```python
[unix@localhost Python-3.8.16]$ python3.8
Python 3.8.16 (default, May 20 2023, 10:26:32) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord_ui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'discord_ui'
```

### Expected Results

to find the module

### Actual Results

Cannot find the module

### Intents

all

### System Information

[unix@localhost Python-3.8.16]$ python3.8 -m discord -v 
- Python v3.8.16-final
- py-cord v2.4.None-final
- aiohttp v3.8.4
- system info: Linux 4.18.12-200.fc28.x86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Sengolda** [comment]
It is called `discord.ui` not `discord_ui`

**Comment by ntosis** [comment]
thank you
