### ISSUE TITLE
Inconsistent default arguments in bridge commands

### ISSUE THREAD

**Issue by Krutyi-4el** [Pycord-Development/pycord#2089]
### Summary

Bridge commands do not always handle default arguments in the same way

### Reproduction Steps

1. Create a bridge command with non-required argument (via Option kwargs)
2. Try to run it without the argument in question

### Minimal Reproducible Code

```python
import os

import discord
from discord.ext import bridge
# Option MUST be imported after ext.bridge
# otherwise it won't work with bridge commands
from discord import Option


bot = bridge.Bot()


@bot.bridge_command()
async def test_default1(ctx, text: Option(str) = "hello"):
    await ctx.respond(text)


@bot.bridge_command()
async def test_default2(ctx, text: Option(str, default="hello")):
    await ctx.respond(text)


@bot.bridge_command()
async def test_no_default(ctx, text: Option(str, required=False)):
    await ctx.respond(text or "hello")


bot.run(os.getenv("TOKEN"))
```

### Expected Results

I'd expect all three commands from the above code to produce the same output when the argument isn't provided, like it does for slash variants:
![Screenshot_20230528-133333989 (1)](https://github.com/Pycord-Development/pycord/assets/60041069/f6a5901f-0493-49af-a8ef-642a6be0882e)

### Actual Results

However, only the first one works:
![Screenshot_20230528-133607047 (1)](https://github.com/Pycord-Development/pycord/assets/60041069/61027cfa-9b12-476b-af99-28bad240b33f)
Others are throwing an error:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/bridge/bot.py", line 143, in invoke
    await ctx.command.invoke(ctx)
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 942, in invoke
    await self.prepare(ctx)
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 872, in prepare
    await self._parse_arguments(ctx)
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 774, in _parse_arguments
    transformed = await self.transform(ctx, param)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/bridge/core.py", line 105, in transform
    return await super().transform(ctx, param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 601, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: text is a required argument that is missing.
```

### Intents

None

### System Information

- Python v3.11.2-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: `Linux 4.14.232-QuicksilveR™-ReloadedOS-Edition #1 SMP PREEMPT Wed May 26 07:08:17 UTC 2021`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Not related to this particular issue, but I don't quite like how Option works with bridge commands. Relying on the order of imports is something very non-obvious, confusing and, iirc, not documented.

**Comment by Middledot** [comment]
Not sure when but it was fixed, but testing your code seems to work fine on latest (927f8cefb0a5ba8ed5f2c7ccad3f734852bef62e).
![image](https://github.com/Pycord-Development/pycord/assets/78228142/ca835718-7cf4-4b0f-8ad5-62aea3dd1944)

I also think modifying Option on import is a bit hacky, and the solution seems to just force people to use BridgeOption, so that's what I'll do.

**Comment by Krutyi-4el** [comment]
@Middledot your screenshot shows slash invocation, have you tried prefix invocation?

Also, `BridgeOption` is not documented and can only be accessed as `bridge.core.BridgeOption` which suggests that it's part of internal API.

**Comment by Middledot** [comment]
Thank you for pointing that out cuz I did not try that. Text commands don't process Option, so that's what it does now (#2256)

For BridgeOption, I think we should expose it as the option class bridge commands should use instead of Option (#2252) but I want to wait on some internal stuff to sort out before merging
