### ISSUE TITLE
ui button can't add url

### ISSUE THREAD

**Issue by linty1997** [Pycord-Development/pycord#2094]
### Summary

ui button can't add url

### Reproduction Steps

import discord

class InviteView(discord.ui.View):
    @discord.ui.button(label="Add bot to server",
                       url="https://...",
                       style=discord.ButtonStyle.link,
                       emoji="👉")
    async def button_callback(self, button, interaction):
        await interaction.response.send_message("You clicked the button!", ephemeral=True)

### Expected Results

It should be possible to add url normally

### Actual Results

TypeError: button() got an unexpected keyword argument 'url'

### Intents

Do not use

### System Information

- Python v3.11.2-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JustaSqu1d** [comment]
Link buttons cannot have callbacks so they were not implemented into the decorator.
