### ISSUE TITLE
tasks recipes in docs do not work if the user passes their own event loop to bot constructor

### ISSUE THREAD

**Issue by gregdan3** [Pycord-Development/pycord#2097]
### Summary

If bot is constructed with a loop provided, the docs' task recipes do not work

### Reproduction Steps

[I set this up as well](https://github.com/gregdan3/pycord-bug-2023-06-05), which reproduces the issue.

1. Set up a cog with a task [as the documentation specifies](https://docs.pycord.dev/en/stable/ext/tasks/index.html#recipes). Slightly altered example:
```py
from discord.ext import tasks, commands

class BrokenCog(commands.Cog):
    def __init__(self):
        self.index = 0
        self.printer.start()
        print("Broken cog initialized")

    def cog_unload(self):
        self.printer.cancel()

    @tasks.loop(seconds=5.0)
    async def printer(self):
        print("Broken Cog: %s" % self.index)
        self.index += 1
```

2. Construct the bot with your own event loop:

```py
import asyncio
from discord.ext import commands

TOKEN = "YOUR_TOKEN"
LOOP = asyncio.new_event_loop()
BOT = commands.Bot(loop=LOOP)

def main():
    BOT.load_extension(f"example.cogs.working")
    BOT.load_extension(f"example.cogs.broken")
    BOT.run(TOKEN)

if __name__ == "__main__":
    main()
```

3. Run the bot
4. Observe that the cog does not print, or execute beyond its `__init__` method

If you examine the created `asyncio.Task` object, it remains in the `Pending` state indefinitely, and the task never executes.

---

Removing the user-added event loop fixes the issue:
```py
BOT = commands.Bot()
```
But this may not be desirable to some users needing an event loop for other work before they initialize the bot.

---

Another workaround, for those trying to diagnose this issue: You can use `@commands.Cog.listener()` with `on_ready` to accomplish the same, but in an async context so that the task's `start` method works:

```py
from discord.ext import tasks, commands

class WorkingCog(commands.Cog):
    def __init__(self):
        self.index = 0
        print("Working cog initialized")

    def cog_unload(self):
        self.printer.cancel()

    @commands.Cog.listener()
    async def on_ready(self):
        await self.printer.start()

    @tasks.loop(seconds=5.0)
    async def printer(self):
        print("Working Cog: %s" % self.index)
        self.index += 1
```

### Minimal Reproducible Code

```python
# __main__.py
import asyncio
from discord.ext import commands

TOKEN = "YOUR_TOKEN"
LOOP = asyncio.new_event_loop()
BOT = commands.Bot(loop=LOOP)

def main():
    BOT.load_extension(f"example.cogs.working")
    BOT.load_extension(f"example.cogs.broken")
    BOT.run(TOKEN)

if __name__ == "__main__":
    main()



# cogs/broken/cog.py
from discord.ext import tasks, commands
class BrokenCog(commands.Cog):
    def __init__(self):
        self.index = 0
        self.printer.start()
        print("Broken cog initialized")

    def cog_unload(self):
        self.printer.cancel()

    @tasks.loop(seconds=5.0)
    async def printer(self):
        print("Broken Cog: %s" % self.index)
        self.index += 1



# cogs/working/cog.py
from discord.ext import tasks, commands
class WorkingCog(commands.Cog):
    def __init__(self):
        self.index = 0
        print("Working cog initialized")

    def cog_unload(self):
        self.printer.cancel()

    @commands.Cog.listener()
    async def on_ready(self):
        await self.printer.start()

    @tasks.loop(seconds=5.0)
    async def printer(self):
        print("Working Cog: %s" % self.index)
        self.index += 1
```

### Expected Results

Given task recipes should work regardless of user-provided or bot-constructed event loop; the task in the cog should execute.

### Actual Results

Given task recipes did not work so long as the user provided their own event loop; only worked if the bot was not passed a `loop` parameter. The task in the cog never starts.

### Intents

None

### System Information
```
- Python v3.10.11-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Linux 6.3.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Mon, 29 May 2023 13:58:34 +0000
```
(edited into a codeblock bc the `#1` in the response turned into a link to #1)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
This seems to be a problem with the two using different event loops.
Manually adding the bot's event loop before starting the task seems to rectify the issue:
```py
self.printer.loop = bot.loop
```
Since tasks are standalone and are currently not attached to the bot in any way, it would be impractical to do this automatically in the library.

For reference, here's the code I used:

### `main.py`
```py
import asyncio
from discord.ext import commands

LOOP = asyncio.new_event_loop()
BOT = commands.Bot(loop=LOOP)

def main():
    BOT.load_extension(f"cog")
    LOOP.run_forever()

if __name__ == "__main__":
    main()
```

### `cog.py`

```py
from discord.ext import tasks, commands


class BrokenCog(commands.Cog):
    def __init__(self, bot):
        self.index = 0
        self.printer.loop = bot.loop
        self.printer.start()
        print("Broken cog initialized")

    def cog_unload(self):
        self.printer.cancel()

    @tasks.loop(seconds=5.0)
    async def printer(self):
        print("Broken Cog: %s" % self.index)
        self.index += 1


def setup(bot):
    bot.add_cog(BrokenCog(bot))
```

![image](https://github.com/Pycord-Development/pycord/assets/49261529/688446f0-2f65-47ee-89aa-9c34e4310f4f)

**Comment by gregdan3** [comment]
Yep, that would be the issue! This change worked. It occurred to me that I could just use the bot's loop to do what I wanted after I construct the bot anyway, so gonna do that. Thanks!
