### ISSUE TITLE
Add support for `guild events`

### ISSUE THREAD

**Issue by Grace-codes** [Pycord-Development/pycord#210]
### Summary

Add support for `guild events`

### What is the feature request for?

The core library

### The Problem

Add support for `guild events`. Refer https://github.com/discord/discord-api-docs/pull/3586

### The Ideal Solution

Add support for `guild events`.

### Additional Context

https://github.com/discord/discord-api-docs/pull/3586

**Comment by dtrm-thil** [comment]
cover photo will be added.

**Comment by ImNimboss** [comment]
Speaking of which, [this message](https://discord.com/channels/613425648685547541/697138785317814292/911017260406153256) came out in the DDevs server about guild events

**Comment by Lulalaby** [comment]
@ImNimboss We are already aware of this.
I'm in direct contact with hemu and worked with her on this.
