### ISSUE TITLE
New username system not showing correctly

### ISSUE THREAD

**Issue by etienne51** [Pycord-Development/pycord#2115]
### Summary

With the new Discord Unique Username system, member attributes "name" and "display_name" now shows the username and not the actual displayed name in the Discord app.

### Reproduction Steps

With the new Unique Username system now slowly rolling out, the name displayed in Discord for some user is not reported incorrectly by the bots.

For example, someone using the old system (without using a special nickname in the server):
Actual username showing in the Discord app: "\~FancyNickname\~":
```
str(member)          -> ~FancyNickname~#4242
member.name          -> ~FancyNickname~
member.display_name  -> ~FancyNickname~
member.nick          -> None
member.discriminator -> 4242
```
Here it's all good, what is being shown in name & display_name is the actual name seen in the Discord app when interacting with that user.

Now someone who already moved to the new system (still not using a special nickname in the server):
Actual username showing in the Discord app: "\*\*CoolNickname\*\*":
```
str(member)          -> _coolnickname#0
member.name          -> _coolnickname
member.display_name  -> _coolnickname
member.nick          -> None
member.discriminator -> 0
```
Now that's not good! The real name the user has in Discord is not picked up by the bot. I tried different attributes and it all reports the same thing. I need access to the real name of the user shown in Discord.

For members using a special nickname in servers, it bypasses this issue as the attributes "nick" and "display_name" shows the proper displayed name in that particular server. But that's just a special case, and unfortunately is not applicable to every member.
For example with a member who already moved to the new system, with its username showing in DMs as "MyRealUsername", but nicknamed "CustomUsername" in the server:
```
str(member)          -> newdiscordusername#0
member.name          -> newdiscordusername
member.display_name  -> CustomUsername
member.nick          -> CustomUsername
member.discriminator -> 0
```
Here we get "CustomUsername" which is correct in the server. But how can we get the real username of the member which is "MyRealUsername"? It's still the same issue as the previous example.

### Expected Results

The attributes "name" and "display_name" of the member object should show the actual displayed name of a Discord member we can see in the Discord app.

### Actual Results

At the moment, after the rollout of the new Discord naming system that gets rid of the discriminator in favor of Unique Usernames, when using the attributes "name" and "display_name" of the member object, it shows the Unique Username, and there is no way to access the displayed name of the member, as seen in the Discord app.

### Intents

discord.Intents.all()

### System Information

- Python v3.10.6-final
- py-cord v2.4.1-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Om1609** [comment]
The Pomelo updates are on master branch. What is the behaviour when using master branch? (`pip install -U git+https://github.com/Pycord-Development/pycord`)
