### ISSUE TITLE
AttributeError: 'Bot' object has no attribute 'on_message'. Did you mean: 'get_message'?

### ISSUE THREAD

**Issue by Razboinicul** [Pycord-Development/pycord#2147]
### Summary

I try to use @client.on_message but I get this error

### Reproduction Steps

Make a Bot instance
Use @client.on_message

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
import os

TOKEN = os.getenv("DISCORD_TOKEN")
intents = discord.Intents.all()
client = discord.Bot(intents=intents,
                     activity=discord.Game(name='a random game'),
                     command_prefix="m!")


@client.event
async def on_ready():
  print(f'{client.user} Welcome to Discord!')


@client.slash_command(name="ban")
@commands.has_permissions(ban_members=True)
async def ban(ctx, member: discord.Member):
  await member.ban()


@client.on_message()
async def get(ctx, message):
  print(message)


client.run(TOKEN)
```

### Expected Results

No error

### Actual Results

I get "AttributeError: 'Bot' object has no attribute 'on_message'. Did you mean: 'get_message'?"

### Intents

discord.Intents.all()

### System Information

- Python v3.10.8-final
- py-cord v2.4.1-final
- aiohttp v3.8.3
- system info: Linux 5.19.0-1026-gcp #28~22.04.1-Ubuntu SMP Tue Jun 6 07:24:26 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment]
That's not how you set an event for `on_message`. Please read the documentation next time.

**Comment by Razboinicul** [comment]
Welp, my mistake!
