### ISSUE TITLE
await bot.fetch_invite a custom invite with the return discord.NotFound

### ISSUE THREAD

**Issue by ricard0l23** [Pycord-Development/pycord#2155]
### Summary

It cannot show whether the custom invite is valid or not

### Reproduction Steps

I input an invite for it to see whether it is valid, when I try custom invite (like the one that I was trying: https://discord.gg/nurlace-network-862991388966125589 ), it returns discord.NotFound.

### Minimal Reproducible Code

```python
bot = discord.Bot()
try:
    invite = await bot.fetch_invite('https://discord.gg/nurlace-network-862991388966125589')
    print('Invite Valid')
except discord.NotFound:
    print('Invite invalid')
```

### Expected Results

It should print Invite Valid, yet the invite is invalid (The above function is used on an active online bot)

### Actual Results

It printed Invite Invalid

### Intents

discord.Intents.all()

### System Information

- Python v3.11.4-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
`fetch_invite` is meant to be used with an invite code, not the entire link.
