### ISSUE TITLE
Add timeout feature to buttons

### ISSUE THREAD

**Issue by Rxann** [Pycord-Development/pycord#218]
### Summary

Add a timeout kwarg for an amount of time before a button disables itself.

### What is the feature request for?

The core library

### The Problem

I am trying to solve the problem of having to manually disable buttons. It would become a lot easier if there was a kwarg kind of like delete_after but it would disable the button after a certain amount of time.

### The Ideal Solution

The ideal solution is that a kwarg will be added and a button will disable itself after the amount of time (seconds) specified.

### The Current Solution

Manually disable the button

**Comment by MhmCats** [comment]
You can already add a timeout to views [like this](https://gist.github.com/MhmCats/500eafdad0aaf278b94c612764688976#timeouts).

**Comment by Rxann** [comment]
Thank you for this!
