### ISSUE TITLE
Slash Command does not respond if you use on_interaction

### ISSUE THREAD

**Issue by muhy06** [Pycord-Development/pycord#2183]
### Summary

Slash Command does not respond if you use on_interaction (event)

### Reproduction Steps

Slash Command does not respond if you use on_interaction. 

One more problem is when you use interaction defer in callback function for buttons, it does not work.

class ButtonView(discord.ui.View):
    def __init__(self,results,solution):
        super().__init__()

        self.solution = solution
        for res in results:
            self.add_buttons(res) # Remember to add this line to call the add_buttons() function
    
    def add_buttons(self,res):
        mybutton = discord.ui.Button(label=str(res),style=discord.ButtonStyle.green)
        self.add_item(mybutton)

        async def buttoncallback(ctx):
            print(res,self.solution)
            if res != self.solution:
                await ctx.response.send_message(f"Wrong Answer, Try Again!",ephemeral=True,delete_after=4)
                return
            else:
                await ctx.response.defer(ephemeral=True)
                await asyncio.sleep(10)
                await ctx.response.send_message(f"Correct!",ephemeral=True,delete_after=4)

        mybutton.callback = buttoncallback

### Expected Results

run properly

### Actual Results

errors, no response

### Intents

default

### System Information

pycord

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Om1609** [comment]
You are not supposed to override the default working of `on_interaction`. The library uses it for App cmds

**Comment by Om1609** [comment]
And you can either `response.defer` or `response.send_message`. Not both. Use `interaction.followup.send` to send a message if you are deferring.

**Comment by muhy06** [comment]
> You are not supposed to override the default working of `on_interaction`. The library uses it for App cmds

Im not over riding default working of on_interaction. 


`@bot.event
    async def on_interaction(interaction: discord.Interaction):
        
        print(interaction.data)`

**Comment by muhy06** [comment]
> And you can either `response.defer` or `response.send_message`. Not both. Use `interaction.followup.send` to send a message if you are deferring.

also, if we defer on button callback, we dont see any message such as bot thinking. user would not if anything is happening.

**Comment by Om1609** [comment]
> > You are not supposed to override the default working of `on_interaction`. The library uses it for App cmds
> 
> Im not over riding default working of on_interaction.
> 
> ```
> @bot.event
> async def on_interaction(interaction: discord.Interaction):
>         
>       print(interaction.data)
> ```

`@bot.event` overrides the default working. It is equivalent to subclassing the Bot class and overriding the method

**Comment by Om1609** [comment]
> > And you can either `response.defer` or `response.send_message`. Not both. Use `interaction.followup.send` to send a message if you are deferring.
> 
> also, if we defer on button callback, we dont see any message such as bot thinking. user would not if anything is happening.

[RTFM](https://docs.pycord.dev/en/stable/api/models.html#discord.InteractionResponse.defer)

**Comment by muhy06** [comment]
> > > And you can either `response.defer` or `response.send_message`. Not both. Use `interaction.followup.send` to send a message if you are deferring.
> > 
> > 
> > also, if we defer on button callback, we dont see any message such as bot thinking. user would not if anything is happening.
> 
> [RTFM](https://docs.pycord.dev/en/stable/api/models.html#discord.InteractionResponse.defer)

Thank you, appreciated.
