### ISSUE TITLE
`pycord` namespace

### ISSUE THREAD

**Issue by VincentRPS** [Pycord-Development/pycord#2184]
### Summary

As v3 will be permanently cutting out `discord` as an available namespace, it is important to let developers migrate to the new namespace as soon as possible as to infer less breaking changes in the next major version. This would help people prematurely migrate to v3 to avoid more work when v3 does get a full release.

**Comment by Om1609** [comment]
This will lead people into thinking they can get away without rewriting as "V3 might be related to V2". They are not. They are completely different group up. Even if some parts are similar, you should really rewrite

**Comment by Dorukyum** [comment]
I don't think a namespace change should be done in 2.x at any point. The whole point of 3.x is being completely new so we should keep the new namespace there.
