### ISSUE TITLE
Intents wrong value

### ISSUE THREAD

**Issue by davidhozic** [Pycord-Development/pycord#2195]
### Summary

When creating new intents from the old one, it seems their values are different.

### Reproduction Steps

See code below.

### Minimal Reproducible Code

```python
import discord

intents = discord.Intents.default()

flags = {}
for attr in intents.VALID_FLAGS:
    flags[attr] = getattr(intents, attr)

new_intents = discord.Intents(**flags)

print(intents.value)
print(new_intents.value)
```

### Expected Results

The printed values should be the same.

### Actual Results

They are:

4161277
3243773

### Intents

discord.Intents.default() used, no client used

### System Information

- Python v3.8.10-final
- py-cord vNone.1.None-final
- aiohttp v3.8.5
- system info: Windows 10 10.0.19045

(PyCord is on master branch)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context
It's due to a gap between bit masks.
Bit masks without an assigned flag:

- (1 << 17)
- (1 << 18)
- (1 << 19)

Since ``.all`` method just sets all the bits from the highest bit to the lowest, the unused bits also get set.

**Comment by Aityz** [comment]
Can I help fix this in Pycord's code.

**Comment by davidhozic** [comment]
> Can I help fix this in Pycord's code.

1. Fork the PyCord repo
2. Fix the bug in forked repo
3. Update CHANGELOG.MD
4. Open pull request from forked repo to PyCord repo, linking this issue

**Comment by Aityz** [comment]
Thank you. I'm doing that right now.

**Comment by Aityz** [comment]
> ### Additional Context
> It's due to a gap between bit masks. Bit masks without an assigned flag:
> 
> * (1 << 17)
> * (1 << 18)
> * (1 << 19)
> 
> Since `.all` method just sets all the bits from the highest bit to the lowest, the unused bits also get set.


Ahhh, yes I understand what you mean. There is a gap in the intents exponents.

**Comment by Aityz** [comment]
It is not letting me create a new branch and push the commit to the branch. Is there a way that I can create a pull request without a new branch?
