### ISSUE TITLE
Embed class missing property setters

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#2197]
Some setters weren't added but parameters introduced.

- https://github.com/Pycord-Development/pycord/pull/1996
- https://github.com/Pycord-Development/pycord/pull/2063
- https://github.com/Pycord-Development/pycord/pull/2109

From @TheGiga 
![image](https://github.com/Pycord-Development/pycord/assets/14029133/034efa8f-86d7-4440-bf2a-0ac3b5ffdc13)

**Comment by FloncDev** [comment]
Shouldn't you use `Embed.set_thumbnail()` instead of `Embed.thumbnail = ...` to set the thumbnail?

**Comment by Om1609** [comment]
`Embed.thumbnail = ...` will allow you to use an instance of `discord.EmbedMedia`
`Embed.set_thumbnail()` allows you to pass the data as parameters

**Comment by FloncDev** [comment]
To my knowledge, the other 3 parameters of `EmbedMedia` are generated by discord so editing them will have no effect.

**Comment by Om1609** [comment]
Yes but there is also `EmbedAuthor` and `EmbedFooter`. This issue is for all of them
