### ISSUE TITLE
Error discord does not have attribute bot

### ISSUE THREAD

**Issue by knifeworm** [Pycord-Development/pycord#221]
### Summary

Error discord does not have attribute bot

### Reproduction Steps

Attribute Error: module 'discord' has no attribute bot.
Did this on bot startup

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot()
```

### Expected Results

Um the bot start

### Actual Results

Attribute Error: module 'discord' has no attribute bot.

### Intents

Not using any

### System Information

python v3.8.0-final
discord.py v1.7.3-final

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by SshadzZ** [comment]
Try doing 

from discord.ext import commands

bot = commands.Bot(intents = discord.Intents.all())

**Comment by knifeworm** [comment]
Slash commands don't work then

**Comment by MhmCats** [comment]
You probably need to install pycord from master to get slash commands (the release on PyPi does not have this)
```
python3 -m pip install git+https://github.com/pycord-development/pycord.git
# or for the feature/slash branch
python3 -m pip install git+https://github.com/pycord-development/pycord.git@feature/slash
```
if you don't have git installed then do one of the below that applies to you:
- If you are using a linux-based operating system, it is probably already installed but if not find the relevant package on your distro's package manager or check out [this page](https://git-scm.com/download/linux)
- If you are using MacOS then you can install it [with this installer](https://git-scm.com/download/mac).
- If you are using Windows then you can install it [with this installer](https://git-scm.com/download/win)

**Comment by SshadzZ** [comment]
They would work even with commands.Bot, thats how I use it and it works perfectly fine

**Comment by BobDotCom** [comment]
> ### System Information
> 
> python v3.8.0-final
> discord.py v1.7.3-final

Impossible for this to be a valid bug as it appears you aren't even using pycord in the first place.
