### ISSUE TITLE
Failed to build wheels for AIOHTTP 

### ISSUE THREAD

**Issue by anarkitty8** [Pycord-Development/pycord#2210]
### Summary

Does not install as it cannot build wheels

### Reproduction Steps

I just try to install it using the windows command you say to use

### Expected Results

For it to install

### Actual Results

did not install

### Intents

n/a

### System Information

n/a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

this is the error:

 "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tcaiohttp/_websocket.c /Fobuild\temp.win-amd64-cpython-312\Release\aiohttp/_websocket.obj
      _websocket.c
      aiohttp/_websocket.c(1475): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
      aiohttp/_websocket.c(3042): error C2039: 'ob_digit': is not a member of '_longobject'
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
      aiohttp/_websocket.c(3097): error C2039: 'ob_digit': is not a member of '_longobject'
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
      aiohttp/_websocket.c(3238): error C2039: 'ob_digit': is not a member of '_longobject'
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
      aiohttp/_websocket.c(3293): error C2039: 'ob_digit': is not a member of '_longobject'
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
      aiohttp/_websocket.c(3744): error C2039: 'ob_digit': is not a member of '_longobject'
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.193.0_x64__qbz5n2kfra8p0\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2        
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

the same thing happens if i run it with 3.11

**Comment by VincentRPS** [comment]
Since this is an issue with aiohttp, I would recommend making an issue in their repository instead:

https://github.com/aio-libs/aiohttp/issues/new/choose

**Comment by maxgamertyper** [comment]
I have this same issue and would like to know how or if I can fix this

**Comment by Lulalaby** [comment]
@maxgamertyper as vincent said, not our issue

**Comment by VincentRPS** [comment]
> I have this same issue and would like to know how or if I can fix this

While at the moment the newest version of aiohttp does support Python 3.12, Pycord 2.4 and below does not. I'd recommend downgrading to Python 3.11 until Pycord 2.5 releases.
