### ISSUE TITLE
A command.cooldown attribute

### ISSUE THREAD

**Issue by ImNimboss** [Pycord-Development/pycord#223]
### Summary

A command.cooldown attribute that returns a commands.Cooldown object

### What is the feature request for?

discord.ext.commands

### The Problem

A Command object doesn't have a cooldown attribute, which seems strange to me.

### The Ideal Solution

Add a cooldown attribute to Command objects that returns a Cooldown object

### The Current Solution

Currently you can use `command._buckets._cooldown`, which is longer and feels like you're poking through the internals of the library. `._buckets._cooldown` is also undocumented.

### Additional Context

I needed to get a command's cooldown for a more detailed help command so I could show the user how much cooldown a command had, in case you were wondering what the use case for this attribute might be.

**Comment by Dorukyum** [comment]
Done in #225.
