### ISSUE TITLE
Implement App Subscription

### ISSUE THREAD

**Issue by RedVersaMC** [Pycord-Development/pycord#2234]
### Summary

Subscription-only commands, responses, and listeners

### What is the feature request for?

The core library

### The Problem

Discord recently announced that they have released [Application Subscriptions](https://discord.com/developers/docs/monetization/app-subscriptions) to the API, and would be very beneficial to approved apps to have the feature to implement this new feature using this library.

### The Ideal Solution

This feature would enable verified apps to filter between non-subscribed users and subscribed users, making premium subscriptions for bots much easier.

**Comment by Lulalaby** [comment]
_Note that only US based and approved people can even test this_

**Comment by RedVersaMC** [comment]
From the Discord Developer Community Server as of 10/19/2023:

Premium App Subscriptions Launch in the UK and EU.

**Comment by Lulalaby** [comment]
The implementation won't be happening for a while. I suggest going ahead and implementing it on a fork
