### ISSUE TITLE
`edit_original_response` not working if modal was used

### ISSUE THREAD

**Issue by Snawe** [Pycord-Development/pycord#2238]
### Summary

If you send you send a modal, send a message and than try to edit that, it will not work.

### Reproduction Steps

```py
        test_input = discord.ui.InputText(
            label="test",
            placeholder="test",
        )
        modal = discord.ui.Modal(test_input, title="test modal")        
        await ctx.send_modal(modal)
        await modal.wait()
        
        msg = await ctx.respond(content="msg 1", ephemeral=True)
        await ctx.interaction.edit_original_response(content="msg edited") # <= does not work
        # await msg.edit(content="msg edited") # <= does work
```

### Expected Results

I would expect that `edit_original_response` edits the response that was sent before.

### Actual Results

discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

### Intents

default

### System Information

- Python v3.9.4-final
- py-cord-dev v2.5.None-candidate
    - py-cord-dev pkg_resources: v2.5.0rc5
- aiohttp v3.8.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
it is intended.
- send modal
- send followup or respond to modal interaction
