### ISSUE TITLE
Invalid -

### ISSUE THREAD

**Issue by rishicorp1** [Pycord-Development/pycord#2248]
### Summary

prefixed command not worked

### Reproduction Steps

you can use replit , codespace  or you pc install latest python version 
install pycord 
import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix=">", intents=intents)

@bot.command()
async def ping(ctx):
    await ctx.send("pong")

bot.run(token)

 use this it not replies anything

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix=">", intents=intents)

@bot.command()
async def ping(ctx):
    await ctx.send("pong")

bot.run(token)
```

### Expected Results

it not shows any error but also not sends any reply in dc also

### Actual Results

in terminal no error

### Intents

discord>intents.default()

### System Information

I usee mainly replit hacker plan !! my system ihave 24  gb ddr4 ram processor amd ryzen 5500

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment]
Please join the Discord Support Server for help instead of opening an issue on GitHub.
