### ISSUE TITLE
Implement new attachment parameters

### ISSUE THREAD

**Issue by Middledot** [Pycord-Development/pycord#2251]
### Summary

A few parameters were added to attachments urls such as an expiry timestamp and a auth signature for retrieving it.

### What is the feature request for?

The core library

### The Problem

There parameters are not implemented

### The Ideal Solution

These parameters should eventually be implemented

### The Current Solution

There are not implemented, so there is no current solution

### Additional Context

There is currently no set date for when authentication/expiring attachments will be enforced (except for a "later this year")

[DDevs announcement](https://discord.com/channels/613425648685547541/697138785317814292/1157372186160537750)

**Comment by Lulalaby** [comment]
Please not that the end spec isn't out yet.
Some internal info is floating around but nothing notable yet.

So far, only the full url with signature params needs to be called via GET to get the attachment.

**Comment by NeloBlivion** [comment]
Closed in #2342
