### ISSUE TITLE
if a interaction takes too much time to respond, it fails

### ISSUE THREAD

**Issue by nekoraw** [Pycord-Development/pycord#226]
### Summary

if the command takes too much time to respond the user, it automatially fails and raises discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

### Reproduction Steps

adding asyncio.sleep(3) before ctx.respond()

### Minimal Reproducible Code

```python
import discord
import asyncio

token = ""
client = discord.Bot()

@client.slash_command(guild_ids=[...])
async def test(ctx):
    await asyncio.sleep(3) # changing this to 2 works
    await ctx.respond("yeah?")

client.run(token)
```

### Expected Results

to take some time to send the message
![image](https://user-images.githubusercontent.com/50468652/134716358-a4f4889c-fd03-4c6a-9d9c-8d85cbf33a88.png)
![image](https://user-images.githubusercontent.com/50468652/134715292-5899c9d6-4b7e-48b2-a57b-f3bb440bdefb.png)

### Actual Results

![image](https://user-images.githubusercontent.com/50468652/134716374-c2150ac1-5e80-4e56-9ea8-d3df65f1c036.png)
![image](https://user-images.githubusercontent.com/50468652/134715315-109e87ff-5ec3-4ee5-a829-d524e8a6e70d.png)

### Intents

all

### System Information

python 3.9.7
py-cord-2.0.0a3861+g2d747f8f from master branch

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

also tested on slash branch

**Comment by MhmCats** [comment]
This is documented by discord.
![image](https://user-images.githubusercontent.com/71032999/134716757-294330db-69c6-4e0b-8452-7bd52eddbb13.png)

**Comment by CodeWithSwastik** [comment]
You can `await ctx.defer()` and edit it later if you want 🤷
