### ISSUE TITLE
discord.Option autocomplete does not accept string iterable

### ISSUE THREAD

**Issue by Blue-Robin-Taken** [Pycord-Development/pycord#2263]
### Summary

Setting the parameter autocomplete to a string iterable gives an error

### Reproduction Steps

I created a big list of strings with different dog breed types. I then put that in the autocomplete parameter. However, it gave a TypeError

### Minimal Reproducible Code

```python
breed_types = ['affenpinscher', 'african', 'airedale', 'akita', 'appenzeller', 'australian-kelpie',
               'australian-shepherd', 'bakharwal-indian', 'basenji', 'beagle', 'bluetick', 'borzoi', 'bouvier', 'boxer',
               'brabancon', 'briard', 'buhund-norwegian', 'bulldog-boston', 'bulldog-english', 'bulldog-french',
               'bullterrier-staffordshire', 'cattledog-australian', 'cavapoo', 'chihuahua', 'chippiparai-indian',
               'chow', 'clumber', 'cockapoo', 'collie-border', 'coonhound', 'corgi-cardigan', 'cotondetulear',
               'dachshund', 'dalmatian', 'dane-great', 'deerhound-scottish', 'dhole', 'dingo', 'doberman',
               'elkhound-norwegian', 'entlebucher', 'eskimo', 'finnish-lapphund', 'frise-bichon', 'gaddi-indian',
               'germanshepherd', 'greyhound-indian', 'greyhound-italian', 'groenendael', 'havanese', 'hound-afghan',
               'hound-basset', 'hound-blood', 'hound-english', 'hound-ibizan', 'hound-plott', 'hound-walker', 'husky',
               'keeshond', 'kelpie', 'kombai', 'komondor', 'kuvasz', 'labradoodle', 'labrador', 'leonberg', 'lhasa',
               'malamute', 'malinois', 'maltese', 'mastiff-bull', 'mastiff-english', 'mastiff-indian',
               'mastiff-tibetan', 'mexicanhairless', 'mix', 'mountain-bernese', 'mountain-swiss', 'mudhol-indian',
               'newfoundland', 'otterhound', 'ovcharka-caucasian', 'papillon', 'pariah-indian', 'pekinese', 'pembroke',
               'pinscher-miniature', 'pitbull', 'pointer-german', 'pointer-germanlonghair', 'pomeranian',
               'poodle-medium', 'poodle-miniature', 'poodle-standard', 'poodle-toy', 'pug', 'puggle', 'pyrenees',
               'rajapalayam-indian', 'redbone', 'retriever-chesapeake', 'retriever-curly', 'retriever-flatcoated',
               'retriever-golden', 'ridgeback-rhodesian', 'rottweiler', 'saluki', 'samoyed', 'schipperke',
               'schnauzer-giant', 'schnauzer-miniature', 'segugio-italian', 'setter-english', 'setter-gordon',
               'setter-irish', 'sharpei', 'sheepdog-english', 'sheepdog-indian', 'sheepdog-shetland', 'shiba',
               'shihtzu', 'spaniel-blenheim', 'spaniel-brittany', 'spaniel-cocker', 'spaniel-irish', 'spaniel-japanese',
               'spaniel-sussex', 'spaniel-welsh', 'spitz-indian', 'spitz-japanese', 'springer-english', 'stbernard',
               'terrier-american', 'terrier-australian', 'terrier-bedlington', 'terrier-border', 'terrier-cairn',
               'terrier-dandie', 'terrier-fox', 'terrier-irish', 'terrier-kerryblue', 'terrier-lakeland',
               'terrier-norfolk', 'terrier-norwich', 'terrier-patterdale', 'terrier-russell', 'terrier-scottish',
               'terrier-sealyham', 'terrier-silky', 'terrier-tibetan', 'terrier-toy', 'terrier-welsh',
               'terrier-westhighland', 'terrier-wheaten', 'terrier-yorkshire', 'tervuren', 'vizsla', 'waterdog-spanish',
               'weimaraner', 'whippet', 'wolfhound-irish']
breeds = discord.Option(str, autocomplete=breed_types)
```

### Expected Results

I expected it to not give an error and instead work. The docs state:

> The autocomplete handler for the option. Accepts an iterable of [str](https://docs.python.org/3/library/stdtypes.html#str), a callable (sync or async) that takes a single argument of [AutocompleteContext](https://docs.pycord.dev/en/stable/api/application_commands.html#discord.AutocompleteContext), or a coroutine. Must resolve to an iterable of [str](https://docs.python.org/3/library/stdtypes.html#str).

### Actual Results

It gave the error:

> TypeError: ['affenpinscher', 'african', 'airedale', 'akita', 'appenzeller', 'australian-kelpie', 'australian-shepherd', 'bakharwal-indian', 'basenji', 'beagle', 'bluetick', 'borzoi', 'bouvier', 'boxer', 'brabancon', 'briard', 'buhund-norwegian', 'bulldog-boston', 'bulldog-english', 'bulldog-french', 'bullterrier-staffordshire', 'cattledog-australian', 'cavapoo', 'chihuahua', 'chippiparai-indian', 'chow', 'clumber', 'cockapoo', 'collie-border', 'coonhound', 'corgi-cardigan', 'cotondetulear', 'dachshund', 'dalmatian', 'dane-great', 'deerhound-scottish', 'dhole', 'dingo', 'doberman', 'elkhound-norwegian', 'entlebucher', 'eskimo', 'finnish-lapphund', 'frise-bichon', 'gaddi-indian', 'germanshepherd', 'greyhound-indian', 'greyhound-italian', 'groenendael', 'havanese', 'hound-afghan', 'hound-basset', 'hound-blood', 'hound-english', 'hound-ibizan', 'hound-plott', 'hound-walker', 'husky', 'keeshond', 'kelpie', 'kombai', 'komondor', 'kuvasz', 'labradoodle', 'labrador', 'leonberg', 'lhasa', 'malamute', 'malinois', 'maltese', 'mastiff-bull', 'mastiff-english', 'mastiff-indian', 'mastiff-tibetan', 'mexicanhairless', 'mix', 'mountain-bernese', 'mountain-swiss', 'mudhol-indian', 'newfoundland', 'otterhound', 'ovcharka-caucasian', 'papillon', 'pariah-indian', 'pekinese', 'pembroke', 'pinscher-miniature', 'pitbull', 'pointer-german', 'pointer-germanlonghair', 'pomeranian', 'poodle-medium', 'poodle-miniature', 'poodle-standard', 'poodle-toy', 'pug', 'puggle', 'pyrenees', 'rajapalayam-indian', 'redbone', 'retriever-chesapeake', 'retriever-curly', 'retriever-flatcoated', 'retriever-golden', 'ridgeback-rhodesian', 'rottweiler', 'saluki', 'samoyed', 'schipperke', 'schnauzer-giant', 'schnauzer-miniature', 'segugio-italian', 'setter-english', 'setter-gordon', 'setter-irish', 'sharpei', 'sheepdog-english', 'sheepdog-indian', 'sheepdog-shetland', 'shiba', 'shihtzu', 'spaniel-blenheim', 'spaniel-brittany', 'spaniel-cocker', 'spaniel-irish', 'spaniel-japanese', 'spaniel-sussex', 'spaniel-welsh', 'spitz-indian', 'spitz-japanese', 'springer-english', 'stbernard', 'terrier-american', 'terrier-australian', 'terrier-bedlington', 'terrier-border', 'terrier-cairn', 'terrier-dandie', 'terrier-fox', 'terrier-irish', 'terrier-kerryblue', 'terrier-lakeland', 'terrier-norfolk', 'terrier-norwich', 'terrier-patterdale', 'terrier-russell', 'terrier-scottish', 'terrier-sealyham', 'terrier-silky', 'terrier-tibetan', 'terrier-toy', 'terrier-welsh', 'terrier-westhighland', 'terrier-wheaten', 'terrier-yorkshire', 'tervuren', 'vizsla', 'waterdog-spanish', 'weimaraner', 'whippet', 'wolfhound-irish'] is not a callable object

### Intents

all

### System Information

(venv) PS C:\Users\julia\PycharmProjects\AnshBot> python -m discord -v
C:\Users\julia\PycharmProjects\Nestling Bot\venv\lib\site-packages\discord\__main__.py:47: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
C:\Users\julia\PycharmProjects\Nestling Bot\venv\lib\site-packages\discord\__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.9.4-final
- py-cord v2.3.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Blue-Robin-Taken** [comment]
Note: just updated to the latest py-cord version 2.4.1 and it still gives the same error.

**Comment by plun1331** [comment]
Your list should be wrapped in a [`basic_autocomplete`](https://docs.pycord.dev/en/stable/api/utils.html#discord.utils.basic_autocomplete) to be used as an autocomplete function
