### ISSUE TITLE
every command available in bot dms

### ISSUE THREAD

**Issue by zoomingspeed** [Pycord-Development/pycord#2264]
### Summary

All commands (including admin commands) are available through bot direct messages.

### Reproduction Steps

I have been programming my Discord bot using pycord for some time now, and I found this bug out. I reproduced it by just not including `guild_ids=None` or `guild_ids=[]` in my slash command declaration. When I do this, the slash command automatically appears, but the command becomes available in direct messages. Running the command raises an attribute error: `AttributeError: 'User' object has no attribute 'guild_permissions'`

### Minimal Reproducible Code

```python
# a simple kick command
# kick command
@bot.slash_command(name="kick", description="Kick other members from your server!", guild_ids=[])
@default_permissions(kick_members = True)
async def kick(ctx, member : discord.Member, reason=None):
    guild = ctx.guild
    if isinstance(ctx.channel, discord.channel.DMChannel):
        embed=discord.Embed(title="",
                            description="You cannot run this command in direct messages!",
                            color=discord.Color.red())
        await ctx.respond(embed=embed)
    if ctx.author.guild_permissions.kick_members:
        if reason == None:
            guild = ctx.guild
            embed=discord.Embed(title="Kick successful!",
                                color=discord.Color.green())
            embed.add_field(name="", value=f"Successfully kicked {member.mention}, no reason provided.")
            await member.send(f"You have been kicked from {guild}, no reason provided.")
            await ctx.respond(embed=embed)
            await member.kick()
            print(f"{ctx.author} has successfully kicked {member} from {guild}, no reason provided.")
        else:
            embed=discord.Embed(title="Kick successful!",
                                color=discord.Color.green())
            embed.add_field(value=f"Successfully kicked {member.mention}!", inline=False)
            embed.add_field(name="**Reason:**", value=reason, inline=False)
            await ctx.respond(embed=embed)
            await member.send(f"You have been kicked from {guild} due to the following reason: {reason}```")
            await member.kick()
            print(f"{ctx.author} has successfully kicked out {member} from {guild} due to the following reason: {reason}")
    else:
        embed=discord.Embed(title="",
                            description="You do not have permissions to kick other members!",
                            color=discord.Color.red())
        await ctx.respond(embed=embed)
```

### Expected Results

I expected the `isinstance` part of the code block to work

### Actual Results

The bot raises the same attribute error as stated earlier.

### Intents

discord.Intents.all()

### System Information

- Python v3.11.6-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.22621 (I use Windows 11 Pro, I do not know why it says Windows 10)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Here is the trace back:

  Message='User' object has no attribute 'guild_permissions'
  Source=C:\Users\hhous\source\repos\zoomingspeed\discord-bot-learning\Sheikh Bot Folder\sheikh-bot.py
  StackTrace:
  File "C:\Users\hhous\source\repos\zoomingspeed\discord-bot-learning\Sheikh Bot Folder\sheikh-bot.py", line 366, in ban (Current frame)
    if ctx.author.guild_permissions.ban_members:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhous\source\repos\zoomingspeed\discord-bot-learning\Sheikh Bot Folder\sheikh-bot.py", line 483, in <module>
    bot.run("")
AttributeError: 'User' object has no attribute 'guild_permissions'

(This is when the command is ran in direct messages, it works fine in servers.)

**Comment by Lulalaby** [comment]
This is no bug, you have to mark it with an attribute that it's guild_only / restricted for dms.
Search the documentation

**Comment by zoomingspeed** [comment]
@Lulalaby this does not work, it gives me the traceback saying that this command can only be ran in dms but i want my bot to be able to reply

**Comment by Lulalaby** [comment]
that's something u have to implement

**Comment by zoomingspeed** [comment]
anyway i dont want to be able to see the commands in my dms how do i do that
