### ISSUE TITLE
View self.message is None

### ISSUE THREAD

**Issue by denisnumb** [Pycord-Development/pycord#2267]
### Summary

When sending a message with a `View`, the `view` object does not contain a message object

### Reproduction Steps

I create a `View` object, send a message.  However, `view.message` contains `None` instead of a message object.

### Minimal Reproducible Code

```python
@bot.slash_command()
async def test(ctx: discord.ApplicationContext):
    view = View()
    await ctx.respond('test', view=view)
    print(view.message)
```

### Expected Results

```
<InteractionMessage id=1171135113659972648 channel=<discord.channel.PartialMessageable object at 0x0000023DEBE0BC10> type=<MessageType.application_command: 20> author=<User id=773445421175171656 name='name' discriminator='0000' bot=True> flags=<MessageFlags value=0>>
```

### Actual Results

`None`

### Intents

discord.Intents.all()

### System Information

```
- Python v3.10.10-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.19045
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

In the latest version of `py-cord` 2.4.1 everything works correctly, but I'm using the version of the library installed with
```
pip install git+https://github.com/Pycord-Development/pycord
```

I read in `CHANGELOG.md` that a new parameter `view.parent` has been added, but this creates a problem because in my code sometimes `View` can be sent using `ctx.repond()`,  and sometimes with `ctx.send()` and this forces different methods to be used depending on the presence of `view.message` or `view.parent`, whereas before I could just call `view.message`.

**Comment by OmLanke** [comment]
`view.message` will get populated when an interaction from the view is received (when a user uses any of the component).

In order to get the message object before that, use `await ctx.interaction.original_response()`.

Updated code would be-
```py
@bot.slash_command()
async def test(ctx: discord.ApplicationContext):
    view = View()
    await ctx.respond('test', view=view)
    message = await ctx.interaction.original_response()
    print(message)
```
