### ISSUE TITLE
User.display_name is User.name

### ISSUE THREAD

**Issue by Korol-Kotov** [Pycord-Development/pycord#2269]
### Summary

"display_name" shows the same as "name"

### Reproduction Steps

My display name is Korol_Kotov, and name is korolkotov. But "ctx.author.display_name" and "ctx.author.name" show the same thing.

### Expected Results

ctx.author.display_name - Korol_Kotov
ctx.author.name - korolkotov

### Actual Results

ctx.author.display_name - korolkotov
ctx.author.name - korolkotov

### Intents

all

### System Information

- Python v3.8.9-final
- py-cord v2.4.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19041

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JustaSqu1d** [comment]
This is fixed on master branch and [2.5.0rc5](https://pypi.org/project/py-cord-dev/2.5.0rc5/)
