### ISSUE TITLE
ButtonStyle Aliases - AttributeError _LiteralSpecialForm

### ISSUE THREAD

**Issue by lorddusk** [Pycord-Development/pycord#227]
### Summary

Using aliases for ButtonStyle, gives an AttributeError

### Reproduction Steps

Make a button.
Give it a ButtonStyle.blurple.
Get Error when it's called.

### Minimal Reproducible Code

```python
Button(label="This button will not work", style=ButtonStyle.primary)
```

### Expected Results

The button to just show up

### Actual Results

![image](https://user-images.githubusercontent.com/425207/134737600-406c6a81-edac-4281-bf3c-40a86e872482.png)

### Intents

discord.Intents.default()

### System Information

py-cord 2.0.0a (3861+g2d747f8f)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

any and all button aliases are not working, changing them to the ints however does work.

**Comment by nerdguyahmad** [comment]
I can't reproduce this, Can you show your report.update function? Make sure to hide the personal info.

**Comment by lorddusk** [comment]
https://github.com/CrawlerEmporium/GithubCrawler/blob/0783ed5208055c1714b025599d0c0b10a936e398/models/reports.py#L635

I've already changed the style to non aliases, but the rest of the code hasn't changed.

**Comment by nerdguyahmad** [comment]
The problem is not with Enum but your code, The issue is right in your imports:
https://github.com/CrawlerEmporium/GithubCrawler/blob/0783ed5208055c1714b025599d0c0b10a936e398/models/reports.py#L4

You're doing:
```py
from discord.types.components import ButtonStyle
```
`discord.types` is for Discord API typings. You have to import ButtonStyle from enums.
```py
from discord.enums import ButtonStyle
# or
from discord import ButtonStyle
```

**Comment by lorddusk** [comment]
I blame my auto importer. That was indeed the issue. Thanks :)
