### ISSUE TITLE
Add pre-commit and github actions to encourage contributors push code aligned with PEP

### ISSUE THREAD

**Issue by bhattbhuwan13** [Pycord-Development/pycord#228]
### Summary

add pre-commit and github actions for  linting and auto styling 

### What is the feature request for?

The core library

### The Problem

I see that the code has significant number of issues related to python styling convention violation. As such, it would be a great idea to add [pre-commit](https://pre-commit.com) and necessary github actions so that new developers can readily use it and avoid violating python code convention.

### The Ideal Solution

Adding pre-commit and necessary github actions for the job(linting and auto-styling)

### The Current Solution

None

**Comment by ImNimboss** [comment]
Agreed

**Comment by bhattbhuwan13** [comment]
@ImNimboss, I would like to work on this.

**Comment by Rxann** [comment]
I think it could be a better idea for all people making content for the library to use the black formatter so all code is neat and clean.

**Comment by bhattbhuwan13** [comment]
> I think it could be a better idea for all people making content for the library to use the black formatter so all code is neat and clean.

@Rxann, We can use black formatter as a pre-commit. Once pre-commit is set up we don't have to explicitly tell people to use them. However, using black as a github actions is also a good idea as people can't bypass github actions

**Comment by Rxann** [comment]
Yes, if someone could open a pr for this that would be amazing

**Comment by bhattbhuwan13** [comment]
I am working on it.

**Comment by BenDev9** [comment]
If this is still a thing, I'd be happy to write some stuff for it!

**Comment by krittick** [comment]
This was actually already added in #868 and #1019, and we're working on some additional workflows as well. Thank you though!
