### ISSUE TITLE
After is set to id=0 even if you pass a value for after in https://docs.pycord.dev/en/stable/api/models.html#discord.Guild.audit_logs

### ISSUE THREAD

**Issue by champymarty** [Pycord-Development/pycord#2294]
### Summary

After is not updated to the value passed. This result in all audit log being fetch

### Reproduction Steps

1) Call audit_logs() with a value for after that is not the oldest entry id

### Minimal Reproducible Code

```python
object_id = discord.Object(id=any_audit_log_id)
async for entry in guild.audit_logs(after=object_id):
    pass
```

### Expected Results

Received only the entries after the value after

### Actual Results

Received all entry, even the ones before the value after specifed

### Intents

view_audit_log

### System Information

- Python v3.11.1-final
- py-cord-dev v2.5.None-candidate
    - py-cord-dev pkg_resources: v2.5.0rc5
- aiohttp v3.8.5
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Here is the inital question in discord help server: [inital question](https://discord.com/channels/881207955029110855/1132206148309749830/1186522479750029393)
Here is the problem in the code that I identified: [problem](https://discord.com/channels/881207955029110855/1132206148309749830/1186537206358229032)
Here is the potential solution: [solution](https://discord.com/channels/881207955029110855/1132206148309749830/1186541811683033168)

**Comment by Lulalaby** [comment]
You could open a pull request directly if you found a solution already <3

**Comment by JustaSqu1d** [comment]
> You could open a pull request directly if you found a solution already <3

~~But it's more github activity~~

**Comment by champymarty** [comment]
I did not open a PR yet because I dont konw to process of pycord. Also it is late for me

**Comment by Lulalaby** [comment]
bam bam bam, fixed
