### ISSUE TITLE
Renaming slash decorator

### ISSUE THREAD

**Issue by HarryPotter12352** [Pycord-Development/pycord#231]
### Summary

Changing slash commands decorator name

### What is the feature request for?

The core library

### The Problem

Long slash command decorator name

### The Ideal Solution

I suggest we change the command decorator from `slash_command` to just simple `slash`

### The Current Solution

None for now.

### Additional Context

Nothing, thanks

**Comment by Dorukyum** [comment]
This can be added as an alias, no point in renaming.

**Comment by nerdguyahmad** [comment]
"slash" makes no sense. That way we can call user_command deco "user"...

**Comment by Rxann** [comment]
> This can be added as an alias, no point in renaming.

I agree

**Comment by ImNimboss** [comment]
`slash` and `slash_cmd` could both be potential aliases to `slash_command`

**Comment by HarryPotter12352** [comment]
> `slash` and `slash_cmd` could both be potential aliases to `slash_command`

True

**Comment by Dorukyum** [comment]
> `slash` and `slash_cmd` could both be potential aliases to `slash_command`

Do you really think `slash_command` needs 2 aliases? `slash` is fine but `slash_cmd` doesnt seem good, nor it is needed.

**Comment by ImNimboss** [comment]
I mean I wouldn't mind if it had both or just 1, just an idea i had

**Comment by BobDotCom** [comment]
This suggested `slash` alias is short.

There's just about *nothing* else positive about it.

Following our current schema, this would mean `message_command` and `user_command` would have to be renamed to `message` and `user`. Apart from already being used in the namespace, these names are just non-descriptive and confusing. 

There is a potential for `command.xxx` where xxx is `slash`, `message`, or `user` (would NOT be imported into the global namespace of `discord`, would only be in `discord.command`). This would allow for either of the below
```py
from discord.command import slash 

@slash()
def command(ctx):
    ...
```
```py
from discord import command

@command.slash()
def command(ctx):
    ...
```
This may be used in the restructure branch but is nowhere near final yet.
