### ISSUE TITLE
Unable to install in 3.12 due to aiohttp 3.8.6

### ISSUE THREAD

**Issue by nephi-dev** [Pycord-Development/pycord#2334]
### Summary

Can't install on python 3.12 because aiohhtp 3.8.6 fails to build and py-cord rely on a version lower than 3.9.0

### Reproduction Steps

try to install on a python 3.12 env.

### Minimal Reproducible Code

```python
`pip install py-cord`
```

### Expected Results

install succeds

### Actual Results

install fails

### Intents

.

### System Information

.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Known, install from git
