### ISSUE TITLE
Messages can no longer be fetched

### ISSUE THREAD

**Issue by Cyeniia** [Pycord-Development/pycord#2349]
### Summary

Messages can no longer be fetched

### Reproduction Steps

I have tried to fetch a message from a TextChannel

### Minimal Reproducible Code

```python
async def change_reaction(message_id: int, old: str, new: str):
    channel = await bot.fetch_channel(log_channel)
    message = await channel.fetch_message(message_id)
    await message.remove_reaction(old, bot.user)
    await message.add_reaction(new)
```

### Expected Results

I get a message back

### Actual Results

```Unhandled exception in internal background task 'change_reaction'.
Traceback (most recent call last):
  File "D:\Entwicklung\Python\Discord\Announce\main.py", line 40, in change_reaction
    message = await channel.fetch_message(message_id)
  File "D:\Entwicklung\Python\Discord\venv\lib\site-packages\discord\abc.py", line 1696, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "D:\Entwicklung\Python\Discord\venv\lib\site-packages\discord\http.py", line 367, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

### Intents

discord.Intents.default() + message_content

### System Information

- Python v3.10.0-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Try again with the ID of a message that the bot can actually see.

**Comment by Cyeniia** [comment]
The bot can see the message
