### ISSUE TITLE
Ability to filter displayed roles in discord.ui.Select with discord.ComponentType.role_select

### ISSUE THREAD

**Issue by denisnumb** [Pycord-Development/pycord#2354]
### Summary

Ability to customize displayed roles in discord.ui.Select

### What is the feature request for?

The core library

### The Problem

When I use this code:

```py
select = discord.ui.Select(select_type=discord.ComponentType.role_select)
```

I want to be able to customize the roles displayed in the dropdown list.

### The Ideal Solution

Some parameter responsible for the displayed roles

### The Current Solution

At the moment, you have to use `select_type=discord.ComponentType.string_select`, with strings bound to specific roles on the server.

**Comment by Lulalaby** [comment]
We can only support what discord supports.
See [Discord Docs - Select Menu Structure](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure) and [Discord Docs - Select Default Value Structure
](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-default-value-structure).

We can only specify default selected roles, not limit them. You have to use string select if you want to limit the visibility of roles.
