### ISSUE TITLE
Channel members attribute broken

### ISSUE THREAD

**Issue by Aviana** [Pycord-Development/pycord#2355]
### Summary

When getting or fetching a channel the members attribute contains wrong data

### Reproduction Steps

Make a fresh connection with the bot.
Use the get_channel or fetch_channel functions to get a channel object.
Inspect the members property.
It only contains the bot.

### Minimal Reproducible Code

```python
channel1 = await bot.fetch_channel(channel_id)
channel2 = bot.get_channel(channel_id)

print(channel1.members)
print(channel2.members)
```

### Expected Results

A full list of members. For example for a voice channel all connected users.

### Actual Results

Only the bot is listed.

### Intents

4161277

### System Information

- Python v3.11.7-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Linux 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If you connect to for example a voice channel after the bot is connected the members list will include you. It will only fail to fetch already existing users.

**Comment by JustaSqu1d** [comment]
The `intents.value` you provided shows that the `members` intent is not enabled. This is expected behavior because the members are not cached and will not be returned when using `channel.members`.
