### ISSUE TITLE
Change the name of the Nitro Boosting related Attributes

### ISSUE THREAD

**Issue by TjMatBTW** [Pycord-Development/pycord#237]
### Summary

Basically change the names to be easier.

### What is the feature request for?

The core library

### The Problem

The current attributes related to nitro boosting are ``premium_subscriber_role``, ``premium_subscribers``, ``premium_subscription_count`` and ``premium_tier``. The problem is: it's not very easy to know those attributes, as their names are not that related to the words ``nitro``, ``booster`` etc. 

### The Ideal Solution

The solution is to change the name of those attributes to something more intuitive. Examples are: 

**1.** ``premium_subscriber_role`` - This is the name of the role that is assigned to a booster. My suggestion is to change it to ``nitro_booster_role``.

**2.**  ``premium_subscribers`` - The amount of users that are boosting the guild. My suggestion is to change it to ``nitro_boosters``.

**3.** ``premium_subscription_count`` - This is the amount of boosts that the guild has. My suggestion is to turn it to ``nitro_boosts_count`` or just ``nitro_boosts``.

**4.** ``premium_tier`` - The level of guild boosts, from 0 to 3. This could be changed to ``boost_level``.

### Additional Context

I just decided to request this as the current attributes are not that intuitive. For me, the name ``premium`` doesn't make sense, as it's not even close to ``boost`` or ``nitro``. Hope you guys enjoy :)

**Comment by Dorukyum** [comment]
Fyi, these names have been set by Discord.

**Comment by TjMatBTW** [comment]
> Fyi, these names have been set by Discord.

Are they changeable?

**Comment by BobDotCom** [comment]
This will not happen.

Similar to "server" and "guild", "premium_subscription" is the real name for "nitro boost". Changing this would be confusing and wrong.
