### ISSUE TITLE
Paginator author check

### ISSUE THREAD

**Issue by Lumabots** [Pycord-Development/pycord#2381]
### Summary

Paginator.__init__() got an unexpected keyword argument 'user'

### Reproduction Steps

create a paginator, use the author_check function and edit the paginator

### Minimal Reproducible Code

```python
paginator = pages.Paginator(pages=pages, author_check=True, custom_view=View,  user=interaction.user​​ )​
await paginator.edit(interaction.message)
```

### Expected Results

It should just work as in the doc user is an attribute of pages.Paginator so we should be able to edit it like this because if we can't, author_check is useless, no user will never be able to interact since the user is the bot himself

### Actual Results

Paginator.__init__() got an unexpected keyword argument 'user'

### Intents

all

### System Information

- Python v3.11.4-final
- py-cord v2.5.None-final
- aiohttp v3.9.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NeloBlivion** [comment]
You're misunderstanding; Paginator automatically assigns `self.user = ctx.author` from your first `paginator.send` or `respond` etc., so you don't need to define `user` - `author_check` will still work fine.

**Comment by Lumabots** [comment]
So you didnt understand something, if i add the paginator in the view and not at the biginning of a command, the ctx.author will be the bot and not the author of the command

**Comment by NeloBlivion** [comment]
Ah, indeed `edit` is broken; my bad, this is being fixed in the above PR.

**Comment by Lulalaby** [comment]
if it were it would've been mentioned

**Comment by Revnoplex** [comment]
"`paginator.edit()` didn't work at all, because `paginator.user` was being set to `message.author`. But `message.author` will always be the bot itself". 
vs
"`Paginator.edit` sets self.user to the message author... but since you can only edit your own messages, user is set to the bot and so breaks `author_check`." 
Is that not the same? Or is it not because of the different resulting behaviour? And it also mentions adding a user parameter.
