### ISSUE TITLE
Bridge Command Arg

### ISSUE THREAD

**Issue by Lumabots** [Pycord-Development/pycord#2393]
### Summary

Arg Bridge command doesnt work

### Reproduction Steps

Use a bridge command and add some value required in a list
<img width="475" alt="Capture_decran_2024-03-15_a_09 20 53" src="https://github.com/Pycord-Development/pycord/assets/144063653/5fedebb8-2e92-4e1a-82b4-9ae7adc6e27c">

### Minimal Reproducible Code

```python
@bot.bridge_command()
@discord.option("value", choices=[1, 2, 3])
async def choose(ctx: bridge.BridgeContext, value: int):
    await ctx.respond(f"You chose: {value}!")
```

### Expected Results

it supposed to run the command

### Actual Results

Error bad arguments

### Intents

all

### System Information

pycord 2.5

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

link of the code https://github.com/Pycord-Development/pycord/blob/master/examples/bridge_commands.py

**Comment by Blue-Robin-Taken** [comment]
Could this be a problem with types?
