### ISSUE TITLE
Temporary disable slash_command in py-cord

### ISSUE THREAD

**Issue by a14stoner** [Pycord-Development/pycord#2413]
### Summary

I have bot code which I use for multiple projects. For some projects I want to disable a slash_command completely. I found no way to disable a slash_command completely .. only handle this with default_permission. But here i only can disable it for non admins for example.

### Reproduction Steps

Use code below and try to solve this issue. 

### Minimal Reproducible Code

```python
@bot.event
async def on_ready():
    xxxx.start()
    yyyy.start()
    zzzz.start()

@bot.slash_command(name="commandx")
async def commandx(update):
[..code..]

@bot.slash_command(name="commandy")
async def commandy(update):
[..code..]
```
```


### Expected Results

Posibility to disable slash_commands in code. 

### Actual Results

Not possible to do so. 


### Intents

intents = discord.Intents().all()

### System Information

- Python v3.11.8-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29)


### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Blue-Robin-Taken** [comment]
Well, you could disable it for everyone via:
https://stackoverflow.com/questions/78211436/discord-py-check-if-slash-command-exists/78211614#78211614
(Yes, the title is misleading)
The user in that post wants to also disable a slash command via another command. 
```
@tree.command(guild=discord.Object(id=guild_id), name='disable', description='Disable a specified Command')
async def disable(interaction: discord.Interaction, command: str):
    await interaction.response.defer()
    if tree.get_command(command, guild=discord.Object(id=guild_id)):  # check if the command exists
        tree.remove_command(command, guild=discord.Object(id=guild_id))  # remove the command
        print("command removed!")
        await tree.sync(guild=discord.Object(id=guild_id))  # sync the tree
        print("tree synced!")
        await interaction.followup.send(
            f"{command} was disabled. You can reenable it by running /enable {command}")
    else:
        await interaction.followup.send(f"Command could not be found: {command}")
```

**Comment by a14stoner** [comment]
Since i can only add the 

`tree = app_commands.CommandTree(client)
`

when importing

`import discord
from discord import app_commands`

 from discord.py its not a solution for me. 
 
 (reference: https://stackoverflow.com/questions/71165431/how-do-i-make-a-working-slash-command-in-discord-py)

**Comment by Lulalaby** [comment]
Please discuss that in our server https://discord.gg/pycord
