### ISSUE TITLE
Slash commands interaction response doesnt give message

### ISSUE THREAD

**Issue by Lumabots** [Pycord-Development/pycord#2431]
### Summary

return None and not object message

### Reproduction Steps

LIke in the minimal reproducible code
Can be fix using  ctx.interaction.original_response

### Minimal Reproducible Code

```python
@commands.slash_command()
    async def test(self, ctx: discord.ApplicationContext):
        interaction = await ctx.respond(content="test")
        print(interaction.message)
```

### Expected Results

Should be a message object

### Actual Results

None

### Intents

all

### System Information

py-cord 2.5

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
As per [spec](https://discord.com/channels/889823989961224202/996114821177163816/1232023457089327174), initially responding to an interaction does **not** return a message / interaction object.
> Create a response to an Interaction from the gateway. Body is an [interaction response](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object). Returns 204 No Content.

So this is intended
