### ISSUE TITLE
audit_logs not fetching more than 100 logs

### ISSUE THREAD

**Issue by champymarty** [Pycord-Development/pycord#2445]
### Summary

audit_logs not fetching more than 100 logs

### Reproduction Steps

async for entry in guild.audit_logs(limit=None, after=discord.Object(id=0),                                action=discord.AuditLogAction.member_role_update):
  ...

### Minimal Reproducible Code

```python
async for entry in guild.audit_logs(limit=None, after=discord.Object(id=0),                                action=discord.AuditLogAction.member_role_update):
  ...
```

### Expected Results

Fetch all the audit logs in batches:
fetch 1-100, 101-202, ... etc
but in the iterator, we only see them coming one at a time
without to have to do multiple calls

### Actual Results

Only fetch the 100 lastest audit logs

### Intents

    intents.members = True     intents.guilds = True     intents.moderation = True     intents.voice_states = True

### System Information

- Python v3.11.1-final
- py-cord v2.5.1-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The problem migh have been introduced by the after param being fixed: 
Fixed AuditLogIterator not respecting the after parameter. ([#2295](https://github.com/Pycord-Development/pycord/issues/2295))

**Comment by champymarty** [comment]
Here is the fix they did on discord.py on that issue: http
s://github.com/Rapptz/discord.py/pull/9269/files

**Comment by NeloBlivion** [comment]
Can't replicate

**Comment by champymarty** [comment]
I need both limit=None and the after param for my use case

**Comment by champymarty** [comment]
Do you think this will be pick up ?
