### ISSUE TITLE
Vanity URL cannot be edited anymore

### ISSUE THREAD

**Issue by Lumabots** [Pycord-Development/pycord#2477]
### Summary

Guild edit has attribute vanity_role while he cant edit that

### Reproduction Steps

https://github.com/Pycord-Development/pycord/blob/9ab4bd6094e067e0c7956b316f483c6730ff50d1/discord/guild.py#L1718

### Expected Results

N/A

### Actual Results

N/A

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
This is handled through a different endpoint.

https://github.com/Pycord-Development/pycord/blob/9ab4bd6094e067e0c7956b316f483c6730ff50d1/discord/guild.py#L1762-L1763

https://github.com/Pycord-Development/pycord/blob/ec3cf1652e574d4b59b52bde897a21ef51f221ce/discord/http.py#L1631-L1639

**Comment by NeloBlivion** [comment]
I think they meant it shouldn't be available because bots cannot use the endpoint (not documented, and searching on DDevs shows this is intentional)

**Comment by Lulalaby** [comment]
that is correct. bots can't change it anymore do to being a big attack vector afaik for stealing and gatekeeping vanities.

**Comment by Dorukyum** [comment]
Then we can remove the other method.

**Comment by Lulalaby** [comment]
yes
