### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by EmpathyYT** [Pycord-Development/pycord#248]
### Summary

More examples of new features

### What is the feature request for?

The core library

### The Problem

There aren't many examples of new features which makes it a bit harder to figure out how to use an alpha feature. Adding more examples would make it easier for the entire community to get to know how to use the newest features.

### The Ideal Solution

Add more examples

### The Current Solution

A small amount of examples

**Comment by Dorukyum** [comment]
What would the new examples be for?

**Comment by TheSlayerishere** [comment]
> What would the new examples be for?

Maybe using slash commands with cogs, can't really seem to find them anywhere. There also could be an example bot, complete with cogs (since that's what most people are going to end up using anyways) to illustrate how everything can be integrated with cogs.

**Comment by Dorukyum** [comment]
> > What would the new examples be for?
> 
> Maybe using slash commands with cogs, can't really seem to find them anywhere. There also could be an example bot, complete with cogs (since that's what most people are going to end up using anyways) to illustrate how everything can be integrated with cogs.

Update: A slash cog example has been added with #341.

**Comment by Dorukyum** [comment]
> I'd be happy to write an example bot

There are bot examples such as [basic_bot.py](https://github.com/Pycord-Development/pycord/blob/master/examples/basic_bot.py).

**Comment by pratheek78** [comment]
What about more info about dropdown menus, or other smaller features? i struggled to find an example for editing the message with the specific embed when the user reacts with the respective field. There could be a lot more examples related to  things like this even in the official docs.

**Comment by martinbndr** [comment]
> What would the new examples be for?

Would be nice to ``add/improve`` the example for persistent views. Like currently it seems that the persistent view for buttons is for a seperate bot / a bot without a cog.
But I think its really needed to also add an example for how to use **persistent views** in a **cog**.
When a bot has multiple features its kind of a must have to use them in a cog.

I already tried using them in a cog but I am facing issues. An example would really help to understand how that works.

**Comment by ResetXD** [comment]
#484

**Comment by martinbndr** [comment]
![image](https://user-images.githubusercontent.com/55140357/143073851-48734d1e-dc2b-41fb-a9ea-5df16ab44607.png)
Seems that got outdated

**Comment by DefiDebauchery** [comment]
Not just code examples, but screenshots of how the examples would look within Discord would make such examples even more useful.

**Comment by pratheek78** [comment]
yeah this would be quite ueseful, ngl

**Comment by krittick** [comment]
Closing this issue as it's too generic and creating examples is possible by anyone - just submit a PR. It's not really a request for the library itself that needs to be tracked.
