### ISSUE TITLE
Deferred message cannot return as ephemeral

### ISSUE THREAD

**Issue by zoomingspeed** [Pycord-Development/pycord#2485]
### Summary

When using ctx.defer(), it cannot return an ephemeral message, whether you use ctx.followup.send() or ctx.respond()

### Reproduction Steps

1. Call ctx.defer()
2. Make a message send after it defers, include the ephemeral parameter too.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = discord.Bot(intents=discord.Intents.all())

@bot.slash_command(name="wtv", description="wtv")
async def hi(ctx):
    await ctx.defer()
    await asyncio.sleep(1)
    await ctx.followup.send("Hello!", ephemeral=True)

# Or if we wanna do the same thing but with ctx.respond:
@bot.slash_command(name="wtv", description="wtv")
async def hi(ctx):
    await ctx.defer()
    await asyncio.sleep(1)
    await ctx.respond("Hello!", ephemeral=True)
```

### Expected Results

Return an ephemeral message as expected

### Actual Results

Returns the message, but it is not ephemeral

### Intents

discord.Intents.all()

### System Information

  import pkg_resources
- Python v3.10.13-final
- py-cord v2.5.None-final
- aiohttp v3.8.6
- system info: Linux 6.5.0-1022-azure #23~22.04.1-Ubuntu SMP Thu May  9 17:59:24 UTC 2024

(vscode.dev environment)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Note, also using ctx.send() makes the program return a type error:

```
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/workspaces/sheikh-bot/sheikh-dev.py", line 837, in prayertimes
    await ctx.send(embed=embed, ephemeral=True)
TypeError: Messageable.send() got an unexpected keyword argument 'ephemeral'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/discord/commands/core.py", line 139, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: Messageable.send() got an unexpected keyword argument 'ephemeral'
```

**Comment by Blue-Robin-Taken** [comment]
Do we know if this is a discord limitation or just the library

**Comment by Vondyy** [comment]
pass this ephemeral=True in your defer.

**Comment by Blue-Robin-Taken** [comment]
@Vondyy 
This is supported by the docs
https://docs.pycord.dev/en/stable/api/application_commands.html#discord.ApplicationContext.defer

**Comment by Dorukyum** [comment]
`await ctx.defer(ephemeral=True)` if you're eventually going to send an ephemeral response.
