### ISSUE TITLE
Unload cog does not remove prefix command

### ISSUE THREAD

**Issue by Lumabots** [Pycord-Development/pycord#2499]
### Summary

Unload cog does not remove prefix command

### Reproduction Steps

unload a cog 

### Minimal Reproducible Code

```python
for cog_module in list(bot.extensions)
        bot.unload_extension(cog_module)
    print(bot.prefixed_commands)
```

### Expected Results

{}

### Actual Results

list of command

### Intents

all

### System Information

2.6

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NeloBlivion** [comment]
Can't repro
