### ISSUE TITLE
Quest Profile Badge

### ISSUE THREAD

**Issue by Areoxy** [Pycord-Development/pycord#2514]
### Summary

Add the quest profile badge to public_flags

### What is the feature request for?

The core library

### The Problem

Just add the new quest profile badge to the public_flags. Because now you can't fetch this badge from members data.

### The Ideal Solution

Just add the new quest profile badge to the public_flags. Because now you can't fetch this badge from members data.

**Comment by Lulalaby** [comment]
That's not how `badges` nor `public_flags` work.
These kind of badges aren't flags anymore since a few years(?).
It's only visible for the `/api/v10/users/:user_id/profile` route, which is inaccessible for bots (user-only route).
```json
{
    "user": {
        // ..
     },
    "connected_accounts": [
        // ..
      ],
    "premium_since": "",
    "premium_type": 2,
    "user_profile": {
        // ..
     },
    "badges": [
        // ..
        {
            "id": "quest_completed",
            "description": "Completed a Quest",
            "icon": "7d9ae358c8c5e118768335dbe68b4fb8",
            "link": "https://discord.com/settings/inventory"
        }
    ]
}
```
