### ISSUE TITLE
Add server-specific member banners

### ISSUE THREAD

**Issue by ToothyDev** [Pycord-Development/pycord#2516]
### Summary

It isn't possible to access a member's server specific banner, if set

### What is the feature request for?

The core library

### The Problem

Currently, only `Member.banner` exists. This is different from avatars, where both `Member.avatar` and `Member.display_avatar` are implemented. This makes it impossible to access members' server-specific banners, as currently, `Member.banner` will always return their globally set banner

### The Ideal Solution

`Member.display_banner` is added, making it possible to access members' server-specific banners if set

**Comment by plun1331** [comment]
Someone else take care of this, I'm on vacation :p
