### ISSUE TITLE
Slash Commands Issue

### ISSUE THREAD

**Issue by BruceCodesGithub** [Pycord-Development/pycord#257]
### Summary

Problem with Slash Command - Slash Commands not working after I make them global - no new slash commands get registered anymore.

### Reproduction Steps

1. Created a guild-only slash command regularly
2. Made it global
3. It stopped working, and no new slash commands were registered any longer. Has happened before, have reproduced.

### Minimal Reproducible Code

```python
@bot.slash_command(guild_ids=[remove this later], name='covid', description="Better Covid-19 Statistics")
async def _covid_slash(ctx):
	await ctx.respond("Wow")
```

### Expected Results

The Slash Command becomes global after some time, and in the meanwhile other guild-only Slash COmmands get registered

### Actual Results

No new Slash Commands get registered. The Slash Command registered before still stays, but does not work. 

### Intents

discord.Intents.all()

### System Information

- Python v3.8.12-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a3883+g27e0b42d
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-1020-gcp #22~20.04.1-Ubuntu SMP Tue Sep 21 10:54:26 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have removed my token from display, if visible.
- [X] I have shown the entire traceback, if possible.

### Additional Context

I have tried this twice, and it still does not work.
After I remove a Slash Command, it does not sync and no new Slash Commands get registered.
I tired asking for help, but no one could.

**Comment by BruceCodesGithub** [comment]
@zeffo  I waited for above 1 hour, and its still not registered. Also, the main issue is that new Slash Commands, even if guild-specific are no longer registered, and moreover, no previous slash commands are getting removed either.

**Comment by L0ckout** [comment]
Might I suggest kicking the bot from your server and reinviting it. This could fix the issue.

**Comment by Hype3808** [comment]
Did you reached the limit of slash commands?

**Comment by Lulalaby** [comment]
> Did you reached the limit of slash commands?

That isn't really possible 

But it wouldn't be bad to check it with a manual call.
/api/v9/applications/:id/commands

**Comment by ReenigneArcher** [comment]
`discord-py-slash-command` has a way to sync commands, so no waiting is required and no need to kick your bot and re-invite.

https://pypi.org/project/discord-py-slash-command/

```py
from discord_slash import SlashCommand
slash = SlashCommand(client, sync_commands=True)
```

However this doesn't seem to be working with 2.x releases of py-cord. Maybe py-cord can implement something similar?

**Comment by Dorukyum** [comment]
> `discord-py-slash-command` has a way to sync commands, so no waiting is required and no need to kick your bot and re-invite.
> 
> https://pypi.org/project/discord-py-slash-command/
> 
> ```python
> from discord_slash import SlashCommand
> slash = SlashCommand(client, sync_commands=True)
> ```
> 
> However this doesn't seem to be working with 2.x releases of py-cord. Maybe py-cord can implement something similar?

Pycord does sync commands and the global command registration delay is on Discord's side.

**Comment by ReenigneArcher** [comment]
> Pycord does sync commands and the global command registration delay is on Discord's side.

Thanks, I found it after I made my comment. For anyone else it may help, found it here: https://docs.pycord.dev/en/master/api.html#discord.Bot.auto_sync_commands
