### ISSUE TITLE
Add support for voice messages

### ISSUE THREAD

**Issue by aka-tinyy** [Pycord-Development/pycord#2571]
### Summary

Adding the option to send an audio file as a native discord file

### What is the feature request for?

The core library

### The Problem

Making audio files viewable on mobile

### The Ideal Solution

Adding the proper parameters, such as voice message flags, duration, and waveform, to allow for native audio messages.

**Comment by Lulalaby** [comment]
This is currently not documented by discord and doesn't seem like it will be in future either.
So for the time being this won't be added.

**Comment by aka-tinyy** [comment]
According to advaith in the ddevs server he said it was documented. "you just send a message with the voice message flag and an audio attachment with waveform and duration fields".
