### ISSUE TITLE
Slash commands work in main file but not when moved to a Cog file

### ISSUE THREAD

**Issue by aghering23** [Pycord-Development/pycord#2572]
### Summary

When using the decorator @bot.command directly in main.py, the slash commands show up correctly in the Discord slash menu. However, when migrating the commands to a cog (slashCommands.py), the commands no longer appear in the slash menu.

### Reproduction Steps

Reproduction Steps:

1. Define slash commands using @bot.command in main.py. These commands work and appear in the Discord slash menu.
2. Comment the @bot.command(description="Sends the bot's latency.") ping function in main.py
3. Move the commands into a separate file (slashCommands.py) and register them using a Cog with bot.load_extension('botModules.slashCommands') in main.py.
4. uncomment loadModules() in on_ready()
5. The slash commands no longer appear in the Discord slash command menu after being migrated to the Cog.

### Minimal Reproducible Code

```python
[main.py]
import discord
from config.config import discordToken

bot = discord.Bot(intents=discord.Intents.default())

## comment this out when using cog
@bot.command(description="Sends the bot's latency.")
async def ping(ctx):
    await ctx.respond(f"Pong! Latency is {bot.latency}")
## function-end

async def loadModules():
    # Load the commands cog from botModules.slashCommands
    try:
        bot.load_extension('botModules.slashCommands')
    except Exception as e:
        print(f"Failed to load commands cog: {str(e)}")

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user}")
    # await loadModules() # comment this out when not using cog

if __name__ == "__main__":
    bot.run(discordToken)



[botModules/slashCommands.py]
import discord
from discord.ext import commands

class SlashCommands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.slash_command(description="Sends the bot's latency.")
    async def ping(self, ctx):
        await ctx.respond(f"Pong! Latency is {self.bot.latency}")

def setup(bot):
    bot.add_cog(SlashCommands(bot))
```

### Expected Results

The commands should appear in the Discord slash command menu, just as they did when they were directly in main.py.

### Actual Results

The commands do not appear in the Discord slash command menu when they are defined in the slashCommands.py file and loaded as a cog.

### Intents

I'm using discord.Intents.default() for intents.

### System Information

Python: 3.12.3
Pycord: 2.6.0
Operating System: WIN10
---

python.exe -m pip list                                                                                                              
Package            Version
------------------ ---------------
aiohappyeyeballs   2.4.0
aiohttp            3.10.5
aiosignal          1.3.1
annotated-types    0.6.0
anyio              4.3.0
attrs              24.2.0
bitarray           2.9.2
certifi            2024.2.2
charset-normalizer 3.3.2
ckzg               2.0.1
colorama           0.4.6
cytoolz            0.12.3
distro             1.9.0
eth_abi            5.1.0
eth-account        0.13.3
eth-hash           0.7.0
eth-keyfile        0.8.1
eth-keys           0.5.1
eth-rlp            2.1.0
eth-typing         5.0.0
eth-utils          5.0.0
frozenlist         1.4.1
greenlet           3.0.3
h11                0.14.0
hexbytes           1.2.1
httpcore           1.0.5
httpx              0.27.0
idna               3.7
loguru             0.7.2
multidict          6.0.5
oauthlib           3.2.2
openai             1.28.0
parsimonious       0.10.0
pip                24.2
py-cord            2.6.0
pycryptodome       3.20.0
pydantic           2.7.1
pydantic_core      2.18.2
python-dotenv      1.0.1
pytz               2024.1
pyunormalize       15.1.0
pywin32            306
regex              2024.7.24
requests           2.31.0
requests-oauthlib  1.3.1
rlp                4.0.1
schedule           1.2.1
setuptools         74.1.2
sniffio            1.3.1
SQLAlchemy         2.0.34
toolz              0.12.1
tqdm               4.66.4
tweepy             4.14.0
types-requests     2.32.0.20240905
typing_extensions  4.11.0
urllib3            2.2.1
web3               7.2.0
websockets         13.0.1
win32-setctime     1.1.0
yarl               1.9.11

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
cogs with commands must be added before running the bot (not in on_ready)
