### ISSUE TITLE
running bot after upgrading

### ISSUE THREAD

**Issue by K1ng04** [Pycord-Development/pycord#2576]
### Summary

Having trouble using  remove_command

### Reproduction Steps

Upgraded to the latest version

example code:

```
intents = discord.Intents.default()
client = commands.Bot(command_prefix='/', intents=intents) 
@client.command(aliases=['next', 'Next', "NEXT"], guild_ids=testserver, name='next', description='used to loop through queue')
async def play_next(ctx):
    ********* code **********
```

### Expected Results

Command to work as expected before upgrade

### Actual Results

```discord.ext.commands.errors.CommandRegistrationError: The alias next is already an existing command or alias.```

### Intents

default

### System Information

- Python v3.9.5-final
- discord.py v2.4.0-final
- aiohttp v3.8.5
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Tried running client.remove_command(), but, that hasn't help

**Comment by plun1331** [comment]
your command has its own name as an alias

**Comment by Icebluewolf** [comment]
Feel free to ask for help in our discord: https://discord.gg/pycord
