### ISSUE TITLE
Role Position Return 1

### ISSUE THREAD

**Issue by Lumabots** [Pycord-Development/pycord#2578]
### Summary

Role Position Return The Wrong Position

### Reproduction Steps

I used the role.position

### Minimal Reproducible Code

```python
for role in guild.roles:
    print(role, role.position)
```

### Expected Results

role and position

### Actual Results

role and 1 for each (except everyone which is 0)

### Intents

all

### System Information

in 2.5 working normally
in 2.6 giving 0, 1 and 2 max
in 2.6.1 giving 0 and 1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NeloBlivion** [comment]
can't repro, position is received directly from the API that we don't modify.

**Comment by Paillat-dev** [comment]
I'll test this later today

**Comment by Lumabots** [comment]
Did try in another server and it works great, I guess the issue come from the guild, which is strange...
