### ISSUE TITLE
bypassing machine ssl certs when connecting to discord, a way to use certifi w/ pycord?

### ISSUE THREAD

**Issue by cosmoselodie** [Pycord-Development/pycord#2591]
### Summary

A way to use 'certifi' package with py-cord

### Reproduction Steps

so, in our infrastructure i don't have machines that have ssl certs on them.  I was bypassing them with an env var SSL_CERTS_FILE and the certs installed from 'ceritifi'.  However, a recent release of aiohttp which py-cord uses creates the ssl context at import time making my workaround more difficult as I'm programmatically manipulating this environment variable and if aiohttp imports before I do that, it doesn't work.  I wrote the aiohttp folks about it and they propose some solutions/discussion but none of this looks like stuff I can fix in my code, which consumes py-cord not aiohttp - but i could be wrong.  

 https://github.com/aio-libs/aiohttp/issues/9296

anyways, just wondering what your thoughts are on the right way to use the certifi package with py-cord for the ssl certs to connect to discord.  Maybe you have a suggestion?

### Minimal Reproducible Code

```python
check this out:  https://github.com/aio-libs/aiohttp/issues/9296
```

### Expected Results

just need a way to run py-cord when the ssl certs aren't available on a machine

### Actual Results

once py-cord pulled aiohttp 3.10.6 I got ssl verification errors

### Intents

they aren't really relevant in this case

### System Information

- Python v3.10.11-final
- py-cord v2.6.None-final
- aiohttp v3.10.6
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

most of the context is on this bug I sent aiohttp 

https://github.com/aio-libs/aiohttp/issues/9296

**Comment by plun1331** [comment]
Reading through the linked issue, [this](https://docs.aiohttp.org/en/stable/client_advanced.html#example-use-certifi) seems to be aiohttp's method of using certifi.

py-cord allows you to pass your own connector ([here](https://docs.pycord.dev/en/stable/api/clients.html#discord.Client:~:text=asyncio.get_event_loop().-,connector,-(Optional%5Baiohttp))), which should enable that capability
