### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [Pycord-Development/pycord#2625]
### Summary

return in finally swallows exceptions

### Reproduction Steps

In https://github.com/Pycord-Development/pycord/blob/9a6cbff489526e6011a9ebddad67ce0e103eee0b/discord/player.py#L595
there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except:` clause, it will not propagate on as expected.

If the intention is to suppress all exceptions, I would propose to make this clear by using "except BaseException".

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

### Expected Results

Avoid return in finally.

### Actual Results

NA

### Intents

NA

### System Information

NA

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Looks intentional to me
Also there's an except block above it that handles exceptions, so it's not swallowing them

**Comment by iritkatriel** [comment]
The except clause doesn't handle BaseExceptions (like KeyboardInterrupt). These are exceptions that you don't want to swallow, and you are.
