### ISSUE TITLE
Add the user install events

### ISSUE THREAD

**Issue by UnBonWhisky** [Pycord-Development/pycord#2626]
### Summary

It would be good to add it on the bot

### What is the feature request for?

The core library

### The Problem

Currently, we can only listen for the on_guild_join, which is when the bot joins a server, not a user.

### The Ideal Solution

The solution would be to listen to this event type : https://discord.com/developers/docs/events/webhook-events#application-authorized if possible

**Comment by Paillat-dev** [comment]
Hey, that is a webhook event, which means it needs a webserver and is likely outside of the scope of pycord

**Comment by UnBonWhisky** [comment]
okay, then I close this issue
