### ISSUE TITLE
TypeError when adding a sku in the entitlements() method

### ISSUE THREAD

**Issue by UnBonWhisky** [Pycord-Development/pycord#2627]
### Summary

When calling entitlements() method with the skus argument, a TypeError is raised.

### Reproduction Steps

Make a call with `guild.entitlements(limit=None, skus=[<sku Object>])`

### Expected Results

return all the entitlements that correspond to the SKU

### Actual Results

It raises something like this `TypeError: sequence item 0: expected str instance, int found`

### Intents

guilds, messages, reactions, message_content

### System Information

- Python v3.12.2-final
- py-cord v2.6.1-final
- aiohttp v3.10.10
- system info: Linux 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The source code that raises the error is this one : 
https://github.com/Pycord-Development/pycord/blob/72ba1b1c8311633612bedc3c6449e28fd9d16102/discord/http.py#L3015

I have checked, edited and verified that if we edit this line into this one : 
`params["sku_ids"] = ",".join(str(sku_id) for sku_id in sku_ids)`

The code works perfectly.

**Comment by NeloBlivion** [comment]
Well, if you have the solution you can just PR it directly 😅

**Comment by UnBonWhisky** [comment]
I don't understand everything plun made on his PR about the entitlements and SKU, so I prefer to make an issue, in case this part of the code is not anymore in the 2.7 with this PR https://github.com/Pycord-Development/pycord/pull/2564

So I make an issue in case it is not needed to PR this.
If it is, then I will PR it, but for now I am not sure about the code of the upcoming 2.7

**Comment by plun1331** [comment]
PR it, it still exists in my pr

**Comment by UnBonWhisky** [comment]
PR added !
