### ISSUE TITLE
ApplicationContext attributes have wrong type annotations

### ISSUE THREAD

**Issue by probablyjassin** [Pycord-Development/pycord#2635]
### Summary

The ctx attributes `channel`, `user` and `message`, `guild`, and possible more, are typed as methods, not attributes

### Reproduction Steps

- install pycord 
- i'm on version `2.6.1.dev134+g9a6cbff4` (i simply use 'git+https://github.com/Pycord-Development/pycord' in my requirements.txt)
- write a basic bot with the slash command below

### Minimal Reproducible Code

```python
import os

import discord
from discord.ext import commands

from logger import setup_logger
from config import DISCORD_TOKEN
from models.CustomMogiContext import MogiApplicationContext

logger = setup_logger(__name__)

intents = discord.Intents.all()


class customBot(commands.Bot):
    def __init__(self, *args, **kwargs):
        return super().__init__(*args, **kwargs)

    @slash_command(name="test_issue")
    async def test_issue(self, ctx: ApplicationContext):
        await ctx.respond(ctx.channel.id)
        # this works, but `channel` has the type annotation of a method:
        # (method) def channel(self: Self@ApplicationContext) -> (InteractionChannel | None)

        channel = ctx.channel()
        await ctx.send(channel)
        # this however obviously doesn't work:
        # discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: 'TextChannel' object is not callable



bot = customBot(
    command_prefix=".",
    intents=intents,
)

bot.run(TOKEN)
```

### Expected Results

Expected the type annotations to treat the ctx attributes `channel`, `user` and `message` as attributes.

And the syntax highlighting reflects them as such, causing following type annotations to break. (For example, theres no more autocomplete for ctx.channel.id, because the editor thinks channel is a method)

### Actual Results

They get autocompleted as methods.

### Intents

discord.Intents.all()

### System Information

- Python v3.12.7-final
- py-cord v2.6.1-final
- aiohttp v3.10.10
- system info: Windows 11 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

full traceback:

Traceback (most recent call last):
  File "C:\Users\Me\MyProject\venv\Lib\site-packages\discord\bot.py", line 1149, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\Me\MyProject\venv\Lib\site-packages\discord\commands\core.py", line 435, in invoke
    await injected(ctx)
  File "C:\Users\Me\MyProject\venv\Lib\site-packages\discord\commands\core.py", line 138, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "C:\Users\Me\MyProject\venv\Lib\site-packages\discord\commands\core.py", line 1486, in _invoke
    await command.invoke(ctx)
  File "C:\Users\Me\MyProject\venv\Lib\site-packages\discord\commands\core.py", line 435, in invoke
    await injected(ctx)
  File "C:\Users\Me\MyProject\venv\Lib\site-packages\discord\commands\core.py", line 146, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: 'TextChannel' object is not callable

I went to the definition of ApplicationContext and saw that the properties with this problem have the decorator @cached_property
Replacing this with @property fixes the issue, but of course I'm new to the codebase so this might not be the best way to fix this.

```python
@property # instead of @cached_property
    def channel(self) -> InteractionChannel | None:
        """Union[:class:`abc.GuildChannel`, :class:`PartialMessageable`, :class:`Thread`]:
        Returns the channel associated with this context's command. Shorthand for :attr:`.Interaction.channel`.
        """
        return self.interaction.channel
```

so maybe this is the fix, or the definition of @cached_property needs some fixing

**Comment by probablyjassin** [comment]
So i found the definition of @chached_property:

`cached_property = NewType("cached_property", property)`

Again as I'm not very familiar with the codebase, I don't know why this is a thing.

But simply replacing this with 

`cached_property = functools.cached_property`

fixes this.

Is this a good solution or would this break something else?

**Comment by Paillat-dev** [comment]
Indeed `cached_property` could either benefit of a better typing and or a better implementation. I can confirm that I experienced this issue myself, even tough it shouldn't happen.

Currently the implementation is as follows:
```python

class _cached_property:
    def __init__(self, function):
        self.function = function
        self.__doc__ = getattr(function, "__doc__")

    def __get__(self, instance, owner):
        if instance is None:
            return self

        value = self.function(instance)
        setattr(instance, self.function.__name__, value)

        return value

if TYPE_CHECKING:
    cached_property = NewType("cached_property", property)
else:
    cached_property = _cached_property
```
So the `TYPE_CHECKING` check should correctly type it as acting like a nomal `property`.
This could maybe be replaced with `functools.cached_property` might work, but idk if its implementation is incompatible.

**Comment by probablyjassin** [comment]
@Paillat-dev thanks for your quick reply!

correct me if I misunderstand but what does `NewType("cached_property", property)` even mean in the first place? It's just a type derived from `property`, right? 

So unless I'm misunderstanding some context, using `functools.cached_property` shouldn't be an issue.

I did try replacing it and that does fix the issue, and within my own discord bot it caused no other problems anywhere.

Could you find out if it's compatible, so that if it is, this can be implemented to fix the issue?
I've had this problem for a long time at this point.

**Comment by Paillat-dev** [comment]
`NewType("cached_property", property)` at runtime returns `property`, but is interpreted as type checkers like the creation of a different type from `property`.

**Comment by Paillat-dev** [comment]
![image](https://github.com/user-attachments/assets/09c2c7d3-ab67-4ea5-83b6-751cca214757)

**Comment by probablyjassin** [comment]
I see. Yeah as part of this issue, usr has an `Any` type which sucks.

![grafik](https://github.com/user-attachments/assets/7b6da92b-ae2b-471e-88ee-e5f440a71167)

and using `chached_property = functools.cached_property` would indeed fix this:

![grafik](https://github.com/user-attachments/assets/1be527d3-0326-479a-be68-708a69dc8ec3)

**Comment by probablyjassin** [comment]
#2636
