### ISSUE TITLE
Application Command Cooldowns

### ISSUE THREAD

**Issue by RGBCube** [Pycord-Development/pycord#266]
### Summary

cooldown for slash cmds

### What is the feature request for?

discord.ext.commands

### The Problem

the title

### The Ideal Solution

???

**Comment by mcbabo** [comment]
What do you mean by cooldown?

**Comment by NoPlagiarism** [comment]
@mcbabo 
> What do you mean by cooldown?

I can understand this as implement cooldown support in ApplicationCommand or SlashCommand
So i disagree with @RGBCube that feature request is for discord.ext.commands, but it's for discord.commands

**Comment by NoPlagiarism** [comment]
Oh, and it's clone of #454

**Comment by VincentRPS** [comment]
> Oh, and it's clone of #454

this was made before that issue i wouldn't call it a clone

**Comment by zeffo** [comment]
454 looks better than this one

**Comment by GrandMoff100** [comment]
Does this mean that application command cooldowns are merged now?

**Comment by plun1331** [comment]
> Does this mean that application command cooldowns are merged now?

Yes.
