### ISSUE TITLE
List of 5 select menu fails to work for more than total of 119 options

### ISSUE THREAD

**Issue by Carol52x** [Pycord-Development/pycord#2674]
### Summary

I wrote the script to split options to different select menus if there are more than 25 optionsbelow. This however fails to work when there are more than 119 options (total)

### Reproduction Steps

I made a script to split options to different menus to respect the limit of 25 options per menu. In the examples below, i test cases where no. of options are 119 and 120, and no. of select menus in both of these cases are 5. However, the script fails when 120 or more options are passed, when in theory it *should* be able to post 5 select menus with total of 125 options in one message.

### Minimal Reproducible Code

```python
def create_select_menus(self, options):
                MAX_OPTIONS = 25
                option_chunks = [options[i:i + MAX_OPTIONS]
                                 for i in range(0, len(options), MAX_OPTIONS)]
                print(len(option_chunks))
                for i in option_chunks:
                    print(len(i))
                select_menus = []

                for idx, chunk in enumerate(option_chunks):
                    select_menus.append(discord.ui.Select(
                        placeholder=f"Menu {idx + 1}",
                        min_values=1,
                        max_values=1,
                        options=[discord.SelectOption(
                            label=option, value=option) for option in chunk]
                    ))

                return select_menus
```

### Expected Results

No errors being thrown since the script was designed to adhere to the hard limit of 25 options per menu as well as 5 select menus per message. Also, the type of error being thrown doesn't make sense if it actually exceeds the limits (which according to the docs, doesn't)

### Actual Results

5 # no. of select menus
25 # no. of options in menu 1
25 # no. of options in menu 2
25 # no. of options in menu 3
25 # no. of options in menu 4
20 # no. of options in menu 5
Ignoring exception in on_application_command
Traceback (most recent call last):
  File "C:\Users\GuestID\Desktop\formulaStats\f1bot\Lib\site-packages\discord\client.py", line 412, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\GuestID\Desktop\formulaStats\f1\commands.py", line 91, in on_application_command
    await ctx.defer(
  File "C:\Users\GuestID\Desktop\formulaStats\f1bot\Lib\site-packages\discord\interactions.py", line 783, in defer
    await self._locked_response(
  File "C:\Users\GuestID\Desktop\formulaStats\f1bot\Lib\site-packages\discord\interactions.py", line 1291, in _locked_response
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before
Traceback (most recent call last):
  File "C:\Users\GuestID\Desktop\formulaStats\f1\cogs\season.py", line 377, in records
    await ctx.respond(embed=embed, view=Menu(options=headings))
  File "C:\Users\GuestID\Desktop\formulaStats\f1bot\Lib\site-packages\discord\interactions.py", line 622, in respond
    return await self.followup.send(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuestID\Desktop\formulaStats\f1bot\Lib\site-packages\discord\webhook\async_.py", line 1794, in send
    data = await adapter.execute_webhook(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GuestID\Desktop\formulaStats\f1bot\Lib\site-packages\discord\webhook\async_.py", line 234, in request
    raise DiscordServerError(response, data)
discord.errors.DiscordServerError: 500 Internal Server Error (error code: 0): 500: Internal Server Error

### Intents

default

### System Information

- Python v3.11.8-final
- py-cord v2.6.1-final
- aiohttp v3.9.3
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

-

**Comment by Lulalaby** [comment]
500 Internal Server Error is a discord problem, not a library problem. Please report the bug to discord.
Either through the support form https://support-dev.discord.com/hc/en-us/requests/new?ticket_form_id=12094720423319 or on github through https://github.com/discord/discord-api-docs/issues/new?assignees=&labels=bug&projects=&template=api-bug-report.yml.

Make sure to search for existing reports about it.

**Comment by NeloBlivion** [comment]
You're probably hitting some internal Discord limit on json body
Example:
```py
content = "a"*2000,  # Generates 2000 character string
embeds = [discord.Embed(description="i"*1000)]*6  # Generates 6 embeds of 1000 characters each
await ctx.send(content, embeds=embeds)
```

works normally
```py
menus = create_select_menus([str(x) for x in range(125)])  # Generates 125 options all with name and value 0, 1, 2, ..., 123, 124
view = discord.ui.View(*menus)
await ctx.send(view=view)
```

Also works normally. But if we combine them...
```py
await ctx.send(content, embeds=embeds, view=view)
```

This results in the bot hanging for a couple seconds, followed by your same error. This had a character count of around 8300, but if we change the numbers a little (pay attention to `str(x)`)...
```py
content = "a"*1000,
embeds = [discord.Embed(description="i"*500)]*6
menus = create_select_menus([str(x)*10 for x in range(125)])
```

This brings us down to ~6650 characters, but still gives the same error. If we remove embeds/contents and just send components, it's still possible to error:
```py
menus = create_select_menus([str(x)*20 for x in range(125)])
await ctx.send(view=View(*menus))
```

This is down to 5300 characters yet still errors - components add more to the json than embeds and regular content, so it's likely you need to reduce the scale you're working at in each message.
