### ISSUE TITLE
Pycord's docs have a typo

### ISSUE THREAD

**Issue by ImNimboss** [Pycord-Development/pycord#28]
### Summary

Pycord's docs say "discord.py" everywhere, not "pycord"

### What is the feature request for?

The documentation

### The Problem

Go to https://pycord.readthedocs.io/en/latest and observe how "discord.py" is written everywhere instead of pycord. Even the page title is "Welcome to discord.py"

### The Ideal Solution

Replace all "discord.py" instances with "pycord"

**Comment by MhmCats** [comment]
This is because pycord is a fork of discord.py and the documentation has not been updated accordingly. You are welcome to do this yourself though... the documentation lives in the `docs/` folder and in the docstrings of methods/classes.

**Comment by ImNimboss** [comment]
Yes, I thought so, thank you

**Comment by CodeWithSwastik** [comment]
The docs have already been updated, check [master](pycord.rtfd.org/en/master).

**Comment by Dorukyum** [comment]
The hyperlink in the message above is incorrect, [here](https://pycord.readthedocs.io/en/master/) are the docs for master.
