### ISSUE TITLE
Typo, it says "discord.py" instead of "pycord"

### ISSUE THREAD

**Issue by ImNimboss** [Pycord-Development/pycord#30]
### Summary

Under the "Exceptions" category of https://pycord.readthedocs.io/en/master/api.html#exceptions at discord.DiscordException, it says discord.py instead of pycord

### What is the feature request for?

The documentation

### The Problem

Under the Exceptions category of the docs @ https://pycord.readthedocs.io/en/master/api.html#exceptions ,
The description of discord.DiscordException says this:

> Base exception class for **discord.py**
> Ideally speaking, this could be caught to handle any exceptions raised from this library.

### The Ideal Solution

This should be changed to:

> Base exception class for **pycord**
> Ideally speaking, this could be caught to handle any exceptions raised from this library.

### Additional Context

I couldn't figure out how to change the files in the docs folder to fix the typo to do a PR, so I made this issue instead.

**Comment by BobDotCom** [comment]
you can make a fork and make a pull request from that

**Comment by ImNimboss** [comment]
@BobDotCom Yes that's fine, I just don't know where to edit the "docs" folder to fix the typo

**Comment by GreenDiscord** [comment]
Fixed by my pr, this can be closed!

**Comment by Dorukyum** [comment]
Closing this as it was done
