### ISSUE TITLE
Slash Cogs don't register in on_ready event

### ISSUE THREAD

**Issue by Hype3808** [Pycord-Development/pycord#300]
### Summary

Slash Cogs don't register in on_ready event, works outside on_ready event instead

### Reproduction Steps

load the slash cogs inside of `on_ready` event

### Expected Results

Slash command is working

### Actual Results

Slash command doesn't show

### Intents

discord.Intents.all

### System Information

py-cord v2.0.0a
python 3.9.7

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

You need to load the cog outside of `on_ready` event to make it work

**Comment by LouissXI** [comment]
Hi, how's it going? When do you think it will happen? Because for the moment I can't continue the development of my bot due to the fact that I use only cogs. I know it's hard to take back a library from A to Z, you have all my support but without discord.py and now pycord, how to do ?

**Comment by Hype3808** [comment]
> Hi, how's it going? When do you think it will happen? Because for the moment I can't continue the development of my bot due to the fact that I use only cogs. I know it's hard to take back a library from A to Z, you have all my support but without discord.py and now pycord, how to do ?

you could load the cogs outside of `on_ready` event, it will fix the problem....

**Comment by LouissXI** [comment]
> > Hi, how's it going? When do you think it will happen? Because for the moment I can't continue the development of my bot due to the fact that I use only cogs. I know it's hard to take back a library from A to Z, you have all my support but without discord.py and now pycord, how to do ?
> 
> 
> 
> you could load the cogs outside of `on_ready` event, it will fix the problem....

Thanks for the help !

**Comment by BobDotCom** [comment]
Will be fixed by #433.
