### ISSUE TITLE
Add support for text-in-voice

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#347]
# Text in Voice Support

## Description
This isn't out yet, but soon you can write in voice channels.
It's bound to the guild feature `TEXT_IN_VOICE_ENABLED`

### For users:
You have to be connected to the voice channel.
### For bots:
They can receive and write messages without being in the channel.

## How should this be implemented?
Just remove possible checks on the methods to send messages for channel type 2 `GUILD_VOICE`.
The channel type should be handled like a normal text channel.

**Comment by Dorukyum** [comment]
Added in #1231.
