### ISSUE TITLE
Make ctx.respond return the message sent

### ISSUE THREAD

**Issue by RealBongoChongo** [Pycord-Development/pycord#350]
### Summary

similar to ctx.send which returns the message that was sent

### What is the feature request for?

discord.ext.commands

### The Problem

Many people want to know how to get the message sent by ctx.respond so i think it would be something nice to have

### The Ideal Solution

really just make it similar how ctx.send returns the message

**Comment by nerdguyahmad** [comment]
This is not possible. Interaction messages are way different than actual messages.

**Comment by BobDotCom** [comment]
It could return the InteractionMessage

**Comment by krittick** [comment]
I think a better option may be to return the Interaction object itself, which can then use `edit_original_message` to accomplish this. I have this working locally and will submit a PR shortly for review.
