### ISSUE TITLE
[ApplicationCommands] New auditlog types & targets

### ISSUE THREAD

**Issue by Lulalaby** [Pycord-Development/pycord#351]
## TODO 1:
Implement the new audit log action `APPLICATION_COMMAND_PERMISSION_UPDATE`

 - New audit log action: APPLICATION_COMMAND_PERMISSION_UPDATE: 121
 - New audit log target type: APPLICATION_COMMAND

## TODO 2:
Implement channel permission

```
enum ApplicationCommandPermissionTypes {
    ROLE = 1,
    USER = 2,
    CHANNEL = 3,
}
```

**Comment by plun1331** [comment]
Implemented in https://github.com/Pycord-Development/pycord/commit/68752f149e60b02220a1c3fc1de50239bbb3fbfe
