### ISSUE TITLE
discord.User is not a valid input type for discord.commands.Option()

### ISSUE THREAD

**Issue by Apocryphon-X** [Pycord-Development/pycord#367]
### Summary

 Statement from @Lulalaby:
> Libs should be able to parse Option(discord.User) and make it Castable as member within the context of the current guild, If applicable.

### Reproduction Steps

- Pass a `discord.User` to the type argument in a `discord.commands.Option()`.

### Minimal Reproducible Code

```python
import discord
...
discord.commands.Option(discord.User)
```

### Expected Results

Get a user object similar to the `discord.Member` class.

### Actual Results

```
Traceback (most recent call last):
  File "C:\Dev\Projects\bot.py", line 75, in <module>
    discord.commands.Option(discord.User)
  File "C:\Users\mendo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\commands.py", line 564, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "C:\Users\mendo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\enums.py", line 659, in from_datatype
    raise TypeError(f'Invalid class {datatype} used as an input type for an Option')
TypeError: Invalid class <class 'discord.user.User'> used as an input type for an Option
```

### Intents

Im not using intents.

### System Information

```
- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4214+g5a23a46
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000
```
(Actually, Windows 11 10.0.22000)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I was trying to make a Slash command with an `Option(discord.Member)` argument and it worked perfectly, except when someone called the command from the bot DM's. 

Since it is a DM and there is no guild, the `Option()` class can not use the `get_member()` method from a NoneType. I tried to implement the @Lulalaby idea of using a `discord.User` instead and if the slash command was called from a guild, then get the discord.Member trough the user ID.

**Comment by UP929312** [comment]
![image](https://user-images.githubusercontent.com/36114463/139741658-75735c1a-4613-4551-b733-dcb59c56b327.png)

It appears it does support users

**Comment by UP929312** [comment]
Seems like someone forgot the case for user, because the rest appear to have cases but can't find one for user

**Comment by UP929312** [comment]
https://github.com/Pycord-Development/pycord/commit/e01739d597eda10556c71f4653021c707e3549d3

Could be the required change for this to be fixed

**Comment by Apocryphon-X** [comment]
If this helps, here is an example of the data retrieved by the slash interaction.
```json
{
    "id": "904771131771351040",
    "name": "example",
    "options": [
        {
            "name": "member",
            "type": 6,
            "value": "229764530354388992"
        }
    ],
    "resolved": {
        "users": {
            "229764530354388992": {
                "avatar": "f51f64e4d2e9af8f3164ccafdfe48b78",
                "discriminator": "8282",
                "id": "229764530354388992",
                "public_flags": 128,
                "username": "Apocryphon"
            }
        }
    },
    "type": 1
}
```

**Comment by Lulalaby** [comment]
Fixed

**Comment by BobDotCom** [comment]
Why was this reopened?

**Comment by Lulalaby** [comment]
Because it's kinda not resolved

**Comment by Apocryphon-X** [comment]
> Why was this reopened?

Because `discord.commands.Option()` is actually not able to parse a `discord.User` argument - i.e: [Slash invocation from a DM](https://www.toptal.com/developers/hastebin/okoxexixep.coffeescript) with `Option(discord.User)` as required option.

**Comment by Apocryphon-X** [comment]
Looks like the exception is being launched by this [line](https://github.com/Pycord-Development/pycord/blob/master/discord/commands/commands.py#L508).

```py
508                arg = await get_or_fetch(ctx.guild, name, int(arg), default=int(arg))
-------------------------------------------------^
When invoked from a DM, ctx.guild is `None`
```

**Comment by Lulalaby** [comment]
Seems we need a null check here.
Would you like to open a PR and fix that @Apocryphon-X

**Comment by Apocryphon-X** [comment]
Sure, let me try

**Comment by Lulalaby** [comment]
More detailed:

It needs to be implemented that if guild is null, that a user fetch will be made instead
