### ISSUE TITLE
Group Commands in cog

### ISSUE THREAD

**Issue by Floo1337** [Pycord-Development/pycord#372]
### Summary

add grouping in cogs 

### What is the feature request for?

The core library

### The Problem

Grouping is possible in Bot.py (where the bot is launched) but not in cogs even tho grouping is especially important for big bots which most of use cogs

### The Ideal Solution

Add Groups in Cogs (sorry dont know much technical)

**Comment by Lulalaby** [comment]
This is already worked one

**Comment by Floo1337** [comment]
okay, thanks! appreicate 

how can i keep up to date and get to know when it works?

**Comment by Lulalaby** [comment]
> how can i keep up to date and get to know when it works?

Join our server! ❤️ 
https://discord.gg/pycord
