### ISSUE TITLE
Fetching Voice Members Fails

### ISSUE THREAD

**Issue by Space-Turtle0** [Pycord-Development/pycord#384]
### Summary

Fetching Voice Members Fails

### Reproduction Steps

Simply fetching a VoiceChannel and then attempting to do something with `discord.VoiceChannel.members` returns a funky error (internal error). The channel is fetched properly and when printing out `VoiceChannel` in the code snippet provided below, I get my channel's name back. 

### Minimal Reproducible Code

```python
@tasks.loop(seconds = 60)
async def PRIVVC_DELETION_QUEUE(self):
    for VC in database.PrivVCQueue:
        VoiceChannel: discord.VoiceChannel = await self.bot.fetch_channel(VC.ChannelID)
        if len(VoiceChannel.members) != 0:
              VC.delete_instance()
              await VoiceChannel.delete()
```

### Expected Results

The function should interpret `len(VoiceChannel.members)` and either delete the VC & Entry or move on based on that information.

### Actual Results

```py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/Users/space/Documents/GitHub/Timmy-SchoolSimplified/utils/bots/TutorVC/cogs/vcUpdateNEW.py", line 399, in PRIVVC_DELETION_QUEUE
    if len(VoiceChannel.members) != 0:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/channel.py", line 837, in members
    for user_id, state in self.guild._voice_states.items():
AttributeError: 'Object' object has no attribute '_voice_states'
```

I get this internal traceback instead. 

### Intents

discord.Intents.all()

### System Information

```bash
- Python v3.9.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4293+g416f97c
- aiohttp v3.6.2
- system info: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
I've added the `feature` label because it could be that it relates to a new thing in discord.

I'm gonna investigate this myself.

**Comment by zeffo** [comment]
Hi, could you ensure you have Guild intents enabled and then see if it crashes?

**Comment by Space-Turtle0** [comment]
Yeah my bot is subscribed to all the available intents.

**Comment by plun1331** [comment]
@Lulalaby any news on this?

**Comment by Lulalaby** [comment]
Can not repro
