### ISSUE TITLE
on_application_command_error can't catch custom exception

### ISSUE THREAD

**Issue by Asherlam** [Pycord-Development/pycord#402]
### Summary

on_application_command_error can't catch custom exception

### Reproduction Steps

![image](https://user-images.githubusercontent.com/35485292/140495413-cb8f4b52-ec6b-49c1-aade-aab9d1dbfa30.png)

### Expected Results

it should catch my custom error and print something I want.

### Actual Results

it just returns the error

### Intents

default, members

### System Information

Python Version: 3.9.6
Pycord Version: 2.0.0a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by CodeWithSwastik** [comment]
It is most likely an `ApplicationCommandInvokeError`, you need to access its `.original` attribute to catch the original error.

**Comment by Asherlam** [comment]
i think `ApplicationCommandInvokeError` is not exits
