### ISSUE TITLE
Add a method to define command options dynamically and update them

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#403]
### Summary

Add a method to define command options dynamically and update them

### What is the feature request for?

The core library

### The Problem

Currently, you define the command options by using type hinting in the callback. There are also use cases that require either defining new commands during runtime or updating them.,

### The Ideal Solution

For defining the options:
```py
example_command = discord.SlashCommand(..., options=[discord.Option(...)])
bot.add_application_command(example_command)
```

For updating the options:
```py
example_command.options.append(discord.Option(...))
bot.sync_commands()
```

### The Current Solution

none

**Comment by Lulalaby** [comment]
This is not intended by discord.
Use autocomplete instead.
