### ISSUE TITLE
Wrong URL to the documentation from the website

### ISSUE THREAD

**Issue by CallMePixelMan** [Pycord-Development/pycord#405]
### Summary

The Documentation tab on the website brings to an outdated documentation

### Reproduction Steps

- Go to the [website](https://pycord.dev/).
- Click on the Documentation tab, in the top left corner. (or click [here](https://docs.pycord.dev/) to get redirected)
- That's all, you're on the wrong documentation,

### Expected Results

The current documentation (https://docs.pycord.dev/en/master/)

### Actual Results

Old documentation (https://docs.pycord.dev/en/latest/), the header is "Welcome to discord.py", nothing about the `discord.ui`, slash_commands, etc.  
This is just the old discord.py documentation.

### Intents

This isn't a bug about the library.

### System Information

This isn't a bug about the library.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
It redirects to latest docs.

**Comment by Lulalaby** [comment]
This is intented

**Comment by CallMePixelMan** [comment]
> 
> 
> It redirects to latest docs.

Why isn't this the same link than in the #links channel on the discord server then ?

**Comment by Dorukyum** [comment]
We get a lot of questions about master development so we shared master docs there.

**Comment by Lulalaby** [comment]
and for the pypi version it's still correct.
we've added the master link on places which involves the github version
