### ISSUE TITLE
discord.Member.avatar_url 

### ISSUE THREAD

**Issue by Root-Time** [Pycord-Development/pycord#407]
### Summary

Can we get the discord.Member.avatar_url back? 

### What is the feature request for?

The core library

### The Problem

I need the url of a User avatar for Example for the discord.Embed().set_author(...)
or for embed picture linking

### The Ideal Solution

add avatar_url parameter for the discord.Member

**Comment by Lulalaby** [comment]
öpö

**Comment by Lulalaby** [comment]
lol

**Comment by Lulalaby** [comment]
No

**Comment by CodeWithSwastik** [comment]
Please use `Member.avatar.url` or `Member.display_avatar.url`

**Comment by timmypidashev** [comment]
This genuinely sucks, and there is no clear documentation on this issue.

**Comment by Lulalaby** [comment]
Why should there be any documentation?

Visit the docs, insert avatar in the search bar, boom, you get avatar.url.

People should learn how to use docs.
