### ISSUE TITLE
if message.author.id == self.user.id # type: ignore Attribute Error

### ISSUE THREAD

**Issue by iamuRon** [Pycord-Development/pycord#418]
### Summary

Error after trying to run a simple cog "ping" command

### Reproduction Steps

I think the issue stems from reading/writing to text files but im not entirely sure since ive yet to understand how self.user.id's value type got set to 'ignore' when its spitting out values in print functions.

### Minimal Reproducible Code

```python
@bot.event
    async def on_message(self, message):
        context = [f"Server: {message.author.guild} -> Channel: {message.channel} ->  User: {message.author} | {message.created_at} : {message.content}"]
        msg_count =+ 1
        with open("chatlog.txt", 'a') as chatlog:
            chatlog.write(f"{context}\n")
        chatlog.close()
        check = database_read()
        user = message.author
        if str(user) not in check:
            database_write(user)
        await bot.process_commands(message)
```

### Expected Results

I expected no errors and for my on_message event to recognize a prefix command

### Actual Results

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\Trump V2\Desktop\Coding and Websites\Python SHit\Discord Bot\RaiseBOT.py", line 59, in on_message
    await bot.process_commands(message)
  File "C:\Python\lib\site-packages\discord\ext\commands\bot.py", line 918, in process_commands
    ctx = await self.get_context(message)
  File "C:\Python\lib\site-packages\discord\ext\commands\bot.py", line 825, in get_context
    if message.author.id == self.user.id:  # type: ignore
AttributeError: 'NoneType' object has no attribute 'id'

### Intents

Im not entirely sure but I just tried to make a basic bot so nothing crazy

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4341+g5bee7e3
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I have a github repo for this issue and you can find the full source code here:
https://github.com/iamuRon/Pycord
I did remove my token for obvious reasons

**Comment by BobDotCom** [comment]
> ### Intents
> 
> Im not entirely sure but I just tried to make a basic bot so nothing crazy

There's your problem. Take a look at [the docs for intents](https://docs.pycord.dev/en/master/intents.html).
