### ISSUE TITLE
Add a Dropdown menu role selection example

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#434]
### Summary

Provide an example like button roles, but using dropdown menus

### What is the feature request for?

The documentation

### The Problem

I'm not sure how to have persistent dropdown menus

### The Ideal Solution

Provide an example of having role selection using dropdown menus

**Comment by Dorukyum** [comment]
Can't you use the dropdown example and make it add roles?

**Comment by timmypidashev** [comment]
@KosmicAnomaly What exactly are you asking for here, `persistent dropdown menus` or `dropdown menus with roles`, or both?

**Comment by Lulalaby** [comment]
Closing this.
We have:
- https://github.com/Pycord-Development/pycord/blob/master/examples/interactionsBot/cogs/dropdown_cog.py
- https://github.com/Pycord-Development/pycord/blob/master/examples/views/dropdown.py

Feel free to add examples via pr yourself, but we won't focus on that

**Comment by timmypidashev** [comment]
eyyy ty
