### ISSUE TITLE
Redesign ApplicationContext.respond

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#438]
### Summary

The ApplicationContext.respond property needs to be redesigned.

### What is the feature request for?

The core library

### The Problem

The `ApplicationContext.respond` property  returns 2 different functions depending on `InteractionResponse.is_done()`. Both take different parameters and return different objects. This is bad practice because it can result in unexpected behavior. Also, type-hinting is kinda hard. 

### The Ideal Solution

It might make sense to create a function `ApplicationContext.respond` that merges all parameters. Depending on `InteractionResponse.is_done()` it ignores the parameter of the other function. The only remaining problem is the different return types. This would simplify the situation, but isn't perfect yet. Maybe someone got a better idea.

### The Current Solution

A property that returns 2 different functions depending on `InteractionResponse.is_done()`.

**Comment by BobDotCom** [comment]
We could make `ctx.respond` only invoke `ctx.interaction.response.send_message`, and `ctx.followup` would be for the followup messages. We could make some other method that implements the current functionality of `ctx.respond`.
