### ISSUE TITLE
@is_owner() restricts the command, even to the bot owner

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#447]
### Summary

Owners aren't allowed to use slash commands that are blocked behind @is_owner()

### Reproduction Steps

Used the @is_owner() check

### Expected Results

Allow me to use the command, and nobody else

### Actual Results

Nobody can use the command, not even me

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4338+g7e4ce97
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by pratheek78** [comment]
show the owners variable which is in your main file

**Comment by KosmicAnomaly** [comment]
> show the owners variable which is in your main file

I shouldn't need to assign it, because it is retrieved automatically
[https://docs.pycord.dev/en/master/ext/commands/api.html?highlight=is_owner#discord.ext.commands.Bot.is_owner](is_owner)

**Comment by CodeWithSwastik** [comment]
`is_owner` works fine for me, can you confirm that you actually are the owner of the bot 🤔

**Comment by zeffo** [comment]
No repro my side

**Comment by pratheek78** [comment]
the owners variable needs to be an integer, not a string. if you dont have the variable, add it in the main file and also in the client variable

**Comment by f4b14n-d** [comment]
I am getting the same issue. Even when I have my ID in the owner_id in my bot's init

**Comment by AmirAvram** [comment]
I've encountered it as well, the documentation says that you shouldn't define the bot owner and it will retrieve it automatically but only when I've manually assigned myself on constructor of the bot it worked.

**Comment by Dorukyum** [comment]
> I shouldn't need to assign it, because it is retrieved automatically [is_owner](https://docs.pycord.dev/en/master/ext/commands/api.html?highlight=is_owner#discord.ext.commands.Bot.is_owner)

That's the wrong method/documentation. The method you showed is used like this: `await bot.is_owner(user)`
