### ISSUE TITLE
Adding "Watch Together" Or YouTube API Support

### ISSUE THREAD

**Issue by VincentRPS** [Pycord-Development/pycord#448]
### Summary

The New "Watch Together" Feature Syncing The Discord API With The YouTube API

### What is the feature request for?

The core library

### The Problem

Making using the "Watch Together" Feature On pycord Easier and safer then installing random plugins and hoping it works

### The Ideal Solution

imo It should be set onto on_ready close to discord-togethers way of doing it

```py
@bot.event
async def on_ready():
    bot.watch = await YouTube("BOT_TOKEN")
    print('Bot is online!')
```
Then It would send the invite link to youtube via a command which could go like

```py
@bot.command()
async def watch(ctx):
    link = await bot.watch.make_link(ctx.author.voice.channel.id, 'youtube')
    await ctx.send(f"Your Watch Together Link\n{link}")
```

This is 
1 particularly how i would want to make it 
2 somewhat based off what discord-together is designed

**Comment by Dorukyum** [comment]
This has already been done and was made easier with #128.
