### ISSUE TITLE
Add support between application commands and normal commands in `commands.Bot`

### ISSUE THREAD

**Issue by BobDotCom** [Pycord-Development/pycord#451]
A compatibility layer proposed by @BobDotCom

**Comment by TheReaper62** [comment]
Can you further elaborate on what support means, cos I don't seem to be getting where you're coming from?

**Comment by timmypidashev** [comment]
I think what he means is slash-commands and message commands can be synchronized together... Not completely sure but that would be pretty neat

**Comment by timmypidashev** [comment]
This is probably a library abstraction proposal though. Instead of having two distinct command-types in bot.py, a single type would do all the work.
