### ISSUE TITLE
Add categories for event reference (docs)

### ISSUE THREAD

**Issue by Sengolda** [Pycord-Development/pycord#455]
### Summary

Put events in sub-categories in the event-reference in `api.html`

### What is the feature request for?

The documentation

### The Problem

It's kind of hard not knowing which events fall in which categories, I feel it would be easier if they were in sub-categories.

### The Ideal Solution

Make subcategories for each type of events like `Roles`, `Messages`, etc

Like

```rst
Event Reference
---------------------------

Message Event Reference
~~~~~~~~~~~~~~~

.. autofunction:: on_message
.. autofunction:: on_message_delete
.. autofunction:: on_message_edit
```

**Comment by UP929312** [comment]
Would love to see this added, it's been something I've been thinking about for a while

**Comment by zeffo** [comment]
Good idea Seng00lda

**Comment by dtrm-thil** [comment]
cover foto is will be added

**Comment by TheReaper62** [comment]
How about events that are related to message but doesn't return message as a parameter.
Example: discord.on_raw_bulk_message_delete(payload)
Which is a message-related function but returns payload.
Where would you categorise this

**Comment by zeffo** [comment]
I would put it in the Message Event reference, as well as a separate category for raw events

**Comment by Akashdeep122** [comment]
What if we could do message Event / raw Event reference and mention them all in same?

**Comment by hi-im-morgan** [comment]
Is this still open? If so, how should it be documented?
