### ISSUE TITLE
Access to `bot` in AutocompleteContext

### ISSUE THREAD

**Issue by SlimShadyIAm** [Pycord-Development/pycord#459]
### Summary

In `AutocompleteContext` it's currently not possible to access `bot`. This would add a lot of functionality to autocomplete.

### What is the feature request for?

The core library

### The Problem

AutocompleteContext doesn't have a `bot` attribute. In my use case, I wanted to get a list of commands for which I need to loop through the cogs. Another possibility is when users add their database as an attribute to `bot`, so they would be able to access the database in their autocomplete callback.

### The Ideal Solution

Add the attribute to `AutocompleteContext`.

### The Current Solution

A dumb workaround for now could be to use `bot` as a global variable.

```py
BOT_GLOBAL = None


async def commands_list(ctx: AutocompleteContext):
    print(BOT_GLOBAL)


class Utilities(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        global BOT_GLOBAL
        BOT_GLOBAL = bot
```

**Comment by NoPlagiarism** [comment]
>  use bot as a global variable.

Not necessary, if you use cog and it has attribute bot:
`AutocompleteContext.cog.bot`
But implementing `AutocompleteContext.bot` still will come in handy

**Comment by CodeWithSwastik** [comment]
I think https://github.com/Pycord-Development/pycord/commit/16e7aff696f5541040b71722f31971336dd5fad2 solves this

**Comment by SlimShadyIAm** [comment]
Yes that solves it, thanks!
