### ISSUE TITLE
Broken commands within cogs. (Both slash and normal, alongside)

### ISSUE THREAD

**Issue by mxze16** [Pycord-Development/pycord#463]
### Summary

Cog slash commands/standard commands breakage.

### Reproduction Steps

First: Create a command inside of a cog that is both a slash command and a normal command. Example. '@commands.command' and '@slash_command'.

Second: Create another standard command just to ensure it isn't a broken cog.

Third: Make sure you have a functioning bot for said cog.

Fourth: Run and test. Keep in mind I haven't done much testing myself. I just know this is my scenario. Cogs work fine, it's just the commands with slash commands alongside them. (Two separate commands, one for slash, one normal, both written pretty much with no differences.)

### Minimal Reproducible Code

```python
@commands.command(description='Test')
async def test(self, ctx):
   await ctx.send('lol')

@slash_command(description='Test')
async def test(self, ctx):
   await ctx.send('lol')

@commands.command(description='Should work.')
async def work(self, ctx):
   await ctx.send('works')
```

### Expected Results

The slash commands should register, the normal command with the slash command should also register. Nothing should seem broken, command should be able to be used.

### Actual Results

Project acts as if the two commands don't exist. You try to use them and it tells you it doesn't exist. Other commands work that don't have slash command brothers. 

### Intents

discord.Intents.all

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4408+g3d16786
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Not sure if this is a broken install. But this is both on my server and on my local machine.

**Comment by NoPlagiarism** [comment]
Try to use other names of functions and give name of command in decorator

**Comment by mxze16** [comment]
> Try to use other names of functions and give name of command in decorator

I'll be sure to look into that. Regardless shouldn't be an issue.
