### ISSUE TITLE
React on respond messages

### ISSUE THREAD

**Issue by mcbabo** [Pycord-Development/pycord#466]
### Summary

You can't react on respond messages from slash commands

### What is the feature request for?

The core library

### The Problem

You can't react on respond messages from slash commands

### The Ideal Solution
```py
embed = await ctx.respond(embed=embed)
await embed.add_reaction("1️⃣")
```
### The Current Solution

None

**Comment by JDJGInc** [comment]
🤔 I am going to ask the discord api developers guild if it's possible on discord's side.

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/142071661-9c7ad9e8-be22-4f4b-b859-69ccd53969ae.png)
so, What is the ctx.respond thing?
oh do you want embed to return a message object so you can add a reaction?

**Comment by krittick** [comment]
This seems to work fine as long as the original message isn't deferred: 

```py
interaction = await ctx.respond(content)
orig = await interaction.original_message()
await orig.add_reaction("🤩")
```

![image](https://user-images.githubusercontent.com/935885/142071698-a71e17c3-c3d4-46d0-8f03-51a2de92f1ff.png)

Or am I missing what you're asking for?

**Comment by krittick** [comment]
@mcbabo Upon further testing, this already works fine in both scenarios as long as you get the right object for deferred/non-deferred `ctx.respond`:

**Deferred (reaction is on `WebhookMessage`):**
```py
await ctx.defer()
interaction = await ctx.respond(content)
await interaction.add_reaction("🤩")
```
**Non-deferred (reaction is on `InteractionMessage`:**
```py
interaction = await ctx.respond(content)
orig = await interaction.original_message()
await orig.add_reaction("🤩")
```

**Comment by dtrm-thil** [comment]
ok.

**Comment by mcbabo** [comment]
thank you for your help. On the Pycord Server it was said that it would not work.
