### ISSUE TITLE
> Stalking

### ISSUE THREAD

**Issue by dtrm-thil** [Pycord-Development/pycord#467]
> 
> 
> @Lulalaby Add cover foto because discord may code it to the api anytime.

Stop stalking..

_Originally posted by @Lulalaby in https://github.com/Pycord-Development/pycord/issues/211#issuecomment-969488407_

**Comment by dtrm-thil** [comment]
this is not stalking. you have public githubs on your profile.

**Comment by Middledot** [comment]
??

**Comment by Lulalaby** [comment]
God damn it
