### ISSUE TITLE
Sharded Bot with commands.bot

### ISSUE THREAD

**Issue by Marcel-73** [Pycord-Development/pycord#473]
### Summary

Add an option shards= in the normal commands.bot

### What is the feature request for?

discord.ext.commands

### The Problem

Normal you must use commands. AutoShardedClient or sth else to run this but it would be better if it can be used by commands.bot

### The Ideal Solution

commands.bot(shards=8) option

### The Current Solution

you must use commands. AutoShardedClient

**Comment by Lulalaby** [comment]
It is better to use auto sharding ^^
I don't think we would add this now.
Maybe some day
