### ISSUE TITLE
Example: Embed previously-sent message

### ISSUE THREAD

**Issue by DaveWK** [Pycord-Development/pycord#479]
### Summary

Add an example bot that sends a message previously sent by a user

### What is the feature request for?

The documentation

### The Problem

How does the bot send a message previously sent by another user including a jump_url to the message? It is unclear from the documentation if this is considered an "embed" for the message or something else.

### The Ideal Solution

An ideal example would be:
Bot listens for messages with an emoji react, when it sees a specific message is sent in a channel (ie `!show_messages`) it posts all of the old messages it recorded which had the emoji react, including the actual message and a jump link to the original message.

a basic example would be:
given a jump_url, how does the bot create a new message that contains the (embedded?) actual old discord message and not just a link

**Comment by Lulalaby** [comment]
We only add examples for basic operations.
This would count as extended operation and should maybe be done volunteer.

**Comment by Lulalaby** [comment]
But still feel free to add it tho.
But we don't plan this.
It's not in scope.

**Comment by DaveWK** [comment]
thanks; I think the core question is: if I want the bot to send an old message sent by a user, and not just a jump_url, is that an "embed"? if so, what should the description be?

**Comment by Lulalaby** [comment]
it is not really a embed.
you can quote the message in the embed tho.
You just resend the message object of the users message
