### ISSUE TITLE
SlashCommandOptionType not support Thread class

### ISSUE THREAD

**Issue by S0ltero** [Pycord-Development/pycord#480]
### Summary

SlashCommandOptionType not support Thread class

### Reproduction Steps

Set `discord.Thread` as `input_type` in `Option`

### Minimal Reproducible Code

```python
@slash_command(name="Test")
async def test(ctx, channel: Option(discord.Thread)):
    print("Test")
```

### Expected Results

Can show only `Thread` channel, or `Thread` with `TextChannel` channels

### Actual Results

TypeError: Invalid class <class 'discord.threads.Thread'> used as an input type for an Option

### Intents

all

### System Information

- Python v3.9.5-final 
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4409+g16e7aff6
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Well this is basically because a thread is not a real channel.

**Comment by BobDotCom** [comment]
@Lulalaby is this supported on the API? I don't recall seeing this in the API docs.

**Comment by nerdguyahmad** [comment]
https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure
https://discord.com/developers/docs/resources/channel#channel-object-channel-types
@BobDotCom 

![image](https://user-images.githubusercontent.com/54180221/142737599-84ba56e4-414b-47c4-b598-5ba9577e3d17.png)

**Comment by Lulalaby** [comment]
^ this
