### ISSUE TITLE
Add Support for Special Types

### ISSUE THREAD

**Issue by pandabear189** [Pycord-Development/pycord#486]
### Summary

Adding support for typing.Union... Optional and other types for `input_value`

### What is the feature request for?

discord.ext.commands

### The Problem

Using typing is very convenient and when I have to use other methods it becomes annoying. For example with parameters in slash commands, it would be easier to just do `param: typing.Optional[str]` instead of required = False. Reason 2, Union types allow for easy converting, for example, a command that downloads an image from some discord target, with the current input_value restrictions it would be very hard to do but with typing.Union[discord.User, discord.Guild] ... I understand this would make it impossible to display a type hint on the client side but it would be converting in code easier. 

### The Ideal Solution

Add support for special types in `input_value` 

### The Current Solution

Add support for special types in `input_value`

**Comment by CodeWithSwastik** [comment]
You can already do `param: typing.Optional[str]`

**Comment by pandabear189** [comment]
what about in `param: Option(Optional[str], desc...)` or `param: Option(Union[discord.Member, discord.User], desc...)`

**Comment by pandabear189** [comment]
seems to throw this error
```
  File "C:\Users\\PycharmProjects\bot\cogs\mod.py", line 18, in <module>
    class Moderation(commands.Cog):
  File "C:\Users\\PycharmProjects\bot\cogs\mod.py", line 116, in Moderation
    delay: Option(Optional[int],
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\commands.py", line 618, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\enums.py", line 643, in from_datatype
    if issubclass(datatype, str):
TypeError: issubclass() arg 1 must be a class
```

**Comment by pandabear189** [comment]
Maybe making `input_type` an optional parameter and default to string. so that you can use `param: special_type = Option(description="...")`
