### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by thegame4craft** [Pycord-Development/pycord#492]
### Summary

discord.Bot() not found

### Reproduction Steps

Copy one of the examples with discord.Bot() in a file and run it with the latest pypi version. 

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot()

@bot.slash_command(guild_ids=[...])  # create a slash command for the supplied guilds
async def hello(ctx):
    """Say hello to the bot"""  # the command description can be supplied as the docstring
    await ctx.respond(f"Hello {ctx.author}!")


@bot.slash_command(
    name="hi"
)  # Not passing in guild_ids creates a global slash command (might take an hour to register)
async def global_command(ctx, num: int):  # Takes one integer parameter
    await ctx.respond(f"This is a global command, {num}!")


@bot.slash_command(guild_ids=[...])
async def joined(
        ctx, member: discord.Member = None
):  # Passing a default value makes the argument optional
    user = member or ctx.author
    await ctx.respond(f"{user.name} joined at {discord.utils.format_dt(user.joined_at)}")


# To learn how to add descriptions and choices to options, check slash_options.py
bot.run("****")
```

### Expected Results

Python should find the class Bot and starts the bot.

### Actual Results

Python doesn't finds the class bot and chrashes. My Traceback:
```
Traceback (most recent call last):
  File "C:\Users\Robin\projects\Gamesrapid\python\pingUtil\bot.py", line 3, in <module>
    bot = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'
```

### Intents

Nothing

### System Information

- Python v3.9.6-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
You're running discord.py 1.7.3, not py-cord 2.0.0a.
Install using `pip install git+https://github.com/Pycord-Development/pycord`.
