### ISSUE TITLE
@slash_command missing documentation

### ISSUE THREAD

**Issue by MilimTheTrueOne** [Pycord-Development/pycord#494]
### Summary

the @slash_command decorator is missing documentation

### What is the feature request for?

The documentation

### The Problem

No one can look up how to use @slash_command easily 

### The Ideal Solution

Add documentation for @slash_command

### The Current Solution

There is no proper documentation for @slash_command

**Comment by Lulalaby** [comment]
Dup and already wip

**Comment by MilimTheTrueOne** [comment]
could not find it sorry
