### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by PythonIntermediateCoder** [Pycord-Development/pycord#498]
### Summary

Slash commands should be unregistered when the bot closes, and re-registers when the bot is on

### Reproduction Steps

- Make a slash command
- Close the bot
- The slash command still remains, but not working, as it should not be

### Minimal Reproducible Code

```python
@bot.slash_command(...)
async def slash_command(ctx):
    ...

bot.run() # start the bot
# close the bot
# slash_command is still there but not working
```

### Expected Results

Slash command should be removed when the bot closes or when its code gets removed

### Actual Results

The slash command still remains, even if you close the bot, or remove the code

### Intents

discord.Intents.all()

### System Information

- Python v3.8.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4448+ge00b272d
- aiohttp v3.8.1
- system info: Linux 3.10.72 #1 SMP PREEMPT Mon Mar 27 10:50:45 CST 2017

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

As What should have been done, all slash commands in a bot should be unregistered in

**Comment by Lulalaby** [comment]
Nope that's not how it works.
Discord has its own limits for these operations.
Don't close the bot. Problem solved.

**Comment by PythonIntermediateCoder** [comment]
How could i unregister the slash commands?

**Comment by Dorukyum** [comment]
Removing them from the code and running the command registering method (currently `.register_commands`) would unregister them.

**Comment by PythonIntermediateCoder** [comment]
It looks that I have overriden `on_connect` method so that coroutine will not be called. Calling it into the on_connect fixed my issue.

**Comment by Lulalaby** [comment]
Perfect!
