### ISSUE TITLE
Slash commands don't work in cogs

### ISSUE THREAD

**Issue by FameBtw** [Pycord-Development/pycord#500]
### Summary

Slash Commands

### Reproduction Steps

Cog loading but slash commends written in it don't work

### Minimal Reproducible Code

```python
from discord.ext import commands
from discord.commands import slash_command

class Example(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
 
    @slash_command(guild_ids=[880349000627273819]
    async def h(self, ctx):
        await ctx.respond("Hi, this is a slash command from a cog!")
    

    @slash_command()
    async def hill(self, ctx):
        await ctx.respond(f"Hi, this is a global slash command from a cog!")

def setup(bot):
    bot.add_cog(Example(bot))
```

### Expected Results

?

### Actual Results

slash commands made in cogs are not logged

### Intents

nothing

### System Information

Master branch

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by HarryPotter12352** [comment]
Are you sure that you have the `applications.commands` scope

**Comment by Lulalaby** [comment]
Closing as invalid.
Make sure yourself familiar with python first.
