### ISSUE TITLE
A guild object returned as None

### ISSUE THREAD

**Issue by yAmIZErO31** [Pycord-Development/pycord#501]
### Summary

A guild object returned as None

### Reproduction Steps

So i have my public bot and was checking the servers it is in like i usually do, the command shows the server name, member count and server owner in this format `"{guild.name} - {len(guild.members)} - {guild.owner.name}"`. Recently i encountered an error saying that `NoneType has no attributes to name` which is weird because it was working before normally so i did some changes to pass the error and see what's the problem and to my surprise it showed this (image below)
![Screenshot 2021-11-24 215911](https://user-images.githubusercontent.com/62690188/143310597-10af3d47-9a46-42ba-a0e9-96f6dc5f3310.png)
 now i tried to do some experiments like trying other attributes and the `id` attribute worked, so i tried to fetch the guild with `client.fetch_guild()` and tried the same attributes from before, the result is below 
![Screenshot 2021-11-24 222554](https://user-images.githubusercontent.com/62690188/143310779-9453a6b9-5234-4bd0-9f7e-3b15453bfb22.png)
To my surprise, this server was shown in previous messages (probably a day before the bug) and it was shown normally without any signs of bugs (image below)
![Screenshot 2021-11-24 222613](https://user-images.githubusercontent.com/62690188/143310884-579e8cae-c8ee-4b95-9a19-0f6626c3c6a5.png)

### Minimal Reproducible Code

```python
@client.command()
async def servers(ctx):
    modRole = False
    for roleID in modRoles:
        role = get(ctx.guild.roles, id=roleID)
        if role is not None:
            modRole = True
    if modRole is False and ctx.author.id not in authors:
        return
    text = ""
    for guild in client.guilds:
        if guild is None:
            text += f"Unknown Server????\n"
        else:
            if guild.owner is None:
                text += f"{guild.name} - {len(guild.member_count)} - {guild.owner}\n"
            else:
                text += f"{guild.name} - {len(guild.members)} - {guild.owner.name}\n"
    if len(text) <= 2048:
        embed = Embed(title=f"Total Count: {len(client.guilds)} server(s)",
                      description=text,
                      color=random_color())
        await ctx.send(embed=embed)
        return
    embed = Embed(title=f"Total Count: {len(client.guilds)} server(s)", color=random_color())
    await ctx.send(embed=embed)
    return
```

### Expected Results

it is expected to show like the image below 
![Screenshot 2021-11-24 222613](https://user-images.githubusercontent.com/62690188/143311042-8f7e8027-3ee4-4080-aed5-93d42d37d213.png)

### Actual Results

at first it was 
![Screenshot 2021-11-24 215911](https://user-images.githubusercontent.com/62690188/143311074-d9f6da0e-2801-4f24-9679-dc6a6e75a25c.png)
Then it became after trying `fetch_guild`
![Screenshot 2021-11-24 222554](https://user-images.githubusercontent.com/62690188/143311099-3775961f-1610-43d7-b277-3dd2913d36bc.png)

### Intents

discord.Intents.all()

### System Information

```Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "J:\PycharmProjects\MyWorkProjects\work\pycord\discord\__main__.py", line 300, in <module>
    main()
  File "J:\PycharmProjects\MyWorkProjects\work\pycord\discord\__main__.py", line 297, in main
    args.func(parser, args)
  File "J:\PycharmProjects\MyWorkProjects\work\pycord\discord\__main__.py", line 52, in core
    show_version()
  File "J:\PycharmProjects\MyWorkProjects\work\pycord\discord\__main__.py", line 41, in show_version
    pkg = pkg_resources.get_distribution('pycord')
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pkg_resources\__init__.py", line 480, in get_distribution
    dist = get_provider(dist)
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pkg_resources\__init__.py", line 356, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pkg_resources\__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "J:\PycharmProjects\MyWorkProjects\work\.venv\lib\site-packages\pkg_resources\__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycord' distribution was not found and is required by the application
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JDJGInc** [comment]
Discord's guild cache is sometimes a bit strange.

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/143383650-f05ae39c-c170-4cff-982c-356a5addcb80.png)
for example this:

**Comment by JDJGInc** [comment]
![image](https://user-images.githubusercontent.com/22802640/143383687-18f90c75-95b8-4b7e-9f51-888d58f4d394.png)
Yes this is real.

**Comment by JDJGInc** [comment]
This is a discord issue.

**Comment by Lulalaby** [comment]
> This is a discord issue.

Its not ^^
Probably a caching issue.
