### ISSUE TITLE
README uploaded to PyPI still links to discord.py

### ISSUE THREAD

**Issue by honzajavorek** [Pycord-Development/pycord#502]
### Summary

The page https://pypi.org/project/py-cord/ links to discord.py and e.g. the discord.py Discord server, etc. It also contains wrong installation instructions.

### Reproduction Steps

Go to https://pypi.org/project/py-cord/ and read text, click links.

### Expected Results

The text and links are updated to reflect the changes made with the fork.

### Actual Results

Aaaaa! :) The actual results are... that the text and the links are outdated from before-fork times.

### Intents

N/A

### System Information

N/A

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Thanks, but we know that already.
We decided to wait for the 2.0. release to update pypi.
