### ISSUE TITLE
Add built in support for wavelink/lavalink.

### ISSUE THREAD

**Issue by Rxann** [Pycord-Development/pycord#51]
### Summary

Add built in support for wavelink or lavalink in pycord

### What is the feature request for?

discord.ext.commands

### The Problem

It would become much easier to create bots that can play audio if this is implemented!

### The Ideal Solution

I would like lavalink to be built into the library!

### The Current Solution

Use wavelink, which is not maintained.

### Additional Context

Maybe make a voice/music ext if this is to be implemented.

Thanks for your time!

**Comment by zeffo** [comment]
[Lavalink.py](https://lavalink.readthedocs.io/en/latest/) seems to still be maintained.
