### ISSUE TITLE
Can't edit channels inside of if statements in on_message

### ISSUE THREAD

**Issue by Mlchaell** [Pycord-Development/pycord#515]
### Summary

Unable to edit channels (channel.edit) inside of if statements inside of on_message

### Reproduction Steps

1. Add on_message event
2. Edit channel name inside of an if statement

### Minimal Reproducible Code

```python
@bot.event
async def on_message(m):
    s = m.channel.name.split("-")
    if s[0].startswith("comm") and not m.author.bot and s[2] == "d":
        print("Test")
        await m.channel.edit(name="test")
```

### Expected Results

After checking if the channel the message was sent in meets the requirements, the channel name should be updated. 

### Actual Results

The channel name is never updated, though if the edit is done outside of an if statement everything works fine. Any other code inside of the if statement works fine (can print, etc)

### Intents

All

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4429+gc5bee66
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by nerdguyahmad** [comment]
Renaming channel names has a ratelimit of 2 per 10 minutes. You are more then likely getting ratelimited. If you want to confirm, Consider [setting up logging](https://pycord.readthedocs.io/en/master/logging.html) and looking for ratelimit warnings.
