### ISSUE TITLE
Voice Receive API

### ISSUE THREAD

**Issue by Makiyu-py** [Pycord-Development/pycord#52]
### Summary

Add a voice receiving api here on Pycord!

### What is the feature request for?

The core library

### The Problem

Currently, there isn't a voice receiving API for Pycord. This has been [a long suggestion for discord.py _going back as far as 2017_.](https://github.com/Rapptz/discord.py/issues/444)

There are currently (discord.py) development forks just for this feature, [like imayhaveborkedit's fork](https://github.com/Rapptz/discord.py/issues/1094) and [Gorialis' fork](https://github.com/Gorialis/discord.py/tree/voice-recv-mk3) but it'll be great to have a official solution to this problem!

### The Ideal Solution

Receiving voice from VCs.

### The Current Solution

Use discord.py dev forks that primarily focuses on implementing voice-receiving.

### Additional Context

(pssst, I heard discord.js has an [implementation of this feature](https://github.com/discordjs/voice/tree/main/examples/recorder), if u guys care)

**Comment by Ari24-cb24** [comment]
I tried to do some research but couldn't find anything related to this.
How about legal rights? Do you need an agreement of every person in a voice call if you want to record his voice? Is there a specific format that agreement has to follow? Are there country specific rights?

**Comment by LilJess13** [comment]
I feel like this is a moot point.
Developers/Manufacturers are not responsible for misuse of their products (in the US).

**Comment by OEUG99** [comment]
> In the US it varies. Some states are "one party" states where only one person on a call needs to be aware of the recording, where as some other states require the consent of all parties. If the bot is in the call, is the bot considered a party to the conversation?
> 
> Interesting question.

You can circumvent this by informing the people if they are being recorded. For example, perhaps message everyone who joins the channel that they are being recorded. This can easily be implemented by bot authors.

**Comment by FrequencyX4** [comment]
bot authors can also set the bots nickname as something like `ExampleBot (Recording VC)`

**Comment by FrostByte266** [comment]
Could also have the bot play a sound effect of "This channel is being recorded"

**Comment by tcprescott** [comment]
I think we can agree though that it won't be the responsible of the library to ensure compliance with any applicable laws.

**Comment by ProManGaming** [comment]
> Could also have the bot play a sound effect of "This channel is being recorded"

We NEED IT!
