### ISSUE TITLE
Banner Asset not returned for discord.Member

### ISSUE THREAD

**Issue by zombifications** [Pycord-Development/pycord#541]
### Summary

When trying to get a Asset of the user's banner from a discord.Member it returns None but works fine with discord.User

### Reproduction Steps

```py
import discord

bot = discord.Bot()

@bot.command()
async def banner(self, ctx, member: discord.Member):
	embed = discord.Embed(color=discord.Color.green())
	try:
		embed.set_image(url=member.banner.url)
	except AttributeError as e:
		return await ctx.send(e)
	embed.set_footer(text="{}'s Banner".format(member))
	await ctx.reply(embed=embed, mention_author=True)

bot.run("token")
```

### Minimal Reproducible Code

```py
@commands.command()
async def banner(self, ctx, member):
    print(member.banner.url) # returns None even if member has a banner
```

### Expected Results

![image](https://user-images.githubusercontent.com/85012913/144718085-bd424463-2c94-4781-a026-a1aa82d92acc.png)

### Actual Results

```
Traceback (most recent call last):
  File "C:\Users\cutie\Desktop\tragedy-revamp\.env\lib\site-packages\discord\ext\commands\core.py", line 173, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\cutie\Desktop\tragedy-revamp\src\modules\core\info.py", line 81, in banner
    embed.set_image(url=member.banner.url)
AttributeError: 'NoneType' object has no attribute 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cutie\Desktop\tragedy-revamp\.env\lib\site-packages\discord\ext\commands\bot.py", line 882, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\cutie\Desktop\tragedy-revamp\.env\lib\site-packages\discord\ext\commands\core.py", line 910, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\cutie\Desktop\tragedy-revamp\.env\lib\site-packages\discord\ext\commands\core.py", line 182, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'url'
```

### Intents

discord.Intents.all()

### System Information

- Python v3.9.6-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4407+g65de7f3c
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by MhmCats** [comment]
This is [documented](https://docs.pycord.dev/en/master/api.html#discord.User.banner)... `user.banner` is only available if you fetch it directly from the API first.
![image](https://user-images.githubusercontent.com/71032999/144720621-afc67f0a-5a29-4947-82e3-e17c4f528497.png)
