### ISSUE TITLE
discord.Guild.audit_logs "after" parameter doesn't filter correctly

### ISSUE THREAD

**Issue by Endst** [Pycord-Development/pycord#544]
### Summary

"after" parameter doesn't filter the audit log at all

### Reproduction Steps

Try to use the "after" parameter in discord.Guild.audit_logs to filter logs

### Minimal Reproducible Code

```python
minutes = 30
            after_time = (datetime.now(timezone.utc) - timedelta(minutes = minutes))
            for log in await ctx.guild.audit_logs(limit=None, action=discord.AuditLogAction.channel_create, after = after_time, oldest_first = False).flatten():
                logTime = datetime(year = int(log.created_at.strftime(r"%Y")), 
                month = int(log.created_at.strftime(r"%m")), 
                day = int(log.created_at.strftime(r"%d")), 
                hour = int(log.created_at.strftime(r"%H")), 
                minute = int(log.created_at.strftime(r"%M")), 
                second = int(log.created_at.strftime(r"%S")))
                await ctx.respond(f"Time: {logTime}")
            await ctx.respond("Hi lol")
```

### Expected Results

I expected the logs to be filtered correctly like how the "before" filter works

### Actual Results

It prints out ALL (except ones filtered out by other filters) logs and ignores the "after" filter 

### Intents

All

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
- py-cord pkg_resources: v2.0.0a4501+g9fceff87
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The other filters I've tested (limit, action, before, and oldest_first) all work with the code

**Comment by TheReaper62** [comment]
sounds like a discord limitation, 
does it work sometimes?

**Comment by Endst** [comment]
> sounds like a discord limitation, does it work sometimes?

Nope, not from my experience at least. This may be an issue with Discord itself, just not sure off hand. If it is a Discord issue, it'd be nice if they can take it off the docs to prevent user confusion.

**Comment by BobDotCom** [comment]
> Nope, not from my experience at least. This may be an issue with Discord itself, just not sure off hand. If it is a Discord issue, it'd be nice if they can take it off the docs to prevent user confusion.

See if you can reproduce this bug with discord.py. There were some bugs in audit logs due to discord limitations, so if you can reproduce it then that's likely what's happening.

**Comment by Endst** [comment]
Yeah, turns out Discord didn't implement it into their API for some odd reason. I'd recommend removing it from the Pycord docs just to prevent confusion in the future. I made a feature request for it so hopefully Discord will add it to their API sometime in the future.
