### ISSUE TITLE
[groups] Slash command groups not working correctly

### ISSUE THREAD

**Issue by CDE90** [Pycord-Development/pycord#546]
### Summary

When using slash command groups from 'groups' branch, commands inside cogs are registered correctly, but commands outside raise an error

### Reproduction Steps

Using the [slash_cog_groups.py](https://github.com/Pycord-Development/pycord/blob/groups/examples/app_commands/slash_cog_groups.py) example & the [groups branch](https://github.com/Pycord-Development/pycord/tree/groups), adding another command outside of the cog & not in a group raises an error

### Minimal Reproducible Code

```python
import discord
from discord.commands import SlashCommandGroup, Permission
from discord.ext import commands

bot = discord.Bot(debug_guild=, owner_id=)  # main file

# Command outside of cog
@bot.command()
async def test(ctx):
    await ctx.respond("Hello World")

class Example(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    greetings = SlashCommandGroup("greetings", "Various greeting from cogs!")

    international_greetings = greetings.create_subgroup(
        "international", "International greetings"
    )

    secret_greetings = SlashCommandGroup(
        "secret_greetings",
        "Secret greetings",
        permissions=[
            Permission(
                "owner", 2, True
            )  # Ensures the owner_id user can access this, and no one else
        ],
    )

    @greetings.command()
    async def hello(self, ctx):
        await ctx.respond("Hello, this is a slash subcommand from a cog!")

    @international_greetings.command()
    async def aloha(self, ctx):
        await ctx.respond("Aloha, a Hawaiian greeting")

    @secret_greetings.command()
    async def secret_handshake(self, ctx, member: discord.Member):
        await ctx.respond(f"{member.mention} secret handshakes you")


bot.add_cog(Example(bot))  # put in a setup function for cog files
bot.run("redacted")  # main file
```

### Expected Results

Commands to register with no errors

### Actual Results

```Traceback (most recent call last):
  File "c:\Users\Ethan Coward\VS code - python\Group TEst\bot.py", line 8, in <module>
    async def test(ctx):
  File "C:\Users\Ethan Coward\AppData\Roaming\Python\Python39\site-packages\discord\bot.py", line 520, in decorator
    self.add_application_command(result)
  File "C:\Users\Ethan Coward\AppData\Roaming\Python\Python39\site-packages\discord\bot.py", line 123, in add_application_command
    raise TypeError("The provided command is a sub-command of group")
TypeError: The provided command is a sub-command of group
```
### Intents

None

### System Information

```- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4524+g5a7ef11a
- aiohttp v3.7.4
- system info: Windows 10 10.0.18363
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Using the groups branch #462

**Comment by Blackcool70** [comment]
I get that error too.

Additionally, I'm having trouble adding those group-cog slash commands in my own separate cog files. commands are not registering. I got it to register once and then never again.

**Comment by Lulalaby** [comment]
This is WIP

**Comment by Dorukyum** [comment]
I'll look into this, thanks for reporting.
> I'm having trouble adding those group-cog slash commands in my own separate cog files. commands are not registering. I got it to register once and then never again.

This cog is working for me, maybe you loaded it after on_connect?

**Comment by Dorukyum** [comment]
https://github.com/Pycord-Development/pycord/pull/462/commits/27d0f6cfa7414ee34248b714284db83a863d4d02 should fix this, feel free to reopen this if not.
