### ISSUE TITLE
`IPC` Module

### ISSUE THREAD

**Issue by VincentRPS** [Pycord-Development/pycord#553]
### Summary

Adding a `ipc` feature

### What is the feature request for?

The core library

### The Problem

None really I just think this would be a cool feature to have especially for big bots

### The Ideal Solution

Maybe adding it as a ext? Like discord.ext.web or ipc

**Comment by Quintenvw** [comment]
What about AutoShardedBot?

**Comment by VincentRPS** [comment]
i am developing this rn i won't make a pull for a while since it needs severe rework
