### ISSUE TITLE
Slash Commands stop working after reloading Cog.

### ISSUE THREAD

**Issue by Neehier** [Pycord-Development/pycord#556]
### Summary

Slash Commands cease to work after reloading their Cog.

### Reproduction Steps

1. Unload Cog
2. Load Cog
3. Use Slash Command in-app

### Expected Results

Slash Command executing successfully.

### Actual Results

Slash Command returns `This interaction failed`.

![This interaction failed](https://i.imgur.com/g9NqG5h.png)

### Intents

discord.Intents.all()

### System Information

> - Python v3.9.6-final
> - py-cord v2.0.0-alpha
>     - py-cord pkg_resources: v2.0.0a4440+ge75d7f48
> - aiohttp v3.7.4.post0
> - system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment]
For me, this also happens when you reboot the bot

**Comment by NottCurious** [comment]
Same thing occurs for me, however the functions work fine after rebooting the bot entirely

I have also tried using both
```python
client.reload_extension(file)
```
and
```python
client.unload_extension(file)
client.load_extension(file)
```

**Comment by Lulalaby** [comment]
Actually it's normal behaviour and not really a bug.
It'll work in future tho.
Closing as invalid for now
