### ISSUE TITLE
discord views interaction.message.author.id returns the bot id not the user id

### ISSUE THREAD

**Issue by Jerry-py** [Pycord-Development/pycord#557]
### Summary

I tested my code out and it didn't work the way it was supposed to

### Reproduction Steps
![image](https://user-images.githubusercontent.com/64660183/145697317-f7046bfa-ac86-4a27-b211-89793a62fc11.png)

My id is the first one
The second is the bot

See code below

### Minimal Reproducible Code

```python
async def interaction_check(self, interaction) -> bool: 
        # sourcery skip: remove-unnecessary-else
        print(interaction.user.id)
        print(interaction.message.author.id)
        if interaction.user.id == interaction.message.author.id:
            return True
        else:
            await interaction.response.send_message('You cannot use this interaction!', ephemeral=True)
            return False
```

### Expected Results

The message author's id so the person who sent it's id is equal to interaction author

### Actual Results

returned bot id not author id

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4473+g6b1822ee
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

It's actually Windows 11 (Home)
![image](https://user-images.githubusercontent.com/64660183/145698539-1bd998e1-18a4-4339-9d03-bd667b860de7.png)

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
This is wanted behavior.
Fact is: the original message is the message from the bot containing the message component.
Closing as invalid.
