### ISSUE TITLE
[META] Project Management review of PRs

### ISSUE THREAD

**Issue by krittick** [Pycord-Development/pycord#562]
The library has a few PRs that are stalled, some that are confusing, and others that are stale. It's not immediately clear to an outside observer/contributor where things currently stand and what things are blocked by.

I went ahead and reviewed all of our open PRs and provided some recommendations on what could help to move each of these forward or otherwise closed out. Please find these recommendations below. 

Note that these suggestions are from a product/project management perspective only and do not suggest any code changes.

### State & Recommendations

# #999 - Title
**Last Update:**
**Status:** 
**Recommendations:** 

# #775 - Trunk/docs
**Last Update: Jan 20**
**Status: Ready for review, ** 
**Recommendations:** 
- Prioritize review and merge for 2.0 release

# #762 - chore: bump version to 2.0.0-rc.1
**Last Update: Jan 12**
**Status: Ready for review and merge** 
**Recommendations:** 
- Prioritize reviewing and merging before 2.0

# #759 - Command registration rewrite
**Last Update: Jan 12**
**Status: Draft, in progress** 
**Recommendations:** 
- Confirm whether this is still planned for 2.0 and prioritize completing work if so

# #751 - Features/voice receive
**Last Update: Jan 12**
**Status: Draft, still in progress** 
**Recommendations:** 
- Leave as-is for now, review for possible 2.1 inclusion if completed before then

# #749- feat: discord.ext.ipc module
**Last Update: Jan 19**
**Status: Draft, still in progress** 
**Recommendations:** 
- Leave as-is for now, review for possible 2.1 inclusion if completed before then

# #743- 3.10: get_event_loop has been deprecated
**Last Update: Jan 12**
**Status: Ready for review and merge** 
**Recommendations:** 
- Prioritize review for inclusion in 2.0

# #689- remove useless lambda functions
**Last Update: Jan 6**
**Status: Needs to have conflicts resolved, otherwise ready for merging** 
**Recommendations:** 
- Prioritize review for inclusion in 2.1

# #681 - Fix: Fix discord.errors not working
**Last Update: Jan 12**
**Status: Ongoing discussion on whether this is needed or if users should be using discord.Forbidden instead of discord.errors.Forbidden etc** 
**Recommendations:**
- Prioritize review for inclusion in 2.1, if it's determined that this is actually necessary.

# #640 - Add functions that set permissions for all slash commands in a cog
**Last Update: Jan 7**
**Status: Ready for review** 
**Recommendations:** 
- Prioritize review for inclusion in 2.1

# #630 - Add support for Input Text and Modal components
**Last Update: Jan 12**
**Status:** Tested with a whitelisted bot, and is ready to merge.
**Recommendations:** 
- Prioritize merging once the feature is released to the public.

# #579 - Slash Attachments
**Last Update: Jan 1**
**Status:** Feature not implemented by discord yet
**Recommendations:** 
- Leave as-is unless we're able to somehow get early access before it releases

# #625 - Fix on_ready() comment
**Last Update: Jan 7**
**Status:** Needs agreement on which wording to use for the change.
**Recommendations:** 
- Prioritize and merge. 
- This is pretty minor, and the following proposed option seems to be a best fit: 
  - "whenever the internal cache and the connection of the bot becomes ready."

# #411 - Code fixes
**Last Update: Nov 15**
**Status:** Moved to 2.1
**Recommendations:** 
- Leave as-is

# #432 - Merge core/typing
**Last Update: Nov 30**
**Status:** Recently rebased to trunk/docs
**Recommendations:** 
- Update description to explain the context behind the PR.

# #449 - Document application commands
**Last Update: Dec 18**
**Status:** In progress
**Recommendations:** 
- Prioritize this as soon as possible. 
- This is one of the most commonly-asked questions in the Pycord Discord server and not having documentation for stable features like ApplicationContext, UserCommand, etc creates a bad public perception of the library.

# #525 - V2 migration guide
**Last Update: Jan 12**
**Status:** In progress
**Recommendations:** 
- Prioritize this as soon as possible.

# Summary of findings

**Comment by RPSMai** [comment]
Might close 536 if no one wants to review it

**Comment by NoPlagiarism** [comment]
458 does not breaks anything, you can still import and it's working as was
`from discord.ext.commands import cooldowns`
Tnx for raising this topic btw

**Comment by VincentRPS** [comment]
> 458 does not breaks anything, you can still import and it's working as was
> `from discord.ext.commands import cooldowns`
> Tnx for raising this topic btw

Yeah people still don’t agree with moving it though, application cool down and prefix cooldown should be separate imo

**Comment by Lulalaby** [comment]
> application cool down and prefix cooldown should be separate imo

Exactly

**Comment by krittick** [comment]
Updated list with the great progress made this week.

**Comment by EmreTech** [comment]
I decided to look through this issue and the PRs listed to see their current status.
Here's a list of the PRs listed in this issue that are now merged:
#211 
#443 
#458 
#509 
#518 
#532 
#536 
#543

**Comment by Makiyu-py** [comment]
> I decided to look through this issue and the PRs listed to see their current status. Here's a list of the PRs listed in this issue that are now merged: #211 #443 #458 #509 #518 #532 #536 #543

443 -> #652
458 -> #674
543 -> #662 
:D
