### ISSUE TITLE
`discord.ext.commands.UserConverter` cannot be used as an input type for slash command options

### ISSUE THREAD

**Issue by m1stadev** [Pycord-Development/pycord#567]
### Summary

`discord.ext.commands.UserConverter` cannot be used as an input type for slash command options

### Reproduction Steps

Try to use `discord.ext.commands.UserConverter` as the input type for a slash command option.

### Minimal Reproducible Code

```python
@slash_command
async def hello(ctx, user: Option(discord.ext.commands.UserConverter)):
    await ctx.respond(f'Hi, {user.mention}!')
```

### Expected Results

I expected the Option to call `discord.ext.commands.UserConverter.convert()` properly and parse the argument.

### Actual Results

The argument fails to parse:
```Ignoring exception in command <discord.commands.SlashCommand name=download>:
Traceback (most recent call last):
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 85, in wrapped
    ret = await coro(arg)
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 529, in _invoke
    arg = await op._converter.convert(ctx, arg)
TypeError: convert() missing 1 required positional argument: 'argument'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/bot.py", line 447, in process_application_commands
    await ctx.command.invoke(ctx)
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 134, in invoke
    await injected(ctx)
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 85, in wrapped
    ret = await coro(arg)
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 867, in _invoke
    await command.invoke(ctx)
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 134, in invoke
    await injected(ctx)
  File "/Users/m1sta/Projects/AutoTSS/env/lib/python3.9/site-packages/discord/commands/commands.py", line 91, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: convert() missing 1 required positional argument: 'argument'
```

### Intents

Defaults + Server Members intent

### System Information

- Python v3.9.9-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4537+g6646129e
- aiohttp v3.8.1
- system info: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_6

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
I believe this isn't a bug.
Correct me if I'm wrong, but this function is not intended to be placed in a option.

**Comment by VincentRPS** [comment]
> I believe this isn't a bug. Correct me if I'm wrong, but this function is not intended to be placed in a option.

+1

**Comment by m1stadev** [comment]
> I believe this isn't a bug. Correct me if I'm wrong, but this function is not intended to be placed in a option.

ah. curious then, what's [this code](https://github.com/Pycord-Development/pycord/blob/6646129e29607748d1aa25fb6a18e6aa7caf7f0c/discord/commands/commands.py#L627) for?

**Comment by Lulalaby** [comment]
Oh we forgot to remove it.

**Comment by VincentRPS** [comment]
> Oh we forgot to remove it.

quick pull to remove it? poggers

**Comment by Lulalaby** [comment]
sure go for it.
It was set to slash 11 before, but due to it being attachments, it was removed.

**Comment by Dorukyum** [comment]
> > I believe this isn't a bug. Correct me if I'm wrong, but this function is not intended to be placed in a option.
> 
> ah. curious then, what's [this code](https://github.com/Pycord-Development/pycord/blob/6646129e29607748d1aa25fb6a18e6aa7caf7f0c/discord/commands/commands.py#L627) for?

For custom converters. Couldn't use isinstance since it would create a circular import.
