### ISSUE TITLE
Adjustable button size

### ISSUE THREAD

**Issue by Inge1234567890** [Pycord-Development/pycord#575]
### Summary

Create buttons with adjustable size

### What is the feature request for?

The core library

### The Problem

Buttons with different size look crappy on discord. 

### The Ideal Solution

Make a parameter called size to adjust the size for every button. 

### The Current Solution

There is no solution.

**Comment by Lulalaby** [comment]
Not possible

**Comment by Dorukyum** [comment]
This is a Discord limitation, the API doesn't allow declaring button sizes.
