### ISSUE TITLE
New decorator for slash permissions

### ISSUE THREAD

**Issue by tomschmitz98** [Pycord-Development/pycord#581]
### Summary

Add a new decorator that checks for administrator permission and/or other permissions of user

### What is the feature request for?

discord.ext.commands

### The Problem

Right now, if permissions were implemented on a command, the decorators would require a role id, user id, a role name, and/or a type (I'm assuming the type is the bit field for all the permissions). This is a problem when the bot is in multiple servers because administrator role names/users vary across servers.

The new feature proposed will add a new decorator that will only require the type which will allow users with certain permissions to run certain commands such as administrator commands.

### The Ideal Solution

I would love to see a new decorator such as:

 `@permissions.has_permissions(type)`

This decorator should check if the user/role has the permissions specified by the value of type where the positions of 1's specify which permissions should be checked. Also, if the administrator bit is high, then everything else should be don't cares. 

If a user does not have the permissions to run that command, then the command should be grayed out like the ping command in the image.

![image](https://user-images.githubusercontent.com/37012299/146638334-ecbb613a-c082-4136-aa71-dedb4b66efba.png)

### The Current Solution

The current solution to this problem is using the `@permissions.has_any_role("ROLE_NAME", "ROLE_NAME_2") #<-- can use either a name or id` decorator or any other decorators for permissions. The big problem with this solution is the role names need to be known. This is fine for a single server, but as the bot gets added to more servers, it might lead to undesired roles/users having access to commands that they're not supposed to have access to.

Another solution to this problem is not using a permissions decorator and checking the user permissions when a user tries running the command which will result in a response like "Error: You do not have permission to run this command!" if they don't have the proper permissions.

**Comment by Dorukyum** [comment]
Discord limitation, in work

**Comment by krittick** [comment]
Specifically, you can only disable slash commands for specific users or roles in a guild. Relevant documentation: https://discord.com/developers/docs/interactions/application-commands#application-command-permissions-object-application-command-permission-type

**Comment by tomschmitz98** [comment]
Well darn. It looks like I'm going to have to check the user's permissions if they use a command that they're not supposed to use.

**Comment by Lulalaby** [comment]
Yep :)

But lil hint. Soon after discord holiday ;)
