### ISSUE TITLE
Pypi ctrl-c, ctrl-v from d.py

### ISSUE THREAD

**Issue by Creveoolus** [Pycord-Development/pycord#584]
### Summary

Pypi 

### Reproduction Steps

Check out py-cord's [Pypi page]().
This page was copy-pasted from d.py pypi page. MD wasn't changed at all. Discord widget redirects to d.py server, not to pycord one.
Instalation command has same issue, is from d.py

[Screenshot](https://cdn.creve.fun/NfoPxPfx)

### Expected Results

Everythink is changed to py-cord

### Actual Results

It's not

### Intents

bruh

### System Information

bruh

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
I see this is not serious, however if it isn't then you should do some research on "github forks"

**Comment by Creveoolus** [comment]
> I see this is not serious, however if it isn't then you should do some research on "github forks"

Can't you just change the pypi page?

**Comment by Lulalaby** [comment]
not now
