### ISSUE TITLE
Discord Timeouts

### ISSUE THREAD

**Issue by pratheek78** [Pycord-Development/pycord#605]
### Summary

Add support for discord timeouts

### What is the feature request for?

The core library

### The Problem

The problem is that right now, it is quite hard to make a good tempmute command, because first of all, using asyncio to manage timeouts sucks, because if the bot shuts down, the people muted will be muted forever. The other option is to use a database to manage times, but that will take a ton of time and effort. The second problem is that this will not affect the staff, and if you want it to, you'll have to make a system to store their roles, and then remove them, and then once the timeout is over, give them back. This will take even more time.

### The Ideal Solution

The new discord timeouts feature aims to fix this by giving users a tempmute option right inside discord. This is already added and documented in the API as well. This will make it so that discord handles the user roles, times, etc. and makes our lives a ton easier

### The Current Solution

As stated above, it is to use databases, but this will be VERY time consuming to implement, because you have to manage the members, their roles, the time, etc. And then theres also bot downtimes which you also need to handle by making on_ready events to check if the timeout is over.

**Comment by zeffo** [comment]
Timeouts are already supported.

**Comment by Lulalaby** [comment]
Already there. Read the docs please.
