### ISSUE TITLE
Renaming threads fails silently

### ISSUE THREAD

**Issue by jaimevisser** [Pycord-Development/pycord#611]
### Summary

Renaming threads fails silently

### Reproduction Steps

Rename a thread a couple of times.

### Minimal Reproducible Code

```python
thread = await ctx.channel.create_thread(name="test", type=ChannelType.public_thread)
thread = await thread.edit(name="test 0")
thread = await thread.edit(name="test 1")
thread = await thread.edit(name="test 0")
```

### Expected Results

Thread renamed each time

### Actual Results

Async task silently fails

### Intents

None?

### System Information

- Python v3.9.2-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4496+gb872cfea
- aiohttp v3.7.4.post0
- system info: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Could be a ratelimit

**Comment by jaimevisser** [comment]
> Could be a ratelimit

I'd expect some sort of error when hitting a ratelimit. At the moment it just fails silently.

**Comment by timmypidashev** [comment]
Pretty sure a ratelimit would log.

**Comment by timmypidashev** [comment]
Just did some testing and honestly pycord is fairly good at handling thread edits that quickly. After 2 edits, the third one becomes the issue, after which yes it does silently fail. Being able to edit a thread name 2 times right after creation is fairly solild.

**Comment by krittick** [comment]
Discord limits channel edits to 2 times per 10 minutes I believe, which this would fall under since Threads are a type of channel.

**Comment by krittick** [comment]
Additionally, rate limits won't show in a traceback but should be visible in the actual discord logs as "you are being rate limited" or similar if logging is properly set up.

**Comment by timmypidashev** [comment]
Setting up logging should fix the issue completely. 
![image](https://user-images.githubusercontent.com/64367077/147150272-7681ebc4-dc20-4e14-a37a-72763a8eb498.png)

**Comment by jaimevisser** [comment]
Is there a specific way to set up logging for pycord? Couldn't find anything in the examples or docs.

**Comment by jaimevisser** [comment]
Nevermind, just turning on python logging works.

**Comment by timmypidashev** [comment]
ye this issue is pretty much closed
