### ISSUE TITLE
Cog.get_commands() does not return ext.commands commands

### ISSUE THREAD

**Issue by HyperGH** [Pycord-Development/pycord#618]
### Summary

`Cog.get_commands()` no longer returns anything but slash/interaction based commands, breaking all help commands

### Reproduction Steps

Run the example below with a cog that has `ext.commands` based commands.

### Minimal Reproducible Code

```python
cog = bot.get_cog("MyCog")
commands = cog.get_commands()
print(commands)
#This will return [] unless MyCog contains slash/interaction based commands
```

### Expected Results

Commands inside cog returned as a list.

### Actual Results

Only interaction-based commands are returned

### Intents

```
discord.Intents(guilds = True, members = True, bans = True, emojis = True, messages = True, invites = True, reactions = True)
```

### System Information
```
- Python v3.10.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4627+gca1a76cb
- aiohttp v3.7.4.post0
- system info: Linux 5.15.10-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 17 Dec 2021 11:17:39 +0000
```
### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
This was changed in a recent pull request by me, I made it fit the typehint (it just showed ApplicationCommand)

**Comment by HyperGH** [comment]
It would be great as currently any and all help commands that were implemented by subclassing `HelpCommand` break, as `send_bot_help` uses this to create it's mapping.

**Comment by Dorukyum** [comment]
After thinking, this change was correct and the behavior should just be overwritten in `ext.commands.Cog`.
