### ISSUE TITLE
Timeouts are not synced with the Timezone.

### ISSUE THREAD

**Issue by Tanay-Nasikkar** [Pycord-Development/pycord#624]
### Summary

Not synced with the Timezone

### Reproduction Steps

Used datetime.fromtimestamp

### Minimal Reproducible Code

```python
end_time = int(time.time() + duration_in_seconds)
await member.timeout(datetime.datetime.fromtimestamp(end_time))
```

### Expected Results

Expected it to sync with my local timezone.

### Actual Results

My timezone is +5:30, so it shifted the time +5:30

### Intents

discord.Intents.all()

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4631+g16f9bcb5
- aiohttp v3.7.4.post0
- system info: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by HyperGH** [comment]
You should try using timezone-aware timestamps, for example: `discord.utils.utcnow() + datetime.timedelta(seconds=10)`, you may also substitute `discord.utils.utcnow()` with `datetime.datetime.now(datetime.timezone.utc)`

**Comment by Tanay-Nasikkar** [comment]
Yes, it works now.
