### ISSUE TITLE
commands.CommandNotFound is never raised

### ISSUE THREAD

**Issue by HyperGH** [Pycord-Development/pycord#643]
### Summary

commands.CommandNotFound is not raised when a command is not found.

### Reproduction Steps

Try to invoke any `ext.commands` command that does not exist.

### Expected Results

`commands.CommandNotFound` is raised.

### Actual Results

Literally nothing.

### Intents

`discord.Intents.all()`

### System Information

```
- Python v3.10.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4644+gf5c3e600
- aiohttp v3.7.4.post0
- system info: Linux 5.15.11-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 22 Dec 2021 09:23:53 +0000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by rtk-rnjn** [comment]
confirmed bug

**Comment by Kartik9876** [comment]
I have added on_command_error and it sends the error so how it does not work

**Comment by Makiyu-py** [comment]
The error raised on mine and I don't have a `on_command_error` event.

My Pycord version is `py-cord-2.0.0a4648+g025d7725`. Maybe try updating to the latest commit and try again, or check if you've (unintentionally) intentionally not raise it in your `on_command_error` event.

**Comment by HyperGH** [comment]
On further testing it looks like this is indeed an issue with my code somehow, as with minimal reproducible code the issue no longer occurs.
