### ISSUE TITLE
`utils.get` only returning one match

### ISSUE THREAD

**Issue by Sengolda** [Pycord-Development/pycord#646]
### Summary

`utils.get` only returns match even if there are 2 roles named the same

### Reproduction Steps

Make 2 roles named the same
Try utils.get, it only returned one.

### Minimal Reproducible Code

```python
role = discord.utils.get(ctx.guild.roles, name="test")
print(role) # There were 2 roles named "test" and only one of them were printed.
```

### Expected Results

I expected a list of both roles.

### Actual Results

Only returned 1 role.

### Intents

discord.Intents.all()

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4648+g025d7725
- aiohttp v3.8.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
That's the purpose.
> A helper that returns the first element in the iterable that meets all the traits passed in ``attrs``.
