### ISSUE TITLE
ApplicationContext.send_response() and respond() are named too similarly.

### ISSUE THREAD

**Issue by HyperGH** [Pycord-Development/pycord#649]
### Summary

`ApplicationContext.send_response()` and `respond()` are very easy to confuse, and one of them should be possibly renamed.

### What is the feature request for?

The core library

### The Problem

`ApplicationContext.send_response()` and `respond()` essentially mean the exact same thing, even though they perform different functions. An effort should be made to try & find a different name for one of these functions to avoid further confusion.

### The Ideal Solution

`ApplicationContext.send_response()` should be renamed to `respond_or_followup()` or anything similar, to reflect the functionality of this function.

### The Current Solution

The current solution is to simply get confused by the naming.

**Comment by krittick** [comment]
Closing as internal consensus among the core dev team is that we won't be renaming these methods anytime soon.
