### ISSUE TITLE
add_view() needs to be called every on_ready for persistent views to work.

### ISSUE THREAD

**Issue by HyperGH** [Pycord-Development/pycord#650]
### Summary

add_view() needs to be called whenever every on_ready() is dispatched for persistent views to keep working, otherwise they will just fail.

### Reproduction Steps

1. Boot up the bot with persistent views example
2. Trip over your ethernet cable
3. Fix your ethernet cable
4. Notice views not working anymore

### Minimal Reproducible Code

```
See `examples/views/persistent.py` for an example.
```

### Expected Results

`add_view()` only needs to be called when the bot first starts up.

### Actual Results

`add_view()` needs to be called every time `on_ready()` is dispatched.

According to https://github.com/Rapptz/discord.py/pull/7438 this is a bug, and not intended functionality of the library.

### Intents

`discord.Intents.all()`

### System Information

```
- Python v3.10.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4648+g025d7725
- aiohttp v3.7.4.post0
- system info: Linux 5.15.11-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 22 Dec 2021 09:23:53 +0000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by PythonIntermediateCoder** [comment]
If you look at [examples/views/persistent.py](https://github.com/Pycord-Development/pycord/blob/master/examples/views/persistent.py#L44), you'll see that it only adds when the `persistent_added` variable is `False`.

**Comment by PythonIntermediateCoder** [comment]
Also, I think the views work when the bot is online

**Comment by HyperGH** [comment]
> If you look at [examples/views/persistent.py](https://github.com/Pycord-Development/pycord/blob/master/examples/views/persistent.py#L44), you'll see that it only adds when the `persistent_added` variable is `False`.

This was literally my point. Views have to be added on every `on_ready()`, not just the first one, therefore this example is wrong.

**Comment by HyperGH** [comment]
> Also, I think the views work when the bot is online

They work fine as long as the bot does not receive another `READY` event, yes, at which point they cease functioning.

**Comment by krittick** [comment]
Closing as stale. This is generally the expected behavior and even the referenced links state this.
