### ISSUE TITLE
Add `typing_extentions` to internal requirements.txt

### ISSUE THREAD

**Issue by AwesomeSam9523** [Pycord-Development/pycord#660]
### Summary

Installing master branch and running says `No module named 'typing_extensions'`

### Reproduction Steps

Make a new venv
Clone master with `pip install git+https://github.com/Pycord-Development/pycord`
Run the bot

### Minimal Reproducible Code

```python
-
```

### Expected Results

It should run

### Actual Results

```py
    from typing_extensions import ParamSpec
ModuleNotFoundError: No module named 'typing_extensions'
```

### Intents

Not necessary

### System Information

Not necessary

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
#659 should fix this issue.

**Comment by ninratljk980** [comment]
no its still there

**Comment by Dorukyum** [comment]
> no its still there

because the pull request hasn't been merged yet.
