### ISSUE TITLE
Update new Thread Permissions

### ISSUE THREAD

**Issue by CodeWithSwastik** [Pycord-Development/pycord#67]
### Summary

Discord recently updated the thread permissions and these need to be updated in the code

### What is the feature request for?

The core library

### The Problem

Discord recently updated the thread permissions and these need to be updated in the code.

### The Ideal Solution

Add the new thread permissions.

**Comment by Astrea49** [comment]
Wasn't that already taken care of before even d.py closed? 4aafa39e8ca7fcdc7acd34295eed41bd3700d44b should take care of it.

**Comment by CodeWithSwastik** [comment]
Oh my bad, I didn't notice. Apologies.
