### ISSUE TITLE
Add a "files" arg to Paginator.send/respond for embed thumbnails 

### ISSUE THREAD

**Issue by StevensNJD4** [Pycord-Development/pycord#692]
### Summary

A  way to send paginated embeds with local thumbnails

### What is the feature request for?

discord.ext.pages

### The Problem

I am trying to send a paginated list of embeds with thumbnails I have stored locally but there isn't a "files" arg to send my thumbnails as an attachment.

### The Ideal Solution

Add a "files"  arg to Paginator.send/respond

**Comment by andrewkenreich** [comment]
![image](https://user-images.githubusercontent.com/23067478/148290885-fc85e235-1e4e-421e-8156-708e90cade94.png)

would it be added here?

https://github.com/Pycord-Development/pycord/blob/master/discord/ext/pages/pagination.py

**Comment by StevensNJD4** [comment]
> ![image](https://user-images.githubusercontent.com/23067478/148290885-fc85e235-1e4e-421e-8156-708e90cade94.png)
> 
> would it be added here?
> 
> https://github.com/Pycord-Development/pycord/blob/master/discord/ext/pages/pagination.py

I would assume so.

**Comment by andrewkenreich** [comment]
`    async def send(self, ctx: Union[ApplicationContext, Context], files: List[discord.File], ephemeral: bool = False) -> Union[discord.Message, discord.WebhookMessage]:`

`        if isinstance(ctx, ApplicationContext):
            msg = await ctx.respond(
                content=page if isinstance(page, str) else None,
                embed=page if isinstance(page, discord.Embed) else None,
                view=self,
                files=files,
                ephemeral=ephemeral,
            )
            print(msg)

        else:
            msg = await ctx.send(
                content=page if isinstance(page, str) else None,
                embed=page if isinstance(page, discord.Embed) else None,
                files=files,
                view=self,
            )`


ok here's what I changed in pagination.py

It works...kinda.

if you do 

await paginator.send(ctx, files, ephemeral=False)  - files being a list of discord file objects.

Problem is hiding the other files that send - see below - it does work to change them on the buttons but they all show up there. Not sure what do from here

![image](https://user-images.githubusercontent.com/23067478/148329251-b6dd24ee-f4d2-4d9a-b188-a824b210e3bd.png)

**Comment by StevensNJD4** [comment]
Cool thanks!

I wonder if this is even possible now since you have to attach all at once and you can't send a file when you edit a message (or in this case change a page).

**Comment by StevensNJD4** [comment]
Thanks so much!

So can your tweak be also be implemented in `respond` as well?

**Comment by krittick** [comment]
Planned to be added to the functionality for the `Page` object.
