### ISSUE TITLE
Command raised an exception: AttributeError: 'Member' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by djwalkzz16** [Pycord-Development/pycord#707]
### Summary

so Member.timeout not working

### Reproduction Steps

```python
@bot.command()
async def timeout(ctx, member: discord.Member, time=None, reason=None):
  await member.timeout(until = discord.utils.utcnow() + datetime.timedelta(minutes=time), reason=reason)
  await ctx.send (f"{member} timedout till {time}")
```

### Expected Results

It should timeout member

### Actual Results

it gave error `Command raised an exception: AttributeError: 'Member' object has no attribute 'timeout'`

### Intents

Message contents and default 

### System Information

1.1.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Hype3808** [comment]
You gotta update pycord using the command `pip install -U git+https://github.com/pycord-development/pycord`

**Comment by djwalkzz16** [comment]
ok , let me try

**Comment by Dorukyum** [comment]
You can get further help and information on our Discord server (.gg/pycord).
