### ISSUE TITLE
Slash command not registering even after add guild id

### ISSUE THREAD

**Issue by tungdo0602** [Pycord-Development/pycord#708]
### Summary

here my code: https://replit.com/@tungdo0602gmail/Quizizz-Tools

### Reproduction Steps

![image](https://user-images.githubusercontent.com/89498812/148246904-e835f222-baf9-4d8f-8f8e-1f7c3c6094e3.png)
for some reason it just register 1 command not 3 but in older version of pycord it registered for me all 3 command, i have try to add guild_ids params but not working. I also try to waiting for to next day but when i check it still not register the slash command

### Minimal Reproducible Code

```python
no error was shown
```

### Expected Results

it need to show 3 in it just show 1

### Actual Results

show 1 command

### Intents

no intents

### System Information

- Python v3.8.12-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4742+g552dccfb
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-1023-gcp #25~20.04.1-Ubuntu SMP Mon Nov 15 15:54:39 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context
Sorry my english is bad
_No response_

**Comment by plun1331** [comment]
Update Pycord, I think this was fixed in #705
