### ISSUE TITLE
a "before_ready" event / signal if the bot needs to interact with the discord api on startup

### ISSUE THREAD

**Issue by leElvyn** [Pycord-Development/pycord#71]
### Summary

An event similar to on_ready, that would be called once the bot has almost finished initializing, and everything is cached, but just before it starts receiving on_message events and sending commands

### What is the feature request for?

The core library

### The Problem

Some bots need to interact with the API when initializing, and this would provide an easy and safe way to make sure everything is ready before users can run any command, which could cause problems if some elements are missing.

### The Ideal Solution

a simple blocking method that can would work similarly to `on_ready`, where the bot or client object would be available. 
Example : 
```
@commands.Cog.listener()
async def before_ready(self):
    emojis = self.bot.get_guild(self.emoji_guild_id).emojis
```
This is a minimalist example, but some bots need to cache elements before starting.
once the command returns, the bot will start listening for commands and messages 

### The Current Solution

currently, it is possible to add some checks at the start of every commands, that makes them return if it isn't initialized. However, this requires a check on every commands which can quickly be hard

**Comment by Rxann** [comment]
The bot should always need to interact with the discord api on startup because, it needs to connect to the websocket! Also, If you have anything in the on_ready event that requires interaction with the discord API!

**Comment by Dorukyum** [comment]
The library only dispatches events supplied by the API. Also you can interact with the API under the `CONNECT` event which dispatches before `READY`.
