### ISSUE TITLE
close event

### ISSUE THREAD

**Issue by Rxann** [Pycord-Development/pycord#72]
### Summary

Add a close event

### What is the feature request for?

The core library

### The Problem

I would like a close event to be implemented because it would make things much easier to when the bot is shutting down. This would be very helpful for things like closing aiohttp Client Sessions and etc.

### The Ideal Solution

An event for close would be implemented.

### The Current Solution

None

### Additional Context

I have heard before that this could be hard to do, but I think it would help a lot of people!

**Comment by Luc1412** [comment]
I think that is redundant. Events are used for things you don't know when they will happen. In case of closing the Client you know when it happens. (If you using `client.close()`)

You can either call those actions before you call `client.close()` or you overwrite the close function.

**Comment by Rxann** [comment]
Oki, Thanks for the response and feedback!
