### ISSUE TITLE
Role object converted to str in member.add_roles()

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#730]
### Summary

Role object converted to str

### Reproduction Steps

Passed a role object into member.add_roles()

### Minimal Reproducible Code

```python
roleObj = message.guild.get_role(someAwesomeInteger) or None
if roleObj is not None:
    await message.author.add_roles(roleObj, "Adding a role")
```

### Expected Results

Add the role to the member like normal

### Actual Results

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\ree\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ree\Desktop\Code\DiscordBots\BlackHole\Modules\Fun\Leveling.py", line 478, in on_message
    await message.author.add_roles(roleObj, "Adding a role")
  File "C:\Users\ree\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\member.py", line 950, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
AttributeError: 'str' object has no attribute 'id'

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4757+g02e346db
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Makiyu-py** [comment]
Since `add_roles` take up multiple `Snowflake` objects, my guess is that it misinterpreted your reason as a snowflake object which gave that error. A simple fix to this is to make your reason a kwarg (i.e. `await message.author.add_roles(roleObj, reason="Adding a role")`).

**Comment by KosmicAnomaly** [comment]
> Since `add_roles` can take up multiple `Snowflake` objects, my guess is that it misinterpreted your reason as a snowflake object which gave that error. A simple fix to this is to make your reason a kwarg (i.e. `await message.author.add_roles(roleObj, reason="Adding a role")`).

Yep that ended up being the issue, can't believe I missed that. Thanks! 😅
