### ISSUE TITLE
Application command version of Bot.commands

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#731]
### Summary

A way to see the total amount of context menu commands and slash commands that are registered

### What is the feature request for?

The core library

### The Problem

Bot.commands doesn't include subcommands and subcommand groups

### The Ideal Solution

Have something along the lines of Bot.context_menu_commands and Bot.slash_commands that return lists of their respective objects.

**Comment by Makiyu-py** [comment]
There's a recent new feature ~~that I made~~ that was recently pushed (02e346dbf05086bcf3358e3706df8c41329ea8ba) relating to the `Bot` object, it can now let you walk/iterate through application commands, including subcommands. Maybe you can use that?
Something like:
```py
slash_commands = [i for i in bot.walk_application_commands() if isinstance(i, SlashCommand)]
```

**Comment by KosmicAnomaly** [comment]
> There's a recent new feature ~~that I made~~ that was recently pushed (02e346dbf05086bcf3358e3706df8c41329ea8ba) relating to the `Bot` object, it can now let you walk/iterate through application commands, including subcommands. Maybe you can use that?
> Something like:
> ```py
> slash_commands = [i for i in bot.walk_application_commands() if isinstance(i, SlashCommand)]
> ```

This works perfectly, thanks!
