### ISSUE TITLE
Slash command group registration error, with more than 1 command

### ISSUE THREAD

**Issue by MuffinAmor** [Pycord-Development/pycord#747]
### Summary

see title 

### Reproduction Steps

install pycord, try to add more than 1 command in a group with SlashCommandGroup()

### Minimal Reproducible Code

```python
moderation = SlashCommandGroup("mod", "Raum Moderations Commands")

    @is_registered()
    @moderation.command(name="spam", description="Stelle das Spamlimit ein")
    async def spam(self, ctx, room_name: str, seconds: int):
        if not ctx.author.bot:
            room_id = RoomIdResolve(room_name).get_id()
            respond = RoomSettings(room_id, ctx.author.id, str(seconds)).edit_spam()
            if respond:
                room.cache_clear()
                await ctx.respond(f"Die Nachrichten pro Sekunde wurden auf {seconds} festgelegt.")
            else:
                await ctx.respond("Du hast wohl keine Berechtigung dazu.")

    @is_registered()
    @moderation.command(name="add_word", description="Füge ein Word der Blacklist hinzu")
    async def add_word(self, ctx, room_name: str, word: str):
        if not ctx.author.bot:
            room_id = RoomIdResolve(room_name).get_id()
            respond = Blacklist(room_id, ctx.author.id, word).add_word()
            if respond:
                blacklist.cache_clear()
                await ctx.respond(f"Das Wort {word} wurde in die Blacklist geschrieben", ephemeral=True)
```

### Expected Results

2 Commands in a SlashCommand Group

### Actual Results

Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\n-des\anaconda3\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\n-des\anaconda3\lib\site-packages\discord\bot.py", line 785, in on_connect
    await self.register_commands()
  File "C:\Users\n-des\anaconda3\lib\site-packages\discord\bot.py", line 278, in register_commands
    if key2 in match[key][i].keys():
IndexError: list index out of range

### Intents

intents = discord.Intents().all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4771+gef9b5983
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000
(Actually windows 11)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

the people in the pycord discord help channel told me to open an issue.
Just correct me, if I have a programming error, that the discord users haven't see.

Used Database:
MySql with sqlalchemy (latest)

Interpreter:
anaconda with python3.9 (latest)

IDE:
Pycharm latest

**Comment by zeffo** [comment]
is the SlashCommandGroup instance created in the cog?

**Comment by MuffinAmor** [comment]
yes

**Comment by Dorukyum** [comment]
Cannot reproduce with the latest commit.

**Comment by MuffinAmor** [comment]
it is fixed now somehow, thanks anyway

**Comment by MuffinAmor** [comment]
Hey,
 i got the same issue again, with the same code in the newest pycord commit

other SlashCommand groups are not affected (i guess)

**Comment by MuffinAmor** [comment]
i really fixed the issue just by renaming the slash command group.
i would be happy when someone can review this phenomenon.
thanks
