### ISSUE TITLE
Components require a reboot of the bot to be caught in on_interaction

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#753]
### Summary

Trying to use on_interaction with new components raises NotFound until the bot is restarted

### Reproduction Steps

Create a dropdown menu, then try to interact with it and catch the interaction using on_interaction()

### Expected Results

Not have an error

### Actual Results

Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\nvrgonnagiveuup\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\nvrgonnagiveuup\Desktop\Code\DiscordBots\BlackHole\Modules\Utility\Polls.py", line 127, in on_interaction
    await response.edit_message(embed=embed)
  File "C:\Users\nvrgonnagiveuup\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 717, in edit_message
    await adapter.create_interaction_response(
  File "C:\Users\nvrgonnagiveuup\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\webhook\async_.py", line 192, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4757+g02e346db
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by MhmCats** [comment]
Could you provide some code so that I can try and repro this, this is what the "Minimal reproducible code" section is for y'know

**Comment by KosmicAnomaly** [comment]
yeah sure! And I am handling my components in on_interaction because it is the method that makes most sense to me.
```from discord import ApplicationContext, Interaction, SelectOption
from discord.commands import slash_command
from discord.ext.commands import Cog, guild_only
from discord.ui import Select, View


class CoolDropdown(Select):
    def __init__(self):
        optionList = [SelectOption(
            label="thing1", value="Option 1"), SelectOption(
            label="thing2", value="Option 2")]

        super().__init__(
            placeholder="choose one",
            min_values=0,
            max_values=1,
            options=optionList
        )


class CoolView(View):
    def __init__(self):
        super().__init__()

        self.add_item(CoolDropdown())


class randomthing(Cog):
    def __init__(self, bot):
        self.BlackHole = bot

    @slash_command(name="make-dropdown")
    @guild_only()
    async def make_dropdown(self, ctx: ApplicationContext):

        await ctx.defer(ephemeral=True)

        view = CoolView()
        await ctx.send(content="yeet", view=view)
        await ctx.respond("dropdown created!", ephemeral=True)

    @Cog.listener()
    async def on_interaction(self, interaction: Interaction):
        if not interaction.is_component():
            return
        if not interaction.guild:
            return

        response = interaction.response

        await response.send_message("yayeet")


def setup(bot):
    bot.add_cog(randomthing(bot))
```

**Comment by phenom4n4n** [comment]
This code doesn't correspond to your traceback, which shows that the erroring line is `await response.edit_message(embed=embed)`.

**Comment by KosmicAnomaly** [comment]
Sorry, I had changed my code because I needed to create some minimal code. The error is the same tho. Here's the new traceback
```Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\nvrgonnagiveuup\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\nvrgonnagiveuup\Desktop\Code\DiscordBots\BlackHole\Modules\Utility\randomthing.py", line 51, in on_interaction
    await response.send_message("yayeet")
  File "C:\Users\nvrgonnagiveuup\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 610, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\nvrgonnagiveuup\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\webhook\async_.py", line 192, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction```

**Comment by MhmCats** [comment]
You can just override the `callback` method of `discord.ui.Select` if you want something called when someone selects an item, you can get what was selected with `self.values`.

**Comment by AnimateShadows** [comment]
I think that this might be because the view auto-defers the interaction for you, I guess just don't use `on_interaction`.

**Comment by KosmicAnomaly** [comment]
Why would it start working perfectly fine after a reboot then?

**Comment by AnimateShadows** [comment]
likely because the library doesn't know about the components after you restart and doesn't attach them to a view object (that does the auto deferring)

**Comment by KosmicAnomaly** [comment]
Is there a way to disable the auto-deferring?

**Comment by AnimateShadows** [comment]
No.

**Comment by AnimateShadows** [comment]
This is a horrible solution

**Comment by KosmicAnomaly** [comment]
It is a glorious solution

**Comment by Dorukyum** [comment]
It is highly suggested to use the callback attribute of the component and not `on_interaction`.
