### ISSUE TITLE
ScheduledEvent.subscribers() and event.subsciber_count don't work

### ISSUE THREAD

**Issue by djee-dev** [Pycord-Development/pycord#780]
### Summary

Guild.get_scheduled_event() doesn't get event.subscribers

### Reproduction Steps

```py
event = ctx.guild.get_scheduled_event(int(eventid))

if event is not None:
    print('Got event')
    print(f'Event name: {event.name}') # Works
    print(f'Event description: {event.description}') # Works
    print(f'Event subs: {event.subscriber_count}') # Doesn't work without Guild.fetch_scheduled_events()
    print(f'Event interested: {event.interested}') # Doesn't work without Guild.fetch_scheduled_events()
            
    async for member in event.subscribers(limit=100, as_member=True, before=datetime.datetime.utcnow, after=event.created_at):
        print(member.display_name)
```

Also repricable with Guild.fetch_scheduled_events()

### Expected Results

List of event.subscribers

### Actual Results

site-packages\discord\iterators.py", line 805, in fill_subs
    before = self.before.id if self.before else None
AttributeError: 'builtin_function_or_method' object has no attribute 'id'

discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'builtin_function_or_method' object has no attribute 'id'

### Intents

guilds=True, members=True, reactions=True, scheduled_events=True

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4771+gef9b5983
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Middledot** [comment]
This is an API limitation, the subscriber_count is optional information and so not given when the bot starts up (or on events iirc).
In the `before` parameter in `event.subscribers`, you forgot to call the datetime method (`datetime.datetime.utcnow()`)

**Comment by djee-dev** [comment]
> This is an API limitation, the subscriber_count is optional information and so not given when the bot starts up (or on events iirc). In the `before` parameter in `event.subscribers`, you forgot to call the datetime method (`datetime.datetime.utcnow()`)

The thing is that my bot is started up and even gets the name, description etc...
I made this a slash command to enter whenever I like and then print out the infos on my terminal...

And thanks for the call thing, but this happened because I changed the code so often for reporting my issues.
The new error is now
```
site-packages\discord\state.py", line 330, in store_user
    user_id = int(data['id'])
KeyError: 'id'

discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'id'
```

which I also reported.

**Comment by Middledot** [comment]
> > This is an API limitation, the subscriber_count is optional information and so not given when the bot starts up (or on events iirc). In the `before` parameter in `event.subscribers`, you forgot to call the datetime method (`datetime.datetime.utcnow()`)
> 
> The thing is that my bot is started up and even gets the name, description etc... I made this a slash command to enter whenever I like and then print out the infos on my terminal...
> 
> And thanks for the call thing, but this happened because I changed the code so often for reporting my issues. The new error is now
> 
> ```
> site-packages\discord\state.py", line 330, in store_user
>     user_id = int(data['id'])
> KeyError: 'id'
> 
> discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'id'
> ```
> 
> which I also reported.

Is this the full traceback?

**Comment by djee-dev** [comment]
PS:
[Guild.get_scheduled_event()](https://docs.pycord.dev/en/master/api.html?highlight=scheduled#discord.Guild.get_scheduled_event) is not an API call..
[Guild.fetch_scheduled_event()](https://docs.pycord.dev/en/master/api.html?highlight=event#discord.Guild.fetch_scheduled_event) is.

**Comment by djee-dev** [comment]
> > > This is an API limitation, the subscriber_count is optional information and so not given when the bot starts up (or on events iirc). In the `before` parameter in `event.subscribers`, you forgot to call the datetime method (`datetime.datetime.utcnow()`)
> > 
> > 
> > The thing is that my bot is started up and even gets the name, description etc... I made this a slash command to enter whenever I like and then print out the infos on my terminal...
> > And thanks for the call thing, but this happened because I changed the code so often for reporting my issues. The new error is now
> > ```
> > site-packages\discord\state.py", line 330, in store_user
> >     user_id = int(data['id'])
> > KeyError: 'id'
> > 
> > discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'id'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which I also reported.
> 
> Is this the full traceback?

Here's the full one:
```
Ignoring exception in command <discord.commands.SlashCommand name=getevent>:
Traceback (most recent call last):
  File "lib\site-packages\discord\commands\commands.py", line 97, in wrapped
    ret = await coro(arg)
  File "lib\site-packages\discord\commands\commands.py", line 627, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "\cogs\getevent.py", line 35, in getevent
    async for member in event.subscribers(limit=100, as_member=True, before=datetime.datetime.utcnow(), after=event.created_at):
  File "\lib\site-packages\discord\iterators.py", line 126, in __anext__
    return await self.next()
  File "\lib\site-packages\discord\iterators.py", line 774, in next
    await self.fill_subs()
  File "\lib\site-packages\discord\iterators.py", line 811, in fill_subs
    self.subscribers.put(self.member_from_payload(element))
  File "\lib\site-packages\discord\iterators.py", line 796, in member_from_payload
    return Member(data=member, guild=self.event.guild, state=self.event._state)
  File "\lib\site-packages\discord\member.py", line 294, in __init__
    self._user: User = state.store_user(data['user'])
  File "\lib\site-packages\discord\state.py", line 330, in store_user
    user_id = int(data['id'])
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\lib\site-packages\discord\bot.py", line 512, in process_application_commands
    await ctx.command.invoke(ctx)
  File "\lib\site-packages\discord\commands\commands.py", line 215, in invoke
    await injected(ctx)
  File "\lib\site-packages\discord\commands\commands.py", line 103, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'id'
```
