### ISSUE TITLE
Bot fails to register slash commands after adding a new argument

### ISSUE THREAD

**Issue by Andell4301** [Pycord-Development/pycord#798]
### Summary

After adding a new argument to an existing slash command, the bot fails to register commands.

### Reproduction Steps

Create a relatively simple bot with a slash command and run the bot. Then turn the bot off, and add an argument to the slash command. Run the bot again and it will fail to register commands with the following error:

```
Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\Andell\Desktop\New folder\env\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Andell\Desktop\New folder\env\lib\site-packages\discord\bot.py", line 785, in on_connect
    await self.register_commands()
  File "C:\Users\Andell\Desktop\New folder\env\lib\site-packages\discord\bot.py", line 278, in register_commands
    if key2 in match[key][i].keys():
IndexError: list index out of range
```

### Minimal Reproducible Code

```python
Run the following bot first:

from discord.ext import commands
bot = commands.Bot()

@bot.slash_command()
async def test(ctx, a):
    await ctx.respond("Test")

bot.run("TOKEN")
```

Then close it, and run the following:
```py
from discord.ext import commands
bot = commands.Bot()

@bot.slash_command()
async def test(ctx, a, b):
    await ctx.respond("Test")

bot.run("TOKEN")
```

### Expected Results

The bot will run and register command successfully, and the new command will be usable with the new argument.

### Actual Results

The bot does not register commands successfully. No slash commands can be used.

### Intents

None

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4795+g71c0711e
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I've seen people post similar errors in the discord since the end of December and as recent as yesterday at the time of posting, but I couldn't find a bug report for it. The closest I could find was https://github.com/Pycord-Development/pycord/issues/747 which seems to be getting the same issue, but the context of how it was reproduced there is different.

**Comment by Dorukyum** [comment]
A new registration system is under work. You can join our Discord server (discord.gg/pycord) to stay updated.
