### ISSUE TITLE
Compatibility of SlashCommands with the existing HelpCommand classes

### ISSUE THREAD

**Issue by TheSlayerishere** [Pycord-Development/pycord#805]
### Summary

The HelpCommand classes do not include SlashCommands in them, I'd like for this to be fixed

### What is the feature request for?

The core library

### The Problem

The problem is that currently if we use the default help command in pycord, it completely ignores SlashCommands.

This problem seems to stem from the difference in SlashCommands as in normal commands, say, the mapping object has a  `<discord.commands.SlashCommand name=hello>`  for slash command rather than just a `hello` for a normal command, this difference leads to exceptions, which ultimately results in SlashCommands being ignored altogether.

### The Ideal Solution

Well, we could add a signature attribute to SlashCommands which has the possibility of making this compatible with lots of current existing code

### The Current Solution

Currently, we can change the HelpCommand class to  use (command).name to get the name of a slash command, this will allow to 
go on with our work as usual

### Additional Context

again, the issue here is that the mapping object in `send_bot_help` function returns something different from the usual thing for commands, leading to exceptions, and ultimately ignoring the entire thing. there will probably be better ways to fix this than what I've mentioned here.

**Comment by EmreTech** [comment]
What's the purpose of this? The fundamentals of how Slash Commands work (by typing `/`) means that there is no need for a Help Command. The context menu that shows up shows you all of the commands available, what they accept as inputs, and a description.

**Comment by krittick** [comment]
I'm actually already working on a unified help command using ext.pages, so I'll assign this to myself.

**Comment by krittick** [comment]
Note that this likely won't change any of the ext.commands Help-related classes though.

**Comment by TheSlayerishere** [comment]
> What's the purpose of this? The fundamentals of how Slash Commands work (by typing `/`) means that there is no need for a Help Command. The context menu that shows up shows you all of the commands available, what they accept as inputs, and a description.

Sorry, for not responding, but this is simply a convenience feature, a help command helps us to categorise and look through all the commands in a bot, having slash commands included simply helps in user experience.
Discord currently just dumps all slash commands to choose from in one place, being able to categorise the commands helps in finding the correct thing, no?

**Comment by Dorukyum** [comment]
There is no plan in including slash commands in the default help command as they just show up when you type `/`.
