### ISSUE TITLE
SlashCommandGroups are broken again 😢 

### ISSUE THREAD

**Issue by timmypidashev** [Pycord-Development/pycord#811]
### Summary

Basically completely broken registration of slash command groups

### Reproduction Steps

Create a SlashCommandGroup with at least 2 slash commands within. 

**THIS WORKS**
```python
group = SlashCommandGroup(
    "group", "descr here"
)

@group.command(
    description="descr here"
)
async def cmd1(self, context):
    pass
```
**THIS DOESNT**
```python
group = SlashCommandGroup(
    "group" "descr here"
)

@group.command(
    descriptiopn="descr here"
)
async def cmd1(self, context):
    pass

@group.command(
   description="descr here"
)
async def cmd2(self, context):
    pass
```

### Minimal Reproducible Code

```python
group = SlashCommandGroup(
    "group" "descr here"
)

@group.command(
    descriptiopn="descr here"
)
async def cmd1(self, context):
    pass

@group.command(
   description="descr here"
)
async def cmd2(self, context):
    pass
```

### Expected Results

A working slashcommandgroup

### Actual Results

```bash
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/discord/bot.py", line 785, in on_connect
    await self.register_commands()
  File "/usr/local/lib/python3.8/dist-packages/discord/bot.py", line 278, in register_commands
    if key2 in match[key][i].keys():
IndexError: list index out of range
```

### Intents

All intents(testing bot so yee)

### System Information

- Python v3.8.10-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a0
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-94-generic

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This wasn't an issue before, and now legacy code breaks. Assuming this was a pr or something that introduced it. Will keep looking to find a fix, and im aware that SlashCommandGroups are undergoing a rework.

**Comment by EmreTech** [comment]
I thought SlashCommandGroups were being reworked?

**Comment by Lulalaby** [comment]
This is already been working on with a rework of the whole registration

**Comment by Maschga** [comment]
Hi, I am still getting this error with the latest version of Pycord. Is there a timeline when this bug will be fixed or when will the rework be finished?

**Comment by Lulalaby** [comment]
We're finishing the rewrok with the release.
The progress is going well. Ask @BobDotCom for more infos

**Comment by timmypidashev** [comment]
I can't wait im getting same error as well

**Comment by Dorukyum** [comment]
This is an alpha version and by using it you accept that there might be bugs so please be patient as we try to fix them.

**Comment by timmypidashev** [comment]
Ok so I noticed v2 just went into beta. Does this mean the groups are working now? Just curious, since the projects board hasn't gotten updated.

**Comment by Lulalaby** [comment]
just wait

**Comment by timmypidashev** [comment]
> just wait

Alr sounds good :D

**Comment by krittick** [comment]
Re-opening as we've been able to reproduce this issue on demand and it might warrant a fix before #759

**Comment by krittick** [comment]
Also related to #798

**Comment by timmypidashev** [comment]
Sigh
