### ISSUE TITLE
Permission for MessageCommand

### ISSUE THREAD

**Issue by sushichan044** [Pycord-Development/pycord#820]
### Summary

Permission for MessageCommand

### What is the feature request for?

The core library

### The Problem

I'm making a bot uses MessageCommands(Application Command).
And I am trying to create a command that can only be operated by members with permissions 'Manage Messages'.
But from the example code, it looks like permissions can only be set by role or ID.

### The Ideal Solution

I want a decorator for make the ApplicationCommand can be operated by members have specific permissions like 'Manage Messages'.

### Additional Context

This is my first issue so I may not have written it correctly.

**Comment by Dorukyum** [comment]
You can use commands.check or wait until the new permission system is released.
