### ISSUE TITLE
Aliases for slash commands

### ISSUE THREAD

**Issue by JavaProgswing** [Pycord-Development/pycord#84]
### Summary

This will allow slash commands to have multiple names

### What is the feature request for?

discord.ext.commands

### The Problem

It will solve the issue in which you have to write a seperate command for every aliases of your one command which does the same thing .

### The Ideal Solution

If this feature is implemented then the slash command can be accessed by multiple names , like the following example
`@client.slash_command(aliases=["dc","disconnect"])
@commands.guild_only()
async def leave(ctx):`
this command then could be executed by "dc" , "disconnect" and "leave".

**Comment by Luc1412** [comment]
The reason for aliases to exists was simplifying the process of invoking a commands. Slash Commands provide autocomplete which extinguishes this problem.

Aliases would be bad practice and just decrease the userbility by cluttering the command selection.

**Comment by Div-100** [comment]
> The reason for aliases to exists was simplifying the process of invoking a commands. Slash Commands provide autocomplete which extinguishes this problem.
> 
> Aliases would be bad practice and just decrease the userbility by cluttering the command selection.

I was gonna almost say the same thing-
