### ISSUE TITLE
Allow ctx and cog to be passed as kwargs to chained decorators

### ISSUE THREAD

**Issue by AmirAvram** [Pycord-Development/pycord#841]
### Summary

Allow cog and ctx to be passed as **kwargs instead of **args to chained decorators

### What is the feature request for?

discord.ext.commands

### The Problem

In file discord/commands/core.py the _invoke function calls self.callback and passes self.cog and ctx as **args and not **kwargs

### The Ideal Solution

In the file discord/commands/core.py function _invoke pass the argument self.cog as cog=self.cog and ctx as ctx=ctx
for example line 722: 
from:            await self.callback(self.cog, ctx, **kwargs)
to:            await self.callback(cog=self.cog, ctx=ctx, **kwargs)

Allowing chained decorators to use self.cog and ctx as **kwargs and not just guessing its position inside **args

**Comment by EmreTech** [comment]
Probably the reason why this wasn't added before is that not everyone calls the context parameter `ctx` or the cog parameter `self`. So if a person that does that uses the library, it won't work for them.

**Comment by Dorukyum** [comment]
As EmreTech has stated, the name of the parameters can change.
