### ISSUE TITLE
SlashCommandGroup Doesn't Support Some Keyword Arguments

### ISSUE THREAD

**Issue by HoggyTheWizard** [Pycord-Development/pycord#845]
### Summary

SlashCommandGroup does not accept keyword arguments for name and description

### Reproduction Steps

Initially I had used SlashCommandGroup like so:
```py
test_group = SlashCommandGroup(name="test", description="Please work")
```

However this was raising this error:

`TypeError: discord.commands.core.SlashCommandGroup() got multiple values for keyword argument 'name'` upon startup. 

After doing some digging, I discovered that this only applied to keyword arguments. Simply doing:
```py
test_group = SlashCommandGroup("test", "Please work")
```
does in fact work. 

### Minimal Reproducible Code

```python
from discord.commands import SlashCommandGroup
from discord.ext import commands

class TestClass(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    test_group = SlashCommandGroup(name="test", description="Please work")  # see `name` and `description`

    @test_group.command()
    async def test_command(self, ctx):
        await ctx.respond("Hey look, it worked!")

def setup(bot):
    bot.add_cog(TestClass(bot))
```

### Expected Results

Using keyword arguments for SlashCommandGroup should not raise an error. 

### Actual Results

It returned `TypeError: discord.commands.core.SlashCommandGroup() got multiple values for keyword argument 'name'` upon startup, therefore not loading the command. The same error also applies to `description`.

### Intents

all

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4850+gd2878166
- aiohttp v3.8.0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
Can't reproduce.

**Comment by Dorukyum** [comment]
Closing as stale and still unreproducable.
