### ISSUE TITLE
Set pagination's current page before pagination is sent or responded

### ISSUE THREAD

**Issue by bensaine** [Pycord-Development/pycord#858]
### Summary

The ability to set the inital current page index before sending a pagination message.

### What is the feature request for?

discord.ext.pages

### The Problem

I'll give an example use case:

Say I have a school schedule system in my discord bot. Using a command I can view each day of the week and my classes for that day (See screenshot).  Page 1 is Monday all the way to page 7 being Sunday.

![image](https://user-images.githubusercontent.com/34781348/151098747-ef3b8fa2-5f88-4cab-8fa0-b28f06e3e7ca.png)

Now, say I want the initial page shown to be the current day of the week. Meaning, by default this command displays my current day, and can still navigate through the week.  If today is Tuesday, the page would be `2/7`.  Unfortunately, there is no way to set the current page index before sending the pagination.

### The Ideal Solution

Ideally, either goto_page() could be called before the pagination is responded (`pagination.respond()`) or sent (`pagination.send()`) (currently it throws an error if this is the case) or another method like set_initial_page() could be added.

### The Current Solution

Right now, the best way to do this is to `pagination.send()` or `pagination.respond()` and immediately after call `pagination.goto_page(desired_index)`. However, this gives a displeasing glitch as it quickly switches from page 1 to `desired_index` when sent. 

Another way, but just a work-around, is to make your `pages` list start with your desired page's message (or embed). So if today is Tuesday, my pages list would look like `[tue, wed, thu, fri, sat, sun, mon]`. But this is not great as I want Tuesday to be `2/7` and not `1/7`.

**Comment by krittick** [comment]
I've submitted #859 to address this. Thanks for the feedback!
