### ISSUE TITLE
.ext.pages suggestions

### ISSUE THREAD

**Issue by nziie214** [Pycord-Development/pycord#870]
### Summary

1. A kwarg for `pages.Paginator` (name: quitButton=bool; False by default).  2. An event that people can use when the paginator is completely done: whether it's by timeout, or by the quit button being pressed. 3. A method to stop the paginator (if there isn't already one): `self.paginator.stop()' if subclassed

### What is the feature request for?

discord.ext.pages

### The Problem

Quit Button: So users can stop the paginator early without having to wait for a timeout
Event: So developers can do stuff when a paginator has ended
(If event is not added) Stop paginator: To stop the paginator 

### The Ideal Solution

Quit Button: This can possibly be set by a `discord.ui.Button` object so there is more customization (e.g. be able to set the color, label, etc), this will call the `paginator_disabled` event). If a discord.ui.Button object is not provided, it could default to a button object being (did this in a dictionary so it's easier to read: {"label": "Quit", "style": Discord.ButtonStyle.red}
Event: In this event, developers can ✨ make stuff happen ✨(e.g. send a message in the channel or edit `self.message` to say something)
(THIS CAN BE ADDED IF THE EVENT IS NOT ADDED) Stop method: This will simply stop the paginator and the bot won't do anything when the buttons are clicked.

**Comment by krittick** [comment]
Item 3 has been implemented in #895, item 2 has been determined as not being a good fit for the extension as it doesn't meet our other criteria for event dispatching (i.e. most dispatched events should correspond to an API event).

Item 1 is on the roadmap as part of a larger feature addition to include a second row of "action" buttons for interacting with the paginator and page contents.
