### ISSUE TITLE
Exception when starting bot with guilds+members intent using bot.start()

### ISSUE THREAD

**Issue by snazzyfox** [Pycord-Development/pycord#872]
### Summary

When starting the bot using bot.start() instead of bot.run(), an exception is thrown if guilds and members intents are both enabled.

### Reproduction Steps

Run a bot with the minimum bot code below.

### Minimal Reproducible Code

```python
import discord
import asyncio

bot = discord.Bot(intents=discord.Intents(guilds=True, members=True))

async def main():
    # await initialize_database() ...
    await bot.start('TOKEN')

asyncio.run(main())
```

### Expected Results

The bot starts up.

### Actual Results

The following traceback is printed:

```
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<ConnectionState._delay_ready() done, defined at C:\Users\snaz\AppData\Local\pypoetry\Cache\virtualenvs\temp-test-coV1hBcm-py3.10\lib\site-packages\discord\state.py:503> exception=ValueError('The future belongs to a different loop than the one specified as the loop argument')>
Traceback (most recent call last):
  File "C:\Users\snaz\AppData\Local\pypoetry\Cache\virtualenvs\discord-dingomata-coV1hBcm-py3.10\lib\site-packages\discord\state.py", line 525, in _delay_ready
    await asyncio.wait_for(future, timeout=5.0)
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 426, in wait_for
    fut = ensure_future(fut, loop=loop)
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 621, in _ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument
```

### Intents

discord.Intents(guilds=True, members=True)

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-candidate
    - py-cord pkg_resources: v2.0.0rc1
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

- This only happens when both guilds and members intents are turned on
- This only happens when I start the bot with `bot.start()`. It does not happen with `bot.run()`.
- Same results if I use `loop.run_until_complete(bot.start())` instaed of `asyncio.run(main())`

**Comment by EmreTech** [comment]
Can you try other intents? Also why are you using `bot.start` to start the bot instead of running it with `bot.run`?

**Comment by snazzyfox** [comment]
Other intents do not cause this issue. Using `guilds` or `members` intent on their own also are ok. This issue only appears when **both** `guilds` and `members` are requested (regardless of what other intents are present), but I would imagine this combination is fairly commonly used.

I'm trying to use `start()` because I need to run some additional async code at startup time *before* the bot is ready, but in the same event loop, for example creating database connections. I'd prefer not using the `on_ready` event, because it's run after the bot is connected and can be called multiple times while the bot is running.

**Comment by nbowen** [comment]
No fixes here, but some additional info and workarounds:

In my testing, this "different loop" ValueError occurs consistently when the Guilds and Members intents are used together _without_ the Presences intent. Other intents can be included or not, but when Guilds and Members are provided together, Presences also has to be included to prevent the error.

Digging into the stack a bit, I could find places where two different loops existed and probably shouldn't, but I don't yet understand why.

In case it helps anyone else, the startup also consistently worked fine for me if I replaced:
```
asyncio.run(main())
```
with
```
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by nbowen** [comment]
I can still reproduce this as of v2.0.0, I don't think it should be closed yet.

**Comment by EmreTech** [comment]
See https://discord.com/channels/881207955029110855/881735314987708456/995539823928545280 (on the Pycord Support server)

**Comment by nbowen** [comment]
I see; thank you!

**Comment by netrunnernobody** [comment]
Having this exact same issue - not sure if there's any useful information to contribute that other users haven't, yet.
