### ISSUE TITLE
view_channels permission can't be called via member.guild_permissions

### ISSUE THREAD

**Issue by BlckViper** [Pycord-Development/pycord#875]
### Summary

view_channels permission can't be called via member.guild_permissions

### Reproduction Steps

```py
import discord
from discord.ext import commands

TOKEN = 'YOUR_DISCORD_BOT_TOKEN'
PREFIX = '!'
INTENTS = discord.Intents.all()

bot = commands.Bot(command_prefix=PREFIX, intents=INTENTS)

@bot.command()
async def test(ctx):
    ctxa: discord.Member = ctx.author
    [print(a) for a in ctxa.guild_permissions]

bot.run(TOKEN)
```

### Expected Results

```py
>>> (view_channels, True)
```

### Actual Results

Any other permissions would be shown, but not the `view_channels` permission

### Intents

discord.Intents.all()

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4841+gc3265c24
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
`view_channels` is not a valid permission unlike `view_channel`.

**Comment by BlckViper** [comment]
> `view_channels` is not a valid permission unlike `view_channel`.

There is a permission called `view_channel`
https://docs.pycord.dev/en/master/api.html?highlight=edit#discord.Permissions

**Comment by Lulalaby** [comment]
exactly and you expect the wrong one

**Comment by BlckViper** [comment]
> But anyways the permission `view_channel` doesn't exist in `member.guild_permissions`

**Comment by Lulalaby** [comment]
Use `read_messages`

**Comment by BlckViper** [comment]
> Use `read_messages`
Anyways there are still voice channels and you can't read text from a voice channel.

Example:
Users can't see voice channels, but the voice channel him self, still exist.
