### ISSUE TITLE
view_channel permission is not listed in the member.guild_permissions

### ISSUE THREAD

**Issue by BlckViper** [Pycord-Development/pycord#878]
### Summary

view_channel permission is not listed in the member.guild_permissions

### Reproduction Steps

```py
import discord
from discord.ext import commands

TOKEN = 'YOUR_DISCORD_BOT_TOKEN'
PREFIX = '!'
INTENTS = discord.Intents.all()

bot = commands.Bot(command_prefix=PREFIX, intents=INTENTS)

@bot.command()
async def test(ctx):
    ctxa: discord.Member = ctx.author
    [print(a) for a in ctxa.guild_permissions]

bot.run(TOKEN)
```

### Minimal Reproducible Code

```py
[print(a) for a in ctxa.guild_permissions]
```

### Expected Results

```py
>>> (view_channel, True)
```

or

```py
>>> (view_channel, False)
```

### Actual Results

All other permissions, but not the `view_channel` permission in the console

### Intents

discord.Intents.all()

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4876+gf3143023
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

There is the permission:
https://docs.pycord.dev/en/master/api.html?highlight=view_channel#discord.Permissions.view_channel

The permission in the internal discord guild permission system:
![grafik](https://user-images.githubusercontent.com/57014404/151614230-735daf1d-4dca-4846-8cc0-1aeb0eb0daa1.png)

The `view_channel` must be in the `member.guild_permissions`, cause of the following example:
Users can't see a voice channel, but the voice channel him self, still exist.

**So the discord bot can't even know if:**
- the channel doesn't exist, 

**`or`**
 
- he doesn't have the permission to view the channel.

**Comment by Dorukyum** [comment]
`view_channel` is supposed to be channel-based as stated in the API docs:
> Allows guild members to view a channel

**Comment by BlckViper** [comment]
> `view_channel` is supposed to be channel-based as stated in the API docs:

The view_channel must be in the member.guild_permissions, cause of the following example:
Users can't see a voice channel, but the voice channel him self, still exist.

So the discord bot can't even know if:

    the channel doesn't exist,

or

    he doesn't have the permission to view the channel.


And `view_channel` permission includes the `read_messages` permissions, when the channel is a text channel.
But when the channel is a voice channel you CAN'T read messages in there.

So if check, if the bot has the permission to read messages, the bot can read messages in a text channel.
But if the bot has the `read_messages` permission and not the `view_channel` permission, 
he CAN'T see the voice channel.

So there is definitely a bug in the pycord api.

**Comment by BlckViper** [comment]
> `view_channel` is supposed to be channel-based as stated in the API docs

Yeah, you can call every channel permission like `create_instant_invite` as a "channel-based" permission,
cause you can edit those permissions a specific role. So the member with the permission `create_instant_invite` can create invites generally. 
But when you remove the permission `create_instant_invite` from the same role from a channel, all the users with this role can't anymore create invites to the specific channel.

**Comment by Dorukyum** [comment]
After testing, `guild_permissions.view_channel` is a thing (returned True) but it's not included while iterating.

**Comment by BlckViper** [comment]
> After testing, `guild_permissions.view_channel` is a thing (returned True) but it's not included while iterating.

Yeah, because you with the `guild_permissions.view_channel` the view_channel permission to true.
With other words, you didn't check the permission. You set the permission.

**Comment by BlckViper** [comment]
> After testing, `guild_permissions.view_channel` is a thing (returned True) but it's not included while iterating.

If it's better for you, we can go asap in a voice call and i will explain it to you as good as i can.

**Comment by Dorukyum** [comment]
> > After testing, `guild_permissions.view_channel` is a thing (returned True) but it's not included while iterating.
> 
> Yeah, because you with the `guild_permissions.view_channel` the view_channel permission to true. With other words, you didn't check the permission. You set the permission.

What I said was that there _was_ a bug. However, I wasn't setting the permission but I was viewing it: `return ctx.author.guild_permissions.view_channel`

**Comment by BlckViper** [comment]
> What I said was that there was a bug. However, I wasn't setting the permission but I was viewing it: return ctx.author.guild_permissions.view_channel

Okay, but anyways can you guys please fix this bug with the `member.guild_permissions` and the missing `view_channel` permission?

**Comment by Dorukyum** [comment]
It seems `view_channel` isn't included in `Permissions.all`.

**Comment by BlckViper** [comment]
> It seems `view_channel` isn't included in `Permissions.all`.

Will this be fixed too?

**Comment by Dorukyum** [comment]
Yes, as create_instant_activity behaves different showing something's wrong here.

> > It seems `view_channel` isn't included in `Permissions.all`.
> 
> Will this be fixed too?

**Comment by BlckViper** [comment]
So both bugs which are now found would be fixed?

**Comment by rtk-rnjn** [comment]
Not a bug, both `view_channel` and `read_messages` are same. `view_channel` is aliases for `read_messages`
https://github.com/Pycord-Development/pycord/blob/master/discord/permissions.py#L335-L346

**Comment by plun1331** [comment]
imo `read_messages` should be an alias for `view_channels`
