### ISSUE TITLE
case_insensitive not working properly in 2.0.0b1

### ISSUE THREAD

**Issue by Dearex** [Pycord-Development/pycord#885]
### Summary

Commands will only be accepted if they are full lowercase

### Reproduction Steps

Implement command with not only lowercase letters
Add case_insensitive=True
Command is only accessible with full lowercase 

Tested the same setup in 2.0.0b1 and 1.7.3
1.7.3 accepted all inputs as Command, 2.0.0b1 only accepts lowercase commands

### Minimal Reproducible Code

```python
from discord.ext import commands

comand_prefix = "-"
bot_token = open("Bot_Token.txt").readline()

bot = commands.Bot(command_prefix=comand_prefix, case_insensitive=True)

class a(commands.Cog, name="Cog Name"):

    @commands.command()
    async def Test(self, ctx):
        print("test")

bot.add_cog(a(bot))
bot.run(bot_token)

# -> Accepts "-test" but not "-Test"
```

### Expected Results

Accept commands case insensitive

### Actual Results

Accepts commands only when lowercase, otherwise CommandNotFound error

### Intents

None

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

**Comment by rtk-rnjn** [comment]
> https://discord.com/channels/881207955029110855/881224361015672863/934131768938876958

I saw that coming...

Probably this is causing the issues:

https://github.com/Pycord-Development/pycord/blob/master/discord/ext/commands/core.py#L1174-L1179
