### ISSUE TITLE
Custom events

### ISSUE THREAD

**Issue by pintermor9** [Pycord-Development/pycord#889]
### Summary

Make custom events, that people could call from anywhere in their bot. 

### What is the feature request for?

The core library

### The Problem

If I want functions to be accessable from anywhere i need these long imports:
```py
from  ..Utils import test
```
But sometimes, its really hard to do it this way

### The Ideal Solution

So you could make custom events which would work like this:
```py
# This is how you'd set up an event
@bot.listen("my_test_event")
async def _my_test_event(bot, *args, **kwargs):
    print("do something with", args, kwargs)

#This is how you'd call it
@bot.command
async def call_test_command(ctx):
    bot.emit("my_test_event", "this is an arg", and="this is a kwarg")
```

#### Update! 
```py
async def _my_bad_solution(*args, **kwargs):
    print("do something with", args, kwargs)

bot.my_test_event = _my_bad_solution

#calling it:
@bot.command
async def call_test_command(ctx):
    bot.my_test_event("this is an arg", and="this is a kwarg")
```
**BUT THIS CALLS THE _EVENT_ ONLY AT ONE PLACE**
I would like to be able to listen to these events at different places (cogs).

**Comment by zeffo** [comment]
You can use the `dispatch` method: https://github.com/Pycord-Development/pycord/blob/master/discord/client.py#L366

**Comment by pintermor9** [comment]
Ohh, thanks
