### ISSUE TITLE
v2.0.0b1 Ineteraction fail to delete_after if some other interaction is send during the waiting time for delete

### ISSUE THREAD

**Issue by Grolicek** [Pycord-Development/pycord#899]
### Summary

Ineteraction fail to delete_after if some other interaction is send during the waiting time for delete

### Reproduction Steps

I was trying to delete interaction response after some time but it only deleted response, if in that window (for ex. for me 10sec) there wasn't any other interaction response.

### Minimal Reproducible Code

```python
await ctx.respond('Something', delete_after=10)
#if done at least once during countdown of first one
```

### Expected Results

`Ignoring exception in command <discord.commands.SlashCommand name=skip>:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/core.py", line 110, in wrapped
    ret = await coro(arg)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/core.py", line 762, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/runner/Musician7997/cogs/controlcommands.py", line 24, in skip
    await ctx.respond('Skipped', delete_after=10)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/interactions.py", line 614, in send_message
    await adapter.create_interaction_response(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 192, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 520, in process_application_commands
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/core.py", line 306, in invoke
    await injected(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/core.py", line 116, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction`

### Actual Results

Code runned in some error described earlier

### Intents

none

### System Information

- Python v3.9.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by zeffo** [comment]
I'm not sure I understand, are you responding to the same interaction twice?

**Comment by Grolicek** [comment]
> I'm not sure I understand, are you responding to the same interaction twice?

![Screenshot_20220202-064019_Discord](https://user-images.githubusercontent.com/58747066/152099235-672ab095-4746-4d91-9a0a-4401ea844460.jpg)
 
I sent 3 messages that responded with skipped in 10 seconds, but only the last one got deleted...

**Comment by BobDotCom** [comment]
Cannot reproduce.
```py
@bot.slash_command()
async def test_delete_after(ctx):
    await ctx.respond("testing1", delete_after=5)
    await ctx.respond("testing2", delete_after=5)
```
https://user-images.githubusercontent.com/71356958/152459826-42b02013-f29d-459c-a912-54232639dfa3.mov

**Comment by plun1331** [comment]
`delete_after` can't even raise this exception, as it ignores `HTTPException`.

The traceback also points to the interaction create method, and it's most likely a result of not responding to the interaction in the required timeframe.
