### ISSUE TITLE
Can't run any slash command

### ISSUE THREAD

**Issue by Asherlam** [Pycord-Development/pycord#914]
### Summary

Getting a loop task error while running any slash command

### Reproduction Steps

I got this error everytime when i run a slash command

### Minimal Reproducible Code

```python
ignored in: <function BaseEventLoop.__del__ at 0x7fba368b75e0>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 680, in __del__
    if not self.is_closed():
  File "/usr/lib/python3.9/asyncio/base_events.py", line 677, in is_closed
    return self._closed
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_closed'
```

### Expected Results

expect nothing to pop up and enable to run the slash command

### Actual Results

![image](https://user-images.githubusercontent.com/35485292/152471959-7d575368-efdf-4531-b948-fb3ce07feddf.png)

### Intents

default, member

### System Information

Discord Version: 2.0.0b3
Python Version: 3.10.0
OS: Ubuntu 21.10LTPS

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
Fixed by 2b8f6d3e0abfe778f43900326f315a2c974f5145
