### ISSUE TITLE
Unable to use bot.ipc.start()

### ISSUE THREAD

**Issue by gotwicked** [Pycord-Development/pycord#916]
### Summary

It is impossible to start the ipc client

### Reproduction Steps

I ran the code blow

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
from pycord.ext import ipc

class MyBot(commands.Bot):

	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)

		self.ipc = ipc.Server(self, secret_key="x")

	async def on_ready(self):
		print("Bot is ready.")

	async def on_ipc_ready(self):
		print("Ipc server is ready.")

	async def on_ipc_error(self, endpoint, error):
		print(endpoint, "raised", error)


bot = MyBot(command_prefix="x", intents=discord.Intents.all())

@bot.ipc.route()
async def get_guilds(data):
	return bot.guilds

bot.ipc.start()
bot.run(x)
```

### Expected Results

It should have printed Ipc server is ready.

### Actual Results

It printed the following error:
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    bot.ipc.start()
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\pycord\ext\ipc\server.py", line 253, in start
    self.bot.dispatch("ipc_ready")
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\bot.py", line 1268, in dispatch
    super().dispatch(event_name, *args, **kwargs)  # type: ignore
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 404, in dispatch
    self._schedule_event(coro, method, *args, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 364, in _schedule_event
    return asyncio.create_task(wrapped, name=f'pycord: {event_name}')
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'Client._run_event' was never awaited

### Intents

discord.Intents.all()

### System Information

- Python v3.8.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b3
- aiohttp v3.6.3
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
This is an issue with whichever ext.ipc library you're using. See #626 and the threads linked from it. 

The workaround until someone releases a fixed library is to remove the `on_ipc_ready` event handler.
