### ISSUE TITLE
Reloading cogs to refresh a slash command's callback

### ISSUE THREAD

**Issue by GDKID69** [Pycord-Development/pycord#917]
### Summary

Basically if you update a cog slash command's callback code, all you need to do is reload the cog to update it on the bot

### What is the feature request for?

The core library

### The Problem

I guess the "problem" is that making small changes to your bot's command's functionality is too slow, although it's not that big a deal to have to wait those few extra seconds.

### The Ideal Solution

Make it so that when you load/reload a cog, it gets the new callback from the cog's file and maps it to that same command, if this explanation isn't clear enough, you can just try it out with normal prefix-based commands (which already have this feature) and you'll see what I mean

__Steps:__
- Make a cog, add some prefix commands in it
- Run the bot
- Make some changes to the command's callback code
- Reload the cog
- Now when you run the command it should follow your new code

### The Current Solution

Right now, the only way to refresh the callback that I know of (I'm probably wrong on this) is to just restart your bot, which can take way longer than reloading a cog. In most cases, this feature won't have that big of an impact, just a nice QoL improvement.

### Additional Context

This is already up and working on normal prefix-based commands, so I was wondering if this mechanic can be added to cog slash commands as well

**Comment by Dorukyum** [comment]
Hasn't this been added with #700?

**Comment by pandabear189** [comment]
was reverted

**Comment by Dorukyum** [comment]
The revert was reverted (yes, really)

**Comment by GDKID69** [comment]
So it was a thing then it got removed??

**Comment by Dorukyum** [comment]
It was removed but added back.
