### ISSUE TITLE
Unknown Webhook error when using `interaction.original_message` - unable to edit or delete

### ISSUE THREAD

**Issue by Dhravya** [Pycord-Development/pycord#918]
### Summary

Any reference to the `original_message` of the interaction gives `discord.errors.NotFound` - Unknown webhook error

### Reproduction Steps

- Using version 2.0.0b3
- A discord ui view with `timeout=None` and buttons
- Try to edit (or delete or reference `_original_message` ) the original message 

This should raise the error

I think it could be because of the `timout=None`, but it also fails without the timeout

### Minimal Reproducible Code

```python
class DibsView(discord.ui.View):
    def __init__(self):
        super().__init__(timeout=None)

    @discord.ui.button(label="DIB", style=discord.ButtonStyle.green)
    async def dib(self, button:discord.Button, interaction:discord.Interaction):
        button.disabled=True
        await interaction.edit_original_message(view=self)
```

### Expected Results

Edit the original message 

### Actual Results

Gives error  `discord.errors.NotFound` - Unknown webhook error
```
  File "C:\Users\dhrav\Documents\Python Projects\Discord bot\ChappieRewrite\views\shop_views.py", line 150, in dib
    await interaction.edit_original_message(view=self)
  File "C:\Users\dhrav\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 354, in edit_original_message
    data = await adapter.edit_original_interaction_response(
  File "C:\Users\dhrav\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\webhook\async_.py", line 192, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
```

### Intents

All intents given

### System Information

Discord version 2.0.0b3
Windows 11

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
`edit_original_message` edits the interaction's **response**.
If you want to edit the message the interaction came from (the message with components), either use `interaction.response.edit_message` or `interaction.message.edit` if the interaction was already responded to.
