### ISSUE TITLE
Restricting Access with Slash Commands (Role/Permission Checks)

### ISSUE THREAD

**Issue by Space-Turtle0** [Pycord-Development/pycord#93]
### Summary

Factoring Permissions with Slash Commands

### What is the feature request for?

discord.ext.commands

### The Problem

Currently, there is no way of disabling or "blocking" the user from using a specific slash command. Could there be a way to use role checks (similar to d.py's `@command.has_role(..)`) which grey's out slash commands like so?
![image](https://user-images.githubusercontent.com/56415283/132044741-b3418da0-75ae-4125-ba59-6f19ee87b169.png)

Similar to the role check, but instead of raising an error if they don't have the role, they just won't be able to use it. 

### The Ideal Solution

To factor in permissions/role checks with slash commands.

### The Current Solution

N/A

### Additional Context

I know discord-interactions already has this feature (https://discord-interactions.readthedocs.io/en/latest/gettingstarted.html#want-to-restrict-access-setup-permissions), maybe we could port it over with a more decorator friendly method? Right now that syntax (no offense) discord interaction uses is very long and annoying to work with.

**Comment by Rxann** [comment]
It was announced in the discord server that this wasn't available yet, it will probably be coming soon!

**Comment by Space-Turtle0** [comment]
Which discord server? Discord Interactions?

**Comment by CodeWithSwastik** [comment]
The API doesn't have permissions *yet*, however we do support the checks the dpy has. It is in the development branch (slash branch). You can test it by installing the slash branch.

**Comment by CodeWithSwastik** [comment]
I think discord is working on this again so this can be reopened

**Comment by Dorukyum** [comment]
Implemented in #280.
