### ISSUE TITLE
pycord gives a weird error on startup when using a slash command with guild id

### ISSUE THREAD

**Issue by Highfire1** [Pycord-Development/pycord#933]
### Summary

pycord gives a weird error on startup when using a slash command with guild id

### Reproduction Steps

1) set up a venv
2) download/install pycord from github
3) register a slash command, with at least one guild id
4) start the bot
5) see error
6) bot seems to work fine though

### Minimal Reproducible Code

```python
import discord
from discord.commands import permissions
from discord.commands import Option

bot = discord.Bot()

good_guilds = [714354863349170187]

@bot.event
async def on_ready():
    print(f"\033[1;31;40mBOT STARTED: {bot.user} \033[0;0")

@bot.slash_command(guild_ids=good_guilds)
async def hello(
    ctx: discord.ApplicationContext,
    name: Option(str, "Enter your name"),
    gender: Option(str, "Choose your gender", choices=["Male", "Female", "Other"]),
    age: Option(int, "Enter your age", min_value=1, max_value=99, default=18)
):
    await ctx.respond(f"Hello {name}! Your gender is {gender} and you are {age} years old.")

bot.run('token')
```

### Expected Results

bot starts normally

### Actual Results

instead, pycord prints the following, then runs normally

Ignoring exception in on_connect
Traceback (most recent call last):
  File "C:\Users\Andy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Andy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\bot.py", line 1040, in on_connect
    await self.sync_commands()
  File "C:\Users\Andy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\bot.py", line 582, in sync_commands
    cmd.id = i["id"]
AttributeError: 'NoneType' object has no attribute 'id'

### Intents

none

### System Information

- Python v3.9.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by thegreenshark** [comment]
I also have this error. As a workaround, you can disable auto sync

**Comment by thegreenshark** [comment]
I also have this error. Python 3.9.5, Pycord 2.0.0b4, Aiohttp 3.7.4.post0, Windows 10 Pro 1803
The command itself works fine. So as a workaround to get rid of that error output, you can disable auto_sync_commands 
`bot = discord.Bot(auto_sync_commands = False)`
And sync them manually, ignoring the exception
```
@bot.event
async def on_connect():
    try:
        await bot.sync_commands()
    except: pass
```

**Comment by BobDotCom** [comment]
This should be fixed in the latest versions
