### ISSUE TITLE
There is no on_command() event for the new SlashApplications

### ISSUE THREAD

**Issue by JoshPaulie** [Pycord-Development/pycord#936]
### Summary

Discord.py had an on_command() to quick log any command that is ran or attempted.

### What is the feature request for?

The core library

### The Problem

I would like to log all the commands my users execute. This is still possible with the classic commands, but not the new slash commands.

### The Ideal Solution

Just some new event listeners! On error, on command, etc. 

### The Current Solution

I could patch it in to the library itself, but I would have to do for every new update.

**Comment by Dorukyum** [comment]
Application commands have all these events under on_application_command_x since the contexts will be different.

**Comment by JoshPaulie** [comment]
Ahh, okay. In discord.py I had an event like

```py
@bot.event
async def on_command(ctx):
    """Prints commands to PSEUDO console"""
    if ctx.author.id != BotConfig.GoonIDs.josh_paulie:
        message = ctx.message
        content = message.content
        goon = message.author.name
        now = datetime.now().strftime("%a %I:%M")
        print(BotConfig.pipe.join([f"{now}", goon, content]))
```

but you're saying that because each slash command has its own context, I can't do a catch all like this?

**Comment by krittick** [comment]
No, you still can. You just need to use the `on_application_command` event for slash commands instead of `on_command`.

**Comment by krittick** [comment]
The new properties added in #935 should help you with that as well.

**Comment by JoshPaulie** [comment]
> No, you still can. You just need to use the `on_application_command` event for slash commands instead of `on_command`. 

```py
@bot.event
async def on_application_command(ctx: discord.ApplicationContext):
    console.log(ctx.author, ctx.command.qualified_name)
``` 

This is perfect! Thank you. Here's my code for reference
