### ISSUE TITLE
slash commands in cogs

### ISSUE THREAD

**Issue by Rxann** [Pycord-Development/pycord#94]
### Summary

Add the ability to use commands.slash_command as a decorator

### What is the feature request for?

discord.ext.commands

### The Problem

I am trying to solve the problem of lack of the slash_command decorator for commands!

### The Ideal Solution

Add the ability to use the @commands.slash_command() decorator.

### The Current Solution

None

**Comment by Dorukyum** [comment]
ext-commands is an extension for prefixed commands, so I think a decorator that creates application commands should stay out of it.
