### ISSUE TITLE
Allow directories to be passed in load_extension

### ISSUE THREAD

**Issue by ajratnam** [Pycord-Development/pycord#946]
### Summary

Inbuilt feature for loading all extensions in a directory, instead of manually looping through them.

### What is the feature request for?

discord.ext.commands

### The Problem

Splitting our code into individual **cogs** or **extensions** is pretty common. So it is also common to have our **extensions** in its own separate folder. And people people end up manually looping using **os** or **globs** to do so. So i'm requesting a feature to have this inbuilt.

### The Ideal Solution

The most ideal solution would be like `bot.load_extension('directory_name')` or `bot.load_extensions(['directory_1', 'directory_2'])` which support loading multiple extensions and the directories. `bot.load_extensions(os.listdir('path'))`.

### Additional Context

Perhaps even an **exclude** kwarg to load all extensions except the specified ones.

**Comment by krittick** [comment]
Good feature request. I'll see about implementing this.

**Comment by EmreTech** [comment]
I've actually been working on something similar for Nextcord. Maybe I could port it over for you guys.

**Comment by Dorukyum** [comment]
@EmreTech @krittick any updates?

**Comment by krittick** [comment]
Not really, it's still planned for 2.1 and my focus has been on 2.0 items.

**Comment by EmreTech** [comment]
I'll look into porting my Nextcord PR over to here, but it's not going to happen right now. It'll probably happen during next week if I ever decide to port it over.
