### ISSUE TITLE
Error "The application did not respond" too frequent.

### ISSUE THREAD

**Issue by Tommodev-06** [Pycord-Development/pycord#947]
### Summary

I got "The application did not respond" a lot of times when using slash commands.

### Reproduction Steps

I created a slash commands (code below) and I got the "The application did not respond" error on Discord a lot of times, with different commands. That's strange since with another library the commnd works.

```py
    @slash_command(description="Get information about a user.")
    async def userinfo(
            self,
            ctx,
            user: Option(discord.Member, "User to show information about.", required=False)
    ):
        user = user or ctx.author

        embed = discord.Embed(
            title=f"Information about {user}",
            color=embed_color
        )
        embed.add_field(name="Joined the server", value=f"<t:{round(user.joined_at.timestamp())}:R>")
        embed.add_field(name="Account created", value=f"<t:{round(user.created_at.timestamp())}:R>")
        members = sorted(ctx.guild.members, key=lambda m: m.joined_at)
        embed.add_field(name="Join position", value=str(members.index(user) + 1), inline=False)
        if len(user.roles) > 1:
            roles = ", ".join([role.mention for role in list(user.roles[::-1]) if not role is ctx.guild.default_role])
            embed.add_field(name=f"Roles [{len(user.roles) - 1}]", value=roles)
        embed.set_thumbnail(url=f"{user.avatar}")

        await ctx.respond(embed=embed)
```

### Expected Results

I expect the command not failing since it is a command that doesn't require a lot of time to process.

### Actual Results

![image](https://user-images.githubusercontent.com/83727432/152696127-d7a54356-fa5e-4dca-97c5-7a0d0d5dda5d.png)

### Intents

All of them

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b1
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
You have ~3 seconds to respond and your code looks too complex.
Please defer before creating the embed.

**Comment by Tommodev-06** [comment]
Very useful lmao

**Comment by Tommodev-06** [comment]
My code is clearly not complex. It is also clear you are arrogant and that you didn't look at my code. Bye

**Comment by AnimateShadows** [comment]
@Lulalaby this would likely not take more than 3 seconds to run. It's probably an issue elsewhere.
