### ISSUE TITLE
Command sync loop doesn't work as intended

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#948]
### Summary

Command sync loop doesn't work as intended

### Reproduction Steps

Delete all commands. Sync all commands.

### Expected Results

All commands will be added as bulk

### Actual Results

Every single commands gets manually created.

### Intents

guilds, members, guild_messages, dm_messages

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Luc1412** [comment]
Seems like this issue just happens if there are multiple types of commands. (Guild and Global Commands)

**Comment by Lulalaby** [comment]
@Dorukyum you've got work

**Comment by Lulalaby** [comment]
Re-assign, luc will provide a fix.

**Comment by Luc1412** [comment]
Closed with #957
