### ISSUE TITLE
Add option to prevent commands from being deleting when syncing

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#949]
### Summary

Add option to prevent commands from being deleting when syncing

### What is the feature request for?

The core library

### The Problem

Sometimes a cog isn't loaded on startup or a command will be (re)added after startup. Instead of deleting it, ignoring can be sometimes the better option.

### The Ideal Solution

Add a parameter to `sync_commands`

### The Current Solution

none

**Comment by Lulalaby** [comment]
I think maybe this would be even better @Luc1412 

What if the lib responds to unloaded commands with something like "This command is not loaded at the moment" or similar.
So the users know this command is valid, but not available right now.

**Comment by Luc1412** [comment]
I think such behavior should be implemented by the user.

**Comment by BobDotCom** [comment]
Implemented in #1208
