### ISSUE TITLE
Add application sync log messages

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#950]
### Summary

Add application sync log messages

### What is the feature request for?

The core library

### The Problem

It can be useful to provide details on what the app command sync function did. Currently you don’t really know what the function did.

### The Ideal Solution

This can be done by using more or less verbose logging. The amount of detail can be set by log type. 

Debug provides a lot of detail with multiple messages.
eg. Edit slash command "test"
Remove message command "test2" for guild id 123

Info just mentions that commands have been synced. 
eG. Synced Application Commands: x global commands edited, 7 guild commands deleted

**Comment by BobDotCom** [comment]
Implemented in #1208
