### ISSUE TITLE
Invite.created_at is always None when Client.fetch_invite() is used

### ISSUE THREAD

**Issue by dnlldl** [Pycord-Development/pycord#951]
### Summary

Invite.created_at is always None when Client.fetch_invite() is used

### Reproduction Steps

Use `fetch_invite()` with any invite code.

### Minimal Reproducible Code

```python
@commands.command()
    async def i(self, ctx:commands.Context, code:str):
        try:
            invite = await self.bot.fetch_invite(code)
        except:
            print('Invite not found')
        else:
            print(invite.created_at)
```

### Expected Results

Print the invite creation date

### Actual Results

`None`

### Intents

discord.Intents.all()

### System Information

	vm-dev:~ # python3.9 -m discord -v
	- Python v3.9.6-final
	- py-cord v2.0.0-beta
		- py-cord pkg_resources: v2.0.0b1
	- aiohttp v3.7.4.post0
	- system info: Linux 5.3.18-59.40-default #1 SMP Mon Jan 3 18:43:20 UTC 2022 (34edd9c)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ToxicKidz** [comment]
As stated in [the docs](https://docs.pycord.dev/en/master/api.html?highlight=invite#discord.Invite), `Invite.created_at` is only present when calling [abc.GuildChannel.invites()](https://docs.pycord.dev/en/master/api.html?highlight=invite#discord.abc.GuildChannel.invites) or [Guild.invites()](https://docs.pycord.dev/en/master/api.html?highlight=invite#discord.Guild.invites).

**Comment by dnlldl** [comment]
> As stated in [the docs](https://docs.pycord.dev/en/master/api.html?highlight=invite#discord.Invite), `Invite.created_at` is only present when calling [abc.GuildChannel.invites()](https://docs.pycord.dev/en/master/api.html?highlight=invite#discord.abc.GuildChannel.invites) or [Guild.invites()](https://docs.pycord.dev/en/master/api.html?highlight=invite#discord.Guild.invites).

You're right, I apparently can't read. I was expecting that info to be available in the `created_at` section. I assume it's a Discord API limitation? I'm closing this issue.
