### ISSUE TITLE
Interaction failed but on_error didn't catch it

### ISSUE THREAD

**Issue by B-2U** [Pycord-Development/pycord#952]
### Summary

A sub-class view i made worked for a week started interaction failed when clicking button which happen randomly

### Reproduction Steps

click the button when view come out

### Minimal Reproducible Code

```python
class pickShipView(View):
    def __init__(self, ctx):
        self.ctx = ctx
        super().__init__(timeout=15)
        self.value = None

    @discord.ui.button(emoji='1️⃣')
    async def btn1(self, button, interaction):
        self.value = 1
        self.stop()
    
    async def on_error(self, error, item, interaction):
        print(str(error))
```

### Expected Results

when the interaction failed, the on_error should printed out what happened

### Actual Results

no output

### Intents

default intents

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4884+g68e9cf3d
- aiohttp v3.7.3
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

would it possible to be my discord client or internet problem?

**Comment by Lulalaby** [comment]
If it's a discord-side error pycord can't know that a error happened.
I believe this is no bug. 
Please re-open if I'm wrong
