### ISSUE TITLE
cannot name 2 application commands of different types the same name

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#954]
### Summary

with version beta 4 i can no longer name 2 application commands the same name even though one is a slash command and one is a user command. this did not occur with version beta 1 and earlier.

### Reproduction Steps

name 2 application commands of different types the same name.

### Minimal Reproducible Code

```python
#    create 2 application commands with the same name

#    first the slash command
@commands.slash_command(name='unmute', description="Unmute a user", guild_ids=config.slash_guilds)
@commands.has_permissions(manage_roles=True)
@commands.bot_has_permissions(manage_roles=True, send_messages=True)
async def slash_unmute(self, ctx, member: discord.Member, reason: discord.Option(str, "Reason for muting user",
                                                                                     required=False)):
    await self.unmute(ctx, member, reason)

#    now the context command
@commands.user_command(name='unmute', guild_ids=config.slash_guilds)
@commands.has_permissions(manage_roles=True)
@commands.bot_has_permissions(manage_roles=True, send_messages=True)
async def user_unmute(self, ctx, member: discord.Member):
    await self.unmute(ctx, member)
```

### Expected Results

add both without a problem. like version beta 1 and earlier

### Actual Results

gave the following exception:
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 1042, in on_connect
    await self.sync_commands()
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands
    registered_guild_commands[guild_id] = await self.register_commands(
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 460, in register_commands
    registered.append(await register("edit", cmd["id"], cmd["command"].to_dict()))
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In description: Context menu commands cannot have description
In options: Context menu commands cannot have options

When trying to run a slash command. another error occurs:

Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 738, in process_application_commands
    command = self._application_commands[interaction.data["id"]]
KeyError: '935791615111483445'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 1048, in on_interaction
    await self.process_application_commands(interaction)
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 753, in process_application_commands
    await self.sync_commands()
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 555, in sync_commands
    registered_guild_commands[guild_id] = await self.register_commands(
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/bot.py", line 461, in register_commands
    registered.append(await register("edit", cmd["id"], cmd["command"].to_dict()))
  File "/bot-directory/venv/lib/python3.10/site-packages/discord/http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In description: Context menu commands cannot have description
In options: Context menu commands cannot have options

and sometimes it will not error but not register the context menu command

### Intents

default intents, members and presences

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Linux 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Revnoplex** [comment]
context menu description and option?. Also this does not occur with beta 1

**Comment by Lulalaby** [comment]
ok, we need more code for this to trace it back

**Comment by Revnoplex** [comment]
can user commands not have descriptions?

**Comment by Revnoplex** [comment]
nvm, i tested errors still occur when removing descriptions i could find

**Comment by Revnoplex** [comment]
i need to run some tests on my bot code with context menu commands

**Comment by Revnoplex** [comment]
i have edited the issue with all lines that declare context menu commands

**Comment by Revnoplex** [comment]
im sorry but i gtg. I will continue to diagnose this in 20 hours. i am very busy and program my bot in my spare time

**Comment by Lulalaby** [comment]
yeah, thank u!

**Comment by Revnoplex** [comment]
I have noticed I have made a few errors in copying the code. I copied some of the wrong lines. I have temporarily corrected the lines to what I think they were. I will re-paste the correct lines in 18 hours when I have access to the latest bot code I am working on

**Comment by Lulalaby** [comment]
All fine. We have time.
We wait

**Comment by Revnoplex** [comment]
i have updated the reproduction code with the correct code and some extra info

**Comment by Lulalaby** [comment]
thank you

**Comment by Revnoplex** [comment]
i have updated issue with some exrta errors

**Comment by Revnoplex** [comment]
update: this problem does not occur if i rename all existing context commands to something else. also when messing around with my code, i can't seem to get the error anymore and context commands just don't loadslash

**Comment by Revnoplex** [comment]
i have rewritten the issue because i found what the problem appears to be

**Comment by PaulMndn** [comment]
I just encountered the same bug and believe I might have found the error in the code.

To register the commands `Bot().register_commands()` is called. If `force` is set to `False` (Default), we encounter this bit of code [in bot.py starting at line 434](https://github.com/Pycord-Development/pycord/blob/429dadce242bcdd8cfc224a072a5558497d0618b/discord/bot.py#L434-L455): 
```python
            for cmd in desynced:
                if cmd["action"] == "delete":
                    pending_actions.append(
                        {
                            "action": "delete",
                            "command": cmd["id"],
                            "name": cmd["command"],
                        }
                    )
                    continue
                # We can assume the command item is a command, since it's only a string if action is delete
                match = get(pending, name=cmd["command"].name)
                if match is None:
                    continue
                if cmd["action"] == "edit":
                    pending_actions.append(
                        {
                            "action": "edit",
                            "command": match,
                            "id": cmd["id"],
                        }
                    )
```

Going through the loop with `cmd` equal to the user command: If I take the example above, `pending` contains two elements: the `SlashCommand` with name "unmute" and the `UserCommand` with the name "unmute" in that order. Since `get()` is only performed using the name attribute, the first element with the matching name is returned, which due to the order of the `pending` is the `SlashCommand` object. 
This results in a mismatched `dict` being appended to `pending_actions` and the UserCommand never gets registered.

When I was debugging this I used version 2.0.0-beta3, the code snippet is from the current master.

**Comment by Revnoplex** [comment]
im getting some other errors even if the command names are different

**Comment by Revnoplex** [comment]
i am able to get rid of this other error if i flush all application commands

**Comment by Revnoplex** [comment]
i accidentally hit the application command limit while doing this. so only do it once

**Comment by BobDotCom** [comment]
This issue should be fixed with #1208

**Comment by Revnoplex** [comment]
> This issue should be fixed with #1208 

Ok, will test if the issue still occurs

**Comment by Revnoplex** [comment]
can confirm this no longer occurs on the #1208 branch

**Comment by Revnoplex** [comment]
actually nvm. I'm running to heaps of other issues. I'm not seeing a difference on or off the branch or any other versions. but I completely screwed slash commands across my entire bot

**Comment by Revnoplex** [comment]
ignore what said about before about everything being broken. I don't think it relates to this at all
