### ISSUE TITLE
Per page views with paginator request

### ISSUE THREAD

**Issue by Endst** [Pycord-Development/pycord#955]
### Summary

Allowing the creation of pages with their own views allowing for per page buttons and select menus

### What is the feature request for?

discord.ext.pages

### The Problem

This will allow for multi-paged select menus as a sort of work around to the 25 option limit select menus currently have. This will make it easier for users to have per page message components.

### The Ideal Solution

Add per page views/message components.

**Comment by krittick** [comment]
Planned to be added to the functionality for the `Page` object.
