### ISSUE TITLE
Only update permissions if needed.

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#959]
### Summary

Only update command permissions if required

### Reproduction Steps

Syncing commands multiple times. This happens for example when using a multi process bot.

### Expected Results

`sync_commands` only updates commands permissions if required

### Actual Results

Command permissions will be overwritten anytime `sync_commands ` is called even trough nothing changed.

This will  get the bot in some rate limit problems.

### Intents

guilds, members, guild_messages, dm_messages

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
The command permissions implementation will likely not be updated as v2 permissions will make it obsolete. If you can make a fix for it yourself in the next couple days, it might be merged, but I don't plan on putting effort into upgrading something to remove soon.

**Comment by MebinAbraham** [comment]
> The command permissions implementation will likely not be updated as v2 permissions will make it obsolete. If you can make a fix for it yourself in the next couple days, it might be merged, but I don't plan on putting effort into upgrading something to remove soon.

Is there a link to what you are referring to?. A similar thing happens for registering commands.

Why does the lib make request to the global command registration even when you have no global slash commands?. 
 ```py
    def bulk_upsert_global_commands(
        self, application_id: Snowflake, payload
    ) -> Response[List[interactions.ApplicationCommand]]:
        r = Route('PUT', '/applications/{application_id}/commands', application_id=application_id)
        return self.request(r, json=payload)
```
Even when payload is empty, it will try register. Surely that is a bug?. Deleted slash is another route?. This is causing unnecessary rate limit issues. Existing commands could be checked first also.

Let me know if I have misunderstood something. Thanks

**Comment by BobDotCom** [comment]
Will be fixed with permissions v2 and command registration rewrites
