### ISSUE TITLE
Embed.set_footer doesn't escapes markdown 

### ISSUE THREAD

**Issue by Jerry-py** [Pycord-Development/pycord#96]
### Summary

I want you to add that the footer of the embed doesn't escape markdown text

### What is the feature request for?

The core library

### The Problem

I figured I needed markdown for the footer. It'll become useful to me later.

### The Ideal Solution

Remove the escape markdown in footer

### The Current Solution

Remove the escape markdown in embed.set_footer

### Additional Context

I don't have any

**Comment by RaphaelSantiago53** [comment]
This is a discord limitation not a limitation of the library itself. Discord just doesn't allow markdown in the footer.
