### ISSUE TITLE
Race condition in InteractionResponse

### ISSUE THREAD

**Issue by Mihitoko** [Pycord-Development/pycord#963]
### Summary

There is a race condition in InteractionResponse

### Reproduction Steps

Running two task that will send a response to a Interaction will end in unexpected error.
Second Task will Raise NotFound Exception instead of `InteractionResponded` error.
This is due to a race condition in the libarry.

And because of this ApplicationContext.respond is also broken.

### Minimal Reproducible Code

```python
import asyncio

import discord.ext.commands

bot = discord.ext.commands.Bot()


@bot.slash_command(guild_ids=[...])
async def foo(ctx):
    async def respond():
        await ctx.respond("Race condition")

    asyncio.create_task(respond())
    asyncio.create_task(respond())


@bot.event
async def on_ready():
    print("Online")



bot.run("Token")
```

### Expected Results

Command should exit with `InteractionResponded` or better ApplicationContext.respond should switch to followup.

### Actual Results

NotFound HTTP exeption is raised.

`404`

### Intents

Default

### System Information

py-cord 2.0.0b4 master

Python 3.9 interpreter

OS Name	Microsoft Windows 10 Home
Version	10.0.19041 Build 19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Started working on a fix using asyncio.Lock

**Comment by PythonIntermediateCoder** [comment]
Your System Information should be your OS's information, py-cord's version info and more information if any. Also, can you show us the full exception traceback?

**Comment by TheShubhendra** [comment]
This happens with me also, when I run code in VS code python debugger using some breakpoints.

**Comment by Mihitoko** [comment]
> Your System Information should be your OS's information, py-cord's version info and more information if any. Also, can you show us the full exception traceback?

I'll recreate the bug when I'm in school.
And will update the issue with the requested information.

**Comment by Mihitoko** [comment]
> Your System Information should be your OS's information, py-cord's version info and more information if any. Also, can you show us the full exception traceback?

## Traceback

Task exception was never retrieved
future: <Task finished name='Task-25' coro=<foo.<locals>.respond() done, defined at C:\Users\redacted\PycharmProjects\pycord\tests\bot_test.py:10> exception=NotFound('404 Not Found (error code: 10062): Unknown interaction')>
Traceback (most recent call last):
  File "C:\Users\redacted\PycharmProjects\pycord\tests\bot_test.py", line 11, in respond
    await ctx.respond("Race condition")
  File "C:\Users\redacted\PycharmProjects\pycord\discord\interactions.py", line 615, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\redacted\PycharmProjects\pycord\discord\webhook\async_.py", line 192, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
