### ISSUE TITLE
SlashCommands in SlashCommandGroup wouldn't adhere permissions

### ISSUE THREAD

**Issue by shotwn** [Pycord-Development/pycord#970]
### Summary

SlashCommands created via @group.command() doesn't follow set permissions.

### Reproduction Steps

- Create a group with bot.create_group().
- Add a command with group.command().
- Either pass permissions to command decorator or call permissions decorator.
- Pass guild_ids for all.

### Minimal Reproducible Code

```python
import discord
from discord.commands import permissions

USER_ID = 
GUILD_ID = 
BOT_TOKEN = ""

bot = discord.Bot()

test_group = bot.create_group(
    "test", "Commands related to permissions test."
)  # create a slash command group

perm_arguments = {
    "id": USER_ID,
    "type": 2,
    "permission": True,
    "guild_id": GUILD_ID,
}


@test_group.command(
    guild_ids=[GUILD_ID], permissions=[permissions.CommandPermission(**perm_arguments)]
)  # create a slash command
async def i_should_be_inactive(ctx):
    await ctx.respond("Oups")


@test_group.command(guild_ids=[GUILD_ID])
@permissions.is_user(USER_ID)
async def so_as_i(ctx):
    await ctx.respond("Oups x2")


@bot.command(
    guild_ids=[GUILD_ID], permissions=[permissions.CommandPermission(**perm_arguments)]
)
async def but_i_am(ctx):
    await ctx.respond("Works")


bot.run(BOT_TOKEN)
```

### Expected Results

Commands within SlashCommandGroup to be inactive in the slash commands list and not usable.

### Actual Results

Users without required permissions can still use these commands.
![image](https://user-images.githubusercontent.com/2876361/153123006-c564c1f9-ccd0-46d7-aaf8-961e35ca33af.png)

### Intents

discord.Intents.all()

### System Information

- Python v3.9.1-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b3
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
Only the base command can have permissions added to it. This is intended functionality. We may add an error message when attempting to add permissions to a subcommand.

**Comment by shotwn** [comment]
Actually my first approach was to define my permissions group wide. But since **bot.create_group()** does not accept permissions argument and SlashCommandsGroup docstring doesn't have _permissions_ attribute documented, I assumed it is not possible.

Only now I see SlashCommandsGroup do accept and utilize _permissions_ keyword argument. Following do work as intended:
```python
test_group = SlashCommandGroup(
    "test2",
    "Commands related to permissions test.",
    permissions=[permissions.CommandPermission(**perm_arguments)],
)

...

bot.add_application_command(test_group)
```

So adding an error message and adding **permissions** attribute to SlashCommandGroup's docstring would fix the confusion.

Also expanding bot.create_group's functionality might be considered.

**Comment by Dorukyum** [comment]
The permissions system has now been changed and the new attributes have been added to the docstring.
