### ISSUE TITLE
@commands.has_any_role() can't use list from variable

### ISSUE THREAD

**Issue by mcbabo** [Pycord-Development/pycord#974]
### Summary

@commands.has_any_role() can't use list from variable

### Reproduction Steps

```py

reports_permission = [roleID, roleID]

@slash_command(guild_ids=guilds, description="Show Reports")
@commands.cooldown(rate=20, per=5)
@commands.has_any_role(reports_permission)
    async def show_reports(self, ctx, member: Option(discord.Member, required=True)):
```

### Minimal Reproducible Code

```python
reports_permission = [roleID, roleID]

@slash_command(guild_ids=guilds, description="Show Reports")
@commands.cooldown(rate=20, per=5)
@commands.has_any_role(reports_permission)
    async def show_reports(self, ctx, member: Option(discord.Member, required=True)):
```

### Expected Results

same as

```py
@slash_command(guild_ids=guilds, description="Show Reports")
@commands.cooldown(rate=20, per=5)
@commands.has_any_role(roleID, roleID)
    async def show_reports(self, ctx, member: Option(discord.Member, required=True)):
```

### Actual Results

error
no command excecution

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b1
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
`has_any_role` does not take a list of roles, you need to unpack your list with `*`.

**Comment by mcbabo** [comment]
but with guild_ids=[] i have to put a list ? pls unify this

**Comment by Luc1412** [comment]
It depends on the context. For roles it makes sense, for guild ids not.

**Comment by Middledot** [comment]
You can use an asterix:
```python
@commands.has_any_role(*reports_permission)
```

**Comment by plun1331** [comment]
> but with guild_ids=[] i have to put a list ? pls unify this

A list is used because `guild_ids` is a keyword argument in the slash command decorator, `has_any_role` is an entirely separate decorator and only takes roles.
