### ISSUE TITLE
commands has no attribute guild_ids

### ISSUE THREAD

**Issue by ghost** [Pycord-Development/pycord#979]
### Summary

Slash commands not registering

### Reproduction Steps

Made slash commands in a extension and loaded them

### Minimal Reproducible Code

```python
nothing wrong at my end
```

### Expected Results

The slash command to register

### Actual Results

```
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 1046, in on_connect
    await self.sync_commands()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 541, in sync_commands
    global_commands = [cmd for cmd in commands if cmd.guild_ids is None]
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 541, in <listcomp>
    global_commands = [cmd for cmd in commands if cmd.guild_ids is None]
AttributeError: 'Command' object has no attribute 'guild_ids'
```

### Intents

None

### System Information

 Python v3.8.12-final
- py-cord v2.0.0-beta
- py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Linux 5.11.0-1029-gcp #33~20.04.3-Ubuntu SMP

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by mcbabo** [comment]
code?

**Comment by SlickCrown** [comment]
@commands.command() 
async def add(ctx, *nums):
    operation = " + ".join(nums)
    await ctx.send(f'{operation} = {eval(operation)}')

@commands.command() 
async def sub(ctx, *nums): 
    operation = " - ".join(nums)
    await ctx.send(f'{operation} = {eval(operation)}')

@commands.command() 
async def multiply(ctx, *nums): 
    operation = " * ".join(nums)
    await ctx.send(f'{operation} = {eval(operation)}')

@commands.command() 
async def divide(ctx, *nums): 
    operation = " / ".join(nums)
    await ctx.send(f'{operation} = {eval(operation)}')

def setup(bot):
  bot.add_application_command(add)
  bot.add_application_command(sub)
  bot.add_application_command(multiply)
  bot.add_application_command(divide)

**Comment by EmreTech** [comment]
Remember to use the slash_command decorator from discord.commands in order to register a slash command!
