### ISSUE TITLE
ApplicationContext.respond behaves differently depending on situations (Slash command vs Modal dialog callback)

### ISSUE THREAD

**Issue by IamMusavaRibica** [Pycord-Development/pycord#994]
### Summary

While not necessarily a bug, this is definitely unexpected behaviour. ApplicationContext.respond function acts differently when called from a slash command function and from a modal dialog callback.

### Reproduction Steps

Calling ctx.respond() second time in a slash command interactions acts as a followup message, while calling it second time from a modal callback function acts as an initial response to the user

### Minimal Reproducible Code

```python
import discord
from discord import Bot, Status, ApplicationContext
from discord.ui import InputText, Modal

GUILD_IDS = [...]  # Please edit this
bot = Bot()

class Submit(Modal):
    def __init__(self, bot_, original_context) -> None:
        self.bot = bot_
        self.ctx = original_context
        super().__init__("Submit")
        self.add_item(InputText(label="Sample question", max_length=16))

    async def callback(self, interaction: discord.Interaction):
        # Notice this is the same ctx as from the command. I just passed him to this class
        await self.ctx.respond(content="First response")
        await self.ctx.respond(content="Second response!")
        await interaction.response.send_message("Last (different) response!")


@bot.slash_command(name="justrespond", guild_ids=GUILD_IDS)
async def func1(ctx: ApplicationContext):
    print("justrespond")
    await ctx.respond("First")
    await ctx.respond("Second")
    # This would raise an error: await ctx.send_response("Third (final)")


@bot.slash_command(name="respondwithmodal", guild_ids=GUILD_IDS)
async def func2(ctx: ApplicationContext):
    print("respondwithmodal")
    menu = Submit(bot, ctx)
    await ctx.interaction.response.send_modal(menu)

bot.run('BOT TOKEN GOES HERE')
```

### Expected Results

Please read "Actual Results". (I'm not sure how this is supposed to work)

### Actual Results

Notice how the "Second" appears as a followup message (bot responds to his response to my command)
![image](https://user-images.githubusercontent.com/65848142/153617967-b639616b-2905-461e-a10c-a6fec9bed072.png)

If I ctx.respond from the Modal callback, I get this: (bot always responds to me) 
![image](https://user-images.githubusercontent.com/65848142/153618193-6dfba535-4ca9-4f62-8c08-424ce280d09e.png)

### Intents

None/the default ones (i don't pass anything)

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have removed my token from display, if visible.
- [x] I have shown the entire traceback, if possible.

**Comment by krittick** [comment]
I'll check into this. Really appreciate the detailed report - this is pretty much a perfect example of how to submit an issue.

**Comment by IamMusavaRibica** [comment]
Thanks! 🙂 I wasn't sure how to structure, and even should i report it though. From the top of my head, in an earlier version ctx.respond from a slash command function would also work the same way, but I couldn't get it to happen again

**Comment by plun1331** [comment]
I feel like this would be something on Discord's end.

Both `ctx.respond`s in the modal callback *should* be follow-ups, as the bot had already responded with a modal. However, there isn't actually a message for them to follow-up to, as the response was a modal.

Responding to the modal interaction doesn't seem to have any issues, I believe that it's supposed to display the command's invocation as a reply.

**Comment by IamMusavaRibica** [comment]
I'm sure I was able to respond to a slash command multiple times, which looked like the second image I attached above. Can't recreate it anymore. The bot keeps responding to his response, just like he is supposed to, using a followup.
