### ISSUE TITLE
Aliases for Slash Commands 

### ISSUE THREAD

**Issue by No767** [Pycord-Development/pycord#997]
### Summary

I've noticed that slash cmds don't have an alias attribute like how `ext.commands` has it. This would allow people to set aliases in order to shorten some cmds down

### What is the feature request for?

The core library

### The Problem

Currently with slash commands, there is no way to set aliases. If there could be aliases, this would make it a lot easier to call the specified slash cmd

### The Ideal Solution

 For example, I want to have the command of `/youtube-play`. It would be useful if that slash cmd can be aliased as `/ytp`. The solution would be to add an attribute that takes in a list, and maps it to the regular slash cmd as well. 

### The Current Solution

The current solution could be to set an attribute that takes these and maps them to the regular slash cmd

**Comment by plun1331** [comment]
Aliases aren't supported by slash commands because of a Discord limitation.

**Comment by VincentRPS** [comment]
pretty sure this was intentional, since aliases just fill up the 200 commands limit also when typing a command it just autocompletes the commands name so it aliases aren't really needed

**Comment by krittick** [comment]
Discord has stated that they feel that fuzzy pattern matching solves this better than aliases and they won't be implementing it.  

See: https://github.com/discord/discord-api-docs/issues/2323#issuecomment-761137779

**Comment by EmreTech** [comment]
This is kinda pointless. How Slash Commands were designed eliminates the need for aliases. When you type "/", you get a menu you can scroll through to find the command you're looking for. No need for aliases in that case.

**Comment by KwiiHours** [comment]
> This is kinda pointless. How Slash Commands were designed eliminates the need for aliases. When you type "/", you get a menu you can scroll through to find the command you're looking for. No need for aliases in that case.

Scrolling through menus to find a specific command, especially when many bots share command names is very user unfriendly. For instance, ```/help``` could have the alias ```/botnamehelp```, which would solve this. Fuzzy pattern matching will also solve this, but the idea no issue exists isn't right in my view.

**Comment by bobbyl140** [comment]
Sorry to revive a dead thread, but I have a question regarding this. The point about typing "/" is true, but Discord for me can be quite laggy and I will often type "/show" and press Tab for a bot I wrote, where the command actually begins with "/get". I think having the ability to make aliases would be useful here. Also, I don't see how this is a Discord limitation. Doesn't pycord process the incoming commands however it sees fit? Why not just map one function to two commands? I realize this can be done manually but there should be a way to do this without redefining the function every time IMO.

**Comment by Lulalaby** [comment]
@bobbyl140 this is a discord limitation. every command has it's id and every command name has to be unique.
There's nothing anyone can change about it + what emre said.
If you really wanna achieve something like that, you have to do it yourself. It's not in a libs responsibility to provide functions not native to the api it is made for.

Also it's rather a personal thing or personal inconvenience than a general problem.
If you type too fast / can't remember the correct command, it is your problem (Not meant in a rude way).

The processing of commands is much more complicated than you think btw. It's not just "processing as it sees fit".

**Comment by bobbyl140** [comment]
That's fair that it's my own fault, I'll accept that. I just don't understand why pycord can't register two separate commands with 2 separate IDs that just do the same thing when the bot processes these events.

**Comment by bobbyl140** [comment]
But you're right, as it is probably a small case I don't expect an implementation.

**Comment by Lulalaby** [comment]
Hmm because it would defy the design of application commands, I'd say

**Comment by VincentRPS** [comment]
> Hmm because it would defy the design of application commands, I'd say

^ this.

The reason legacy Prefix Commands had aliases was because Bots weren't limited by the amount of commands, and since Discord had no autocomplete for a Bots account.

However, with Application Commands, both of those have changed, and therefore the primary use and requirements needed for Application Commands don't quite fit well. I might get an application however for more vague command names, or names that may deserve a larger myriad of aliases, but that should be implemented by Discord, not us, because of how little its use would be.

**Comment by bobbyl140** [comment]
Fair enough. So basically while it is *possible*, it's just designed that was because of the inherent system that commands use. And yeah for such a large change that should be a Discord thing (i.e. regex in command names). Thank you both for talking about this with me!
