### ISSUE TITLE
Can't delete message via button

### ISSUE THREAD

**Issue by AsthOfAether** [Pycord-Development/pycord#998]
### Summary

By attempting to make a button that deletes the message the button has been pressed on, an exception will get thrown out instead. 

### Reproduction Steps

1- Run the minimal reproducible code (try to make a view with a simple button that uses `interaction.delete_original_mesage()` )

### Minimal Reproducible Code

```python
# main.py
import discord

intents = discord.Intents.all()
bot = discord.Bot(intents=intents, prefix="-")


bot.load_extension("cog")
bot.run("token")

# cog.py
import discord
from discord.ext import commands


class Tools(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    tools = discord.commands.SlashCommandGroup("tools", "useful tools")

    class MyView(discord.ui.View):
        @discord.ui.button(label="Delete this nessage", style=discord.ButtonStyle.red)
        async def block(self, button: discord.ui.Button, interaction: discord.Interaction):
            await interaction.delete_original_message()

    @tools.command(name="hi")
    async def hi(self, ctx):
        await ctx.respond("hi sir", view=self.MyView(), ephemeral=True)


def setup(bot):
    bot.add_cog(Tools(bot))
```

### Expected Results

The expected results envision the deletion of the message that should be achieved with the button.

### Actual Results

Ignoring exception in view <MyView timeout=180.0 children=1> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='Delete this nessage' emoji=None row=None>:
Traceback (most recent call last):
  File "/Users/usr/PycharmProjects/BugTesting/venv/lib/python3.10/site-packages/discord/ui/view.py", line 365, in _scheduled_task
    await item.callback(interaction)
  File "/Users/usr/PycharmProjects/BugTesting/cog.py", line 18, in block
    await interaction.delete_original_message()
  File "/Users/usr/PycharmProjects/BugTesting/venv/lib/python3.10/site-packages/discord/interactions.py", line 405, in delete_original_message
    await func
  File "/Users/usr/PycharmProjects/BugTesting/venv/lib/python3.10/site-packages/discord/webhook/async_.py", line 192, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook

By using interaction.message.delete(), it will say "unknown message" instead.

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000    

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
`delete_original_message` is for deleting interaction responses, not the interaction message.

To delete the message a component interaction originated from, use `interaction.message.delete`.

Note that you cannot delete ephemeral messages.
